Repository theforeman/foreman-packaging, pull requests merged in 2018-05, with the labels that each got.

#2446 backport patch for katello-host-tools
  packages/katello/katello-host-tools/enabled_repos_format.patch
  packages/katello/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#2425 comps updates for sles11 katello clients
  comps/comps-katello-client-sles11.xml
Labels: Needs testing, RPM

#2444 Add rubygem-puma package
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-puma/puma-3.11.4.gem
  packages/foreman/rubygem-puma/rubygem-puma.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#2443 Add smart_proxy_dhcp_device42 deb
  plugins/smart_proxy_dhcp_device42/changelog
  plugins/smart_proxy_dhcp_device42/compat
  plugins/smart_proxy_dhcp_device42/control
  plugins/smart_proxy_dhcp_device42/copyright
  plugins/smart_proxy_dhcp_device42/dhcp_device42.rb
  plugins/smart_proxy_dhcp_device42/install
  plugins/smart_proxy_dhcp_device42/rules
  plugins/smart_proxy_dhcp_device42/source/format
Labels: DEB, Needs testing, Not yet reviewed

#2450 Add puppet agent rgen
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/puppet-agent-rgen/puppet-agent-rgen.spec
  packages/foreman/puppet-agent-rgen/rgen-0.8.2.gem
  rel-eng/tito.props
Labels: Needs testing, Not yet reviewed, RPM

#2452 Bump puppet strings 1.2.1
  packages/foreman/puppet-agent-puppet-strings/puppet-agent-puppet-strings.spec
  packages/foreman/puppet-agent-puppet-strings/puppet-strings-1.0.0.gem
  packages/foreman/puppet-agent-puppet-strings/puppet-strings-1.2.1.gem
Labels: Needs testing, Not yet reviewed, RPM

#2453 Update rubygem-foreman_maintain to 0.2.1
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.1.5.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.1.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#2418 Update rubygem-foreman_remote_execution to 1.5.1
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.5.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.5.1.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#2433 Update foreman_expire_hosts to 5.1.0
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-5.0.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-5.1.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Needs testing, RPM

#2454 Update foreman nodejs dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2455 update foreman_xen to 0.6.1
  packages/plugins/rubygem-foreman_xen/foreman_xen-0.5.2.gem
  packages/plugins/rubygem-foreman_xen/foreman_xen-0.6.1.gem
  packages/plugins/rubygem-foreman_xen/rubygem-foreman_xen.spec
Labels: Needs testing, RPM

#2469 Update rubygem-hammer_cli to 0.13.0
  packages/foreman/rubygem-hammer_cli/hammer_cli-0.12.0.gem
  packages/foreman/rubygem-hammer_cli/hammer_cli-0.13.0.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
Labels: Needs testing, RPM

#2470 Update rubygem-hammer_cli_foreman to 0.13.0
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.12.1.gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.13.0.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM

#2460 update foreman_salt to 10.0.0
  packages/plugins/rubygem-foreman_salt/foreman_salt-10.0.0.gem
  packages/plugins/rubygem-foreman_salt/foreman_salt-9.0.0.gem
  packages/plugins/rubygem-foreman_salt/rubygem-foreman_salt.spec
Labels: Needs testing, RPM

#2413 Document the current SLES process
  README.md
Labels: Needs testing, RPM

#2471 Updated hammer_cli to 0.13.0
  dependencies/stretch/hammer_cli/changelog
  dependencies/xenial/hammer_cli/changelog
Labels: Needs testing, Not yet reviewed

#2472 Update hammer_cli_foreman to 0.13.0
  dependencies/stretch/hammer_cli_foreman/changelog
  dependencies/stretch/hammer_cli_foreman/control
  dependencies/xenial/hammer_cli_foreman/changelog
  dependencies/xenial/hammer_cli_foreman/control
Labels: Needs testing, Not yet reviewed

#2473 katello-host-tools updates for suse
  packages/katello/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#2459 update foreman_salt to 9.0.1
  rubygem-foreman_salt/foreman_salt-9.0.0.gem
  rubygem-foreman_salt/foreman_salt-9.0.1.gem
  rubygem-foreman_salt/rubygem-foreman_salt.spec
Labels: Needs testing, RPM

#2458 update foreman_salt to 8.0.4
  rubygem-foreman_salt/foreman_salt-8.0.3.gem
  rubygem-foreman_salt/foreman_salt-8.0.4.gem
  rubygem-foreman_salt/rubygem-foreman_salt.spec
Labels: Needs testing, Not yet reviewed, RPM

#2456 update foreman_xen to 0.5.4
  rubygem-foreman_xen/foreman_xen-0.5.2.gem
  rubygem-foreman_xen/foreman_xen-0.5.4.gem
  rubygem-foreman_xen/rubygem-foreman_xen.spec
Labels: Needs testing, Not yet reviewed, RPM

#2479 Fix bogus dates
  packages/foreman/rubygem-rbvmomi/rubygem-rbvmomi.spec
  packages/plugins/rubygem-ffi/rubygem-ffi.spec
Labels: Needs testing, RPM

#2478 Update hammer_cli_csv to 2.3.1
  packages/katello/rubygem-hammer_cli_csv/hammer_cli_csv-2.3.0.gem
  packages/katello/rubygem-hammer_cli_csv/hammer_cli_csv-2.3.1.gem
  packages/katello/rubygem-hammer_cli_csv/rubygem-hammer_cli_csv.spec
Labels: Needs testing, RPM

#2481 Bump nodejs-react-ellipsis-with-tooltip to 1.0.8
  packages/foreman/nodejs-react-ellipsis-with-tooltip/nodejs-react-ellipsis-with-tooltip.spec
  packages/foreman/nodejs-react-ellipsis-with-tooltip/react-ellipsis-with-tooltip-1.0.7.tgz
  packages/foreman/nodejs-react-ellipsis-with-tooltip/react-ellipsis-with-tooltip-1.0.8.tgz
Labels: Needs testing, Not yet reviewed, RPM

#2480 Bump foreman-proxy dependencies
  packages/foreman/foreman-proxy/foreman-proxy.spec
Labels: Needs testing, Not yet reviewed, RPM

#2463 Bump nodejs-babel-core to 6.26.3
  packages/foreman/nodejs-babel-core/babel-core-6.26.0-registry.npmjs.org.tgz
  packages/foreman/nodejs-babel-core/babel-core-6.26.0.tgz
  packages/foreman/nodejs-babel-core/babel-core-6.26.3-registry.npmjs.org.tgz
  packages/foreman/nodejs-babel-core/babel-core-6.26.3.tgz
  packages/foreman/nodejs-babel-core/babel-generator-6.26.0.tgz
  packages/foreman/nodejs-babel-core/babel-generator-6.26.1.tgz
  packages/foreman/nodejs-babel-core/brace-expansion-1.1.11.tgz
  packages/foreman/nodejs-babel-core/brace-expansion-1.1.8.tgz
  packages/foreman/nodejs-babel-core/convert-source-map-1.5.0.tgz
  packages/foreman/nodejs-babel-core/convert-source-map-1.5.1.tgz
  packages/foreman/nodejs-babel-core/core-js-2.5.1.tgz
  packages/foreman/nodejs-babel-core/core-js-2.5.6.tgz
  packages/foreman/nodejs-babel-core/invariant-2.2.2.tgz
  packages/foreman/nodejs-babel-core/invariant-2.2.4.tgz
  packages/foreman/nodejs-babel-core/lodash-4.17.10.tgz
  packages/foreman/nodejs-babel-core/lodash-4.17.4.tgz
  packages/foreman/nodejs-babel-core/nodejs-babel-core.spec
  packages/foreman/nodejs-babel-core/regenerator-runtime-0.11.0.tgz
  packages/foreman/nodejs-babel-core/regenerator-runtime-0.11.1.tgz
Labels: Needs testing, Not yet reviewed, RPM

#2487 Add nodejs-react-bootstrap-tooltip-button package
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/nodejs-react-bootstrap-tooltip-button/nodejs-react-bootstrap-tooltip-button.spec
  packages/katello/nodejs-react-bootstrap-tooltip-button/react-bootstrap-tooltip-button-1.0.6.tgz
  rel-eng/tito.props
Labels: Needs testing

#2465 Adding pcp-mmvstatsd 0.1 RPM
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/pcp-mmvstatsd/pcp-mmvstatsd-0.2.tar.gz
  packages/foreman/pcp-mmvstatsd/pcp-mmvstatsd.default
  packages/foreman/pcp-mmvstatsd/pcp-mmvstatsd.service
  packages/foreman/pcp-mmvstatsd/pcp-mmvstatsd.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#2488 Update rubygem-dynflow to 1.0.3
  packages/foreman/rubygem-dynflow/dynflow-1.0.0.gem
  packages/foreman/rubygem-dynflow/dynflow-1.0.3.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing, RPM

#2486 Bump hammer-cli-katello to 0.13.1
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.13.0.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.13.1.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing

#2485 update scc_manager to 1.3.1
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.0.1.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.3.1.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM

#2143 symlink local_secret_token.rb to /etc/foreman
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2482 Update rubygem-bastion to 6.1.9
  packages/plugins/rubygem-bastion/bastion-6.1.10.gem
  packages/plugins/rubygem-bastion/bastion-6.1.9.gem
  packages/plugins/rubygem-bastion/rubygem-bastion.spec
Labels: Needs testing, RPM

#2484 Fixes #23595 - Set ruby-sequel-pg to conflicting
  debian/stretch/foreman/control
  debian/xenial/foreman/control
Labels: DEB, Needs testing, Not yet reviewed

#2492 Update foreman-tasks to 0.13.1
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB, Needs testing, Not yet reviewed

#2494 Loosen nodejs-react-bootstrap-tooltip-button deps
  packages/katello/nodejs-react-bootstrap-tooltip-button/nodejs-react-bootstrap-tooltip-button.spec
Labels: Needs testing, Not yet reviewed, RPM

#2499 Update rubygem-foreman_column_view to 0.4.0
  packages/plugins/rubygem-foreman_column_view/foreman_column_view-0.3.0.gem
  packages/plugins/rubygem-foreman_column_view/foreman_column_view-0.4.0.gem
  packages/plugins/rubygem-foreman_column_view/rubygem-foreman_column_view.spec
Labels: Needs testing, RPM

#2498 Update foreman-templates to 6.0.1
  plugins/ruby-foreman-templates/debian/changelog
  plugins/ruby-foreman-templates/debian/gem.list
  plugins/ruby-foreman-templates/foreman_templates.rb
Labels: Needs testing, Not yet reviewed

#2502 Update foreman nodejs dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#2462 Update katello nodejs dependencies
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#2497 Update rubygem-foreman_templates to 6.0.1
  packages/plugins/rubygem-foreman_templates/foreman_templates-6.0.0.gem
  packages/plugins/rubygem-foreman_templates/foreman_templates-6.0.1.gem
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
Labels: Needs testing, RPM

#2504 Update rubygem-foreman_maintain to 0.2.2
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.1.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.2.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#2477 set bundle vars
  debian/stretch/foreman/rules
  debian/xenial/foreman/rules
Labels: DEB, Needs testing

#2500 Update rubygem-foreman_column_view to 0.4.0
  plugins/ruby-foreman-column-view/debian/changelog
  plugins/ruby-foreman-column-view/debian/control
  plugins/ruby-foreman-column-view/debian/copyright
  plugins/ruby-foreman-column-view/debian/gem.list
  plugins/ruby-foreman-column-view/foreman_column_view.rb
Labels: DEB, Needs re-review, Needs testing

#2388 Fixes #23397 - Clean up el6 references & remove service-wait
  packages/katello/katello/backup.rb
  packages/katello/katello/katello-remove
  packages/katello/katello/katello-service
  packages/katello/katello/katello-service-bash_completion.sh
  packages/katello/katello/katello.spec
  packages/katello/katello/service-wait
Labels: Needs testing, RPM

#2509 Runcible 2.8.1
  packages/katello/rubygem-runcible/rubygem-runcible.spec
  packages/katello/rubygem-runcible/runcible-2.8.0.gem
  packages/katello/rubygem-runcible/runcible-2.8.1.gem
Labels: Needs testing, Not yet reviewed, RPM

#2256 [rpm] Bump foreman_ansible to 2.1
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.0.4.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.1.2.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#2510 Bump nodejs-patternfly-react to 2.3.4
  packages/foreman/nodejs-patternfly-react/nodejs-patternfly-react.spec
  packages/foreman/nodejs-patternfly-react/patternfly-react-2.2.1.tgz
  packages/foreman/nodejs-patternfly-react/patternfly-react-2.3.4.tgz
Labels: Needs testing, RPM

#2515 Release 1.17.1
  foreman-installer/foreman-installer-1.17.0.tar.bz2
  foreman-installer/foreman-installer-1.17.1.tar.bz2
  foreman-installer/foreman-installer.spec
  foreman-proxy/foreman-proxy-1.17.0.tar.bz2
  foreman-proxy/foreman-proxy-1.17.1.tar.bz2
  foreman-proxy/foreman-proxy.spec
  foreman-selinux/foreman-selinux-1.17.0.tar.bz2
  foreman-selinux/foreman-selinux-1.17.1.tar.bz2
  foreman-selinux/foreman-selinux.spec
  foreman/foreman-1.17.0.tar.bz2
  foreman/foreman-1.17.1.tar.bz2
  foreman/foreman.spec
Labels: Needs testing, RPM

#2517 Release 1.17.1
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: DEB, Needs testing

#2508 Update rubygem-foreman_default_hostgroup to 5.0.0
  packages/plugins/rubygem-foreman_default_hostgroup/foreman_default_hostgroup-4.0.1.gem
  packages/plugins/rubygem-foreman_default_hostgroup/foreman_default_hostgroup-5.0.0.gem
  packages/plugins/rubygem-foreman_default_hostgroup/rubygem-foreman_default_hostgroup.spec
Labels: Needs testing, RPM

#2520 Bump rubygem-fog-vsphere version to 2.1.1
  rubygem-fog-vsphere/fog-vsphere-1.11.3.gem
  rubygem-fog-vsphere/fog-vsphere-2.1.1.gem
  rubygem-fog-vsphere/rubygem-fog-vsphere.spec
Labels: Needs testing, RPM

#2519 Bump rubygem-foreman_snapshot_management to 1.5.0
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.4.0.gem
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.5.0.gem
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Needs testing, RPM

#2554 Allow rewriting the spec file for gems
  add_gem_package.sh
Labels: Needs testing, RPM

#2558 Handle .ssh symlinks in REX SSH
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
Labels: Needs testing, RPM

#2548 Regenerate rubygem-foreman_cockpit based on the current template
  packages/plugins/rubygem-foreman_cockpit/rubygem-foreman_cockpit.spec
Labels: Needs testing, RPM

#2547 Regenerate rubygem-foreman_column_view based on the current template
  packages/plugins/rubygem-foreman_column_view/rubygem-foreman_column_view.spec
Labels: Needs testing, RPM

#2546 Regenerate rubygem-foreman_default_hostgroup based on the current template
  packages/plugins/rubygem-foreman_default_hostgroup/rubygem-foreman_default_hostgroup.spec
Labels: Needs testing, RPM

#2545 Regenerate rubygem-foreman_dhcp_browser based on the current template
  packages/plugins/rubygem-foreman_dhcp_browser/rubygem-foreman_dhcp_browser.spec
Labels: Needs testing, RPM

#2544 Regenerate rubygem-foreman_digitalocean based on the current template
  packages/plugins/rubygem-foreman_digitalocean/rubygem-foreman_digitalocean.spec
Labels: Needs testing, RPM

#2543 Regenerate rubygem-foreman_discovery based on the current template
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, RPM

#2542 Regenerate rubygem-foreman_docker based on the current template
  packages/plugins/rubygem-foreman_docker/foreman_docker-4.0.0.gem
  packages/plugins/rubygem-foreman_docker/foreman_docker-4.1.0.gem
  packages/plugins/rubygem-foreman_docker/rubygem-foreman_docker.spec
Labels: Needs testing, RPM

#2541 Regenerate rubygem-foreman_expire_hosts based on the current template
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Needs testing, RPM

#2539 Regenerate rubygem-foreman_hooks based on the current template
  packages/plugins/rubygem-foreman_hooks/rubygem-foreman_hooks.spec
Labels: Needs testing, RPM

#2538 Regenerate rubygem-foreman_host_extra_validator based on the current template
  packages/plugins/rubygem-foreman_host_extra_validator/foreman_host_extra_validator.spec
  packages/plugins/rubygem-foreman_host_extra_validator/rubygem-foreman_host_extra_validator.spec
Labels: Needs testing, RPM

#2537 Regenerate rubygem-foreman_memcache based on the current template
  packages/plugins/rubygem-foreman_memcache/rubygem-foreman_memcache.spec
Labels: Needs testing, RPM

#2535 Regenerate rubygem-foreman_noenv based on the current template
  packages/plugins/rubygem-foreman_noenv/rubygem-foreman_noenv.spec
Labels: Needs testing, RPM

#2534 Regenerate rubygem-foreman_omaha based on the current template
  packages/plugins/rubygem-foreman_omaha/rubygem-foreman_omaha.spec
Labels: Needs testing, RPM

#2533 Regenerate rubygem-foreman_one based on the current template
  packages/plugins/rubygem-foreman_one/rubygem-foreman_one.spec
Labels: Needs testing, RPM

#2532 Regenerate rubygem-foreman_openscap based on the current template
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#2529 Regenerate rubygem-foreman_salt based on the current template
  packages/plugins/rubygem-foreman_salt/rubygem-foreman_salt.spec
Labels: Needs testing, RPM

#2528 Regenerate rubygem-foreman_setup based on the current template
  packages/plugins/rubygem-foreman_setup/rubygem-foreman_setup.spec
Labels: Needs testing, RPM

#2526 Regenerate rubygem-foreman_snapshot_management based on the current template
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Needs testing, RPM

#2525 Regenerate rubygem-foreman_templates based on the current template
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
Labels: Needs testing, RPM

#2524 Regenerate rubygem-foreman_userdata based on the current template
  packages/plugins/rubygem-foreman_userdata/rubygem-foreman_userdata.spec
Labels: Needs testing, RPM

#2523 Regenerate rubygem-foreman_vmwareannotations based on the current template
  packages/plugins/rubygem-foreman_vmwareannotations/rubygem-foreman_vmwareannotations.spec
Labels: Needs testing, RPM

#2522 Regenerate rubygem-foreman_xen based on the current template
  packages/plugins/rubygem-foreman_xen/rubygem-foreman_xen.spec
Labels: Needs testing, RPM

#2559 Update foreman_bootdisk to 12.0
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-11.0.0.gem
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-12.0.0.gem
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
Labels: Needs testing, RPM

#2555 Clean up nodejs babel situation
  comps/comps-foreman-rhel7.xml
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/foreman/nodejs-babel-plugin-syntax-object-rest-spread/babel-plugin-syntax-object-rest-spread-6.13.0.tgz
  packages/foreman/nodejs-babel-plugin-syntax-object-rest-spread/nodejs-babel-plugin-syntax-object-rest-spread.spec
  packages/foreman/nodejs-babel-plugin-transform-object-rest-spread/babel-plugin-syntax-object-rest-spread-6.13.0.tgz
  packages/foreman/nodejs-babel-plugin-transform-object-rest-spread/babel-plugin-transform-object-rest-spread-6.16.0-registry.npmjs.org.tgz
  packages/foreman/nodejs-babel-plugin-transform-object-rest-spread/babel-plugin-transform-object-rest-spread-6.16.0.tgz
  packages/foreman/nodejs-babel-plugin-transform-object-rest-spread/babel-plugin-transform-object-rest-spread-6.26.0.tgz
  packages/foreman/nodejs-babel-plugin-transform-object-rest-spread/babel-runtime-6.11.6.tgz
  packages/foreman/nodejs-babel-plugin-transform-object-rest-spread/core-js-2.4.1.tgz
  packages/foreman/nodejs-babel-plugin-transform-object-rest-spread/nodejs-babel-plugin-transform-object-rest-spread.spec
  packages/foreman/nodejs-babel-plugin-transform-object-rest-spread/regenerator-runtime-0.9.5.tgz
  packages/foreman/nodejs-babel-runtime/babel-runtime-6.26.0.tgz
  packages/foreman/nodejs-babel-runtime/nodejs-babel-runtime.spec
  packages/katello/nodejs-babel-plugin-transform-object-rest-spread/nodejs-babel-plugin-transform-object-rest-spread.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#2562 Updated bootdisk to v12 (DEB)
  plugins/ruby-foreman-bootdisk/debian/changelog
  plugins/ruby-foreman-bootdisk/debian/control
  plugins/ruby-foreman-bootdisk/debian/gem.list
  plugins/ruby-foreman-bootdisk/foreman_bootdisk.rb
Labels: DEB, Needs testing, Not yet reviewed

#2557 Remove unmaintained rubygem-foreman_snapshot
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/foreman/tfm/tfm.spec
  packages/plugins/rubygem-foreman_snapshot/foreman_snapshot-0.1.0.gem
  packages/plugins/rubygem-foreman_snapshot/rubygem-foreman_snapshot.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#2563 Fix rubygem-foreman_expire_hosts cron.d location
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Needs testing, RPM

#2550 Regenerate rubygem-foreman_bootdisk based on the current template
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
Labels: Needs testing, RPM

#2564 Update rubygem-foreman_virt_who_configure to 0.2.1
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.2.0.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.2.1.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Needs testing, RPM

#2565 Bump tfm release
  packages/foreman/tfm/tfm.spec
Labels: Needs testing, RPM

#2556 Switch to using Rails SCL from yum.theforeman.org
  packages/foreman/foreman-release-scl/foreman-release-scl.spec
  packages/foreman/foreman-release-scl/tfm-ror51.repo
Labels: Needs testing, RPM

#2561 Use multi_json from tfm-ror51
  packages/foreman/rubygem-activerecord-session_store/rubygem-activerecord-session_store.spec
  packages/foreman/rubygem-logging/rubygem-logging.spec
Labels: Needs testing, RPM

#2530 Regenerate rubygem-foreman_remote_execution_core based on the current template
  packages/plugins/rubygem-foreman_remote_execution_core/rubygem-foreman_remote_execution_core.spec
Labels: Needs testing, RPM

#2567 Remove foreman_snapshot
  plugins/ruby-foreman-snapshot/debian/changelog
  plugins/ruby-foreman-snapshot/debian/compat
  plugins/ruby-foreman-snapshot/debian/control
  plugins/ruby-foreman-snapshot/debian/copyright
  plugins/ruby-foreman-snapshot/debian/gem.list
  plugins/ruby-foreman-snapshot/debian/install
  plugins/ruby-foreman-snapshot/debian/postinst
  plugins/ruby-foreman-snapshot/debian/rules
  plugins/ruby-foreman-snapshot/debian/source/format
  plugins/ruby-foreman-snapshot/foreman_snapshot.rb
Labels: Needs testing

#2569 Move nodejs-core-js from katello to foreman
  comps/comps-foreman-rhel7.xml
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/foreman/nodejs-core-js/core-js-2.5.5.tgz
  packages/foreman/nodejs-core-js/nodejs-core-js.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#2570 Move nodejs-regenerator-runtime from katello to foreman
  comps/comps-foreman-rhel7.xml
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/foreman/nodejs-regenerator-runtime/nodejs-regenerator-runtime.spec
  packages/foreman/nodejs-regenerator-runtime/regenerator-runtime-0.11.1.tgz
  rel-eng/tito.props
Labels: Needs testing, Not yet reviewed, RPM

#2571 Point infra to 1.18 instead of nightly
  mock/el7-nonscl.cfg
  mock/el7-scl.cfg
  package_manifest.yaml
  packages/foreman/foreman-release-scl/foreman-release-scl.spec
  packages/foreman/foreman-release-scl/tfm-ror51.repo
  rel-eng/releasers.conf
  rel-eng/tito.props
  repoclosure/yum_el5.conf
  repoclosure/yum_el6.conf
  repoclosure/yum_el7.conf
  repoclosure/yum_f26.conf
  repoclosure/yum_f27.conf
Labels: Needs testing, RPM

#2573 Add 1.18 to the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Needs testing, Not yet reviewed

#2576 Get rails from yum.theforeman.org
  mock/el7-scl.cfg
  repoclosure/yum_el7.conf
Labels: Needs testing

#2577 Bump to 1.19-develop
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  rel-eng/releasers.conf
  rel-eng/tito.props
Labels: Needs testing

#2578 Update 1.18 repoclosures
  mock/el7-scl.cfg
  package_manifest.yaml
  repoclosure/yum_el7.conf
Labels: Needs testing

#2579 Point to yum.theforeman.org for tfm-ror51
  foreman-release-scl/foreman-release-scl.spec
  foreman-release-scl/tfm-ror51.repo
  repoclosure/yum_el7.conf
Labels: Needs testing, RPM

#2572 Update foreman_openscap to 0.9.3
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.9.2.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.9.3.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#2580 Bump bastion to 6.1.11
  packages/plugins/rubygem-bastion/bastion-6.1.10.gem
  packages/plugins/rubygem-bastion/bastion-6.1.11.gem
  packages/plugins/rubygem-bastion/rubygem-bastion.spec
Labels: Needs testing, RPM
