Repository theforeman/foreman-packaging, pull requests merged in 2018-09, with the labels that each got.

#2919 Release 1.18.2
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: DEB, Needs testing, Not yet reviewed

#2920 Correct Rails GPG key in foreman-release
  packages/foreman/foreman-release/foreman-release.spec
Labels: Needs testing, RPM

#2908 Bump hammer-cli-katello to 0.14.1
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.13.4.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.14.1.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM

#2922 Update rubygem-runcible to 2.9.0
  packages/katello/rubygem-runcible/rubygem-runcible.spec
  packages/katello/rubygem-runcible/runcible-2.8.1.gem
  packages/katello/rubygem-runcible/runcible-2.9.0.gem
Labels: Needs testing, RPM

#2926 Fix Katello 3.8 GPG key
  packages/katello/katello-repos/RPM-GPG-KEY-katello-2015
  packages/katello/katello-repos/RPM-GPG-KEY-katello-3.8
  packages/katello/katello-repos/katello-repos.spec
Labels: Needs testing, RPM

#2925 Add foreman_remote_execution as runtime dependency to foreman_ansible
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/control
Labels: DEB, Needs testing

#2904 Update tfm for Rails 5.2 and Ruby 2.5
  packages/foreman/tfm/tfm.spec
  repoclosure/yum.conf
  repoclosure/yum_el7.conf
Labels: Needs testing, RPM

#2928 Recursively git annex add NPM source tarballs
  add_npm_package.sh
Labels: Needs testing, RPM

#2933 Rebuild rubygem-passenger, rubygem-ruby-libvirt
  packages/foreman/rubygem-fog/rubygem-fog.spec
  packages/foreman/rubygem-passenger/rubygem-passenger.spec
  packages/foreman/rubygem-ruby-libvirt/rubygem-ruby-libvirt.spec
Labels: Needs testing, Not yet reviewed, RPM

#2934 Update rubygem-foreman_maintain to 0.2.9
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.8.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.9.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#2936 Update foreman_remote_execution to 1.6.2
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing, Not yet reviewed

#2937 Update Foreman spec for Rails 5.2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2940 Use pkill instead of systemctl kill after logrotate for smart-proxy
  debian/bionic/foreman-proxy/logrotate
  debian/stretch/foreman-proxy/logrotate
  debian/xenial/foreman-proxy/logrotate
Labels: DEB, Needs testing, Not yet reviewed

#2941 Rebuild plugin dependencies for Rails 5.2
  packages/plugins/rubygem-angular-rails-templates/rubygem-angular-rails-templates.spec
  packages/plugins/rubygem-bootstrap-datepicker-rails/rubygem-bootstrap-datepicker-rails.spec
  packages/plugins/rubygem-chunky_png/rubygem-chunky_png.spec
  packages/plugins/rubygem-commonjs/rubygem-commonjs.spec
  packages/plugins/rubygem-dalli/rubygem-dalli.spec
  packages/plugins/rubygem-deface/rubygem-deface.spec
  packages/plugins/rubygem-diffy/rubygem-diffy.spec
  packages/plugins/rubygem-docker-api/rubygem-docker-api.spec
  packages/plugins/rubygem-ffi/rubygem-ffi.spec
  packages/plugins/rubygem-git/rubygem-git.spec
  packages/plugins/rubygem-graphite-api/rubygem-graphite-api.spec
  packages/plugins/rubygem-gssapi/rubygem-gssapi.spec
  packages/plugins/rubygem-jgrep/rubygem-jgrep.spec
  packages/plugins/rubygem-jquery-matchheight-rails/rubygem-jquery-matchheight-rails.spec
  packages/plugins/rubygem-net-ssh-gateway/rubygem-net-ssh-gateway.spec
  packages/plugins/rubygem-net-ssh-krb/rubygem-net-ssh-krb.spec
  packages/plugins/rubygem-net-ssh-multi/rubygem-net-ssh-multi.spec
  packages/plugins/rubygem-opennebula/rubygem-opennebula.spec
  packages/plugins/rubygem-parse-cron/rubygem-parse-cron.spec
  packages/plugins/rubygem-pdf-core/rubygem-pdf-core.spec
  packages/plugins/rubygem-polyglot/rubygem-polyglot.spec
  packages/plugins/rubygem-prawn/rubygem-prawn.spec
  packages/plugins/rubygem-puppetdb_foreman/rubygem-puppetdb_foreman.spec
  packages/plugins/rubygem-rainbow/rubygem-rainbow.spec
  packages/plugins/rubygem-rqrcode/rubygem-rqrcode.spec
  packages/plugins/rubygem-safe_yaml/rubygem-safe_yaml.spec
  packages/plugins/rubygem-smart_proxy_dynflow_core/rubygem-smart_proxy_dynflow_core.spec
  packages/plugins/rubygem-systemu/rubygem-systemu.spec
  packages/plugins/rubygem-ttfunk/rubygem-ttfunk.spec
  packages/plugins/rubygem-wicked/rubygem-wicked.spec
  packages/plugins/rubygem-zscheduler/rubygem-zscheduler.spec
Labels: Needs testing, RPM

#2944 Rebuild hammer-cli_foreman_remote_execution
  packages/plugins/rubygem-hammer_cli_foreman_remote_execution/rubygem-hammer_cli_foreman_remote_execution.spec
Labels: Needs testing, RPM

#2946 Bump Katello dependencies for Rails 5.2
  packages/katello/rubygem-anemone/rubygem-anemone.spec
  packages/katello/rubygem-robotex/rubygem-robotex.spec
  packages/katello/rubygem-runcible/rubygem-runcible.spec
Labels: Needs testing, RPM

#2932 Update rubygem-foreman_openscap to 0.10.3
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.10.2.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.10.3.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#2948 Update rubygem-foreman_ansible to 2.2.6
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.3.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.6.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, Not yet reviewed, RPM

#2945 Bump plugins for Rails 5.2
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
  packages/plugins/rubygem-foreman_cockpit/rubygem-foreman_cockpit.spec
  packages/plugins/rubygem-foreman_column_view/rubygem-foreman_column_view.spec
  packages/plugins/rubygem-foreman_custom_parameters/rubygem-foreman_custom_parameters.spec
  packages/plugins/rubygem-foreman_default_hostgroup/rubygem-foreman_default_hostgroup.spec
  packages/plugins/rubygem-foreman_dhcp_browser/rubygem-foreman_dhcp_browser.spec
  packages/plugins/rubygem-foreman_digitalocean/rubygem-foreman_digitalocean.spec
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
  packages/plugins/rubygem-foreman_dlm/rubygem-foreman_dlm.spec
  packages/plugins/rubygem-foreman_docker/rubygem-foreman_docker.spec
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
  packages/plugins/rubygem-foreman_graphite/rubygem-foreman_graphite.spec
  packages/plugins/rubygem-foreman_hooks/rubygem-foreman_hooks.spec
  packages/plugins/rubygem-foreman_host_extra_validator/rubygem-foreman_host_extra_validator.spec
  packages/plugins/rubygem-foreman_memcache/rubygem-foreman_memcache.spec
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
  packages/plugins/rubygem-foreman_noenv/rubygem-foreman_noenv.spec
  packages/plugins/rubygem-foreman_omaha/rubygem-foreman_omaha.spec
  packages/plugins/rubygem-foreman_one/rubygem-foreman_one.spec
  packages/plugins/rubygem-foreman_rescue/rubygem-foreman_rescue.spec
  packages/plugins/rubygem-foreman_scap_client/rubygem-foreman_scap_client.spec
  packages/plugins/rubygem-foreman_setup/rubygem-foreman_setup.spec
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
  packages/plugins/rubygem-foreman_spacewalk/rubygem-foreman_spacewalk.spec
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
  packages/plugins/rubygem-foreman_userdata/rubygem-foreman_userdata.spec
  packages/plugins/rubygem-foreman_vmwareannotations/rubygem-foreman_vmwareannotations.spec
  packages/plugins/rubygem-foreman_xen/rubygem-foreman_xen.spec
Labels: Needs testing, RPM

#2949 Rebuild more plugins for Rails 5.2
  packages/plugins/rubygem-foreman-tasks-core/rubygem-foreman-tasks-core.spec
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
  packages/plugins/rubygem-foreman_chef/rubygem-foreman_chef.spec
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
  packages/plugins/rubygem-foreman_remote_execution_core/rubygem-foreman_remote_execution_core.spec
  packages/plugins/rubygem-foreman_salt/rubygem-foreman_salt.spec
  packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
Labels: Needs testing, RPM

#2951 Rebuild bastion for Rails 5.2
  packages/plugins/rubygem-bastion/rubygem-bastion.spec
Labels: Needs testing, RPM

#2903 Release rubygem-qpid_messaging 1.38
  packages/katello/rubygem-qpid_messaging/qpid_messaging-1.36.0.gem
  packages/katello/rubygem-qpid_messaging/qpid_messaging-1.38.0.gem
  packages/katello/rubygem-qpid_messaging/rubygem-qpid_messaging.spec
Labels: Needs testing, Not yet reviewed, RPM

#2954 Add nodejs-react-helmet package
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/nodejs-react-helmet/deep-equal-1.0.1.tgz
  packages/katello/nodejs-react-helmet/exenv-1.2.2.tgz
  packages/katello/nodejs-react-helmet/js-tokens-4.0.0.tgz
  packages/katello/nodejs-react-helmet/loose-envify-1.4.0.tgz
  packages/katello/nodejs-react-helmet/nodejs-react-helmet.spec
  packages/katello/nodejs-react-helmet/object-assign-4.1.1.tgz
  packages/katello/nodejs-react-helmet/prop-types-15.6.2.tgz
  packages/katello/nodejs-react-helmet/react-helmet-5.2.0-registry.npmjs.org.tgz
  packages/katello/nodejs-react-helmet/react-helmet-5.2.0.tgz
  packages/katello/nodejs-react-helmet/react-side-effect-1.1.5.tgz
  packages/katello/nodejs-react-helmet/shallowequal-1.1.0.tgz
  rel-eng/tito.props
Labels: Needs testing, RPM

#2956 Update rubygem-bastion to 6.1.13
  packages/plugins/rubygem-bastion/bastion-6.1.11.gem
  packages/plugins/rubygem-bastion/bastion-6.1.13.gem
  packages/plugins/rubygem-bastion/rubygem-bastion.spec
Labels: Needs testing, RPM

#2959 rubygem-katello-nightly-release doesn't exist anymore
  package_manifest.yaml
Labels: Needs testing, RPM

#2958 Drop schema loading for plugin rake tasks in Foreman
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2961 Update foreman_chef to 0.8.1
  plugins/ruby-foreman-chef/debian/changelog
  plugins/ruby-foreman-chef/debian/gem.list
  plugins/ruby-foreman-chef/foreman_chef.rb
Labels: Needs testing, Not yet reviewed

#2962 Bump Katello plugins for Rails 5.2 and Ruby 2.5
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
  packages/katello/rubygem-hammer_cli_csv/rubygem-hammer_cli_csv.spec
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/rubygem-hammer_cli_foreman_virt_who_configure.spec
  packages/katello/rubygem-redhat_access/rubygem-redhat_access.spec
  packages/katello/rubygem-redhat_access_lib/rubygem-redhat_access_lib.spec
Labels: Needs testing, RPM

#2942 hammer_cli_katello 0.13.5
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.13.4.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.13.5.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM

#2929 Update rubygem-scoped_search to 4.1.4
  packages/foreman/rubygem-scoped_search/rubygem-scoped_search.spec
  packages/foreman/rubygem-scoped_search/scoped_search-4.1.3.gem
  packages/foreman/rubygem-scoped_search/scoped_search-4.1.4.gem
Labels: Needs testing, RPM

#2950 Update foreman dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2909 Bump rubygem-hammer_cli_katello to 0.15.0
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.14.1.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#2967 Update hammer-cli-katello for nightly
  package_manifest.yaml
Labels: Needs testing

#2966 Drop signing on foreman-rails repo
  packages/foreman/foreman-release/foreman-rails.repo
  packages/foreman/foreman-release/foreman-release.spec
Labels: Needs testing

#2968 Remove unused scl_prefix_update.rb script
  packages/foreman/tfm/scl_prefix_update.conf
  packages/foreman/tfm/scl_prefix_update.rb
Labels: Needs testing

#2923 Split foreman packages into scl and nonscl groups
  package_manifest.yaml
Labels: Needs testing, RPM

#2971 Fix typo in yaml
  package_manifest.yaml
Labels: Needs testing

#2969 Update hammer_cli packaging to include prerelease
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM

#2976 Update hammer_cli_katello dependency on hammer_cli_foreman
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM

#2981 Update foreman_remote_execution to 1.5.6
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB, Needs testing, Not yet reviewed

#2980 Update rubygem-foreman_remote_execution to 1.5.6
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.5.5.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.5.6.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#2984 fixes #24605 - remove rails 4 patches
  packages/foreman/foreman/foreman.spec
  packages/foreman/foreman/message_encryptor_extensions.rb
Labels: Needs testing, RPM

#2982 Update rubygem-foreman_ansible to 2.2.7
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.6.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.7.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#2987 Update rubygem-foreman_remote_execution to 1.5.6
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.5.5.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.5.6.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#2983 Update foreman_ansible to 2.2.7
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/control
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing, Not yet reviewed

#2921 Break plugins into scl and nonscl groups in package_manifest
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  rel-eng/tito.props
Labels: Needs testing, RPM

#2994 Obsolete SCL rubygem-faraday_middleware
  packages/foreman/tfm/tfm.spec
Labels: Needs testing, RPM

#2917 Add Foreman client release repository package
  comps/comps-foreman-client-fedora27.xml
  comps/comps-foreman-client-fedora28.xml
  comps/comps-foreman-client-rhel5.xml
  comps/comps-foreman-client-rhel6.xml
  comps/comps-foreman-client-rhel7.xml
  comps/comps-foreman-client-sles11.xml
  comps/comps-foreman-client-sles12.xml
  package_manifest.yaml
  packages/foreman/foreman-release/foreman-client.repo
  packages/foreman/foreman-release/foreman-release.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#2996 Fixes #24936 - Use LGPLv2 for both 2 and 2.1 versions.
  packages/foreman/rubygem-journald-native/rubygem-journald-native.spec
  packages/foreman/rubygem-rubyipmi/rubygem-rubyipmi.spec
Labels: Needs testing, RPM

#2997 Rename to foreman-client-release
  packages/foreman/foreman-release/foreman-release.spec
Labels: Needs testing, RPM

#2989 Update rubygem-foreman_ansible to 2.2.7
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.6.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.7.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#2988 Update rubygem-foreman_ansible to 2.2.7
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.5.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.7.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#2993 Fixes #24857 - Require foreman_ansible_core in sp_ansible
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
Labels: Needs testing, RPM

#3006 Fix foreman-client repoclosure reference for fedora
  repoclosure/yum.conf
  repoclosure/yum_f27.conf
  repoclosure/yum_f28.conf
Labels: Needs testing, RPM

#3002 Add nodejs-query-string package
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/katello/nodejs-query-string/decode-uri-component-0.2.0.tgz
  packages/katello/nodejs-query-string/nodejs-query-string.spec
  packages/katello/nodejs-query-string/query-string-6.1.0-registry.npmjs.org.tgz
  packages/katello/nodejs-query-string/query-string-6.1.0.tgz
  packages/katello/nodejs-query-string/strict-uri-encode-2.0.0.tgz
  rel-eng/tito.props
Labels: Needs testing, RPM

#2985 Move nodejs-jed to foreman
  comps/comps-foreman-rhel7.xml
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/foreman/nodejs-jed/jed-1.1.1.tgz
  packages/foreman/nodejs-jed/nodejs-jed.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3015 Update rubygem-hammer_cli_foreman_tasks to 0.0.13
  packages/plugins/rubygem-hammer_cli_foreman_tasks/hammer_cli_foreman_tasks-0.0.12.gem
  packages/plugins/rubygem-hammer_cli_foreman_tasks/hammer_cli_foreman_tasks-0.0.13.gem
  packages/plugins/rubygem-hammer_cli_foreman_tasks/rubygem-hammer_cli_foreman_tasks.spec
Labels: Needs testing, RPM

#3014 Set correct nodejs-query-string comps
  comps/comps-foreman-rhel7.xml
  comps/comps-katello-server-rhel7.xml
Labels: Needs testing, RPM

#3009 Add query-string requirement to rubygem-katello
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#3023 Update foreman_ansible to 2.2.8
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing, Not yet reviewed

#3016 Update hammer-cli-foreman-tasks 0.0.13
  dependencies/bionic/hammer_cli_foreman_tasks/changelog
  dependencies/stretch/hammer_cli_foreman_tasks/changelog
  dependencies/xenial/hammer_cli_foreman_tasks/changelog
Labels: Needs testing, Not yet reviewed

#3018 Obsolete python-pulp-rpm-common for katello-host-tools
  packages/katello/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#3027 Update smart_proxy_dynflow{,_core} to 0.2.1
  plugins/smart_proxy_dynflow/changelog
  plugins/smart_proxy_dynflow/dynflow.rb
  plugins/smart_proxy_dynflow_core/changelog
  plugins/smart_proxy_dynflow_core/dynflow_core.rb
Labels: DEB, Needs testing, Not yet reviewed

#3028 Update smart_proxy_dynflow{,_core} to 0.1.11 (foreman <= 1.17)
  plugins/smart_proxy_dynflow/changelog
  plugins/smart_proxy_dynflow/dynflow.rb
  plugins/smart_proxy_dynflow_core/changelog
  plugins/smart_proxy_dynflow_core/dynflow_core.rb
Labels: Needs testing, Not yet reviewed

#3026 Bump rubygem-smart_proxy_dynflow{,_core} to 0.1.11
  rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.1.10.gem
  rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.1.11.gem
  rubygem-smart_proxy_dynflow_core/rubygem-smart_proxy_dynflow_core.spec
  rubygem-smart_proxy_dynflow_core/smart_proxy_dynflow_core-0.1.10.gem
  rubygem-smart_proxy_dynflow_core/smart_proxy_dynflow_core-0.1.11.gem
Labels: Needs testing, RPM

#3025 Update rubygem-smart_proxy_dynflow to 0.2.1
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.2.0.gem
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.2.1.gem
Labels: Needs testing, RPM

#3029 Lower obsolete version in katello-host-tools
  packages/katello/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#3005 Fixes #24857 - Require foreman_ansible_core in sp_ansible
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
Labels: Needs testing, RPM

#3004 Fixes #24857 - Require foreman_ansible_core in sp_ansible
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
Labels: Needs testing, RPM

#3030 Update rubygem-smart_proxy_dynflow to 0.2.1
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.2.0.gem
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.2.1.gem
Labels: Needs testing, Not yet reviewed, RPM

#3031 Update rubygem-smart_proxy_dynflow to 0.2.1
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.2.0.gem
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.2.1.gem
Labels: Needs testing, Not yet reviewed, RPM

#3032 Release constraings on smart_proxy_dynflow_core version
  rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
Labels: Needs testing, RPM

#2975 Fixes #24922 - Use ASL 2.0 instead of Apache 2.0 or Apache-2.0
  packages/foreman/nodejs-harmony-reflect/nodejs-harmony-reflect.spec
  packages/foreman/nodejs-patternfly-react/nodejs-patternfly-react.spec
  packages/foreman/nodejs-patternfly/nodejs-patternfly.spec
  packages/foreman/rubygem-clamp/rubygem-clamp.spec
  packages/foreman/rubygem-ovirt-engine-sdk/rubygem-ovirt-engine-sdk.spec
  packages/foreman/rubygem-prometheus-client/rubygem-prometheus-client.spec
  packages/foreman/rubygem-quantile/rubygem-quantile.spec
  packages/katello/nodejs-react-router-bootstrap/nodejs-react-router-bootstrap.spec
Labels: Needs testing, RPM

#3037 Update rubygem-foreman_maintain to 0.2.11
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.11.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.9.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#3007 Add nodejs-reselect package
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/nodejs-reselect/nodejs-reselect.spec
  packages/foreman/nodejs-reselect/reselect-3.0.1.tgz
  rel-eng/tito.props
Labels: Needs testing, RPM

#3034 Update rubygem-foreman_ansible to 2.2.9
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.7.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.9.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#3003 Rebuild gettext_i18n_rails_js with Rails 5.1
  packages/foreman/rubygem-gettext_i18n_rails_js/rubygem-gettext_i18n_rails_js.spec
Labels: Needs testing, RPM

#3013 add foreman_m2 package
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_m2/foreman_m2-0.0.1.gem
  packages/plugins/rubygem-foreman_m2/rubygem-foreman_m2.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3020 Update rubygem-smart_proxy_openscap to 0.6.11
  packages/plugins/rubygem-smart_proxy_openscap/rubygem-smart_proxy_openscap.spec
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.6.10.gem
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.6.11.gem
Labels: Needs testing, Not yet reviewed, RPM

#3019 Update rubygem-scoped_search to 4.1.5
  packages/foreman/rubygem-scoped_search/rubygem-scoped_search.spec
  packages/foreman/rubygem-scoped_search/scoped_search-4.1.4.gem
  packages/foreman/rubygem-scoped_search/scoped_search-4.1.5.gem
Labels: Needs testing, RPM

#2978 Update foreman_userdata to 0.1.0
  packages/plugins/rubygem-foreman_userdata/foreman_userdata-0.0.1.gem
  packages/plugins/rubygem-foreman_userdata/foreman_userdata-0.1.0.gem
  packages/plugins/rubygem-foreman_userdata/rubygem-foreman_userdata.spec
Labels: Needs testing, RPM

#3040 Avoid unversioned Provides in gem2rpm templates
  gem2rpm/foreman_plugin.spec.erb
  gem2rpm/smart_proxy_plugin.spec.erb
Labels: Needs testing, RPM

#3039 Bump rubygem-wicked to 1.3.3-1
  packages/plugins/rubygem-wicked/rubygem-wicked.spec
  packages/plugins/rubygem-wicked/wicked-1.3.2.gem
  packages/plugins/rubygem-wicked/wicked-1.3.3.gem
Labels: Needs testing, RPM

#3001 Build katello-host-tools for foreman-client repos
  comps/comps-foreman-client-fedora27.xml
  comps/comps-foreman-client-fedora28.xml
  comps/comps-foreman-client-rhel5.xml
  comps/comps-foreman-client-rhel6.xml
  comps/comps-foreman-client-rhel7.xml
  comps/comps-foreman-client-sles11.xml
  comps/comps-foreman-client-sles12.xml
  package_manifest.yaml
  rel-eng/tito.props
Labels: Needs testing, RPM

#3017 Add rubygem-smart_proxy_m2 package
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-smart_proxy_m2/rubygem-smart_proxy_m2.spec
  packages/plugins/rubygem-smart_proxy_m2/smart_proxy_m2-0.0.1.gem
  rel-eng/tito.props
Labels: Needs testing, RPM

#2991 Add rubygem-fog-proxmox package
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-fog-proxmox/fog-proxmox-0.5.1.gem
  packages/plugins/rubygem-fog-proxmox/rubygem-fog-proxmox.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3042 Cleanup client comps and reduce carried dependencies
  comps/comps-foreman-client-fedora27.xml
  comps/comps-foreman-client-fedora28.xml
  comps/comps-foreman-client-rhel5.xml
  comps/comps-foreman-client-rhel6.xml
  package_manifest.yaml
Labels: Needs testing, RPM

#3041 Update rubygem-hammer_cli_foreman_templates to 0.1.2
  packages/plugins/rubygem-hammer_cli_foreman_templates/hammer_cli_foreman_templates-0.1.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_templates/hammer_cli_foreman_templates-0.1.2.gem
  packages/plugins/rubygem-hammer_cli_foreman_templates/rubygem-hammer_cli_foreman_templates.spec
Labels: Needs testing, RPM

#3035 Update foreman_ansible to 2.2.9
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: DEB, Needs testing, Not yet reviewed

#2965 Update foreman_remote_execution to 1.6.3
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB, Needs testing, Not yet reviewed
