Repository theforeman/foreman-packaging, pull requests merged in 2018-02, with the labels that each got.

#2192 Fixes #21795 - backup should exclude large directories
  katello/katello/backup.rb
Labels: Needs testing

#2198 Fix plugin repo names
  foreman/foreman-plugins.repo
Labels: Needs testing

#2151 Add rubygem-smart_proxy_dhcp_device42 package
  comps/comps-foreman-plugins-rhel7.xml
  rel-eng/tito.props
  rubygem-smart_proxy_dhcp_device42/rubygem-smart_proxy_dhcp_device42.spec
  rubygem-smart_proxy_dhcp_device42/smart_proxy_dhcp_device42-1.0.4.gem
Labels: Needs testing

#2200 Move rubygem-smart_proxy_dhcp_device42 to the correct dir
  packages/plugins/rubygem-smart_proxy_dhcp_device42/rubygem-smart_proxy_dhcp_device42.spec
  packages/plugins/rubygem-smart_proxy_dhcp_device42/smart_proxy_dhcp_device42-1.0.4.gem
  rubygem-smart_proxy_dhcp_device42/smart_proxy_dhcp_device42-1.0.4.gem
Labels: Needs testing

#2202 update foreman_digitalocean to 1.3.0
  plugins/ruby-foreman-digitalocean/debian/changelog
  plugins/ruby-foreman-digitalocean/debian/gem.list
  plugins/ruby-foreman-digitalocean/foreman_digitalocean.rb
Labels: Needs testing, Not yet reviewed

#2203 update foreman_digitalocean to 1.3.0
  packages/plugins/rubygem-foreman_digitalocean/foreman_digitalocean-1.2.0.gem
  packages/plugins/rubygem-foreman_digitalocean/foreman_digitalocean-1.3.0.gem
  packages/plugins/rubygem-foreman_digitalocean/rubygem-foreman_digitalocean.spec
Labels: Needs testing, Not yet reviewed

#2197 Update foreman-release repos to simplify releases
  packages/foreman/foreman/foreman.repo
  packages/foreman/foreman/foreman.spec
Labels: Needs testing

#2193 Fixes #22548 - always use the absolute path for @dir
  packages/katello/katello/backup.rb
Labels: Needs testing

#2205 Bump hammer_cli_katello to 0.11.5.1
  katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.11.0.gem
  katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.11.5.1.gem
  katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing

#2206 update foreman-tasks to 0.11.1
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Not yet reviewed

#2208 update smart_proxy_dhcp_remote_isc to 0.0.4
  plugins/smart_proxy_dhcp_remote_isc/changelog
  plugins/smart_proxy_dhcp_remote_isc/dhcp_remote_isc.rb
Labels: Needs testing, Not yet reviewed

#2211 (DEB) Updated hammer_cli to 0.12.0
  dependencies/stretch/hammer_cli/changelog
  dependencies/stretch/hammer_cli/control
  dependencies/xenial/hammer_cli/changelog
  dependencies/xenial/hammer_cli/control
Labels: Needs testing, Not yet reviewed

#2212 (DEB) Updated hammer_cli_foreman to 0.12.0
  dependencies/stretch/hammer_cli_foreman/changelog
  dependencies/stretch/hammer_cli_foreman/control
  dependencies/xenial/hammer_cli_foreman/changelog
  dependencies/xenial/hammer_cli_foreman/control
Labels: Needs testing, Not yet reviewed

#2207 update foreman-tasks to 0.11.1
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.11.0.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.11.1.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing

#2209 (RPM) Update rubygem-hammer_cli to 0.12.0
  packages/foreman/rubygem-hammer_cli/hammer_cli-0.11.0.gem
  packages/foreman/rubygem-hammer_cli/hammer_cli-0.12.0.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
Labels: Needs testing

#2181 Add rubygem-journald-native package
  comps/comps-foreman-rhel7.xml
  packages/foreman/rubygem-journald-native/journald-native-1.0.9.gem
  packages/foreman/rubygem-journald-native/rubygem-journald-native.spec
  rel-eng/tito.props
Labels: Needs testing

#2183 Add rubygem-logging-journald package
  comps/comps-foreman-rhel7.xml
  packages/foreman/rubygem-logging-journald/logging-journald-1.0.0.gem
  packages/foreman/rubygem-logging-journald/rubygem-logging-journald.spec
  rel-eng/tito.props
Labels: Needs testing

#2210 (RPM) Update rubygem-hammer_cli_foreman to 0.12.0
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.11.0.gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.12.0.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing

#2214 Cleanup whitelists and releasers
  rel-eng/releasers.conf
  rel-eng/tito.props
Labels: Needs testing

#2195 [rpm] Update smart_proxy_ansible to 2.0.1
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-2.0.0.gem
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-2.0.1.gem
Labels: Needs testing

#2204 Fixes #22607 - add rex ssh to backup
  packages/katello/katello/backup.rb
Labels: Needs testing

#2215 Updated rubygem-smart_proxy_dhcp_infoblox to 0.0.12
  packages/plugins/rubygem-smart_proxy_dhcp_infoblox/rubygem-smart_proxy_dhcp_infoblox.spec
  packages/plugins/rubygem-smart_proxy_dhcp_infoblox/smart_proxy_dhcp_infoblox-0.0.10.gem
  packages/plugins/rubygem-smart_proxy_dhcp_infoblox/smart_proxy_dhcp_infoblox-0.0.12.gem
Labels: Needs testing

#2157 Fix committing in npm package update script
  add_npm_package.sh
Labels: Needs testing

#2182 Add rubygem-journald-logger package
  comps/comps-foreman-rhel7.xml
  packages/foreman/rubygem-journald-logger/journald-logger-2.0.3.gem
  packages/foreman/rubygem-journald-logger/rubygem-journald-logger.spec
  rel-eng/tito.props
Labels: Needs re-review, Needs testing

#2116 Replace bundled-npm() with bundled(npm())
  packages/foreman/nodejs-babel-cli/nodejs-babel-cli.spec
  packages/foreman/nodejs-babel-core/nodejs-babel-core.spec
  packages/foreman/nodejs-babel-loader/nodejs-babel-loader.spec
  packages/foreman/nodejs-babel-plugin-lodash/nodejs-babel-plugin-lodash.spec
  packages/foreman/nodejs-babel-plugin-transform-class-properties/nodejs-babel-plugin-transform-class-properties.spec
  packages/foreman/nodejs-babel-plugin-transform-object-assign/nodejs-babel-plugin-transform-object-assign.spec
  packages/foreman/nodejs-babel-plugin-transform-object-rest-spread/nodejs-babel-plugin-transform-object-rest-spread.spec
  packages/foreman/nodejs-babel-polyfill/nodejs-babel-polyfill.spec
  packages/foreman/nodejs-babel-preset-env/nodejs-babel-preset-env.spec
  packages/foreman/nodejs-babel-preset-react/nodejs-babel-preset-react.spec
  packages/foreman/nodejs-babel-register/nodejs-babel-register.spec
  packages/foreman/nodejs-brace/nodejs-brace.spec
  packages/foreman/nodejs-compression-webpack-plugin/nodejs-compression-webpack-plugin.spec
  packages/foreman/nodejs-css-loader/nodejs-css-loader.spec
  packages/foreman/nodejs-extract-text-webpack-plugin/nodejs-extract-text-webpack-plugin.spec
  packages/foreman/nodejs-fbjs/nodejs-fbjs.spec
  packages/foreman/nodejs-file-loader/nodejs-file-loader.spec
  packages/foreman/nodejs-isomorphic-fetch/nodejs-isomorphic-fetch.spec
  packages/foreman/nodejs-jsdom/nodejs-jsdom.spec
  packages/foreman/nodejs-lodash-webpack-plugin/nodejs-lodash-webpack-plugin.spec
  packages/foreman/nodejs-node-gyp/nodejs-node-gyp.spec
  packages/foreman/nodejs-node-sass/nodejs-node-sass.spec
  packages/foreman/nodejs-react-bootstrap/nodejs-react-bootstrap.spec
  packages/foreman/nodejs-react-dom/nodejs-react-dom.spec
  packages/foreman/nodejs-react-redux/nodejs-react-redux.spec
  packages/foreman/nodejs-react/nodejs-react.spec
  packages/foreman/nodejs-redux-form/nodejs-redux-form.spec
  packages/foreman/nodejs-redux-logger/nodejs-redux-logger.spec
  packages/foreman/nodejs-redux/nodejs-redux.spec
  packages/foreman/nodejs-sass-loader/nodejs-sass-loader.spec
  packages/foreman/nodejs-style-loader/nodejs-style-loader.spec
  packages/foreman/nodejs-url-loader/nodejs-url-loader.spec
Labels: Needs testing, RPM

#2220 Update foreman NPM dependencies
  packages/foreman/foreman/foreman.spec
  packages/foreman/foreman/update-node-dependencies
Labels: Needs testing, Not yet reviewed, RPM

#2196 [deb] Update smart_proxy_ansible to 2.0.1
  plugins/smart_proxy_ansible/ansible.rb
  plugins/smart_proxy_ansible/changelog
Labels: Needs testing, Not yet reviewed

#2222 Handle new package structure in bump_rpm.sh
  bump_rpm.sh
Labels: Needs testing, RPM

#2219 update katello-debug deps
  packages/katello/katello/katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#2218 replace net-tools with ss
  packages/katello/katello/katello.spec
  packages/katello/katello/service-wait
Labels: Needs testing, RPM

#2228 Fix plugin repoclosure
  rel-eng/tito.props
Labels: Needs testing, RPM

#2187 Add .rc1 to katello-repos spec file
  comps/comps-katello-pulp-server-rhel7.xml
  katello/katello-repos/katello-repos.spec
  katello/katello-repos/katello.repo
Labels: Needs testing, Not yet reviewed, RPM, Waiting on contributor

#2227 Drop python as a BuildRequires for katello-repos
  packages/katello/katello-repos/katello-repos.spec
Labels: Needs testing, RPM

#2229 Drop python
  katello/katello-repos/katello-repos.spec
Labels: Needs testing, RPM

#2201 Add Package Manifest for obal
  package_manifest.yaml
Labels: Needs testing, RPM

#2233 Refs #18675 - Create a foreman-telemetry package
  packages/foreman/foreman/foreman.spec
Labels: Needs testing

#2231 Fix npm package updating script to use PACKAGE_DIR
  add_npm_package.sh
Labels: Needs testing, RPM

#2230 create foreman-telemetry package
  debian/stretch/foreman/control
  debian/stretch/foreman/foreman-telemetry.install
  debian/stretch/foreman/foreman-telemetry.postinst
  debian/xenial/foreman/control
  debian/xenial/foreman/foreman-telemetry.install
  debian/xenial/foreman/foreman-telemetry.postinst
Labels: DEB, Needs testing, Not yet reviewed

#2234 Add repoclosures to package_manifest
  package_manifest.yaml
  repoclosure/yum_el5.conf
  repoclosure/yum_el6.conf
  repoclosure/yum_el7.conf
  repoclosure/yum_f25.conf
  repoclosure/yum_f26.conf
  repoclosure/yum_f27.conf
Labels: Needs testing, RPM
