Repository theforeman/foreman-packaging, pull requests merged in 2018-07, with the labels that each got.

#2713 Bump hammer-cli-katello to 0.13.3
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.13.2.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.13.3.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM

#2686 Create a rubygem-katello-assets subpackage
  comps/comps-katello-server-rhel7.xml
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#2660 Update rubygem-foreman_ansible_core to 2.1.0
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-2.0.2.gem
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-2.1.0.gem
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
Labels: Needs testing, Not yet reviewed, RPM

#2719 Update rubygem-redhat_access to 2.1.6
  packages/katello/rubygem-redhat_access/redhat_access-2.1.5.gem
  packages/katello/rubygem-redhat_access/redhat_access-2.1.6.gem
  packages/katello/rubygem-redhat_access/rubygem-redhat_access.spec
Labels: Needs testing, RPM

#2718 Update foreman_templates to 6.0.2
  packages/plugins/rubygem-foreman_templates/foreman_templates-6.0.1.gem
  packages/plugins/rubygem-foreman_templates/foreman_templates-6.0.2.gem
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
Labels: Needs testing, RPM

#2404 Add rubygem-hammer_cli_foreman_ansible package
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-hammer_cli_foreman_ansible/hammer_cli_foreman_ansible-0.1.1.gem
  packages/plugins/rubygem-hammer_cli_foreman_ansible/rubygem-hammer_cli_foreman_ansible.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#2717 Update foreman_templates to 6.0.2
  plugins/ruby-foreman-templates/debian/changelog
  plugins/ruby-foreman-templates/debian/gem.list
  plugins/ruby-foreman-templates/foreman_templates.rb
Labels: 1.18-plugin-rebuild, DEB, Needs testing, Not yet reviewed

#2687 Fix foreman-proxy logrotate with systemd
  debian/bionic/foreman-proxy/logrotate
  debian/stretch/foreman-proxy/logrotate
  debian/xenial/foreman-proxy/logrotate
Labels: DEB, Needs testing, Not yet reviewed

#2633 katello-host-tools 3.3.1
  packages/katello/katello-host-tools/katello-host-tools-3.3.0.tar.gz
  packages/katello/katello-host-tools/katello-host-tools-3.3.1.tar.gz
  packages/katello/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#2726 Bump fog-ovirt minimum version
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed

#2725 Update Dynflow to 1.1.0
  dependencies/bionic/dynflow/changelog
  dependencies/stretch/dynflow/changelog
  dependencies/xenial/dynflow/changelog
Labels: Needs testing, Not yet reviewed

#2731 Refs #24213 - Upgrade fog-vsphere gem version to 2.3.0
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-2.1.1.gem
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-2.3.0.gem
  packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec
Labels: Needs testing, RPM

#2729 Fixes #24213 - Upgrade fog-vsphere gem version to 2.3.0
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2727 katello-host-tools 3.3.1
  packages/katello/katello-host-tools/katello-host-tools-3.3.0.tar.gz
  packages/katello/katello-host-tools/katello-host-tools-3.3.1.tar.gz
  packages/katello/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, Not yet reviewed

#2735 Correct call to update-requirements
  bump_rpm.sh
Labels: Needs testing, Not yet reviewed

#2736 Release 1.18.0
  packages/foreman/foreman-installer/foreman-installer-1.18.0-RC3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-1.18.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-1.18.0-RC3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-1.18.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-selinux/foreman-selinux-1.18.0-RC3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-1.18.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-1.18.0-RC3.tar.bz2
  packages/foreman/foreman/foreman-1.18.0.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing

#2746 Refs #23836 - update fog-ovirt deps
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2748 Drop initscripts from Foreman
  packages/foreman/foreman/foreman.init
  packages/foreman/foreman/foreman.service
  packages/foreman/foreman/foreman.spec
  packages/foreman/foreman/foreman.sysconfig
Labels: Needs testing, RPM

#2750 Require qpid-cpp-client explicitly for qpid_messaging
  packages/katello/rubygem-qpid_messaging/rubygem-qpid_messaging.spec
Labels: Needs testing, RPM

#2738 Release 1.18.0
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: DEB, Needs testing, Not yet reviewed

#2745 Discovery 12.0.2 - DEB
  plugins/ruby-foreman-discovery/debian/changelog
  plugins/ruby-foreman-discovery/debian/gem.list
  plugins/ruby-foreman-discovery/foreman_discovery.rb
Labels: Needs testing, Not yet reviewed

#2740 Update foreman_remote_execution to 1.5.4 [deb]
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing, Not yet reviewed

#2733 Update foreman_templates to 6.0.3
  plugins/ruby-foreman-templates/debian/changelog
  plugins/ruby-foreman-templates/debian/gem.list
  plugins/ruby-foreman-templates/foreman_templates.rb
Labels: DEB, Needs testing, Not yet reviewed

#2751 update foreman_salt to 10.1.0
  plugins/ruby-foreman-salt/debian/changelog
  plugins/ruby-foreman-salt/debian/gem.list
  plugins/ruby-foreman-salt/foreman_salt.rb
Labels: DEB, Needs testing, Not yet reviewed

#2747 katello-host-tools 3.3.2
  packages/katello/katello-host-tools/katello-host-tools-3.3.1.tar.gz
  packages/katello/katello-host-tools/katello-host-tools-3.3.2.tar.gz
  packages/katello/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, Not yet reviewed, RPM

#2752 add puppet-agent-rgen
  plugins/puppet-agent-rgen/debian/changelog
  plugins/puppet-agent-rgen/debian/compat
  plugins/puppet-agent-rgen/debian/control
  plugins/puppet-agent-rgen/debian/copyright
  plugins/puppet-agent-rgen/debian/dirs
  plugins/puppet-agent-rgen/debian/gem.list
  plugins/puppet-agent-rgen/debian/install
  plugins/puppet-agent-rgen/debian/postinst
  plugins/puppet-agent-rgen/debian/prerm
  plugins/puppet-agent-rgen/debian/rules
  plugins/puppet-agent-rgen/debian/source/format
Labels: DEB, Needs testing, Not yet reviewed

#2741 Update rubygem-foreman_maintain to 0.2.4
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.2.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.4.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#2743 Update rubygem-foreman_ansible to 2.2.3
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.1.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.3.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, Not yet reviewed, RPM

#2724 Update rubygem-dynflow to 1.1.0
  packages/foreman/rubygem-dynflow/dynflow-1.0.5.gem
  packages/foreman/rubygem-dynflow/dynflow-1.1.0.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing, RPM

#2754 Update rubygem-hammer_cli_foreman to 0.13.1
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.13.0.gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.13.1.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#2739 Update rubygem-foreman_remote_execution to 1.5.4 [rpm]
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.5.3.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.5.4.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, Not yet reviewed, RPM

#2513 [rpm] Update rubygem-smart_proxy_ansible to 2.0.3
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-2.0.2.gem
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-2.0.3.gem
Labels: Needs testing, RPM, Waiting on contributor

#2758 Remove abrt and azure plugins
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/foreman/tfm/tfm.spec
  packages/plugins/rubygem-foreman_abrt/foreman_abrt-0.0.7.gem
  packages/plugins/rubygem-foreman_abrt/rubygem-foreman_abrt.spec
  packages/plugins/rubygem-foreman_azure/foreman_azure-1.3.1.gem
  packages/plugins/rubygem-foreman_azure/rubygem-foreman_azure.spec
  packages/plugins/rubygem-smart_proxy_abrt/rubygem-smart_proxy_abrt.spec
  packages/plugins/rubygem-smart_proxy_abrt/smart_proxy_abrt-0.0.8.gem
  rel-eng/tito.props
Labels: Needs testing, RPM

#2759 Remove azure dependencies
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/foreman/tfm/tfm.spec
  packages/plugins/rubygem-azure-core/azure-core-0.1.1.gem
  packages/plugins/rubygem-azure-core/rubygem-azure-core.spec
  packages/plugins/rubygem-azure/azure-0.7.10.gem
  packages/plugins/rubygem-azure/rubygem-azure.spec
  packages/plugins/rubygem-fog-azure/fog-azure-0.0.2.gem
  packages/plugins/rubygem-fog-azure/rubygem-fog-azure.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#2757 katello-host-tools 3.3.2
  packages/katello/katello-host-tools/katello-host-tools-3.3.1.tar.gz
  packages/katello/katello-host-tools/katello-host-tools-3.3.2.tar.gz
  packages/katello/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, Not yet reviewed, RPM

#2760 Add 1.19, remove 1.16 from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Needs testing, Not yet reviewed

#2761 Switch from nightly to 1.19/3.8
  mock/el7-nonscl.cfg
  mock/el7-scl.cfg
  package_manifest.yaml
  packages/foreman/foreman-release-scl/foreman-release-scl.spec
  packages/foreman/foreman-release-scl/tfm-ror51.repo
  packages/foreman/foreman/foreman-plugins.repo
  packages/foreman/foreman/foreman.gpg
  packages/foreman/foreman/foreman.repo
  rel-eng/releasers.conf
  rel-eng/tito.props
  repoclosure/yum.conf
  repoclosure/yum_el5.conf
  repoclosure/yum_el6.conf
  repoclosure/yum_el7.conf
  repoclosure/yum_f27.conf
  repoclosure/yum_f28.conf
Labels: Needs testing, RPM

#2762 Bump version to 1.20-develop
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  rel-eng/package2tags
  rel-eng/releasers.conf
Labels: Needs testing, Not yet reviewed, RPM

#2766 Fix host tools dep resolution
  packages/katello/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#2756 Release Katello 3.7 RC2
  packages/katello/katello-installer/katello-installer-3.7.0.rc1.tar.gz
  packages/katello/katello-installer/katello-installer-3.7.0.rc2.tar.gz
  packages/katello/katello-installer/katello-installer-base.spec
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.7.0.rc1.gem
  packages/katello/rubygem-katello/katello-3.7.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#2771 Update rubygem-foreman_openscap to 0.10.2
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.10.1.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.10.2.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#2778 Fixes #24312 - Remove Pulp Resource Manager Qpid command.
  packages/katello/katello/katello-debug.sh
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#2779 Bump hammer-cli-katello to 0.13.4
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.13.3.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.13.4.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#2781 Release 1.19.0-RC1
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: Needs testing, Not yet reviewed

#2780 Release 1.19.0-RC1
  packages/foreman/foreman-installer/foreman-installer-1.19.0-RC1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-1.19.0-RC1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-selinux/foreman-selinux-1.19.0-RC1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-1.19.0-RC1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#2784 katello-host-tools 3.3.3
  packages/katello/katello-host-tools/katello-host-tools-3.3.2.tar.gz
  packages/katello/katello-host-tools/katello-host-tools-3.3.3.tar.gz
  packages/katello/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, Not yet reviewed, RPM

#2769 Add GPG checking to foreman-release-scl
  packages/foreman/foreman-release-scl/copr.gpg
  packages/foreman/foreman-release-scl/foreman-release-scl.spec
  packages/foreman/foreman-release-scl/tfm-ror51.repo
Labels: Needs testing, RPM

#2768 Fixes #24287 - Enable GPG checks on foreman-release-scl
  foreman-release-scl/copr.gpg
  foreman-release-scl/foreman-release-scl.spec
  foreman-release-scl/tfm-ror51.repo
Labels: Needs testing, RPM

#2734 Update rubygem-foreman_templates to 6.0.3
  packages/plugins/rubygem-foreman_templates/foreman_templates-6.0.2.gem
  packages/plugins/rubygem-foreman_templates/foreman_templates-6.0.3.gem
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
Labels: Needs testing, Not yet reviewed, RPM

#2732 Introduce a nightly_releaser variable
  package_manifest.yaml
Labels: Needs testing, RPM

#2788 Release katello-host-tools-3.3.4
  packages/katello/katello-host-tools/katello-host-tools-3.3.3.tar.gz
  packages/katello/katello-host-tools/katello-host-tools-3.3.4.tar.gz
  packages/katello/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#2789 Add -nf to symlink for rex webpack
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/postinst
Labels: DEB, Needs testing, Not yet reviewed

#2793 Enable gpgcheck
  packages/katello/katello-repos/katello-client.repo
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello-repos/katello.repo
Labels: Needs testing, RPM

#2794 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2770 Rename spec files to match directory names
  package_manifest.yaml
  packages/foreman/tfm-rubygem-rest-client/tfm-rubygem-rest-client.spec
  packages/katello/katello-installer-base/katello-installer-base.spec
  packages/plugins/rubygem-radcli/rubygem-radcli.spec
  packages/plugins/rubygem-smart_proxy_realm_ad_plugin/rubygem-smart_proxy_realm_ad_plugin.spec
Labels: Needs testing, RPM

#2796 Cleanup gofer requirements
  comps/comps-katello-client-fedora27.xml
  comps/comps-katello-client-fedora28.xml
  comps/comps-katello-client-rhel5.xml
  comps/comps-katello-client-rhel6.xml
  comps/comps-katello-client-rhel7.xml
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#2798 Add nightly back to katello-repos
  packages/katello/katello-repos/katello-repos.spec
Labels: Needs testing, RPM

#2800 Bump hammer-cli-katello to 0.13.4
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.13.3.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.13.4.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM

#2801 Remove python-gofer-qpid traces
  comps/comps-katello-server-rhel7.xml
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#2797 Update rubygem-foreman_ansible to 2.2.5
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.3.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.5.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#2802 Remove python-gofer-qpid traces
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#2803 Update rubygem-foreman_ansible to 2.2.5
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.3.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.5.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, Not yet reviewed, RPM

#2805 Put python-gofer-qpid back in katello server comps
  comps/comps-katello-server-rhel7.xml
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#2806 Put python-gofer-qpid back in katello server comps
  comps/comps-katello-server-rhel7.xml
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#2807 Update rubygem-foreman_maintain to 0.2.5
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.4.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.5.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#2809 Update katello-repos gpg key
  packages/katello/katello-repos/RPM-GPG-KEY-katello-2015
  packages/katello/katello-repos/RPM-GPG-KEY-katello-3.7
  packages/katello/katello-repos/katello-repos.spec
Labels: Needs testing, RPM

#2744 Discovery 12.0.2 - RPM
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-12.0.1.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-12.0.2.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing

#2813 Discovery 12.0.2 - RPM for 1.18 (#2744)
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-12.0.0.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-12.0.2.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing

#2814 Discovery 12.0.2 - RPM for 1.19 (#2744)
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-12.0.1.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-12.0.2.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing

#2808 Fixes #24422 - k-c-h Check hostname is not current hostname
  packages/katello/katello/hostname-change.rb
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM
