Repository theforeman/foreman-packaging, pull requests merged in 2018-04, with the labels that each got.

#2314 [RPM] Update rubygem-dynflow to 0.9.0
  packages/foreman/rubygem-dynflow/dynflow-0.8.37.gem
  packages/foreman/rubygem-dynflow/dynflow-1.0.0.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing, RPM

#2330 update foreman-tasks to 0.13.0
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB, Needs testing, Not yet reviewed

#2328 Update foreman_setup to 6.0.0
  packages/plugins/rubygem-foreman_setup/foreman_setup-5.0.0.gem
  packages/plugins/rubygem-foreman_setup/foreman_setup-6.0.0.gem
  packages/plugins/rubygem-foreman_setup/rubygem-foreman_setup.spec
Labels: Needs testing, RPM

#2322 Fixes #23052 - Use the correct license on the spec file
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#2325 Fixes #23059 - foreman-journald package now installable
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/foreman/foreman.spec
  packages/foreman/rubygem-journald-native/0000-relative-load-native.patch
  packages/foreman/rubygem-journald-native/rubygem-journald-native.spec
Labels: Needs testing, RPM

#2339 Release rubygem-runcible 2.8.0
  packages/katello/rubygem-runcible/rubygem-runcible.spec
  packages/katello/rubygem-runcible/runcible-2.6.0.gem
  packages/katello/rubygem-runcible/runcible-2.8.0.gem
Labels: Needs testing, RPM

#2341 Add nodejs-css-element-queries package
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/nodejs-css-element-queries/css-element-queries-1.0.2.tgz
  packages/foreman/nodejs-css-element-queries/nodejs-css-element-queries.spec
  rel-eng/tito.props
Labels: Needs testing

#2335 Add missing packages to the manifest
  package_manifest.yaml
Labels: Needs testing, RPM

#2337 Updated to journald-native-1.0.10.gem
  packages/foreman/rubygem-journald-native/0000-relative-load-native.patch
  packages/foreman/rubygem-journald-native/journald-native-1.0.10.gem
  packages/foreman/rubygem-journald-native/journald-native-1.0.9.gem
  packages/foreman/rubygem-journald-native/rubygem-journald-native.spec
Labels: Needs testing, RPM

#2318 Bump rubygem-logging to 2.2.2
  rubygem-logging/logging-1.8.2.gem
  rubygem-logging/logging-2.2.2.gem
  rubygem-logging/rubygem-logging.spec
Labels: Needs testing, RPM

#2319 Bump rubygem-awesome_print to 1.8.0
  rubygem-awesome_print/awesome_print-1.7.0.gem
  rubygem-awesome_print/awesome_print-1.8.0.gem
  rubygem-awesome_print/rubygem-awesome_print.spec
Labels: Needs testing, RPM

#2316 Update foreman_monitoring to 0.1.3 [rpm]
  rubygem-foreman_monitoring/foreman_monitoring-0.1.2.gem
  rubygem-foreman_monitoring/foreman_monitoring-0.1.3.gem
  rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
Labels: Needs testing, RPM

#2320 Update foreman_monitoring to 1.0.1 [rpm]
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-1.0.0.gem
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-1.0.1.gem
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
Labels: Needs testing, RPM

#2269 Update foreman_openscap to 0.9.2
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.9.0.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.9.2.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#2327 Fixes #23065 - kbackup add validator for --split-pulp-tar
  packages/katello/katello/backup.rb
Labels: Needs testing, RPM

#2324 Update rubygem-apipie-rails to 0.5.7
  packages/foreman/rubygem-apipie-rails/apipie-rails-0.5.6.gem
  packages/foreman/rubygem-apipie-rails/apipie-rails-0.5.7.gem
  packages/foreman/rubygem-apipie-rails/rubygem-apipie-rails.spec
Labels: Needs testing, RPM

#2333 Update foreman dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Ready to merge

#2344 [RPM] Add hammer_cli_foreman_tasks
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-hammer_cli_foreman_templates/hammer_cli_foreman_templates-0.1.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_templates/rubygem-hammer_cli_foreman_templates.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#2347 Add rubygem-ovirt-engine-sdk package
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-ovirt-engine-sdk/ovirt-engine-sdk-4.2.3.gem
  packages/foreman/rubygem-ovirt-engine-sdk/rubygem-ovirt-engine-sdk.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#2338 [deb] Core projects: Release 1.16.1
  debian/jessie/foreman-installer/changelog
  debian/jessie/foreman-proxy/changelog
  debian/jessie/foreman/changelog
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: DEB, Needs testing, Not yet reviewed

#2349 Deb/develop rex 150
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing, Not yet reviewed

#2340 [rpm] Release 1.16.1
  foreman-installer/foreman-installer-1.16.0.tar.bz2
  foreman-installer/foreman-installer-1.16.1.tar.bz2
  foreman-installer/foreman-installer.spec
  foreman-proxy/foreman-proxy-1.16.0.tar.bz2
  foreman-proxy/foreman-proxy-1.16.1.tar.bz2
  foreman-proxy/foreman-proxy.spec
  foreman-selinux/foreman-selinux-1.16.0.tar.bz2
  foreman-selinux/foreman-selinux-1.16.1.tar.bz2
  foreman-selinux/foreman-selinux.spec
  foreman/foreman-1.16.0.tar.bz2
  foreman/foreman-1.16.1.tar.bz2
  foreman/foreman.spec
Labels: Needs testing, RPM

#2348 Migrate proxy config to /etc and state to /var
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
Labels: Needs testing, RPM

#2313 fixes #23029 - fixes incremental backup of failed online pulp backup
  packages/katello/katello/backup.rb
Labels: Needs testing, RPM

#2289 foreman_maintain pkg should provide foreman-maintain
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#2351 Update rubygem-fog-ovirt to 1.0.2
  packages/foreman/rubygem-fog-ovirt/fog-ovirt-1.0.1.gem
  packages/foreman/rubygem-fog-ovirt/fog-ovirt-1.0.2.gem
  packages/foreman/rubygem-fog-ovirt/rubygem-fog-ovirt.spec
Labels: Needs testing, RPM

#2353 Update rubygem-smart_proxy_openscap to 0.6.10
  packages/plugins/rubygem-smart_proxy_openscap/rubygem-smart_proxy_openscap.spec
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.6.10.gem
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.6.9.gem
Labels: Needs testing, RPM

#2356 Update rubygem-foreman-tasks to 0.13.0
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.12.1.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.13.0.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#2358 Update rubygem-smart_proxy_dynflow_core to 0.2.0
  packages/plugins/rubygem-smart_proxy_dynflow_core/rubygem-smart_proxy_dynflow_core.spec
  packages/plugins/rubygem-smart_proxy_dynflow_core/smart_proxy_dynflow_core-0.1.10.gem
  packages/plugins/rubygem-smart_proxy_dynflow_core/smart_proxy_dynflow_core-0.2.0.gem
Labels: Needs testing

#2354 Add foreman-telemetry to comps
  comps/comps-foreman-rhel7.xml
Labels: Needs testing, RPM

#2355 Correct comps
  comps/comps-foreman-plugins-rhel7.xml
  comps/comps-foreman-rhel7.xml
Labels: Needs testing, RPM

#2357 Update smart_proxy_dynflow_core to 0.2.0
  plugins/smart_proxy_dynflow_core/changelog
  plugins/smart_proxy_dynflow_core/control
Labels: DEB, Needs testing, Not yet reviewed

#2309 Fixes #23021 - Update Tomcat curl for cert error
  packages/katello/katello/katello.spec
  packages/katello/katello/service-wait
Labels: Needs testing, RPM

#2361 Update rubygem-smart_proxy_dynflow to 0.2.0
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.1.10.gem
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.2.0.gem
Labels: Needs testing, Not yet reviewed, RPM

#2360 Add tfm-rubygem-ttfunk to comps
  comps/comps-foreman-plugins-rhel7.xml
Labels: Needs testing, Not yet reviewed, RPM

#2267 Update foreman_openscap to 0.7.13
  rubygem-foreman_openscap/foreman_openscap-0.7.11.gem
  rubygem-foreman_openscap/foreman_openscap-0.7.13.gem
  rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#2268 Update foreman_openscap to 0.8.6
  rubygem-foreman_openscap/foreman_openscap-0.8.3.gem
  rubygem-foreman_openscap/foreman_openscap-0.8.6.gem
  rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs re-review, Needs testing, RPM

#2363 Update rubygem-foreman_remote_execution to 1.5.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.4.6.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.5.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing

#2364 Update rubygem-foreman_snapshot_management to 1.4.0
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.3.0.gem
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.4.0.gem
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Needs testing, RPM

#2365 Update rubygem-smart_proxy_remote_execution_ssh to 0.2.0
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.1.5.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.2.0.gem
Labels: Needs testing, RPM

#2369 Update rubygem-foreman_ansible to 2.0.2
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.0.1.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.0.2.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM, Waiting on contributor

#2370 Update rubygem-hammer_cli_foreman_openscap to 0.1.6
  packages/plugins/rubygem-hammer_cli_foreman_openscap/hammer_cli_foreman_openscap-0.1.5.gem
  packages/plugins/rubygem-hammer_cli_foreman_openscap/hammer_cli_foreman_openscap-0.1.6.gem
  packages/plugins/rubygem-hammer_cli_foreman_openscap/rubygem-hammer_cli_foreman_openscap.spec
Labels: Needs testing, RPM

#2371 Update rubygem-foreman_ansible to 2.0.4
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.0.2.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.0.4.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#2373 bump rubygem-katello requires on foreman-tasks
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#2368 Refs #21520 - Update rubygem-fog-vsphere to 2.1.0
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-1.13.1.gem
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-2.1.0.gem
  packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec
Labels: Needs testing, RPM

#2374 Update foreman gem dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2378 Fix a typo in foreman-proxy user comment
  packages/foreman/foreman-proxy/foreman-proxy.spec
Labels: Needs testing, Not yet reviewed, RPM

#2379 Match the foreman-proxy user description to RPMs
  debian/stretch/foreman-proxy/postinst
  debian/xenial/foreman-proxy/postinst
Labels: Needs testing

#2380 Update rubygem-foreman_virt_who_configure to 0.2.0
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.1.9.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.2.0.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Needs testing, RPM

#2381 Handle .ansible symlinks
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
Labels: Needs testing, RPM

#2376 Refs #21520 - Update rubygem-fog-vsphere to 2.1.0
  rubygem-fog-vsphere/fog-vsphere-1.13.1.gem
  rubygem-fog-vsphere/fog-vsphere-2.1.0.gem
  rubygem-fog-vsphere/rubygem-fog-vsphere.spec
Labels: Needs testing, RPM

#2389 Update hammer_cli_katello to 0.12.1
  katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.11.5.1.gem
  katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.12.1.gem
  katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM

#2390 Update hammer_cli_katello to 0.12.1
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.12.0.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.12.1.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#2384 Update rubygem-foreman_templates to 6.0.0
  packages/plugins/rubygem-foreman_templates/foreman_templates-5.0.1.gem
  packages/plugins/rubygem-foreman_templates/foreman_templates-6.0.0.gem
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
Labels: Needs testing, RPM

#2391 Make bump_rpm.sh a bit more user friendly
  bump_rpm.sh
Labels: Needs testing, Not yet reviewed

#2392 Update rubygem-fog-ovirt to 1.0.3
  packages/foreman/rubygem-fog-ovirt/fog-ovirt-1.0.2.gem
  packages/foreman/rubygem-fog-ovirt/fog-ovirt-1.0.3.gem
  packages/foreman/rubygem-fog-ovirt/rubygem-fog-ovirt.spec
Labels: Needs testing, RPM

#2375 Fixes #16003 - add unattended option to remove
  packages/katello/katello/katello-remove
Labels: Needs testing, RPM

#2393 Update katello for GA
  katello/katello-installer/katello-installer-3.6.0.rc2.tar.gz
  katello/katello-installer/katello-installer-3.6.0.tar.gz
  katello/katello-installer/katello-installer-base.spec
  katello/katello-repos/katello-client.repo
  katello/katello-repos/katello-repos.spec
  katello/katello-repos/katello.repo
  katello/katello/katello.spec
  katello/rubygem-katello/katello-3.6.0.1.rc2.gem
  katello/rubygem-katello/katello-3.6.0.gem
  katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#2396 Release 1.17.0
  debian/stretch/foreman-installer/build_vars.sh
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/build_vars.sh
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/build_vars.sh
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: DEB, Needs testing, Not yet reviewed

#2395 Release 1.17.0
  foreman-installer/foreman-installer-1.17.0-RC2.tar.bz2
  foreman-installer/foreman-installer-1.17.0.tar.bz2
  foreman-installer/foreman-installer.spec
  foreman-proxy/foreman-proxy-1.17.0-RC2.tar.bz2
  foreman-proxy/foreman-proxy-1.17.0.tar.bz2
  foreman-proxy/foreman-proxy.spec
  foreman-selinux/foreman-selinux-1.17.0-RC2.tar.bz2
  foreman-selinux/foreman-selinux-1.17.0.tar.bz2
  foreman-selinux/foreman-selinux.spec
  foreman/foreman-1.17.0-RC2.tar.bz2
  foreman/foreman-1.17.0.tar.bz2
  foreman/foreman.spec
Labels: Needs testing, RPM

#2372 Remove foreman_host_rundeck
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_host_rundeck/foreman_host_rundeck-0.0.2.gem
  packages/plugins/rubygem-foreman_host_rundeck/rubygem-foreman_host_rundeck.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#2350 fixes #23124 - validates services on prior to backup start
  packages/katello/katello/backup.rb
Labels: Needs testing, RPM

#2403 Remove ruby-foreman-host-rundeck
  plugins/ruby-foreman-host-rundeck/debian/changelog
  plugins/ruby-foreman-host-rundeck/debian/compat
  plugins/ruby-foreman-host-rundeck/debian/control
  plugins/ruby-foreman-host-rundeck/debian/copyright
  plugins/ruby-foreman-host-rundeck/debian/gem.list
  plugins/ruby-foreman-host-rundeck/debian/install
  plugins/ruby-foreman-host-rundeck/debian/postinst
  plugins/ruby-foreman-host-rundeck/debian/rules
  plugins/ruby-foreman-host-rundeck/debian/source/format
  plugins/ruby-foreman-host-rundeck/foreman_host_rundeck.rb
Labels: DEB, Needs testing, Not yet reviewed

#2402 Add the el7-tfm-ror51 repo to el7-scl.cfg
  mock/el7-scl.cfg
Labels: Needs testing, RPM

#2323 Add redhat_access plugin
  comps/comps-foreman-plugins-rhel7.xml
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-redhat_access/redhat_access-2.1.4.gem
  packages/katello/rubygem-redhat_access/rubygem-redhat_access.spec
  packages/katello/rubygem-redhat_access_lib/redhat_access_lib-1.1.4.gem
  packages/katello/rubygem-redhat_access_lib/rubygem-redhat_access_lib.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#2407 Change build_vars back to develop
  debian/stretch/foreman-installer/build_vars.sh
  debian/stretch/foreman-proxy/build_vars.sh
  debian/stretch/foreman/build_vars.sh
Labels: DEB, Needs testing

#2311 fixes #23107 - skips dropping database upon incremental restore
  packages/katello/katello/backup.rb
  packages/katello/katello/restore.rb
Labels: Needs testing, RPM

#2408 update fog-vsphere to 2.1.1 [rpm]
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-2.1.0.gem
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-2.1.1.gem
  packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec
Labels: Needs testing, RPM

#2406 add sles11 katello client support
  comps/comps-katello-client-sles11.xml
Labels: Needs testing, RPM

#2411 Refs #23217 - Exclude package.json and webpack in RPM
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#2410 katello-host-tools support sles 11 & 12
  packages/katello/katello-host-tools/katello-host-tools-3.2.0.tar.gz
  packages/katello/katello-host-tools/katello-host-tools-3.2.1.tar.gz
  packages/katello/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#2414 Add Public GPG key for 3.6
  katello/katello-repos/RPM-GPG-KEY-katello-2015
  katello/katello-repos/RPM-GPG-KEY-katello-3.6
  katello/katello-repos/katello-repos.spec
Labels: Needs testing, RPM

#2343 Refs #23030 - Switch to mongodb from rh-mongodb34
  packages/katello/katello/katello-remove
  packages/katello/katello/katello-service
  packages/katello/katello/katello-service-bash_completion.sh
  packages/katello/katello/katello.spec
  packages/katello/katello/restore.rb
  packages/katello/katello/service-wait
Labels: Needs testing, RPM

#2415 Bump katello release
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#2416 Use python2 on Fedora 26 for katello-host-tools
  packages/katello/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#2299 Switch Katello to Pulp 2.16 stable
  packages/katello/katello-repos/gofer-copr.repo
  packages/katello/katello-repos/katello-repos.spec
Labels: Needs testing, RPM

#2422 Add nodejs-react-router package
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/nodejs-react-router/asap-2.0.6.tgz
  packages/foreman/nodejs-react-router/core-js-1.2.7.tgz
  packages/foreman/nodejs-react-router/encoding-0.1.12.tgz
  packages/foreman/nodejs-react-router/fbjs-0.8.16.tgz
  packages/foreman/nodejs-react-router/history-4.7.2.tgz
  packages/foreman/nodejs-react-router/hoist-non-react-statics-2.5.0.tgz
  packages/foreman/nodejs-react-router/iconv-lite-0.4.21.tgz
  packages/foreman/nodejs-react-router/invariant-2.2.4.tgz
  packages/foreman/nodejs-react-router/is-stream-1.1.0.tgz
  packages/foreman/nodejs-react-router/isarray-0.0.1.tgz
  packages/foreman/nodejs-react-router/isomorphic-fetch-2.2.1.tgz
  packages/foreman/nodejs-react-router/js-tokens-3.0.2.tgz
  packages/foreman/nodejs-react-router/loose-envify-1.3.1.tgz
  packages/foreman/nodejs-react-router/node-fetch-1.7.3.tgz
  packages/foreman/nodejs-react-router/nodejs-react-router.spec
  packages/foreman/nodejs-react-router/object-assign-4.1.1.tgz
  packages/foreman/nodejs-react-router/path-to-regexp-1.7.0.tgz
  packages/foreman/nodejs-react-router/promise-7.3.1.tgz
  packages/foreman/nodejs-react-router/prop-types-15.6.1.tgz
  packages/foreman/nodejs-react-router/react-router-4.2.0-registry.npmjs.org.tgz
  packages/foreman/nodejs-react-router/react-router-4.2.0.tgz
  packages/foreman/nodejs-react-router/resolve-pathname-2.2.0.tgz
  packages/foreman/nodejs-react-router/safer-buffer-2.1.2.tgz
  packages/foreman/nodejs-react-router/setimmediate-1.0.5.tgz
  packages/foreman/nodejs-react-router/ua-parser-js-0.7.17.tgz
  packages/foreman/nodejs-react-router/value-equal-0.4.0.tgz
  packages/foreman/nodejs-react-router/warning-3.0.0.tgz
  packages/foreman/nodejs-react-router/whatwg-fetch-2.0.4.tgz
  rel-eng/tito.props
Labels: Needs testing, RPM

#2419 foreman_webpack_plugin macro in foreman.spec
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2397 Use more modern RPM macros in foreman-proxy.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
Labels: Needs testing, RPM

#2428 Bump nodejs-dotenv to 5.0.1
  packages/foreman/nodejs-dotenv/dotenv-2.0.0.tgz
  packages/foreman/nodejs-dotenv/dotenv-5.0.1.tgz
  packages/foreman/nodejs-dotenv/nodejs-dotenv.spec
Labels: Needs testing, RPM

#2409 Update rubygem-safemode to 1.3.5
  packages/foreman/rubygem-safemode/rubygem-safemode.spec
  packages/foreman/rubygem-safemode/safemode-1.3.4.gem
  packages/foreman/rubygem-safemode/safemode-1.3.5.gem
Labels: Needs testing, RPM

#2426 update smart_proxy_dhcp_device42 to 1.0.7
  packages/plugins/rubygem-smart_proxy_dhcp_device42/rubygem-smart_proxy_dhcp_device42.spec
  packages/plugins/rubygem-smart_proxy_dhcp_device42/smart_proxy_dhcp_device42-1.0.4.gem
  packages/plugins/rubygem-smart_proxy_dhcp_device42/smart_proxy_dhcp_device42-1.0.7.gem
Labels: Needs testing, RPM

#2434 Update foreman_memcache to 0.1.0
  packages/plugins/rubygem-foreman_memcache/foreman_memcache-0.0.6.gem
  packages/plugins/rubygem-foreman_memcache/foreman_memcache-0.1.0.gem
  packages/plugins/rubygem-foreman_memcache/rubygem-foreman_memcache.spec
Labels: Needs testing, RPM

#2436 Fix webpack
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2304 Add nodejs-react-json-tree package
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/nodejs-react-json-tree/asap-2.0.6.tgz
  packages/plugins/nodejs-react-json-tree/babel-runtime-6.26.0.tgz
  packages/plugins/nodejs-react-json-tree/base16-1.0.0.tgz
  packages/plugins/nodejs-react-json-tree/core-js-1.2.7.tgz
  packages/plugins/nodejs-react-json-tree/core-js-2.5.5.tgz
  packages/plugins/nodejs-react-json-tree/encoding-0.1.12.tgz
  packages/plugins/nodejs-react-json-tree/fbjs-0.8.16.tgz
  packages/plugins/nodejs-react-json-tree/iconv-lite-0.4.21.tgz
  packages/plugins/nodejs-react-json-tree/is-stream-1.1.0.tgz
  packages/plugins/nodejs-react-json-tree/isomorphic-fetch-2.2.1.tgz
  packages/plugins/nodejs-react-json-tree/js-tokens-3.0.2.tgz
  packages/plugins/nodejs-react-json-tree/lodash.curry-4.1.1.tgz
  packages/plugins/nodejs-react-json-tree/lodash.flow-3.5.0.tgz
  packages/plugins/nodejs-react-json-tree/loose-envify-1.3.1.tgz
  packages/plugins/nodejs-react-json-tree/node-fetch-1.7.3.tgz
  packages/plugins/nodejs-react-json-tree/nodejs-react-json-tree.spec
  packages/plugins/nodejs-react-json-tree/object-assign-4.1.1.tgz
  packages/plugins/nodejs-react-json-tree/promise-7.3.1.tgz
  packages/plugins/nodejs-react-json-tree/prop-types-15.6.1.tgz
  packages/plugins/nodejs-react-json-tree/pure-color-1.3.0.tgz
  packages/plugins/nodejs-react-json-tree/react-base16-styling-0.5.3.tgz
  packages/plugins/nodejs-react-json-tree/react-json-tree-0.11.0-registry.npmjs.org.tgz
  packages/plugins/nodejs-react-json-tree/react-json-tree-0.11.0.tgz
  packages/plugins/nodejs-react-json-tree/regenerator-runtime-0.11.1.tgz
  packages/plugins/nodejs-react-json-tree/safer-buffer-2.1.2.tgz
  packages/plugins/nodejs-react-json-tree/setimmediate-1.0.5.tgz
  packages/plugins/nodejs-react-json-tree/ua-parser-js-0.7.17.tgz
  packages/plugins/nodejs-react-json-tree/whatwg-fetch-2.0.4.tgz
  rel-eng/tito.props
Labels: Needs testing, RPM

#2437 Correct nodejs-core-js in katello comps
  comps/comps-katello-server-rhel7.xml
Labels: Needs testing, RPM

#2440 Update rubygem-smart_proxy_dhcp_infoblox to 0.0.13
  packages/plugins/rubygem-smart_proxy_dhcp_infoblox/rubygem-smart_proxy_dhcp_infoblox.spec
  packages/plugins/rubygem-smart_proxy_dhcp_infoblox/smart_proxy_dhcp_infoblox-0.0.12.gem
  packages/plugins/rubygem-smart_proxy_dhcp_infoblox/smart_proxy_dhcp_infoblox-0.0.13.gem
Labels: Needs testing, RPM

#2438 Refs #23423 - Loosen foreman javascript dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#2387 Update foreman_templates to 6.0.0
  plugins/ruby-foreman-templates/debian/changelog
  plugins/ruby-foreman-templates/debian/control
  plugins/ruby-foreman-templates/debian/gem.list
  plugins/ruby-foreman-templates/debian/rules
  plugins/ruby-foreman-templates/foreman_templates.rb
Labels: DEB, Needs re-review, Needs testing

#2432 Update rubygem-katello spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#2398 Update rubygem-sequel to 5.7.1
  packages/foreman/rubygem-sequel/rubygem-sequel.spec
  packages/foreman/rubygem-sequel/sequel-4.20.0.gem
  packages/foreman/rubygem-sequel/sequel-5.7.1.gem
Labels: Needs testing, RPM

#2286 add ansiblerole-insights-client
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/ansiblerole-insights-client/ansiblerole-insights-client.spec
  packages/plugins/ansiblerole-insights-client/insights-client-1.5.tar.gz
  rel-eng/tito.props
Labels: Needs testing, RPM

#2430 Document building packages on koji via obal
  README.md
Labels: Needs testing, RPM
