Repository theforeman/foreman-packaging, pull requests merged in 2018-10, with the labels that each got.

#2910 Require current selinux policy in foreman-selinux
  packages/foreman/foreman-selinux/foreman-selinux.spec
Labels: Needs testing, RPM, Waiting on contributor

#2998 Added stripping for mmv-statsd
  packages/foreman/pcp-mmvstatsd/pcp-mmvstatsd.spec
Labels: Needs testing, RPM

#3045 update deface to 1.3.2
  plugins/ruby-foreman-deface/debian/changelog
  plugins/ruby-foreman-deface/debian/gem.list
  plugins/ruby-foreman-deface/foreman_deface.rb
Labels: DEB

#3046 rubygem-angular-rails-templates-fips - enable FIPS
  packages/plugins/rubygem-angular-rails-templates/enable-fips.patch
  packages/plugins/rubygem-angular-rails-templates/rubygem-angular-rails-templates.spec
Labels: Needs testing, RPM

#3043 Add dependent client repos to foreman-client-release
  package_manifest.yaml
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-release/pulp.repo
  packages/foreman/foreman-release/qpid-copr.repo
  packages/foreman/foreman-release/subscription-manager.repo
  repoclosure/yum.conf
  repoclosure/yum_el6.conf
Labels: Needs testing, RPM

#3044 Update rubygem-deface to 1.3.2
  packages/plugins/rubygem-deface/deface-1.2.0.gem
  packages/plugins/rubygem-deface/deface-1.3.2.gem
  packages/plugins/rubygem-deface/rubygem-deface.spec
Labels: Needs testing, RPM

#3050 [DEB] Updated hammer-cli-foreman-templates to 0.1.2
  dependencies/bionic/hammer_cli_foreman_templates/changelog
  dependencies/stretch/hammer_cli_foreman_templates/changelog
  dependencies/xenial/hammer_cli_foreman_templates/changelog
Labels: DEB, Needs testing, Not yet reviewed

#3049 Fix client EL6 adding sub-man repo and pulp repoclosure
  package_manifest.yaml
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-release/subscription-manager.repo
  repoclosure/yum.conf
  repoclosure/yum_el6.conf
Labels: Needs testing, RPM

#3056 Bootdisk v13 release [RPM]
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-12.0.0.gem
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-13.0.0.gem
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
Labels: Needs testing, RPM

#2986 refs #23211 - foreman-proxy: puppetca token whitelisting
  packages/foreman/foreman-proxy/foreman-proxy.spec
Labels: Needs testing, RPM

#3055 Fixes #24927 - Fix sending signal after logrotate
  debian/bionic/foreman-proxy/logrotate
  debian/stretch/foreman-proxy/logrotate
  debian/xenial/foreman-proxy/logrotate
Labels: DEB, Needs testing

#3066 Update rubygem-fog-proxmox to 0.5.2
  packages/plugins/rubygem-fog-proxmox/fog-proxmox-0.5.1.gem
  packages/plugins/rubygem-fog-proxmox/fog-proxmox-0.5.2.gem
  packages/plugins/rubygem-fog-proxmox/rubygem-fog-proxmox.spec
Labels: Needs testing, RPM

#2952 Refs #24874 - update secure_headers to 6.0.0
  packages/foreman/rubygem-secure_headers/rubygem-secure_headers.spec
  packages/foreman/rubygem-secure_headers/secure_headers-5.0.5.gem
  packages/foreman/rubygem-secure_headers/secure_headers-6.0.0.gem
Labels: Needs testing, RPM

#3072 Fix foreman-client repoclosure for Fedoras
  package_manifest.yaml
Labels: Needs testing, RPM

#3073 Add missing f27 and f28 updates to foreman client repoclosures
  package_manifest.yaml
Labels: Needs testing, RPM

#3076 Update foreman_remote_execution to 1.6.4 [deb]
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing, Not yet reviewed

#3057 Bootdisk v13.0.0 [DEB]
  plugins/ruby-foreman-bootdisk/debian/changelog
  plugins/ruby-foreman-bootdisk/debian/gem.list
  plugins/ruby-foreman-bootdisk/foreman_bootdisk.rb
Labels: Needs testing, Not yet reviewed

#3074 Drop java dependency in katello meta RPM
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#3060 Remove Katello client in favor of Foreman client
  comps/comps-katello-client-fedora27.xml
  comps/comps-katello-client-fedora28.xml
  comps/comps-katello-client-rhel5.xml
  comps/comps-katello-client-rhel6.xml
  comps/comps-katello-client-rhel7.xml
  comps/comps-katello-client-sles11.xml
  comps/comps-katello-client-sles12.xml
  package_manifest.yaml
  packages/client/katello-host-tools/katello-host-tools-3.3.5.tar.gz
  packages/client/katello-host-tools/katello-host-tools.spec
  rel-eng/releasers.conf
  rel-eng/tito.props
  repoclosure/yum.conf
  repoclosure/yum_el5.conf
  repoclosure/yum_el6.conf
  repoclosure/yum_el7.conf
  repoclosure/yum_f27.conf
  repoclosure/yum_f28.conf
Labels: Needs testing, RPM

#3067 Adds logging-journald to nonscl
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
Labels: Needs testing, RPM

#3068 Update rubygem-dynflow to 1.1.1
  packages/foreman/rubygem-dynflow/dynflow-1.1.0.gem
  packages/foreman/rubygem-dynflow/dynflow-1.1.1.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing, RPM

#3081 Reformat the manifest
  package_manifest.yaml
Labels: Needs testing, RPM

#3070 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Waiting on contributor

#3080 Update foreman-tasks to 0.14.1 [deb]
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Not yet reviewed

#3079 Update rubygem-foreman-tasks to 0.14.1 [rpm]
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.14.0.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.14.1.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, Not yet reviewed, RPM

#3082 Release Katello 3.7.1
  packages/katello/katello-installer/katello-installer-3.7.0.tar.gz
  packages/katello/katello-installer/katello-installer-3.7.1.tar.gz
  packages/katello/katello-installer/katello-installer-base.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.7.0.gem
  packages/katello/rubygem-katello/katello-3.7.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#3083 Update katello package dependencies
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#3090 Update rubygem-foreman_scap_client to 0.4.0
  packages/plugins/rubygem-foreman_scap_client/foreman_scap_client-0.3.0.gem
  packages/plugins/rubygem-foreman_scap_client/foreman_scap_client-0.4.0.gem
  packages/plugins/rubygem-foreman_scap_client/rubygem-foreman_scap_client.spec
Labels: Needs testing, Not yet reviewed, RPM

#3088 Update rubygem-smart_proxy_openscap to 0.7.0
  packages/plugins/rubygem-smart_proxy_openscap/rubygem-smart_proxy_openscap.spec
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.6.11.gem
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.7.0.gem
Labels: Needs testing, RPM

#3084 Bump journald-logger, journad-native and logging-journald
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-journald-logger/journald-logger-2.0.3.gem
  packages/foreman/rubygem-journald-logger/journald-logger-2.0.4.gem
  packages/foreman/rubygem-journald-logger/rubygem-journald-logger.spec
  packages/foreman/rubygem-journald-native/journald-native-1.0.10.gem
  packages/foreman/rubygem-journald-native/journald-native-1.0.11.gem
  packages/foreman/rubygem-journald-native/rubygem-journald-native.spec
  packages/foreman/rubygem-logging-journald/logging-journald-1.0.0.gem
  packages/foreman/rubygem-logging-journald/logging-journald-2.0.0.gem
  packages/foreman/rubygem-logging-journald/rubygem-logging-journald.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3095 Updated foreman logging dependency
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#3100 Refs #24928 - ignore JS maps in webpack requires/provides
  packages/foreman/foreman/foreman.provreq
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#3099 add ruby-jwt recommendation to foreman-proxy
  debian/bionic/foreman-proxy/control
  debian/stretch/foreman-proxy/control
  debian/xenial/foreman-proxy/control
Labels: DEB, Needs testing

#3103 Add 1.20 to template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Needs testing

#3104 Remove incorrect systemd service alias
  packages/foreman/foreman/foreman.service
  packages/foreman/foreman/foreman.spec
Labels: Needs testing

#3109 Update mock to include missing repos
  mock/el7-nonscl.cfg
  mock/el7-scl.cfg
Labels: Needs testing, RPM

#3114 Update rubygem-foreman_maintain to 0.2.12
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.11.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.12.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#3118 Update rubygem-foreman_maintain to 0.2.12
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.11.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.12.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM

#3110 Bump katello versions to 3.10
  package_manifest.yaml
  packages/katello/katello-installer-base/katello-installer-base.spec
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#3111 Release Katello RC1
  package_manifest.yaml
  packages/katello/katello-installer-base/katello-installer-3.9.0.rc1.tar.gz
  packages/katello/katello-installer-base/katello-installer-base.spec
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.9.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#3108 katello-host-tools 3.3.6 release
  packages/client/katello-host-tools/katello-host-tools-3.3.5.tar.gz
  packages/client/katello-host-tools/katello-host-tools-3.3.6.tar.gz
  packages/client/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#3092 Fixes #25195 - Avoid removing mounted filesystems & support for wildcard
  packages/katello/katello/katello-remove
  packages/katello/katello/katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#3101 Update fog-vsphere to 2.4.0
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-2.3.0.gem
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-2.4.0.gem
  packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec
Labels: Needs testing, RPM

#3113 Drop remaining Katello client configs
  comps/comps-foreman-client-rhel7.xml
  package_manifest.yaml
  packages/katello/katello-repos/katello-client.repo
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello-repos/qpid-copr.repo
Labels: Needs testing, RPM

#3097 New subpackage foreman-proxy-journald
  comps/comps-foreman-rhel7.xml
  packages/foreman/foreman-proxy/foreman-proxy.spec
Labels: Needs testing, RPM

#3131 Release katello-installer RC 1.1
  packages/katello/katello-installer-base/katello-installer-3.9.0.rc1.1.tar.gz
  packages/katello/katello-installer-base/katello-installer-3.9.0.rc1.tar.gz
  packages/katello/katello-installer-base/katello-installer-base.spec
Labels: Needs testing

#3132 Update rubygem-hammer_cli to 0.15.0
  packages/foreman/rubygem-hammer_cli/hammer_cli-0.14.0.gem
  packages/foreman/rubygem-hammer_cli/hammer_cli-0.15.0.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
Labels: Needs testing

#3140 update ruby-clamp to 1.1.1-1 for Ubuntu/xenial
  dependencies/xenial/clamp/debian/changelog
  dependencies/xenial/clamp/debian/compat
  dependencies/xenial/clamp/debian/control
  dependencies/xenial/clamp/debian/copyright
  dependencies/xenial/clamp/debian/ruby-clamp.docs
  dependencies/xenial/clamp/debian/ruby-clamp.examples
  dependencies/xenial/clamp/debian/ruby-tests.rake
  dependencies/xenial/clamp/debian/ruby-tests.rb
  dependencies/xenial/clamp/debian/rules
  dependencies/xenial/clamp/debian/source/format
  dependencies/xenial/clamp/debian/watch
Labels: DEB, Needs testing, Not yet reviewed

#3134 Updated hammer_cli to 0.15.0
  dependencies/bionic/hammer_cli/changelog
  dependencies/bionic/hammer_cli/control
  dependencies/stretch/hammer_cli/changelog
  dependencies/stretch/hammer_cli/control
  dependencies/xenial/hammer_cli/changelog
  dependencies/xenial/hammer_cli/control
Labels: Needs testing, Not yet reviewed

#3135 Updated hammer_cli_foreman to 0.15.0
  dependencies/bionic/hammer_cli_foreman/changelog
  dependencies/bionic/hammer_cli_foreman/control
  dependencies/stretch/hammer_cli_foreman/changelog
  dependencies/stretch/hammer_cli_foreman/control
  dependencies/xenial/hammer_cli_foreman/changelog
  dependencies/xenial/hammer_cli_foreman/control
Labels: DEB, Needs testing, Not yet reviewed

#3126 move rubygem-foreman_scap_client to client repos
  comps/comps-foreman-client-fedora27.xml
  comps/comps-foreman-client-fedora28.xml
  comps/comps-foreman-client-rhel5.xml
  comps/comps-foreman-client-rhel6.xml
  comps/comps-foreman-client-rhel7.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.4.0.gem
  packages/client/rubygem-foreman_scap_client/foreman_scap_client.gemspec
  packages/client/rubygem-foreman_scap_client/rubygem-foreman_scap_client.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3141 Release foreman-installer 1.20.0-RC1.1
  debian/bionic/foreman-installer/changelog
  debian/stretch/foreman-installer/changelog
  debian/xenial/foreman-installer/changelog
Labels: Needs testing, Not yet reviewed

#3058 Update rubygem-smart_proxy_dynflow_core to 0.2.1
  packages/plugins/rubygem-smart_proxy_dynflow_core/rubygem-smart_proxy_dynflow_core.spec
  packages/plugins/rubygem-smart_proxy_dynflow_core/smart_proxy_dynflow_core-0.2.0.gem
  packages/plugins/rubygem-smart_proxy_dynflow_core/smart_proxy_dynflow_core-0.2.1.gem
Labels: Needs testing, RPM

#3142 Update rubygem-smart_proxy_dynflow_core to 0.2.1
  packages/plugins/rubygem-smart_proxy_dynflow_core/rubygem-smart_proxy_dynflow_core.spec
  packages/plugins/rubygem-smart_proxy_dynflow_core/smart_proxy_dynflow_core-0.2.0.gem
  packages/plugins/rubygem-smart_proxy_dynflow_core/smart_proxy_dynflow_core-0.2.1.gem
Labels: Needs testing, Not yet reviewed, RPM

#3133 Update rubygem-hammer_cli_foreman to 0.15.0
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.14.0.gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.15.0.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM

#3144 Update rubygem-foreman_openscap to 0.11.0
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.10.4.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.11.0.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#3139 Bump rubygem-hammer_cli_katello to 0.15.0
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.15.0.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Blocked on build, RPM

#3122 Fixes #25289 - Split out Katello and Smart Proxy Cron
  packages/katello/katello/foreman-proxy-content.cron
  packages/katello/katello/katello.cron
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#3115 Update foreman_m2 to 0.0.4
  packages/plugins/rubygem-foreman_m2/foreman_m2-0.0.3.gem
  packages/plugins/rubygem-foreman_m2/foreman_m2-0.0.4.gem
  packages/plugins/rubygem-foreman_m2/rubygem-foreman_m2.spec
Labels: Needs testing, RPM

#3117 Update rubygem-foreman_snapshot_management to 1.5.1
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.5.0.gem
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.5.1.gem
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Needs testing, RPM

#3146 Update rubygem-foreman_hooks to 0.3.15
  packages/plugins/rubygem-foreman_hooks/foreman_hooks-0.3.14.gem
  packages/plugins/rubygem-foreman_hooks/foreman_hooks-0.3.15.gem
  packages/plugins/rubygem-foreman_hooks/rubygem-foreman_hooks.spec
Labels: Needs testing, Not yet reviewed, RPM

#3147 Update rubygem-foreman_hooks to 0.3.15
  packages/plugins/rubygem-foreman_hooks/foreman_hooks-0.3.14.gem
  packages/plugins/rubygem-foreman_hooks/foreman_hooks-0.3.15.gem
  packages/plugins/rubygem-foreman_hooks/rubygem-foreman_hooks.spec
Labels: Needs testing, Not yet reviewed, RPM

#3148 Drop remaining Katello client configs
  comps/comps-foreman-client-rhel7.xml
  packages/katello/katello-repos/katello-client.repo
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello-repos/qpid-copr.repo
Labels: Needs testing, RPM

#3011 insert nightly macro for nightly built packages
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
  packages/katello/katello-installer-base/katello-installer-base.spec
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#3149 build rubygem-foreman_scap_client on EL6+ and Fedora only
  comps/comps-foreman-client-rhel5.xml
  packages/client/rubygem-foreman_scap_client/foreman_scap_client.gemspec
  packages/client/rubygem-foreman_scap_client/rubygem-foreman_scap_client.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3116 Use pulp nightly
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello-repos/katello.repo
Labels: Needs testing, RPM

#3047 Require Foreman selinux the installed selinux-policy
  packages/foreman/foreman-selinux/foreman-selinux.spec
Labels: Needs testing, RPM

#3150 Spec file improvements for rubygem-foreman_ansible
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#3151 Remove JS maps in plugin asset precompile
  packages/foreman/foreman/foreman.spec
Labels: Needs testing

#3152 Correct source map behavior
  packages/katello/rubygem-katello/rubygem-katello.spec
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#3153 Release 1.20.0-RC2
  packages/foreman/foreman-installer/foreman-installer-1.20.0-RC1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-1.20.0-RC2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-1.20.0-RC1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-1.20.0-RC2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-1.20.0-RC1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-1.20.0-RC2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-1.20.0-RC1.tar.bz2
  packages/foreman/foreman/foreman-1.20.0-RC2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#3154 Release 1.20.0-RC2
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: Needs testing, Not yet reviewed

#3098 add foreman-proxy-journald meta package
  debian/bionic/foreman-proxy/control
  debian/stretch/foreman-proxy/control
  debian/xenial/foreman-proxy/control
Labels: DEB, Needs testing
