Repository theforeman/foreman-packaging, pull requests merged in 2018-08, with the labels that each got.

#2799 Switch Foreman specs to use prerelease
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  rel-eng/custom/custom.py
Labels: Needs testing, RPM

#2828 Release katello-client-bootstrap 1.6.0
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.5.1.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.6.0.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap.spec
Labels: Needs testing, RPM

#2826 Update foreman_host_extra_validator to 0.1.0
  packages/plugins/rubygem-foreman_host_extra_validator/foreman_host_extra_validator-0.0.4.gem
  packages/plugins/rubygem-foreman_host_extra_validator/foreman_host_extra_validator-0.1.0.gem
  packages/plugins/rubygem-foreman_host_extra_validator/rubygem-foreman_host_extra_validator.spec
Labels: Needs testing, RPM

#2823 Move foreman-rails repo to foreman-release
  packages/foreman/foreman-release-scl/foreman-release-scl.spec
  packages/foreman/foreman/foreman-rails.gpg
  packages/foreman/foreman/foreman-rails.repo
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2824 [1.19] Move foreman-rails repo to foreman-release
  packages/foreman/foreman-release-scl/foreman-release-scl.spec
  packages/foreman/foreman-release-scl/tfm-ror51.repo
  packages/foreman/foreman/foreman-rails.gpg
  packages/foreman/foreman/foreman-rails.repo
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2829 [1.18] Move foreman-rails repo to foreman-release
  packages/foreman/foreman-release-scl/foreman-release-scl.spec
  packages/foreman/foreman-release-scl/tfm-ror51.repo
  packages/foreman/foreman/foreman-rails.gpg
  packages/foreman/foreman/foreman-rails.repo
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2835 Access Jenkins over HTTPS
  rel-eng/custom/custom.py
  rel-eng/releasers.conf
Labels: Needs testing, RPM

#2820 Enable Fedora 28 builds for katello client
  rel-eng/releasers.conf
  repoclosure/yum.conf
Labels: Needs testing, RPM

#2825 source_files arg to fetchbuilder
  rel-eng/custom/custom.py
Labels: Needs testing, RPM

#2831 [1.17] Move foreman-rails repo to foreman-release
  foreman-release-scl/foreman-release-scl.spec
  foreman/foreman-rails.gpg
  foreman/foreman-rails.repo
  foreman/foreman.spec
Labels: Needs testing, RPM

#2817 Update rubygem-foreman-tasks to 0.13.4
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.13.3.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.13.4.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing

#2815 Update rubygem-foreman-tasks to 0.14.0
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.13.3.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.14.0.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#2818 Update rubygem-foreman_maintain to 0.2.6
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.5.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.6.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing

#2839 Release 1.17.2
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: Needs testing, Not yet reviewed

#2833 Correct foreman-rails repo definition
  packages/foreman/foreman/foreman-rails.gpg
  packages/foreman/foreman/foreman-rails.repo
Labels: Needs testing, RPM

#2847 Release 1.19.0-RC2
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: Needs testing, Not yet reviewed

#2845 Release 1.19.0-RC2
  packages/foreman/foreman-installer/foreman-installer-1.19.0-RC1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-1.19.0-RC2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-1.19.0-RC1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-1.19.0-RC2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-selinux/foreman-selinux-1.19.0-RC1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-1.19.0-RC2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-1.19.0-RC1.tar.bz2
  packages/foreman/foreman/foreman-1.19.0-RC2.tar.bz2
  packages/foreman/foreman/foreman-rails.gpg
  packages/foreman/foreman/foreman-rails.repo
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed

#2846 adds webpack-bundle-analyzer to ignore whitelist
  update-requirements
Labels: Needs testing, Not yet reviewed, RPM

#2848 Katello rc2
  packages/katello/katello-installer/katello-installer-3.8.0.rc1.tar.gz
  packages/katello/katello-installer/katello-installer-3.8.0.rc2.tar.gz
  packages/katello/katello-installer/katello-installer-base.spec
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.8.0.rc1.gem
  packages/katello/rubygem-katello/katello-3.8.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#2842 "fix" fetchbuilder's interaction with rubygem-hammer_cli_katello
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM

#2838 Release 1.17.3
  foreman-installer/foreman-installer-1.17.1.tar.bz2
  foreman-installer/foreman-installer-1.17.3.tar.bz2
  foreman-installer/foreman-installer.spec
  foreman-proxy/foreman-proxy-1.17.1.tar.bz2
  foreman-proxy/foreman-proxy-1.17.3.tar.bz2
  foreman-proxy/foreman-proxy.spec
  foreman-selinux/foreman-selinux-1.17.1.tar.bz2
  foreman-selinux/foreman-selinux-1.17.3.tar.bz2
  foreman-selinux/foreman-selinux.spec
  foreman/foreman-1.17.1.tar.bz2
  foreman/foreman-1.17.3.tar.bz2
  foreman/foreman.spec
Labels: Needs testing, RPM

#2837 Discovery 13.0.1 - RPM
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-12.0.2.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-13.0.1.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, RPM

#2841 Update foreman_scc_manager to 1.4.0
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.3.1.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.4.0.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM

#2827 Include redhat_access plugin static assets in the spec
  packages/katello/rubygem-redhat_access/rubygem-redhat_access.spec
Labels: Needs testing, RPM

#2851 Blacklist highlight.js npm package
  update-requirements
Labels: Needs testing, RPM

#2855 Update foreman-tasks to 0.11.3 [1.17/deb]
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB, Needs testing, Not yet reviewed

#2859 Update foreman_remote_execution to 1.5.5
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing, Not yet reviewed

#2852 Blacklist raw-loader and remarkable npm packages
  update-requirements
Labels: Needs testing, Not yet reviewed, RPM

#2840 [1.18] Fix foreman spec
  packages/foreman/foreman/foreman-rails.gpg
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2853 Handle GPG checking after branching
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2858 Update rubygem-foreman_remote_execution to 1.5.5
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.5.4.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.5.5.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#2863 Release 1.18.1
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: DEB, Needs testing, Not yet reviewed

#2864 Update rubygem-foreman_remote_execution to 1.5.5 (#2858)
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.5.4.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.5.5.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing

#2865 Update rubygem-foreman_remote_execution to 1.5.5 (#2858)
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.5.4.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.5.5.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing

#2776 Update foreman_ansible_core to 2.1.1
  dependencies/bionic/foreman_ansible_core/changelog
  dependencies/bionic/foreman_ansible_core/control
  dependencies/stretch/foreman_ansible_core/changelog
  dependencies/stretch/foreman_ansible_core/control
  dependencies/xenial/foreman_ansible_core/changelog
  dependencies/xenial/foreman_ansible_core/control
Labels: DEB, Needs testing, Not yet reviewed

#2721 Update foreman_ansible to 2.2.5
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/control
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/debian/install
  plugins/ruby-foreman-ansible/debian/postinst
  plugins/ruby-foreman-ansible/debian/rules
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: DEB, Needs testing, Not yet reviewed

#2867 Update rubygem-foreman_maintain to 0.2.7
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.6.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.7.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#2862 Release 1.18.1
  packages/foreman/foreman-installer/foreman-installer-1.18.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-1.18.1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-1.18.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-1.18.1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-selinux/foreman-selinux-1.18.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-1.18.1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-1.18.0.tar.bz2
  packages/foreman/foreman/foreman-1.18.1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2866 Add rubygem-fast_gettext to plugins nonscl
  package_manifest.yaml
  rel-eng/tito.props
Labels: Needs testing, RPM

#2816 Update foreman-tasks to 0.14.0
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Blocked on build, Needs testing, Not yet reviewed

#2861 Update foreman_remote_execution to 1.6.1
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/control
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB, Needs testing, Not yet reviewed

#2875 Update hammer_cli to 0.13.1
  dependencies/bionic/hammer_cli/changelog
  dependencies/stretch/hammer_cli/changelog
  dependencies/xenial/hammer_cli/changelog
Labels: DEB, Needs testing, Not yet reviewed

#2876 Update hammer_cli_foreman to 0.13.2
  dependencies/bionic/hammer_cli_foreman/changelog
  dependencies/stretch/hammer_cli_foreman/changelog
  dependencies/xenial/hammer_cli_foreman/changelog
Labels: DEB, Needs testing, Not yet reviewed

#2873 Update rubygem-hammer_cli to 0.13.1
  packages/foreman/rubygem-hammer_cli/hammer_cli-0.13.0.gem
  packages/foreman/rubygem-hammer_cli/hammer_cli-0.13.1.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
Labels: Needs testing, Not yet reviewed, RPM

#2874 Update rubygem-hammer_cli_foreman to 0.13.2
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.13.1.gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.13.2.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM

#2869 Update rubygem-foreman_ansible_core to 2.1.2
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-2.1.1.gem
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-2.1.2.gem
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
Labels: Needs testing, RPM

#2870 Update rubygem-foreman_ansible to 2.2.6
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.5.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.6.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, Not yet reviewed, RPM

#2821 Add Foreman client repositories
  comps/comps-foreman-client-fedora27.xml
  comps/comps-foreman-client-fedora28.xml
  comps/comps-foreman-client-rhel5.xml
  comps/comps-foreman-client-rhel6.xml
  comps/comps-foreman-client-rhel7.xml
  comps/comps-foreman-client-sles11.xml
  comps/comps-foreman-client-sles12.xml
  package_manifest.yaml
  rel-eng/releasers.conf
  rel-eng/tito.props
Labels: Needs testing, RPM

#2834 Enable packaging diffing for release
  package_manifest.yaml
Labels: Needs testing, RPM

#2878 Add Foreman client repoclosure config
  package_manifest.yaml
  repoclosure/yum.conf
  repoclosure/yum_el5.conf
  repoclosure/yum_el6.conf
  repoclosure/yum_el7.conf
  repoclosure/yum_f27.conf
  repoclosure/yum_f28.conf
Labels: Needs testing, RPM

#2877 Update rails-i18n to 5.1.1
  packages/foreman/rubygem-rails-i18n/rails-i18n-5.0.4.gem
  packages/foreman/rubygem-rails-i18n/rails-i18n-5.1.1.gem
  packages/foreman/rubygem-rails-i18n/rubygem-rails-i18n.spec
Labels: Needs testing, RPM

#2879 Switch Katello to pulp 2.17 beta
  packages/katello/katello-repos/katello-repos.spec
Labels: Needs testing, RPM

#2854 Release 1.19.0-RC3
  packages/foreman/foreman-installer/foreman-installer-1.19.0-RC2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-1.19.0-RC3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-1.19.0-RC2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-1.19.0-RC3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-selinux/foreman-selinux-1.19.0-RC2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-1.19.0-RC3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-1.19.0-RC2.tar.bz2
  packages/foreman/foreman/foreman-1.19.0-RC3.tar.bz2
  packages/foreman/foreman/foreman-plugins.repo
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2884 Remove extra package http-parser
  comps/comps-foreman-rhel7.xml
  extras/extras-foreman-rhel7-x86_64
Labels: Needs testing, RPM

#2882 Fix hammer nightly
  package_manifest.yaml
  rel-eng/custom/custom.py
Labels: Needs testing, RPM

#2886 Release Katello 3.8.0 RC3
  packages/katello/katello-installer/katello-installer-3.8.0.rc2.tar.gz
  packages/katello/katello-installer/katello-installer-3.8.0.rc3.tar.gz
  packages/katello/katello-installer/katello-installer-base.spec
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.8.0.rc2.gem
  packages/katello/rubygem-katello/katello-3.8.0.rc3.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#2887 Remove rubygem-jquery_pwstrength_bootstrap_4
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-jquery_pwstrength_bootstrap_4/jquery_pwstrength_bootstrap_4-1.2.2.gem
  packages/foreman/rubygem-jquery_pwstrength_bootstrap_4/rubygem-jquery_pwstrength_bootstrap_4.spec
  packages/foreman/tfm/tfm.spec
  rel-eng/tito.props
Labels: Needs testing, Not yet reviewed, RPM

#2888 Disable gpg check for 1.19 plugins repo
  packages/foreman/foreman/foreman-plugins.repo
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#2881 Update rubygem-foreman_maintain to 0.2.8
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.7.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.2.8.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#2885 Remove the dependency on SCLo
  comps/comps-foreman-rhel7.xml
  extras/extras-foreman-rhel7-x86_64
  mock/el7-scl.cfg
  package_manifest.yaml
  packages/foreman/foreman-release-scl/foreman-release-scl.spec
  repoclosure/yum.conf
  repoclosure/yum_el7.conf
Labels: Needs testing, RPM

#2894 Update smart_proxy_omaha to 0.0.5
  packages/plugins/rubygem-smart_proxy_omaha/rubygem-smart_proxy_omaha.spec
  packages/plugins/rubygem-smart_proxy_omaha/smart_proxy_omaha-0.0.4.gem
  packages/plugins/rubygem-smart_proxy_omaha/smart_proxy_omaha-0.0.5.gem
Labels: Needs testing, RPM

#2896 Update foreman_wreckingball to 3.0.1
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-3.0.0.gem
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-3.0.1.gem
  packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
Labels: Needs testing, RPM

#2901 Updated hammer-cli to 0.14.0
  dependencies/bionic/hammer_cli/changelog
  dependencies/stretch/hammer_cli/changelog
  dependencies/xenial/hammer_cli/changelog
Labels: DEB, Needs testing, Not yet reviewed

#2900 Update hammer-cli-foreman to 0.14.0
  dependencies/bionic/hammer_cli_foreman/changelog
  dependencies/bionic/hammer_cli_foreman/control
  dependencies/stretch/hammer_cli_foreman/changelog
  dependencies/stretch/hammer_cli_foreman/control
  dependencies/xenial/hammer_cli_foreman/changelog
  dependencies/xenial/hammer_cli_foreman/control
Labels: DEB, Needs testing, Not yet reviewed

#2906 Release 1.17.4
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: DEB, Needs testing, Not yet reviewed

#2905 Release 1.17.4
  foreman-installer/foreman-installer-1.17.3.tar.bz2
  foreman-installer/foreman-installer-1.17.4.tar.bz2
  foreman-installer/foreman-installer.spec
  foreman-proxy/foreman-proxy-1.17.3.tar.bz2
  foreman-proxy/foreman-proxy-1.17.4.tar.bz2
  foreman-proxy/foreman-proxy.spec
  foreman-selinux/foreman-selinux-1.17.3.tar.bz2
  foreman-selinux/foreman-selinux-1.17.4.tar.bz2
  foreman-selinux/foreman-selinux.spec
  foreman/foreman-1.17.3.tar.bz2
  foreman/foreman-1.17.4.tar.bz2
  foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#2891 Move REX .ssh directory to /var/lib/foreman-proxy
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/ruby-smart-proxy-remote-execution-ssh.postinst
Labels: DEB, Needs testing, Not yet reviewed

#2897 Update rubygem-hammer_cli to 0.14.0
  packages/foreman/rubygem-hammer_cli/hammer_cli-0.13.1.gem
  packages/foreman/rubygem-hammer_cli/hammer_cli-0.14.0.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
Labels: Needs testing, Not yet reviewed, RPM

#2898 Update rubygem-hammer_cli_foreman to 0.14.0
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.13.2.gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.14.0.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#2907 katello-host-tools 3.3.5 release
  packages/katello/katello-host-tools/katello-host-tools-3.3.4.tar.gz
  packages/katello/katello-host-tools/katello-host-tools-3.3.5.tar.gz
  packages/katello/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, Not yet reviewed, RPM

#2911 Release 1.19.0
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: DEB, Needs testing, Not yet reviewed

#2912 Release 1.19.0
  packages/foreman/foreman-installer/foreman-installer-1.19.0-RC3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-1.19.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-1.19.0-RC3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-1.19.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-selinux/foreman-selinux-1.19.0-RC3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-1.19.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-1.19.0-RC3.tar.bz2
  packages/foreman/foreman/foreman-1.19.0.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#2822 Split out foreman-release RPM
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/foreman-release/foreman-plugins.repo
  packages/foreman/foreman-release/foreman-rails.gpg
  packages/foreman/foreman-release/foreman-rails.repo
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-release/foreman.gpg
  packages/foreman/foreman-release/foreman.repo
  packages/foreman/foreman/foreman.spec
  rel-eng/tito.props
Labels: Needs testing, RPM
