Repository theforeman/foreman-packaging, pull requests merged in 2019-10, with the labels that each got.

#4144 Bump rubygem-unicode to 0.4.4.4-1
  packages/foreman/rubygem-unicode/rubygem-unicode.spec
  packages/foreman/rubygem-unicode/unicode-0.4.4.1.gem
  packages/foreman/rubygem-unicode/unicode-0.4.4.4.gem
Labels: Needs testing, RPM

#4108 Add rkerberos
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-rkerberos/rkerberos-0.1.5-gcc8-argnum-fix.patch
  packages/foreman/rubygem-rkerberos/rkerberos-0.1.5.gem
  packages/foreman/rubygem-rkerberos/rubygem-rkerberos.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#4154 Update deep_cloneable to 3.0.0
  packages/foreman/rubygem-deep_cloneable/deep_cloneable-2.3.2.gem
  packages/foreman/rubygem-deep_cloneable/deep_cloneable-3.0.0.gem
  packages/foreman/rubygem-deep_cloneable/rubygem-deep_cloneable.spec
Labels: Needs testing, RPM

#4158 Drop Fedora 28 for client repositories
  comps/comps-foreman-client-fedora28.xml
  package_manifest.yaml
  rel-eng/releasers.conf
  rel-eng/tito.props
  repoclosure/yum.conf
  repoclosure/yum_f28.conf
Labels: Needs testing, RPM

#4157 Update foreman package dependency
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#4159 Refs #27999 - Update responders to 3.0.0
  packages/foreman/rubygem-responders/responders-2.4.0.gem
  packages/foreman/rubygem-responders/responders-3.0.0.gem
  packages/foreman/rubygem-responders/rubygem-responders.spec
Labels: Needs testing, Not yet reviewed, RPM

#4160 Refs #27999 - Update foreman package dependency
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#4156 Update smart proxy plugin dependencies spec files to handle SCL
  comps/comps-foreman-plugins-rhel7.xml
  packages/plugins/rubygem-chef-api/rubygem-chef-api.spec
  packages/plugins/rubygem-openscap/rubygem-openscap.spec
  packages/plugins/rubygem-route53/rubygem-route53.spec
  packages/plugins/rubygem-ruby-hmac/rubygem-ruby-hmac.spec
Labels: Needs testing, RPM

#4167 Update foreman_remote_execution to 2.0.0
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/control
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB, Needs testing, Not yet reviewed

#4170 Fix license
  packages/foreman/rubygem-httpclient/rubygem-httpclient.spec
Labels: Needs testing, RPM

#4175 Update katello package dependencies
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#4174 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#4177 Release Katello 3.13
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.13.0.gem
  packages/katello/rubygem-katello/katello-3.13.0.rc2.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#4176 Refs #27994 - remove deprecated foreman-config reference
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#4173 Update plugin nodejs specs to build for SCL
  package_manifest.yaml
  packages/plugins/nodejs-babel-plugin-module-resolver/glob-7.1.3.tgz
  packages/plugins/nodejs-babel-plugin-module-resolver/glob-7.1.4.tgz
  packages/plugins/nodejs-babel-plugin-module-resolver/inherits-2.0.3.tgz
  packages/plugins/nodejs-babel-plugin-module-resolver/inherits-2.0.4.tgz
  packages/plugins/nodejs-babel-plugin-module-resolver/nodejs-babel-plugin-module-resolver-3.2.0-registry.npmjs.org.tgz
  packages/plugins/nodejs-babel-plugin-module-resolver/nodejs-babel-plugin-module-resolver.spec
  packages/plugins/nodejs-babel-plugin-module-resolver/resolve-1.10.1.tgz
  packages/plugins/nodejs-babel-plugin-module-resolver/resolve-1.12.0.tgz
  packages/plugins/nodejs-react-json-tree/asap-2.0.6.tgz
  packages/plugins/nodejs-react-json-tree/core-js-1.2.7.tgz
  packages/plugins/nodejs-react-json-tree/core-js-2.5.5.tgz
  packages/plugins/nodejs-react-json-tree/core-js-2.6.9.tgz
  packages/plugins/nodejs-react-json-tree/encoding-0.1.12.tgz
  packages/plugins/nodejs-react-json-tree/fbjs-0.8.16.tgz
  packages/plugins/nodejs-react-json-tree/iconv-lite-0.4.21.tgz
  packages/plugins/nodejs-react-json-tree/is-stream-1.1.0.tgz
  packages/plugins/nodejs-react-json-tree/isomorphic-fetch-2.2.1.tgz
  packages/plugins/nodejs-react-json-tree/js-tokens-3.0.2.tgz
  packages/plugins/nodejs-react-json-tree/js-tokens-4.0.0.tgz
  packages/plugins/nodejs-react-json-tree/loose-envify-1.3.1.tgz
  packages/plugins/nodejs-react-json-tree/loose-envify-1.4.0.tgz
  packages/plugins/nodejs-react-json-tree/node-fetch-1.7.3.tgz
  packages/plugins/nodejs-react-json-tree/nodejs-react-json-tree-0.11.0-registry.npmjs.org.tgz
  packages/plugins/nodejs-react-json-tree/nodejs-react-json-tree.spec
  packages/plugins/nodejs-react-json-tree/promise-7.3.1.tgz
  packages/plugins/nodejs-react-json-tree/prop-types-15.6.1.tgz
  packages/plugins/nodejs-react-json-tree/prop-types-15.7.2.tgz
  packages/plugins/nodejs-react-json-tree/react-is-16.10.2.tgz
  packages/plugins/nodejs-react-json-tree/react-json-tree-0.11.0-registry.npmjs.org.tgz
  packages/plugins/nodejs-react-json-tree/safer-buffer-2.1.2.tgz
  packages/plugins/nodejs-react-json-tree/setimmediate-1.0.5.tgz
  packages/plugins/nodejs-react-json-tree/ua-parser-js-0.7.17.tgz
  packages/plugins/nodejs-react-json-tree/whatwg-fetch-2.0.4.tgz
Labels: Needs testing, RPM

#4180 Add license translation
  gem2rpm/foreman_plugin.spec.erb
  gem2rpm/hammer_plugin.spec.erb
  gem2rpm/nonscl.spec.erb
  gem2rpm/scl.spec.erb
  gem2rpm/smart_proxy_plugin.spec.erb
  licenses.json
Labels: Needs testing, RPM

#4183 Adding pulp 2.21 GA
  packages/katello/katello-repos/katello-repos.spec
Labels: Needs testing, RPM

#4182 Update tfm-rubygem-jwt to 2.2.1
  packages/foreman/tfm-rubygem-jwt/jwt-2.1.0.gem
  packages/foreman/tfm-rubygem-jwt/jwt-2.2.1.gem
  packages/foreman/tfm-rubygem-jwt/tfm-rubygem-jwt.spec
Labels: Needs testing, RPM

#4185 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#4190 Bump rubygem-foreman_inventory_upload to 1.0.0.beta7-1
  packages/katello/rubygem-foreman_inventory_upload/foreman_inventory_upload-1.0.0.beta4.gem
  packages/katello/rubygem-foreman_inventory_upload/foreman_inventory_upload-1.0.0.beta7.gem
  packages/katello/rubygem-foreman_inventory_upload/rubygem-foreman_inventory_upload.spec
Labels: Needs testing, RPM

#4195 Regenerate comps file
  comps/comps-foreman-plugins-rhel7.xml
  comps/comps-foreman-rhel7.xml
Labels: Needs testing, Not yet reviewed, RPM

#4200 Make optionality of parameters more explicit
  add_gem_package.sh
Labels: Needs testing, RPM

#4165 Update rubygem-smart_proxy_dynflow to 0.2.4
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.2.3.gem
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.2.4.gem
Labels: Needs testing, RPM

#4198 Update rubygem-kafo to 4.0.0
  packages/foreman/rubygem-kafo/kafo-3.0.0.gem
  packages/foreman/rubygem-kafo/kafo-4.0.0.gem
  packages/foreman/rubygem-kafo/rubygem-kafo.spec
Labels: Needs testing, RPM

#4199 Update to Kafo 4.0.0
  dependencies/bionic/kafo/changelog
  dependencies/bionic/kafo/control
  dependencies/stretch/kafo/changelog
  dependencies/stretch/kafo/control
  dependencies/xenial/kafo/changelog
  dependencies/xenial/kafo/control
Labels: Needs testing, Not yet reviewed

#4202 Update installer package dependencies
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: Needs testing, RPM

#4203 Update installer dependencies
  debian/bionic/foreman-installer/control
  debian/stretch/foreman-installer/control
  debian/xenial/foreman-installer/control
Labels: Needs testing, Not yet reviewed

#4205 always expire yum metadata on repoclosure
  repoclosure/yum.conf
  repoclosure/yum_el5.conf
  repoclosure/yum_el6.conf
  repoclosure/yum_el7.conf
  repoclosure/yum_f29.conf
Labels: Needs testing, RPM

#4197 Add rubygem-smart_proxy_dhcp_bluecat package
  comps/comps-foreman-plugins-rhel7.xml
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-smart_proxy_dhcp_bluecat/rubygem-smart_proxy_dhcp_bluecat.spec
  packages/plugins/rubygem-smart_proxy_dhcp_bluecat/smart_proxy_dhcp_bluecat-0.1.0.gem
  rel-eng/tito.props
Labels: Needs testing, RPM

#4191 adding pulp_rpm and 2to3 migration bindings
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-pulp_2to3_migration_client/pulp_2to3_migration_client-0.0.1a1.dev01570560174.gem
  packages/katello/rubygem-pulp_2to3_migration_client/rubygem-pulp_2to3_migration_client.spec
  packages/katello/rubygem-pulp_rpm_client/pulp_rpm_client-3.0.0b7.dev01570381057.gem
  packages/katello/rubygem-pulp_rpm_client/rubygem-pulp_rpm_client.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#4206 Automatically set gpgcheck=1 for release versions
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello-repos/katello.repo
Labels: Needs testing, RPM

#4134 Add NodeJS SCL to tfm
  packages/foreman/tfm/nodejs-symlink-deps
  packages/foreman/tfm/tfm.attr
  packages/foreman/tfm/tfm.spec
Labels: Blocked on build, Needs testing, RPM

#4208 Use RPM-GPG-KEY-foreman from foreman-release
  packages/katello/katello-repos/RPM-GPG-KEY-katello-2015
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello-repos/katello.repo
Labels: Needs testing, RPM

#4186 Update nodejs-node-gyp for SCL
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/nodejs-node-gyp/node-gyp-node-dirs.patch
  packages/foreman/nodejs-node-gyp/nodejs-node-gyp-3.3.1-registry.npmjs.org.tgz
  packages/foreman/nodejs-node-gyp/nodejs-node-gyp.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#4213 Build another chunk of SCL nodejs packages
  comps/comps-foreman-rhel7.xml
  packages/foreman/nodejs-harmony-reflect/nodejs-harmony-reflect.spec
  packages/foreman/nodejs-hoist-non-react-statics/nodejs-hoist-non-react-statics.spec
  packages/foreman/nodejs-humanize-duration/nodejs-humanize-duration.spec
  packages/foreman/nodejs-identity-obj-proxy/nodejs-identity-obj-proxy.spec
  packages/foreman/nodejs-intl/nodejs-intl.spec
  packages/foreman/nodejs-invariant/nodejs-invariant.spec
  packages/foreman/nodejs-jed/nodejs-jed.spec
  packages/foreman/nodejs-jquery/nodejs-jquery.spec
  packages/foreman/nodejs-js-tokens/nodejs-js-tokens.spec
  packages/foreman/nodejs-lodash-es/nodejs-lodash-es.spec
  packages/foreman/nodejs-lodash.debounce/nodejs-lodash.debounce.spec
  packages/foreman/nodejs-lodash/nodejs-lodash.spec
  packages/foreman/nodejs-loose-envify/nodejs-loose-envify.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#4215 Fix paths in node-gyp for SCL builds
  packages/foreman/nodejs-node-gyp/addon-rpm.gypi
  packages/foreman/nodejs-node-gyp/node-gyp-addon-gypi.patch
  packages/foreman/nodejs-node-gyp/nodejs-node-gyp.spec
Labels: Needs testing, RPM

#4216 Release Katello 3.13.1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.13.0.gem
  packages/katello/rubygem-katello/katello-3.13.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#4218 Update plugin NodeJS moduels for SCL
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/nodejs-babel-plugin-module-resolver/nodejs-babel-plugin-module-resolver-3.2.0-registry.npmjs.org.tgz
  packages/plugins/nodejs-babel-plugin-module-resolver/nodejs-babel-plugin-module-resolver.spec
  packages/plugins/nodejs-react-json-tree/nodejs-react-json-tree-0.11.0-registry.npmjs.org.tgz
  packages/plugins/nodejs-react-json-tree/nodejs-react-json-tree.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#4219 Final round of Foreman nodejs modules
  comps/comps-foreman-rhel7.xml
  packages/foreman/nodejs-react-bootstrap-switch/nodejs-react-bootstrap-switch.spec
  packages/foreman/nodejs-react-bootstrap-typeahead/nodejs-react-bootstrap-typeahead.spec
  packages/foreman/nodejs-react-bootstrap/nodejs-react-bootstrap-0.32.1-registry.npmjs.org.tgz
  packages/foreman/nodejs-react-bootstrap/nodejs-react-bootstrap.spec
  packages/foreman/nodejs-react-c3js/nodejs-react-c3js.spec
  packages/foreman/nodejs-react-click-outside/nodejs-react-click-outside.spec
  packages/foreman/nodejs-react-collapse/nodejs-react-collapse.spec
  packages/foreman/nodejs-react-debounce-input/nodejs-react-debounce-input.spec
  packages/foreman/nodejs-react-dom/nodejs-react-dom-16.8.1-registry.npmjs.org.tgz
  packages/foreman/nodejs-react-dom/nodejs-react-dom.spec
  packages/foreman/nodejs-react-ellipsis-with-tooltip/nodejs-react-ellipsis-with-tooltip.spec
  packages/foreman/nodejs-react-fontawesome/nodejs-react-fontawesome.spec
  packages/foreman/nodejs-react-intl/nodejs-react-intl-2.8.0-registry.npmjs.org.tgz
  packages/foreman/nodejs-react-intl/nodejs-react-intl.spec
  packages/foreman/nodejs-react-is/nodejs-react-is.spec
  packages/foreman/nodejs-react-lifecycles-compat/nodejs-react-lifecycles-compat.spec
  packages/foreman/nodejs-react-motion/nodejs-react-motion.spec
  packages/foreman/nodejs-react-overlays/nodejs-react-overlays.spec
  packages/foreman/nodejs-react-popper/nodejs-react-popper.spec
  packages/foreman/nodejs-react-redux/nodejs-react-redux-5.1.1-registry.npmjs.org.tgz
  packages/foreman/nodejs-react-redux/nodejs-react-redux.spec
  packages/foreman/nodejs-react-transition-group/nodejs-react-transition-group.spec
  packages/foreman/nodejs-react/nodejs-react-16.8.1-registry.npmjs.org.tgz
  packages/foreman/nodejs-react/nodejs-react.spec
  packages/foreman/nodejs-reactabular-table/nodejs-reactabular-table.spec
  packages/foreman/nodejs-recompose/nodejs-recompose.spec
  packages/foreman/nodejs-redux-thunk/nodejs-redux-thunk.spec
  packages/foreman/nodejs-redux/nodejs-redux.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#4172 Update Katello nodejs package specs for SCL
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/nodejs-angular/nodejs-angular.spec
  packages/katello/nodejs-bootstrap-select/nodejs-bootstrap-select.spec
  packages/katello/nodejs-decode-uri-component/decode-uri-component-0.2.0.tgz
  packages/katello/nodejs-decode-uri-component/nodejs-decode-uri-component.spec
  packages/katello/nodejs-downshift/nodejs-downshift.spec
  packages/katello/nodejs-ngreact/nodejs-ngreact.spec
  packages/katello/nodejs-query-string/nodejs-query-string.spec
  packages/katello/nodejs-query-string/query-string-6.1.0-registry.npmjs.org.tgz
  packages/katello/nodejs-react-helmet/deep-equal-1.0.1.tgz
  packages/katello/nodejs-react-helmet/deep-equal-1.1.0.tgz
  packages/katello/nodejs-react-helmet/define-properties-1.1.3.tgz
  packages/katello/nodejs-react-helmet/exenv-1.2.2.tgz
  packages/katello/nodejs-react-helmet/function-bind-1.1.1.tgz
  packages/katello/nodejs-react-helmet/has-1.0.3.tgz
  packages/katello/nodejs-react-helmet/is-arguments-1.0.4.tgz
  packages/katello/nodejs-react-helmet/is-date-object-1.0.1.tgz
  packages/katello/nodejs-react-helmet/is-regex-1.0.4.tgz
  packages/katello/nodejs-react-helmet/nodejs-react-helmet-5.2.0-registry.npmjs.org.tgz
  packages/katello/nodejs-react-helmet/nodejs-react-helmet.spec
  packages/katello/nodejs-react-helmet/object-is-1.0.1.tgz
  packages/katello/nodejs-react-helmet/object-keys-1.1.1.tgz
  packages/katello/nodejs-react-helmet/prop-types-15.6.2.tgz
  packages/katello/nodejs-react-helmet/prop-types-15.7.2.tgz
  packages/katello/nodejs-react-helmet/react-helmet-5.2.0-registry.npmjs.org.tgz
  packages/katello/nodejs-react-helmet/react-is-16.10.2.tgz
  packages/katello/nodejs-react-helmet/react-side-effect-1.1.5.tgz
  packages/katello/nodejs-react-helmet/react-side-effect-1.2.0.tgz
  packages/katello/nodejs-react-helmet/regexp.prototype.flags-1.2.0.tgz
  packages/katello/nodejs-strict-uri-encode/nodejs-strict-uri-encode.spec
  packages/katello/nodejs-strict-uri-encode/strict-uri-encode-2.0.0.tgz
  rel-eng/tito.props
Labels: Needs testing, RPM

#4224 Build nodejs-babel-plugin-syntax-dynamic-import for SCl
  package_manifest.yaml
  packages/foreman/nodejs-babel-plugin-syntax-dynamic-import/nodejs-babel-plugin-syntax-dynamic-import.spec
Labels: Needs testing, RPM

#4225 Add missing vendor directory to nodejs-node-sass
  packages/foreman/nodejs-node-sass/nodejs-node-sass.spec
Labels: Needs testing, RPM

#4211 Update rubygem-foreman_virt_who_configure to 0.4.5
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.4.4.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.4.5.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Needs testing, RPM

#4192 Update Foreman RPM to handle SCL nodejs
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#4222 Update rubygem-katello for SCL nodejs packages
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#4223 Rebuild plugin packages for NodeJS SCL
  packages/katello/rubygem-foreman_inventory_upload/rubygem-foreman_inventory_upload.spec
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#4229 Add version to usage of add_changelog
  add_changelog.sh
Labels: Needs testing, RPM

#4232 Clean up nodejs leftovers
  comps/comps-foreman-rhel7.xml
  rel-eng/tito.props
Labels: Needs testing

#4231 Fixes #28125 - Drop foreman_cockpit
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_cockpit/foreman_cockpit-2.0.3.gem
  packages/plugins/rubygem-foreman_cockpit/rubygem-foreman_cockpit.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#4236 Update rubygem-dynflow to 1.4.1
  packages/foreman/rubygem-dynflow/dynflow-1.4.0.gem
  packages/foreman/rubygem-dynflow/dynflow-1.4.1.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing, RPM

#4235 Teach compare-with-tags.rb about nodejs SCL packages
  rel-eng/compare-with-tags.rb
Labels: Needs testing, RPM

#4238 Update rubygem-apipie-bindings to 0.3.0
  packages/foreman/rubygem-apipie-bindings/apipie-bindings-0.2.2.gem
  packages/foreman/rubygem-apipie-bindings/apipie-bindings-0.3.0.gem
  packages/foreman/rubygem-apipie-bindings/rubygem-apipie-bindings.spec
Labels: Needs testing, RPM

#4239 update apipie-bindings to 0.3.0
  dependencies/bionic/apipie-bindings/changelog
  dependencies/buster/apipie-bindings/changelog
  dependencies/stretch/apipie-bindings/changelog
  dependencies/xenial/apipie-bindings/changelog
Labels: DEB, Needs testing, Not yet reviewed

#4233 Bump foreman_openscap to 2.0.0
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-1.0.8.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-2.0.0.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#4248 Update PR template for 1.24
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Needs testing

#4242 Refs #12063 - update fog-libvirt to 0.7.0
  packages/foreman/rubygem-fog-libvirt/fog-libvirt-0.6.0.gem
  packages/foreman/rubygem-fog-libvirt/fog-libvirt-0.7.0.gem
  packages/foreman/rubygem-fog-libvirt/rubygem-fog-libvirt.spec
Labels: Needs testing, Not yet reviewed, RPM

#4241 Drop psql requirement on katello-debug
  packages/katello/katello/katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#4244 Update rubygem-hammer-cli to 0.19.0
  packages/foreman/rubygem-hammer_cli/hammer_cli-0.19.0.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
Labels: Needs testing, Not yet reviewed, RPM

#4251 Bump version to 1.25-develop
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  rel-eng/releasers.conf
  rel-eng/tito.props
Labels: Needs testing, RPM

#4252 Update ansible-collection-theforeman-foreman to 0.2.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-0.1.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-0.2.0.tar.gz
Labels: Needs testing, RPM

#4257 Add rubygem-foreman_azure_rm package
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.0.1.gem
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#4262 Release 1.24.0-RC1
  packages/foreman/foreman-installer/foreman-installer-1.24.0-RC1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-1.24.0-RC1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-1.24.0-RC1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-1.24.0-RC1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#4260 Updated hammer_cli to 0.18.1
  dependencies/bionic/hammer_cli/changelog
  dependencies/stretch/hammer_cli/changelog
  dependencies/xenial/hammer_cli/changelog
Labels: DEB, Needs testing, Not yet reviewed, Stable branch

#4261 Updated hammer_cli_foreman to 0.18.1
  dependencies/bionic/hammer_cli_foreman/changelog
  dependencies/bionic/hammer_cli_foreman/control
  dependencies/stretch/hammer_cli_foreman/changelog
  dependencies/stretch/hammer_cli_foreman/control
  dependencies/xenial/hammer_cli_foreman/changelog
  dependencies/xenial/hammer_cli_foreman/control
Labels: DEB, Needs testing, Not yet reviewed, Stable branch
