Repository theforeman/foreman-packaging, pull requests merged in 2019-02, with the labels that each got.

#3431 Update rubygem-fog-libvirt to 0.6.0
  packages/foreman/rubygem-fog-libvirt/fog-libvirt-0.4.1.gem
  packages/foreman/rubygem-fog-libvirt/fog-libvirt-0.6.0.gem
  packages/foreman/rubygem-fog-libvirt/rubygem-fog-libvirt.spec
Labels: Needs testing, RPM

#3421 Explicitly build katello-host-tools using Python3 on Python3 distibut…
  packages/client/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#3429 Update rubygem-smart_proxy_dynflow to 0.2.2
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.2.1.gem
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.2.2.gem
Labels: Needs testing, Not yet reviewed, RPM

#3428 Update rubygem-smart_proxy_dynflow_core to 0.2.2
  packages/plugins/rubygem-smart_proxy_dynflow_core/rubygem-smart_proxy_dynflow_core.spec
  packages/plugins/rubygem-smart_proxy_dynflow_core/smart_proxy_dynflow_core-0.2.1.gem
  packages/plugins/rubygem-smart_proxy_dynflow_core/smart_proxy_dynflow_core-0.2.2.gem
Labels: Needs testing, Not yet reviewed, RPM

#3432 Build activerecord-import for katello
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-activerecord-import/activerecord-import-1.0.0.gem
  packages/katello/rubygem-activerecord-import/activerecord-import.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3420 Update rubygem-foreman_scc_manager to 1.5.1 for Katello 3.9 Foreman 1.20
  packages/katello-3.9/rubygem-foreman_scc_manager/foreman_scc_manager-1.4.0.gem
  packages/katello-3.9/rubygem-foreman_scc_manager/foreman_scc_manager-1.5.1.gem
  packages/katello-3.9/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM

#3318 Update rubygem-foreman_scc_manager to 1.5.1 for 1.20
  packages/katello-3.10/rubygem-foreman_scc_manager/foreman_scc_manager-1.4.0.gem
  packages/katello-3.10/rubygem-foreman_scc_manager/foreman_scc_manager-1.5.1.gem
  packages/katello-3.10/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM

#3435 katello requires activerecord-import
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#3434 Remove old hammer-cli gem
  packages/foreman/rubygem-hammer_cli/hammer_cli-0.14.0.gem
Labels: Needs testing, RPM

#3437 Update foreman-tasks to 0.15.0 (deb)
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB, Needs testing, Not yet reviewed

#3442 Update foreman_ansible to 2.3.1
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/control
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing, Not yet reviewed

#3441 Update rubygem-foreman_ansible to 2.3.1
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.3.0.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.3.1.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#3446 Release 1.20.2
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: DEB, Needs testing, Not yet reviewed

#3447 Release 1.20.2
  packages/foreman/foreman-installer/foreman-installer-1.20.1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-1.20.2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-1.20.1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-1.20.2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-1.20.1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-1.20.2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-1.20.1.tar.bz2
  packages/foreman/foreman/foreman-1.20.2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed

#3439 Drop outdated hammer_cli_foreman gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.14.0.gem
Labels: Needs testing, Not yet reviewed, RPM

#3444 Update rubygem-fog-ovirt to 1.1.5
  packages/foreman/rubygem-fog-ovirt/fog-ovirt-1.1.2.gem
  packages/foreman/rubygem-fog-ovirt/fog-ovirt-1.1.5.gem
  packages/foreman/rubygem-fog-ovirt/rubygem-fog-ovirt.spec
Labels: Needs testing, Not yet reviewed, RPM

#3449 Rebuild rubygem-foreman_remote_execution for webpack
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#3454 Rebuild rubygem-foreman_ansible for webpack
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, Not yet reviewed, RPM

#3296 Update foreman-tasks to 0.14.5
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/control
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB, Needs testing, Not yet reviewed

#3458 Add rubygem-rack-cors package
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-rack-cors/rack-cors-1.0.2.gem
  packages/foreman/rubygem-rack-cors/rubygem-rack-cors.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3457 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#3459 Update roadie dependency
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#3461 Fixes #26084 - Restart the passenger service again
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#3450 Add rubygem-promise.rb package
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-promise.rb/promise.rb-0.7.4.gem
  packages/foreman/rubygem-promise.rb/rubygem-promise.rb.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3452 Add rubygem-graphql package
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-graphql/graphql-1.8.14.gem
  packages/foreman/rubygem-graphql/rubygem-graphql.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3451 Add rubygem-graphql-batch package
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-graphql-batch/graphql-batch-0.3.10.gem
  packages/foreman/rubygem-graphql-batch/rubygem-graphql-batch.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3463 Update rubygem-foreman_scc_manager to 1.6.0 (#3349)
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.5.1.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.6.0.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM

#3448 Update rubygem-foreman_scap_client to 0.4.2
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.4.1.gem
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.4.2.gem
  packages/client/rubygem-foreman_scap_client/rubygem-foreman_scap_client.spec
Labels: Needs testing, RPM

#3468 Update rubygem-foreman_scap_client to 0.4.2
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.4.1.gem
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.4.2.gem
  packages/client/rubygem-foreman_scap_client/rubygem-foreman_scap_client.spec
Labels: Needs testing, Not yet reviewed, RPM

#2772 Add rubygem-foreman_probing_core package
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_probing_core/foreman_probing_core-0.0.1.gem
  packages/plugins/rubygem-foreman_probing_core/rubygem-foreman_probing_core.spec
  packages/plugins/rubygem-rprogram/rprogram-0.3.2.gem
  packages/plugins/rubygem-rprogram/rubygem-rprogram.spec
  packages/plugins/rubygem-ruby-nmap/ruby-nmap-0.9.3.gem
  packages/plugins/rubygem-ruby-nmap/rubygem-ruby-nmap.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3467 Update rubygem-signet to 0.11.0
  packages/foreman/rubygem-signet/rubygem-signet.spec
  packages/foreman/rubygem-signet/signet-0.11.0.gem
  packages/foreman/rubygem-signet/signet-0.6.0.gem
Labels: Needs testing, RPM

#3466 update rubygem-jwt scl package
  package_manifest.yaml
  packages/foreman/tfm-rubygem-jwt/jwt-2.1.0.gem
  packages/foreman/tfm-rubygem-jwt/tfm-rubygem-jwt.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#2777 Add rubygem-smart-proxy-probing package
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-smart-proxy-probing/rubygem-smart-proxy-probing.spec
  packages/plugins/rubygem-smart-proxy-probing/smart-proxy-probing-0.0.2.gem
  rel-eng/tito.props
Labels: Needs testing, RPM

#3453 Add ansiblerole-foreman_scap_client package
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/ansiblerole-foreman_scap_client/ansiblerole-foreman_scap_client.spec
  packages/plugins/ansiblerole-foreman_scap_client/foreman_scap_client-0.0.1.tar.gz
  rel-eng/tito.props
Labels: Needs testing, RPM

#2783 Add rubygem-foreman_probing package
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_probing/foreman_probing-0.0.2.gem
  packages/plugins/rubygem-foreman_probing/rubygem-foreman_probing.spec
  rel-eng/tito.props
Labels: Needs re-review, Needs testing, RPM

#3455 katello-repos disable gpgcheck on EL5 clients
  packages/katello/katello-repos/katello-repos.spec
Labels: Needs testing, RPM

#3222 1651799 - added logrotate for output log file
  packages/plugins/rubygem-foreman-tasks/foreman-tasks.logrotate
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#3470 update foreman_docker to 4.1.1
  plugins/ruby-foreman-docker/debian/changelog
  plugins/ruby-foreman-docker/debian/gem.list
  plugins/ruby-foreman-docker/foreman_docker.rb
Labels: Needs testing, Not yet reviewed

#3469 Update rubygem-foreman_docker to 4.1.1
  packages/plugins/rubygem-foreman_docker/foreman_docker-4.1.0.gem
  packages/plugins/rubygem-foreman_docker/foreman_docker-4.1.1.gem
  packages/plugins/rubygem-foreman_docker/rubygem-foreman_docker.spec
Labels: Needs testing, RPM

#3471 Release katello-certs-tools 2.5.0
  packages/foreman/katello-certs-tools/2.4.0
  packages/foreman/katello-certs-tools/katello-certs-tools-2.5.0.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools.spec
Labels: Needs testing, RPM

#3473 Update rubygem-dynflow to 1.2.2
  packages/foreman/rubygem-dynflow/dynflow-1.2.1.gem
  packages/foreman/rubygem-dynflow/dynflow-1.2.2.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing, RPM

#3472 Update rubygem-foreman_virt_who_configure to 0.4.0
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.3.2.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.4.0.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Needs testing, RPM

#3476 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#3477 Fixes #26188 - don't duplicate -s in the python shebang
  packages/foreman/katello-certs-tools/katello-certs-tools-2.5.0.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools-2.5.1.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools.spec
Labels: Needs testing, RPM

#3479 Rename activerecord-import spec
  packages/katello/rubygem-activerecord-import/rubygem-activerecord-import.spec
Labels: Needs testing, RPM
