Repository theforeman/foreman-packaging, pull requests merged in 2019-09, with the labels that each got.

#4045 Update rubygem-fog-vsphere to 3.2.1
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.2.0.gem
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.2.1.gem
  packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec
Labels: Needs testing, RPM

#4046 [1.23] Update rubygem-fog-vsphere to 3.2.1
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.2.0.gem
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.2.1.gem
  packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec
Labels: Needs testing, RPM, Stable branch

#4055 Update foreman_expire_hosts to 6.0.2
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-6.0.1.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-6.0.2.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Needs testing, RPM

#4052 Update foreman_git_templates to 1.0.2
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.1.gem
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.2.gem
  packages/plugins/rubygem-foreman_git_templates/rubygem-foreman_git_templates.spec
Labels: Needs testing, RPM, Stable branch

#4003 Update rubygem-foreman_scc_manager to 1.6.3
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.6.2.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.6.3.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#3992 Update rubygem-foreman-tasks to 0.15.8
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.15.7.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.15.8.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM, Stable branch

#4034 Bump rubygem-foreman_inventory_upload to 1.0.0.beta1-1.fm1_16
  packages/katello/rubygem-foreman_inventory_upload/foreman_inventory_upload-0.0.1.dev1.gem
  packages/katello/rubygem-foreman_inventory_upload/foreman_inventory_upload-1.0.0.beta1.gem
  packages/katello/rubygem-foreman_inventory_upload/rubygem-foreman_inventory_upload.spec
Labels: Needs testing, Not yet reviewed, RPM

#4060 Update rubygem-hammer_cli_foreman_virt_who_configure to 0.0.4
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/hammer_cli_foreman_virt_who_configure-0.0.3.gem
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/hammer_cli_foreman_virt_who_configure-0.0.4.gem
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/rubygem-hammer_cli_foreman_virt_who_configure.spec
Labels: Needs testing, RPM

#4061 Update rubygem-runcible to 2.12.1
  packages/katello/rubygem-runcible/rubygem-runcible.spec
  packages/katello/rubygem-runcible/runcible-2.12.0.gem
  packages/katello/rubygem-runcible/runcible-2.12.1.gem
Labels: Needs testing, Not yet reviewed, RPM

#4064 Update foreman-tasks to 0.15.9
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Not yet reviewed, Stable branch

#4066 Update foreman-tasks to 0.17.0
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/debian/install
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Not yet reviewed

#4069 Update rubygem-foreman_maintain to 0.4.8
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.4.5.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.4.8.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing

#4067 Update foreman-tasks to 0.16.1
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/debian/install
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Not yet reviewed

#4063 Update rubygem-foreman-tasks to 0.15.9
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.15.8.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.15.9.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#4062 Update rubygem-foreman_openscap to 1.0.6
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-1.0.5.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-1.0.6.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#4079 Add nodejs-humanize-duration package
  comps/comps-foreman-plugins-rhel7.xml
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/nodejs-humanize-duration/humanize-duration-3.20.1.tgz
  packages/foreman/nodejs-humanize-duration/nodejs-humanize-duration.spec
  rel-eng/tito.props
Labels: Needs testing, Not yet reviewed, RPM

#4078 Add nodejs-humanize-duration package
  comps/comps-foreman-plugins-rhel7.xml
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/nodejs-humanize-duration/humanize-duration-3.20.1.tgz
  packages/foreman/nodejs-humanize-duration/nodejs-humanize-duration.spec
  rel-eng/tito.props
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#4068 Update rubygem-foreman-tasks to 0.17.0
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.16.0.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.17.0.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, Not yet reviewed, RPM

#4065 Update rubygem-foreman-tasks to 0.16.1
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.16.0.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.16.1.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#4083 Drop 'Generated from' headers from gem2rpm templates
  gem2rpm/foreman_plugin.spec.erb
  gem2rpm/hammer_plugin.spec.erb
  gem2rpm/nonscl.spec.erb
  gem2rpm/scl.spec.erb
  gem2rpm/smart_proxy_plugin.spec.erb
Labels: Needs testing, RPM

#4086 Release katello-client-boostrap 1.7.3
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.2.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.3.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap.spec
Labels: Needs testing, RPM

#4084 Update rubygem-foreman_virt_who_configure to 0.4.4
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.4.3.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.4.4.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Needs testing, RPM

#4090 Update foreman_chef to 0.9.0
  plugins/ruby-foreman-chef/debian/changelog
  plugins/ruby-foreman-chef/debian/gem.list
  plugins/ruby-foreman-chef/foreman_chef.rb
Labels: Needs testing, Not yet reviewed

#4088 Update foreman_ansible to 3.0.7
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing, Not yet reviewed

#4070 Update foreman_ansible_core to 3.0.1
  dependencies/bionic/foreman_ansible_core/changelog
  dependencies/stretch/foreman_ansible_core/changelog
  dependencies/xenial/foreman_ansible_core/changelog
Labels: DEB, Needs testing, Not yet reviewed

#4075 Update foreman_ansible_core to 3.0.1
  dependencies/bionic/foreman_ansible_core/changelog
  dependencies/stretch/foreman_ansible_core/changelog
  dependencies/xenial/foreman_ansible_core/changelog
Labels: DEB, Needs testing, Not yet reviewed, Stable branch

#4074 Update foreman_ansible_core to 3.0.1
  dependencies/bionic/foreman_ansible_core/changelog
  dependencies/stretch/foreman_ansible_core/changelog
  dependencies/xenial/foreman_ansible_core/changelog
Labels: DEB, Needs testing, Not yet reviewed, Stable branch

#4092 Update foreman-tasks to 0.15.10
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Not yet reviewed, Stable branch

#4098 Update foreman-tasks to 0.16.2
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Not yet reviewed, Stable branch

#4093 Update python-apypie to 0.1.0
  packages/client/python-apypie/apypie-0.0.5.tar.gz
  packages/client/python-apypie/apypie-0.1.0.tar.gz
  packages/client/python-apypie/python-apypie.spec
Labels: Needs testing

#4082 Bump rubygem-redhat_access_lib to 1.1.5-1
  packages/katello/rubygem-redhat_access_lib/redhat_access_lib-1.1.4.gem
  packages/katello/rubygem-redhat_access_lib/redhat_access_lib-1.1.5.gem
  packages/katello/rubygem-redhat_access_lib/rubygem-redhat_access_lib.spec
Labels: Needs testing, RPM

#4096 hammer_cli_katello 0.19.1
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.19.0.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.19.1.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, Stable branch

#4101 Update rubygem-foreman_openscap to 1.0.7
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-1.0.6.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-1.0.7.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#4103 Update rubygem-foreman_maintain to 0.4.9
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.4.8.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.4.9.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#4071 Update rubygem-foreman_ansible_core to 3.0.1
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-3.0.0.gem
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-3.0.1.gem
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
Labels: Needs testing, RPM

#4106 Make bump_rpm.sh generic for all package types
  bump_rpm.sh
Labels: Needs testing, RPM

#4107 Update katello-certs-tools to 2.6.0
  packages/foreman/katello-certs-tools/katello-certs-tools-2.5.3.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools-2.6.0.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools.spec
Labels: Needs testing, RPM

#4104 Add which as a dependency to foreman-installer
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: Needs testing, RPM

#4095 Release Katello 3.13.0 RC2
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.13.0.rc1.gem
  packages/katello/rubygem-katello/katello-3.13.0.rc2.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#4076 Update rubygem-foreman_ansible_core to 3.0.1
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-3.0.0.gem
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-3.0.1.gem
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
Labels: Needs testing, RPM, Stable branch

#4077 Update rubygem-foreman_ansible_core to 3.0.1
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-3.0.0.gem
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-3.0.1.gem
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
Labels: Needs testing, RPM, Stable branch

#4094 Fixes #27811 - satellite-change-hostname fails if locale is set to ja…
  packages/katello/katello/hostname-change.rb
Labels: Needs testing, RPM, Waiting on contributor

#4115 Fixes #27874 - Optimize tfm wrappers
  packages/foreman/tfm/tfm.spec
Labels: Needs testing, RPM

#4114 Update foreman-tasks to 0.15.11
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Not yet reviewed

#4129 Refs #27874 - Quote the variable in tfm wrappers
  packages/foreman/tfm/tfm.spec
Labels: Needs testing, RPM

#4130 fix apypie package names in comps
  comps/comps-foreman-client-fedora28.xml
  comps/comps-foreman-client-fedora29.xml
  comps/comps-foreman-client-rhel7.xml
Labels: Needs testing, RPM

#4120 Update foreman-proxy to build for the SCL
  packages/foreman/foreman-proxy/foreman-proxy.spec
Labels: Needs testing, RPM

#4023 Add npm @theforeman/vendor update docs
  README.md
Labels: Needs testing, RPM

#3870 Update rubygem-smart_proxy_ansible to 3.0.1
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-2.1.2.gem
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-3.0.1.gem
Labels: Needs testing, RPM, Stable branch

#4131 Update licenses
  packages/foreman/rubygem-kafo/rubygem-kafo.spec
  packages/katello/rhel8-kickstart-setup/rhel8-kickstart-setup.spec
  packages/plugins/rubygem-foreman_git_templates/rubygem-foreman_git_templates.spec
Labels: Needs testing, RPM

#4113 Update rubygem-foreman-tasks to 0.15.11
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.15.10.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.15.11.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#4099 Bump rubygem-foreman_inventory_upload to 1.0.0.beta4-1
  packages/katello/rubygem-foreman_inventory_upload/foreman_inventory_upload-1.0.0.beta1.gem
  packages/katello/rubygem-foreman_inventory_upload/foreman_inventory_upload-1.0.0.beta4.gem
  packages/katello/rubygem-foreman_inventory_upload/rubygem-foreman_inventory_upload.spec
Labels: Needs testing, RPM

#4110 Add rubygem-foreman_inventory_upload package
  comps/comps-foreman-plugins-rhel7.xml
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-foreman_inventory_upload/foreman_inventory_upload-1.0.0.beta6.gem
  packages/katello/rubygem-foreman_inventory_upload/rubygem-foreman_inventory_upload.spec
  rel-eng/tito.props
Labels: Needs testing, RPM, Stable branch

#4097 Update rubygem-foreman-tasks to 0.16.2
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.16.1.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.16.2.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM, Stable branch

#4002 Update rubygem-foreman_scc_manager to 1.6.3
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.6.2.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.6.3.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM, Stable branch

#4021 Update rubygem-foreman_remote_execution to 1.8.4
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.8.3.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.8.4.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#4008 Updated hammer_cli_foreman to 0.17.2
  dependencies/bionic/hammer_cli_foreman/changelog
  dependencies/stretch/hammer_cli_foreman/changelog
  dependencies/xenial/hammer_cli_foreman/changelog
Labels: Needs testing, Stable branch

#4132 Update smart_proxy_pulp to 1.5.0
  packages/plugins/rubygem-smart_proxy_pulp/rubygem-smart_proxy_pulp.spec
  packages/plugins/rubygem-smart_proxy_pulp/smart_proxy_pulp-1.4.1.gem
  packages/plugins/rubygem-smart_proxy_pulp/smart_proxy_pulp-1.5.0.gem
Labels: Needs testing, RPM

#3823 Drop katello-host-tools for F28
  comps/comps-foreman-client-fedora28.xml
  rel-eng/tito.props
Labels: Needs testing, RPM

#4135 Update rubygem-foreman_openscap to 1.0.8
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-1.0.7.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-1.0.8.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#4136 gem2rpm templates: -p is redundant when -a is specified
  gem2rpm/foreman_plugin.spec.erb
  gem2rpm/hammer_plugin.spec.erb
  gem2rpm/nonscl.spec.erb
  gem2rpm/scl.spec.erb
  gem2rpm/smart_proxy_plugin.spec.erb
Labels: Needs testing, RPM

#4137 Regenerate rubygem-foreman_scc_manager spec file
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM

#4138 Regenerate rubygem-foreman_virt_who_configure spec
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Needs testing, Not yet reviewed, RPM

#4127 Add rubygem-rake-compiler package
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-rake-compiler/rake-compiler-1.0.7.gem
  packages/foreman/rubygem-rake-compiler/rubygem-rake-compiler.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#4057 Update puppet-agent-puppet-strings to 2.3.0
  packages/foreman/puppet-agent-puppet-strings/puppet-agent-puppet-strings.spec
  packages/foreman/puppet-agent-puppet-strings/puppet-strings-2.1.0.gem
  packages/foreman/puppet-agent-puppet-strings/puppet-strings-2.3.0.gem
Labels: Needs testing, RPM

#4128 add ansible-collection-theforeman-foreman
  comps/comps-foreman-client-fedora29.xml
  comps/comps-foreman-client-rhel7.xml
  package_manifest.yaml
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-0.1.0.tar.gz
  rel-eng/tito.props
Labels: Needs testing, RPM

#4123 Bump rubygem-rubyipmi to 0.10.0-1
  packages/foreman/rubygem-rubyipmi/rubygem-rubyipmi.spec
Labels: Needs testing, RPM

#4125 Bump rubygem-logify to 0.2.0-1
  packages/plugins/rubygem-logify/rubygem-logify.spec
Labels: Needs testing, RPM

#4124 Bump rubygem-infoblox to 3.0.0-1
  packages/plugins/rubygem-infoblox/rubygem-infoblox.spec
Labels: Needs testing, RPM

#4126 Update rubygem-radcli to support SCL
  packages/plugins/rubygem-radcli/rubygem-radcli.spec
Labels: Needs testing, RPM

#4122 Bump rubygem-rsec to 0.4.3-1
  packages/foreman/rubygem-rsec/rubygem-rsec.spec
Labels: Needs testing, RPM

#4116 Update smart_proxy_plugin gem2rpm template
  gem2rpm/smart_proxy_plugin.spec.erb
Labels: Needs testing, RPM

#4117 Introduce two new package groups in package_manifest for foreman-proxy
  package_manifest.yaml
Labels: Needs testing, RPM

#4145 Explicitly use python3 in add_gem_package.sh
  add_gem_package.sh
Labels: Needs testing, RPM

#4121 Update rubygem-rb-inotify to handle SCL building
  packages/foreman/rubygem-rb-inotify/rubygem-rb-inotify.spec
Labels: Needs testing, RPM

#4150 Add nodejs package group
  package_manifest.yaml
Labels: Needs testing, RPM

#4111 Update for new Obal tito modules
  package_manifest.yaml
Labels: Needs testing, RPM

#4147 Add root_sysconfdir macro to smart_proxy_plugin template
  gem2rpm/smart_proxy_plugin.spec.erb
Labels: Needs testing, RPM

#4139 foreman_datacenter 1.21.1
  plugins/ruby-foreman-datacenter/debian/changelog
  plugins/ruby-foreman-datacenter/debian/control
  plugins/ruby-foreman-datacenter/debian/gem.list
  plugins/ruby-foreman-datacenter/foreman_datacenter.rb
Labels: DEB, Needs testing, Not yet reviewed, Stable branch

#4140 foreman_datacenter 1.22.1
  plugins/ruby-foreman-datacenter/debian/changelog
  plugins/ruby-foreman-datacenter/debian/control
  plugins/ruby-foreman-datacenter/debian/gem.list
  plugins/ruby-foreman-datacenter/foreman_datacenter.rb
Labels: DEB, Needs testing, Not yet reviewed, Stable branch

#4141 foreman_datacenter 1.23.0
  plugins/ruby-foreman-datacenter/debian/changelog
  plugins/ruby-foreman-datacenter/debian/control
  plugins/ruby-foreman-datacenter/debian/gem.list
  plugins/ruby-foreman-datacenter/foreman_datacenter.rb
Labels: DEB, Needs testing, Not yet reviewed, Stable branch
