Repository theforeman/foreman-packaging, pull requests merged in 2019-07, with the labels that each got.

#3873 Update rubygem-foreman_kubevirt to 0.1.4
  packages/plugins/rubygem-foreman_kubevirt/foreman_kubevirt-0.1.3.gem
  packages/plugins/rubygem-foreman_kubevirt/foreman_kubevirt-0.1.4.gem
  packages/plugins/rubygem-foreman_kubevirt/rubygem-foreman_kubevirt.spec
Labels: Needs testing, RPM

#3863 Fixes #26278 - GPG sign client repositories
  packages/foreman/foreman-release/foreman-release.spec
Labels: Needs testing, RPM, Stable branch

#3856 katello-host-tools 3.5.1
  packages/client/katello-host-tools/katello-host-tools-3.5.0.tar.gz
  packages/client/katello-host-tools/katello-host-tools-3.5.1.tar.gz
  packages/client/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#3874 Fixes #26278 - GPG sign client repositories
  packages/foreman/foreman-release/foreman-release.spec
Labels: Needs testing, RPM, Stable branch

#3876 Make repoclosure_target_repos a dict
  package_manifest.yaml
Labels: Needs testing, RPM, Stable branch

#3872 Update foreman_expire_hosts to 6.0.1
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-6.0.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-6.0.1.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Needs testing, RPM

#3879 Update rubygem-foreman_maintain to 0.4.4
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.4.3.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.4.4.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#3880 Updated Hammer CLI Bootdisk to 0.3.0
  packages/plugins/rubygem-hammer_cli_foreman_bootdisk/hammer_cli_foreman_bootdisk-0.1.3.gem
  packages/plugins/rubygem-hammer_cli_foreman_bootdisk/hammer_cli_foreman_bootdisk-0.3.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_bootdisk/rubygem-hammer_cli_foreman_bootdisk.spec
Labels: Needs testing, RPM

#3878 release katello 3.11.2
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.11.1.gem
  packages/katello/rubygem-katello/katello-3.11.2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#3858 Add pulp_ansible_client for katello pulp3 support
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-pulp_ansible_client/pulp_ansible_client-0.2.0b1.dev0.1560866833.gem
  packages/katello/rubygem-pulp_ansible_client/rubygem-pulp_ansible_client.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3794 Refs #26844 - Require at least Puppet 5.5.10
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: Needs testing, RPM

#3877 update katello for pulp ansible client requirement
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#3881 Updated Hammer CLI Bootdisk to 0.3.0 - DEB
  dependencies/bionic/hammer_cli_foreman_bootdisk/changelog
  dependencies/stretch/hammer_cli_foreman_bootdisk/changelog
  dependencies/xenial/hammer_cli_foreman_bootdisk/changelog
Labels: Needs testing, Not yet reviewed

#3885 Do more detection of parameters in add_gem_package
  add_gem_package.sh
Labels: Needs testing, RPM

#3886 Fixes #27225: Fix the Foreman restart macro
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#3888 Release 1.20.3-2 with ruby 2.3 compatible spring
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/stretch/foreman/rules
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
  debian/xenial/foreman/rules
Labels: DEB, Needs testing, Stable branch

#3890 Drop development package
  debian/bionic/foreman/control
  debian/bionic/foreman/foreman-development.install
  debian/bionic/foreman/foreman-development.postinst
  debian/bionic/foreman/rules
  debian/stretch/foreman/control
  debian/stretch/foreman/foreman-development.install
  debian/stretch/foreman/foreman-development.postinst
  debian/stretch/foreman/rules
  debian/xenial/foreman/control
  debian/xenial/foreman/foreman-development.install
  debian/xenial/foreman/foreman-development.postinst
  debian/xenial/foreman/rules
Labels: DEB, Needs testing, Not yet reviewed

#3898 update foreman_xen to 1.0.0
  plugins/ruby-foreman-xen/debian/changelog
  plugins/ruby-foreman-xen/debian/control
  plugins/ruby-foreman-xen/debian/gem.list
  plugins/ruby-foreman-xen/foreman_xen.rb
Labels: Needs testing, Not yet reviewed

#3900 Rpm/develop bump fog kubevirt to 1.3.1
  packages/plugins/rubygem-fog-kubevirt/fog-kubevirt-1.3.0.gem
  packages/plugins/rubygem-fog-kubevirt/fog-kubevirt-1.3.1.gem
  packages/plugins/rubygem-fog-kubevirt/rubygem-fog-kubevirt.spec
Labels: Needs testing, RPM

#3887 Fixes #27225: Fix the Foreman restart macro
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#3891 use puppet6 repo for repoclosure
  package_manifest.yaml
Labels: Needs testing, RPM, Stable branch

#3857 Bump nodejs-diff to 4.0.1
  packages/foreman/nodejs-diff/diff-3.0.1.tgz
  packages/foreman/nodejs-diff/diff-4.0.1.tgz
  packages/foreman/nodejs-diff/nodejs-diff.spec
Labels: Needs testing, RPM

#3897 update foreman_xen to 1.0.0
  packages/plugins/rubygem-foreman_xen/foreman_xen-0.7.1.gem
  packages/plugins/rubygem-foreman_xen/foreman_xen-1.0.0.gem
  packages/plugins/rubygem-foreman_xen/rubygem-foreman_xen.spec
Labels: Needs testing, RPM

#3901 Update rubygem-foreman_openscap to 1.0.4
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-1.0.1.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-1.0.4.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#3902 Refs #27103 - Allow diff 4.x in unidiff
  packages/foreman/nodejs-unidiff/nodejs-unidiff.spec
Labels: Needs testing, RPM

#3903 add the owner to namespaced npm packages
  add_npm_package.sh
Labels: Needs testing, RPM

#3904 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#3896 build pulp_docker gem for katello
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-pulp_docker_client/pulp_docker_client-4.0.0b6.dev01562331743.gem
  packages/katello/rubygem-pulp_docker_client/rubygem-pulp_docker_client.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3906 Update katello package dependencies
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Waiting on contributor

#3907 Update foreman_maintain to 0.4.5
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.4.4.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.4.5.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#3908 don't inspect foreman-nighly when doing nonscl repoclosure
  package_manifest.yaml
Labels: Needs testing, RPM

#3909 don't inspect foreman-plugins-nighly when doing nonscl repoclosure
  package_manifest.yaml
Labels: Needs testing, RPM

#3884 Add rubygem-smart_proxy_dhcp_dnsmasq package
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-smart_proxy_dhcp_dnsmasq/rubygem-smart_proxy_dhcp_dnsmasq.spec
  packages/plugins/rubygem-smart_proxy_dhcp_dnsmasq/smart_proxy_dhcp_dnsmasq-0.7.gem
  rel-eng/tito.props
Labels: Needs testing, RPM

#3754 Update rubygem-fog-proxmox to 0.8.0
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-fog-proxmox/fog-proxmox-0.8.0.gem
  packages/plugins/rubygem-fog-proxmox/rubygem-fog-proxmox.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3910 Update rubygem-foreman_fog_proxmox package to 0.8.0
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.8.0.gem
  packages/plugins/rubygem-foreman_fog_proxmox/rubygem-foreman_fog_proxmox.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3911 Refs #26591 - Drop support for Puppet 3 in proxy
  debian/bionic/foreman-proxy/foreman-proxy.install
  debian/stretch/foreman-proxy/foreman-proxy.install
  debian/xenial/foreman-proxy/foreman-proxy.install
Labels: DEB, Needs testing, Not yet reviewed, Waiting on contributor

#3922 Use bundle exec to generate sources
  rel-eng/custom/custom.py
Labels: Needs testing, RPM

#3918 include seconds in the generated git version number
  rel-eng/custom/custom.py
Labels: Needs testing

#3924 Add nodejs-theforeman-vendor package
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/nodejs-theforeman-vendor/nodejs-theforeman-vendor.spec
  packages/foreman/nodejs-theforeman-vendor/vendor-0.1.0-alpha.11.tgz
  rel-eng/tito.props
Labels: Needs testing

#3892 Update foreman_expire_hosts to 6.0.1
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-6.0.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-6.0.1.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Needs testing, RPM, Stable branch

#3912 Update rubygem-foreman_remote_execution to 1.8.2
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.8.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.8.2.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#3916 Update rubygem-foreman-tasks to 0.16.0
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.15.5.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.16.0.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#3926 [1.21] Update foreman-tasks to 0.14.6
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Not yet reviewed

#3920 [1.22] Update foreman-tasks to 0.15.7
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Not yet reviewed

#3917 Update foreman-tasks to 0.16.0
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB, Needs testing, Not yet reviewed

#3915 [1.22] Update foreman_remote_execution to 1.8.2
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing, Not yet reviewed

#3927 update deface to 1.5.0
  plugins/ruby-foreman-deface/debian/changelog
  plugins/ruby-foreman-deface/debian/gem.list
  plugins/ruby-foreman-deface/foreman_deface.rb
Labels: DEB, Needs testing, Not yet reviewed

#3913 Update foreman_remote_execution to 1.8.2
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB, Needs testing, Not yet reviewed

#3931 add bootstrap-sass to f-tasks to fix build problems
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#3933 Remove foreman-vendor artifacts from plugin builds
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#3930 Rebuild foreman_ansible for @theforeman/vendor
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#3919 [1.22] Update rubygem-foreman-tasks to 0.15.7
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.15.5.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.15.7.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#3925 [1.21] Update rubygem-foreman-tasks to 0.14.6
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.14.5.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.14.6.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#3914 [1.22] Update rubygem-foreman_remote_execution to 1.8.2
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.8.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-1.8.2.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#3934 Fixes #27326 - Non-executable hammer config files
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM

#3928 Katello 3.12.1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.12.0.gem
  packages/katello/rubygem-katello/katello-3.12.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#3935 Update rubygem-fog-vsphere to 3.2.0
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.1.1.gem
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.2.0.gem
  packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec
Labels: Needs testing, RPM

#3940 Update rubygem-foreman_salt to 11.0.1
  packages/plugins/rubygem-foreman_salt/foreman_salt-11.0.0.gem
  packages/plugins/rubygem-foreman_salt/foreman_salt-11.0.1.gem
  packages/plugins/rubygem-foreman_salt/rubygem-foreman_salt.spec
Labels: Needs testing, RPM

#3894 Update foreman_expire_hosts to 6.0.1
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-6.0.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-6.0.1.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Needs testing, RPM, Stable branch

#3893 Update foreman_expire_hosts to 6.0.1
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-6.0.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-6.0.1.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Needs testing, RPM, Stable branch

#3942 fix puppet6 lookasides in rpm/1.22
  package_manifest.yaml
Labels: Needs testing, RPM

#3948 Bump nodejs-theforeman-vendor to 0.1.1
  packages/foreman/nodejs-theforeman-vendor/nodejs-theforeman-vendor.spec
  packages/foreman/nodejs-theforeman-vendor/vendor-0.1.0-alpha.11.tgz
  packages/foreman/nodejs-theforeman-vendor/vendor-0.1.1.tgz
Labels: Needs testing, RPM

#3939 Update rubygem-hammer_cli_foreman to 0.17.1
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.17.0.gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.17.1.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM, Stable branch

#3944 look at puppet5 repos for repoclosure of rpm/1.21
  package_manifest.yaml
Labels: Needs testing, RPM

#3938 Fixes #27255 - katello-change-hostname cleans puppet certs
  packages/katello/katello/hostname-change.rb
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#3936 Update rubygem-foreman_ansible to 3.0.5
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-3.0.3.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-3.0.5.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#3951 Update to Discovery 15.0.1 - RPM
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-15.0.0.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-15.0.1.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, RPM

#3953 Update to Discovery 15.0.1 - 1.22
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-15.0.0.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-15.0.1.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, RPM

#3947 Update katello packaging to @theforeman/vendor bundle
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#3952 call git rev-parse with universal_newlines=True
  rel-eng/custom/custom.py
Labels: Needs testing, RPM

#3943 also look for puppet6 in scl/nonscl packages
  package_manifest.yaml
Labels: Needs testing, RPM

#3957 Update ansiblerole-foreman_scap_client to 0.0.3
  packages/plugins/ansiblerole-foreman_scap_client/ansiblerole-foreman_scap_client.spec
  packages/plugins/ansiblerole-foreman_scap_client/foreman_scap_client-0.0.2.tar.gz
  packages/plugins/ansiblerole-foreman_scap_client/foreman_scap_client-0.0.3.tar.gz
Labels: Needs testing

#3949 Adjust selinux for proxmox
  packages/plugins/rubygem-foreman_fog_proxmox/rubygem-foreman_fog_proxmox.spec
Labels: Needs testing, RPM

#3961 Update rubygem-hammer_cli_katello to 0.18.2
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.18.0.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.18.2.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM, Stable branch

#3850 Update smart_proxy_dynflow to 0.2.3
  plugins/smart_proxy_dynflow/changelog
  plugins/smart_proxy_dynflow/dynflow.rb
Labels: DEB, Needs testing, Not yet reviewed

#3950 Update Discovery to 15.0.1 - DEB
  plugins/ruby-foreman-discovery/debian/changelog
  plugins/ruby-foreman-discovery/debian/gem.list
  plugins/ruby-foreman-discovery/foreman_discovery.rb
Labels: Needs testing, Not yet reviewed

#3962 Update foreman_rescue to 2.0.1
  packages/plugins/rubygem-foreman_rescue/foreman_rescue-2.0.0.gem
  packages/plugins/rubygem-foreman_rescue/foreman_rescue-2.0.1.gem
  packages/plugins/rubygem-foreman_rescue/rubygem-foreman_rescue.spec
Labels: Needs testing, Not yet reviewed, RPM

#3965 use pulp 2.19 for repoclosure
  repoclosure/yum.conf
  repoclosure/yum_el7.conf
Labels: Needs testing, RPM

#3966 Bump Debian changelog to 1.24.0 to match VERSION
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: DEB, Needs testing

#3972 Release 1.23.0-RC1
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: Needs testing, Not yet reviewed, Stable branch
