Repository theforeman/foreman-packaging, pull requests merged in 2019-12, with the labels that each got.

#4430 Update rubygem-fog-ovirt to 1.2.3
  packages/foreman/rubygem-fog-ovirt/fog-ovirt-1.2.2.gem
  packages/foreman/rubygem-fog-ovirt/fog-ovirt-1.2.3.gem
  packages/foreman/rubygem-fog-ovirt/rubygem-fog-ovirt.spec
Labels: Needs testing, RPM

#4429 Update rubygem-foreman_remote_execution to 2.0.4
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-2.0.3.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-2.0.4.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#4428 Update foreman_remote_execution to 2.0.4
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB, Needs testing, Stable branch

#4434 Update rubygem-foreman_discovery to 16.0.1 (1.24)
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-16.0.0.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-16.0.1.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, RPM, Stable branch

#4433 Bump rubygem-pg to 1.1.4-1
  packages/foreman/rubygem-pg/pg-0.21.0.gem
  packages/foreman/rubygem-pg/pg-1.1.4.gem
  packages/foreman/rubygem-pg/rubygem-pg.spec
Labels: Needs testing, RPM

#4432 Use package names, not provides in Obsoletes of the f_openscap package
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#4431 Use package names, not provides in Obsoletes of the tfm package
  packages/foreman/tfm/tfm.spec
Labels: Needs testing, RPM

#4416 Bump nodejs-babel-loader to 8.0.6
  packages/foreman/nodejs-babel-loader/babel-loader-7.1.4.tgz
  packages/foreman/nodejs-babel-loader/babel-loader-8.0.6.tgz
  packages/foreman/nodejs-babel-loader/find-cache-dir-1.0.0.tgz
  packages/foreman/nodejs-babel-loader/find-cache-dir-2.1.0.tgz
  packages/foreman/nodejs-babel-loader/find-up-2.1.0.tgz
  packages/foreman/nodejs-babel-loader/find-up-3.0.0.tgz
  packages/foreman/nodejs-babel-loader/locate-path-2.0.0.tgz
  packages/foreman/nodejs-babel-loader/locate-path-3.0.0.tgz
  packages/foreman/nodejs-babel-loader/make-dir-1.3.0.tgz
  packages/foreman/nodejs-babel-loader/make-dir-2.1.0.tgz
  packages/foreman/nodejs-babel-loader/nodejs-babel-loader-7.1.4-registry.npmjs.org.tgz
  packages/foreman/nodejs-babel-loader/nodejs-babel-loader-8.0.6-registry.npmjs.org.tgz
  packages/foreman/nodejs-babel-loader/nodejs-babel-loader.spec
  packages/foreman/nodejs-babel-loader/p-limit-1.3.0.tgz
  packages/foreman/nodejs-babel-loader/p-limit-2.2.1.tgz
  packages/foreman/nodejs-babel-loader/p-locate-2.0.0.tgz
  packages/foreman/nodejs-babel-loader/p-locate-3.0.0.tgz
  packages/foreman/nodejs-babel-loader/p-try-1.0.0.tgz
  packages/foreman/nodejs-babel-loader/p-try-2.2.0.tgz
  packages/foreman/nodejs-babel-loader/pify-3.0.0.tgz
  packages/foreman/nodejs-babel-loader/pify-4.0.1.tgz
  packages/foreman/nodejs-babel-loader/pkg-dir-2.0.0.tgz
  packages/foreman/nodejs-babel-loader/pkg-dir-3.0.0.tgz
  packages/foreman/nodejs-babel-loader/semver-5.7.1.tgz
Labels: Needs testing, RPM

#4437 Bump rubygem-deface to 1.5.3-1
  packages/plugins/rubygem-deface/deface-1.3.2.gem
  packages/plugins/rubygem-deface/deface-1.5.3.gem
  packages/plugins/rubygem-deface/rubygem-deface.spec
Labels: Needs testing, RPM

#4417 Bump nodejs-theforeman-vendor to 3.3.2
  packages/foreman/nodejs-theforeman-vendor/nodejs-theforeman-vendor.spec
  packages/foreman/nodejs-theforeman-vendor/vendor-1.7.0.tgz
  packages/foreman/nodejs-theforeman-vendor/vendor-3.3.2.tgz
Labels: Needs testing, RPM

#4438 update deface to 1.5.3
  plugins/ruby-foreman-deface/debian/changelog
  plugins/ruby-foreman-deface/debian/gem.list
  plugins/ruby-foreman-deface/foreman_deface.rb
Labels: DEB, Needs testing, Not yet reviewed

#4435 update foreman npm and gem dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#4441 Updated hammer_cli_foreman to 0.19.3
  dependencies/bionic/hammer_cli_foreman/changelog
  dependencies/buster/hammer_cli_foreman/changelog
  dependencies/stretch/hammer_cli_foreman/changelog
  dependencies/xenial/hammer_cli_foreman/changelog
Labels: DEB, Needs testing, Stable branch

#4440 Update rubygem-hammer_cli_foreman to 0.19.3
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.19.2.gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.19.3.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM, Stable branch

#4439 Update rubygem-prometheus-client to 1.0.0
  packages/foreman/rubygem-prometheus-client/prometheus-client-0.7.1.gem
  packages/foreman/rubygem-prometheus-client/prometheus-client-1.0.0.gem
  packages/foreman/rubygem-prometheus-client/rubygem-prometheus-client.spec
Labels: Needs testing, RPM

#4443 Release hammer-cli-katello 0.20.2
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.20.1.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.20.2.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM, Stable branch

#4444 Bump rubygem-deface to 1.5.3-1
  packages/plugins/rubygem-deface/deface-1.3.2.gem
  packages/plugins/rubygem-deface/deface-1.5.3.gem
  packages/plugins/rubygem-deface/rubygem-deface.spec
Labels: Needs testing, RPM, Stable branch

#4445 Update katello-client-bootstrap to 1.7.4
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.3.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.4.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap.spec
Labels: Needs testing, RPM

#4448 Updated foreman-fog-proxmox to 0.9.2
  plugins/ruby-foreman-fog-proxmox/debian/changelog
  plugins/ruby-foreman-fog-proxmox/debian/gem.list
  plugins/ruby-foreman-fog-proxmox/foreman_fog_proxmox.rb
Labels: DEB, Needs testing, Not yet reviewed

#4436 Handle rename of pulp_docker_client
  comps/comps-katello-server-rhel7.xml
  licenses.json
  package_manifest.yaml
  packages/katello/rubygem-pulp_container_client/pulp_container_client-1.0.0rc1.gem
  packages/katello/rubygem-pulp_container_client/rubygem-pulp_container_client.spec
  packages/katello/rubygem-pulp_docker_client/pulp_docker_client-4.0.0b6.dev01562331743.gem
  rel-eng/tito.props
Labels: Needs testing, RPM

#4457 Update rubygem-foreman_ansible to 4.0.2
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-4.0.0.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-4.0.2.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM, Stable branch

#4455 Update rubygem-foreman-tasks to 0.17.4
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.17.3.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.17.4.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM, Stable branch

#4446 Update katello-client-bootstrap to 1.7.4
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.3.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.4.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap.spec
Labels: Needs testing, RPM, Stable branch

#4459 Update katello-client-bootstrap to 1.7.4
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.3.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.4.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap.spec
Labels: Needs testing, RPM, Stable branch

#4460 Update ansible-collection-theforeman-foreman to 0.3.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-0.2.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-0.3.0.tar.gz
Labels: Needs testing, RPM

#4421 Update katello package dependencies
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#4462 update RPM for NPM dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#4453 Update foreman-tasks to 0.17.4
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Not yet reviewed

#4454 Update foreman-tasks to 0.17.4
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Not yet reviewed

#4451 Update foreman_ansible to 4.0.2
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing, Not yet reviewed

#4452 Update foreman_ansible to 4.0.2
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing, Not yet reviewed

#4465 Switch URL quoting to use Python 3
  add_npm_package.sh
Labels: Needs testing, RPM

#4467 Update foreman_git_templates to 1.0.3
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.2.gem
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.3.gem
  packages/plugins/rubygem-foreman_git_templates/rubygem-foreman_git_templates.spec
Labels: Needs testing

#4466 Update foreman_expire_hosts to 7.0.0
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-6.0.2.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-7.0.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Needs testing, RPM

#4470 Update rubygem-foreman_azure_rm to 2.0.3
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.0.2.gem
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.0.3.gem
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
Labels: Needs testing, Not yet reviewed, RPM

#4469 Release Foreman 1.24.0
  packages/foreman/foreman-installer/foreman-installer-1.24.0-RC3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-1.24.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-1.24.0-RC3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-1.24.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-selinux/foreman-selinux-1.24.0-RC3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-1.24.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-1.24.0-RC3.tar.bz2
  packages/foreman/foreman/foreman-1.24.0.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#4471 Release Foreman 1.24.0
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: Needs testing, Not yet reviewed

#4473 foreman-release 1.24.0
  packages/foreman/foreman-release/foreman-release.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#4463 Update rubygem-hammer_cli_foreman to 0.19.4
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.19.3.gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.19.4.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM, Stable branch

#4464 Updated hammer_cli_foreman to 0.19.4
  dependencies/bionic/hammer_cli_foreman/changelog
  dependencies/buster/hammer_cli_foreman/changelog
  dependencies/stretch/hammer_cli_foreman/changelog
  dependencies/xenial/hammer_cli_foreman/changelog
Labels: DEB, Needs testing, Stable branch

#4472 Cherry-pick rubygem-foreman_azure_rm 2.0.3
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.0.2.gem
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.0.3.gem
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
Labels: Needs testing, Stable branch

#4474 remove any BuildRequires for sphinx when adding Python packages
  add_pypi_package.sh
Labels: Needs testing, RPM

#4475 Release Katello 3.14.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.14.0.gem
  packages/katello/rubygem-katello/katello-3.14.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#4477 fix changelog when updating python packages
  add_pypi_package.sh
Labels: Needs testing, RPM

#4476 Update rubygem-foreman_templates to 7.0.5
  packages/plugins/rubygem-foreman_templates/foreman_templates-7.0.4.gem
  packages/plugins/rubygem-foreman_templates/foreman_templates-7.0.5.gem
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#4484 Update rubygem-record_tag_helper to 1.0.1
  packages/foreman/rubygem-record_tag_helper/record_tag_helper-1.0.0.gem
  packages/foreman/rubygem-record_tag_helper/record_tag_helper-1.0.1.gem
  packages/foreman/rubygem-record_tag_helper/rubygem-record_tag_helper.spec
Labels: Needs testing, RPM

#4486 also add apidoc when the plugin only has concerns
  gem2rpm/foreman_plugin.spec.erb
Labels: Needs testing, RPM

#4483 move the 'don't whitelist' comment above the whitelist enty
  rel-eng/tito.props
Labels: Needs testing, RPM

#4482 [1.24] move the 'don't whitelist' comment above the whitelist entyo
  rel-eng/tito.props
Labels: Needs testing, RPM, Stable branch

#4494 Update rubygem-foreman_azure_rm to 2.0.4
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.0.3.gem
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.0.4.gem
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
Labels: Needs testing, RPM

#4481 [1.23] move the 'don't whitelist' comment above the whitelist enty
  rel-eng/tito.props
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#4468 Add recognition of cronjobs to gem2rpm templates
  gem2rpm/foreman_plugin.spec.erb
  gem2rpm/smart_proxy_plugin.spec.erb
Labels: Needs testing, RPM

#4497 Cherry-pick rubygem-foreman_azure_rm 2.0.4
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.0.3.gem
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.0.4.gem
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#4495 Add scl prefix when generating node dependencies
  update-requirements
Labels: Needs testing, RPM, Stable branch

#4500 rename pulpcore tag
  add_pypi_package.sh
  package_manifest.yaml
  rel-eng/releasers.conf
  rel-eng/tito.props
Labels: Needs testing, RPM

#4499 Bump python-django to 2.2.8
  packages/pulpcore/python-django/Django-2.2.7.tar.gz
  packages/pulpcore/python-django/Django-2.2.8.tar.gz
  packages/pulpcore/python-django/python-django.spec
Labels: Needs testing, RPM

#4478 only update if the version differs
  add_gem_package.sh
  add_npm_package.sh
  add_pypi_package.sh
Labels: Needs testing, RPM

#4502 add repoclosure for pulpcore repo
  package_manifest.yaml
  repoclosure/yum.conf
  repoclosure/yum_el7.conf
Labels: Needs testing, RPM

#4501 Add python-pygtrie package
  comps/comps-katello-pulpcore-el7.xml
  package_manifest.yaml
  packages/pulpcore/python-pygtrie/pygtrie-2.3.2.tar.gz
  packages/pulpcore/python-pygtrie/python-pygtrie.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#4504 use el7 not rhel7 as target repo for pulpcore
  package_manifest.yaml
Labels: Needs testing, RPM

#4496 Updated foreman-fog-proxmox to 0.9.3
  plugins/ruby-foreman-fog-proxmox/debian/changelog
  plugins/ruby-foreman-fog-proxmox/debian/gem.list
  plugins/ruby-foreman-fog-proxmox/foreman_fog_proxmox.rb
Labels: DEB, Needs testing, Not yet reviewed

#4488 Update foreman_tasks to 0.17.5
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Not yet reviewed

#4490 Update foreman_tasks to 0.17.5
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Not yet reviewed

#4505 add pulpcore to katello-repos
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello-repos/katello.repo
Labels: Needs testing, RPM

#4405 Update rubygem-fog-proxmox to 0.9.0
  packages/plugins/rubygem-fog-proxmox/fog-proxmox-0.8.3.gem
  packages/plugins/rubygem-fog-proxmox/fog-proxmox-0.9.0.gem
  packages/plugins/rubygem-fog-proxmox/rubygem-fog-proxmox.spec
Labels: Needs testing, RPM

#4498 Update rubygem-foreman_fog_proxmox to 0.9.3
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.8.0.gem
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.9.3.gem
  packages/plugins/rubygem-foreman_fog_proxmox/rubygem-foreman_fog_proxmox.spec
Labels: Needs testing, RPM

#4518 Update rubygem-hammer_cli_foreman_azure_rm to 0.1.1
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/hammer_cli_foreman_azure_rm-0.1.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/hammer_cli_foreman_azure_rm-0.1.1.gem
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/rubygem-hammer_cli_foreman_azure_rm.spec
Labels: Needs testing, RPM

#4510 update vendor and builder to 3.9.0
  packages/foreman/nodejs-theforeman-builder/builder-3.5.2.tgz
  packages/foreman/nodejs-theforeman-builder/builder-3.9.0.tgz
  packages/foreman/nodejs-theforeman-builder/caniuse-lite-1.0.30001015.tgz
  packages/foreman/nodejs-theforeman-builder/caniuse-lite-1.0.30001016.tgz
  packages/foreman/nodejs-theforeman-builder/core-js-compat-3.4.7.tgz
  packages/foreman/nodejs-theforeman-builder/core-js-compat-3.5.0.tgz
  packages/foreman/nodejs-theforeman-builder/nodejs-theforeman-builder-3.5.2-registry.npmjs.org.tgz
  packages/foreman/nodejs-theforeman-builder/nodejs-theforeman-builder-3.9.0-registry.npmjs.org.tgz
  packages/foreman/nodejs-theforeman-builder/nodejs-theforeman-builder.spec
  packages/foreman/nodejs-theforeman-builder/preset-env-7.7.5.tgz
  packages/foreman/nodejs-theforeman-builder/preset-env-7.7.6.tgz
  packages/foreman/nodejs-theforeman-builder/regjsparser-0.6.0.tgz
  packages/foreman/nodejs-theforeman-builder/regjsparser-0.6.1.tgz
  packages/foreman/nodejs-theforeman-vendor/nodejs-theforeman-vendor.spec
  packages/foreman/nodejs-theforeman-vendor/vendor-3.5.2.tgz
  packages/foreman/nodejs-theforeman-vendor/vendor-3.9.0.tgz
Labels: Needs testing, RPM

#4489 [1.24] Update rubygem-foreman-tasks to 0.17.5
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.17.4.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-0.17.5.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, Not yet reviewed

#4491 Update rubygem-foreman_ansible to 4.0.3
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-4.0.2.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-4.0.3.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM, Stable branch

#4522 Bump python-django to 2.2.9
  packages/pulpcore/python-django/Django-2.2.8.tar.gz
  packages/pulpcore/python-django/Django-2.2.9.tar.gz
  packages/pulpcore/python-django/python-django.spec
Labels: Needs testing, RPM

#4527 Update foreman-remote-execution to 2.0.6
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing, Not yet reviewed, Stable branch

#4528 Update foreman-tasks to 1.0.0
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/control
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Not yet reviewed

#4531 Refactor add_host.py to drop click dependency
  add_host.py
Labels: Needs testing, RPM

#4526 Update rubygem-foreman_remote_execution to 2.0.6
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-2.0.4.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-2.0.6.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM, Stable branch

#4520 cherry-pick rubygem-hammer_cli_foreman_azure_rm 0.1.1
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/hammer_cli_foreman_azure_rm-0.1.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/hammer_cli_foreman_azure_rm-0.1.1.gem
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/rubygem-hammer_cli_foreman_azure_rm.spec
Labels: Needs testing, RPM, Stable branch

#4514 Update foreman_hooks to 0.3.16
  plugins/ruby-foreman-hooks/debian/changelog
  plugins/ruby-foreman-hooks/debian/gem.list
  plugins/ruby-foreman-hooks/foreman_hooks.rb
Labels: Needs testing, Not yet reviewed

#4507 Update README with npm2rpm instructions
  README.md
Labels: Needs testing, RPM

#4533 Add foreman_expire_hosts 7.0.0
  plugins/ruby-foreman-expire-hosts/debian/changelog
  plugins/ruby-foreman-expire-hosts/debian/compat
  plugins/ruby-foreman-expire-hosts/debian/control
  plugins/ruby-foreman-expire-hosts/debian/copyright
  plugins/ruby-foreman-expire-hosts/debian/gem.list
  plugins/ruby-foreman-expire-hosts/debian/install
  plugins/ruby-foreman-expire-hosts/debian/postinst
  plugins/ruby-foreman-expire-hosts/debian/ruby-foreman-expire-hosts.cron.d
  plugins/ruby-foreman-expire-hosts/debian/rules
  plugins/ruby-foreman-expire-hosts/debian/source/format
  plugins/ruby-foreman-expire-hosts/foreman_expire_hosts.rb
Labels: DEB, Needs testing, Not yet reviewed
