Repository theforeman/foreman-packaging, pull requests merged in 2019-08, with the labels that each got.

#3971 Release 1.23.0-RC1
  packages/foreman/foreman-installer/foreman-installer-1.23.0-RC1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-1.23.0-RC1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-1.23.0-RC1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-1.23.0-RC1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#3958 Update infoblox gem to 3.0.0
  packages/plugins/rubygem-infoblox/infoblox-2.0.4.gem
  packages/plugins/rubygem-infoblox/infoblox-3.0.0.gem
  packages/plugins/rubygem-infoblox/rubygem-infoblox.spec
Labels: Needs testing, Not yet reviewed, RPM

#3968 Updated discovery hammer to 1.0.1
  dependencies/bionic/hammer_cli_foreman_discovery/changelog
  dependencies/stretch/hammer_cli_foreman_discovery/changelog
  dependencies/xenial/hammer_cli_foreman_discovery/changelog
Labels: Needs testing, Not yet reviewed

#3871 Fixes #27186 - Update katello-remove to include /var/cache/pulp
  packages/katello/katello/katello-remove
Labels: Needs testing, RPM

#3978 Update hammer_cli to 0.18.0
  dependencies/bionic/hammer_cli/changelog
  dependencies/stretch/hammer_cli/changelog
  dependencies/xenial/hammer_cli/changelog
Labels: Needs testing, Not yet reviewed, Stable branch

#3979 Update hammer_cli_foreman to 0.18.0
  dependencies/bionic/hammer_cli_foreman/changelog
  dependencies/bionic/hammer_cli_foreman/control
  dependencies/stretch/hammer_cli_foreman/changelog
  dependencies/stretch/hammer_cli_foreman/control
  dependencies/xenial/hammer_cli_foreman/changelog
  dependencies/xenial/hammer_cli_foreman/control
Labels: Needs testing, Not yet reviewed, Stable branch

#3975 Point repoclosure to foreman-rails-1.23
  repoclosure/yum.conf
  repoclosure/yum_el7.conf
Labels: Needs testing, RPM, Stable branch

#3980 Discovery 15.0.2
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-15.0.1.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-15.0.2.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, RPM

#3976 Update rubygem-hammer-cli to 0.18.0
  packages/foreman/rubygem-hammer_cli/hammer_cli-0.18.0.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
Labels: Needs testing, RPM, Stable branch

#3974 Bump katello to pulp 2.20
  packages/katello/katello-repos/katello-repos.spec
Labels: Needs testing, RPM

#3984 Bump hammer to 0.19-develop
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
Labels: Needs testing, RPM

#3985 Update README to reflect proper SLES client tags
  README.md
Labels: Needs testing, RPM

#3977 Update rubygem-hammer_cli_foreman to 0.18.0
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.18.0.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM, Stable branch

#3986 Bump rubygem-hammer_cli_foreman to 0.19-develop
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM

#3981 Discovery 15.0.2
  plugins/ruby-foreman-discovery/debian/changelog
  plugins/ruby-foreman-discovery/debian/gem.list
  plugins/ruby-foreman-discovery/foreman_discovery.rb
Labels: Needs testing, Not yet reviewed

#3960 Updated infoblox DNS to 1.0.0 - DEB
  plugins/smart_proxy_dns_infoblox/changelog
  plugins/smart_proxy_dns_infoblox/dns_infoblox.rb
Labels: Needs testing, Not yet reviewed

#3956 feat: add ruby-foreman-rescue 2.0.1 plugin
  plugins/ruby-foreman-rescue/debian/changelog
  plugins/ruby-foreman-rescue/debian/compat
  plugins/ruby-foreman-rescue/debian/control
  plugins/ruby-foreman-rescue/debian/copyright
  plugins/ruby-foreman-rescue/debian/gem.list
  plugins/ruby-foreman-rescue/debian/install
  plugins/ruby-foreman-rescue/debian/postinst
  plugins/ruby-foreman-rescue/debian/rules
  plugins/ruby-foreman-rescue/debian/source/format
  plugins/ruby-foreman-rescue/foreman_rescue.rb
Labels: DEB, Needs testing, Not yet reviewed

#3945 Release foreman_salt 11.0.1
  plugins/ruby-foreman-salt/debian/changelog
  plugins/ruby-foreman-salt/debian/gem.list
  plugins/ruby-foreman-salt/foreman_salt.rb
Labels: DEB, Needs testing

#3987 bump katello to 3.14.0-master
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#3969 Bump rubygem-hammer_cli_foreman_discovery to 1.0.1-1
  packages/plugins/rubygem-hammer_cli_foreman_discovery/hammer_cli_foreman_discovery-1.0.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_discovery/hammer_cli_foreman_discovery-1.0.1.gem
  packages/plugins/rubygem-hammer_cli_foreman_discovery/rubygem-hammer_cli_foreman_discovery.spec
Labels: Needs testing, RPM

#3991 Update foreman-tasks to 0.15.8
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB, Needs testing, Not yet reviewed, Stable branch

#3994 Update ruby-foreman-ansible to 3.0.6
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing, Not yet reviewed

#3996 Update to apypie 0.0.4
  packages/client/python-apypie/apypie-0.0.3.tar.gz
  packages/client/python-apypie/apypie-0.0.4.tar.gz
  packages/client/python-apypie/python-apypie.spec
Labels: Needs testing, RPM

#3998 hammer_cli_katello 0.19.0
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.19.0.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM, Stable branch

#3999 regenerate hammer_cli_katello spec
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM

#3988 Update rubygem-foreman_scc_manager to 1.6.3
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.6.2.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.6.3.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM

#4001 Discovery 15.1 - DEB
  plugins/ruby-foreman-discovery/debian/changelog
  plugins/ruby-foreman-discovery/debian/gem.list
  plugins/ruby-foreman-discovery/foreman_discovery.rb
Labels: Needs testing, Not yet reviewed

#4005 Bootdisk 15.1
  plugins/ruby-foreman-bootdisk/debian/changelog
  plugins/ruby-foreman-bootdisk/debian/gem.list
  plugins/ruby-foreman-bootdisk/foreman_bootdisk.rb
Labels: Needs testing, Not yet reviewed

#4007 Update rubygem-hammer_cli_foreman to 0.17.2
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.17.1.gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.17.2.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM, Stable branch

#4000 Discovery 15.1 - RPM
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-15.0.2.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-15.1.0.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, RPM

#4004 Bootdisk 15.1
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-15.0.0.gem
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-15.1.0.gem
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
Labels: Needs testing, RPM

#3997 Katello 3.13.0 RC1
  packages/katello/katello-repos/RPM-GPG-KEY-katello
  packages/katello/katello-repos/RPM-GPG-KEY-katello-2015
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello-repos/katello.repo
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.13.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#4009 Update smart_proxy_dns_powerdns to 0.4.0
  plugins/smart_proxy_dns_powerdns/changelog
  plugins/smart_proxy_dns_powerdns/dns_powerdns.rb
Labels: Needs testing, Not yet reviewed

#3995 Update rubygem-foreman_openscap to 1.0.5
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-1.0.4.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-1.0.5.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#3993 Update rubygem-foreman_ansible to 3.0.6
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-3.0.5.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-3.0.6.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#3954 Fixes #27401 - katello_repositories debug sql query fixed
  packages/katello/katello/katello-debug.sh
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#4019 Katello 3.12.3
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.12.2.gem
  packages/katello/rubygem-katello/katello-3.12.3.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#3959 Updated infoblox DNS to 1.0.0
  packages/plugins/rubygem-smart_proxy_dns_infoblox/rubygem-smart_proxy_dns_infoblox.spec
  packages/plugins/rubygem-smart_proxy_dns_infoblox/smart_proxy_dns_infoblox-0.0.9.gem
  packages/plugins/rubygem-smart_proxy_dns_infoblox/smart_proxy_dns_infoblox-1.0.0.gem
Labels: Needs testing, RPM

#4015 Add rubygem-foreman_inventory_upload package
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-foreman_inventory_upload/foreman_inventory_upload-0.0.1.dev1.gem
  packages/katello/rubygem-foreman_inventory_upload/rubygem-foreman_inventory_upload.spec
  rel-eng/tito.props
Labels: Needs re-review, Needs testing, RPM

#4010 Update rubygem-smart_proxy_dns_powerdns to 0.4.0
  packages/plugins/rubygem-smart_proxy_dns_powerdns/rubygem-smart_proxy_dns_powerdns.spec
  packages/plugins/rubygem-smart_proxy_dns_powerdns/smart_proxy_dns_powerdns-0.3.0.gem
  packages/plugins/rubygem-smart_proxy_dns_powerdns/smart_proxy_dns_powerdns-0.4.0.gem
Labels: Needs testing, RPM

#3990 Update rubygem-foreman_virt_who_configure to 0.4.3
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.4.1.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.4.3.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Needs testing, RPM

#4016 Update apypie to 0.0.5
  packages/client/python-apypie/apypie-0.0.4.tar.gz
  packages/client/python-apypie/apypie-0.0.5.tar.gz
  packages/client/python-apypie/python-apypie.spec
Labels: Needs testing, RPM

#4025 Fixes #27564 - Copy only plugin webpack assets
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/install
Labels: DEB, Needs testing, Not yet reviewed

#4022 Update foreman_remote_execution to 1.8.4
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/debian/install
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB, Needs testing, Not yet reviewed

#4014 Add missing dependencies to readme
  README.md
Labels: Needs testing, RPM

#4027 use the bindir defined in gemspec, not "bin"
  gem2rpm/foreman_plugin.spec.erb
  gem2rpm/hammer_plugin.spec.erb
  gem2rpm/nonscl.spec.erb
  gem2rpm/scl.spec.erb
  gem2rpm/smart_proxy_plugin.spec.erb
Labels: Needs testing, RPM

#4026 Fixes #27670 - Bump rubygem-rbvmomi to 2.2.0-1
  packages/foreman/rubygem-rbvmomi/rbvmomi-2.0.1-tests.tgz
  packages/foreman/rubygem-rbvmomi/rbvmomi-2.0.1.gem
  packages/foreman/rubygem-rbvmomi/rbvmomi-2.2.0.gem
  packages/foreman/rubygem-rbvmomi/rubygem-rbvmomi.spec
Labels: Needs testing, RPM

#4028 Fixes #27670 - Bump rubygem-rbvmomi to 2.2.0-1
  packages/foreman/rubygem-rbvmomi/rbvmomi-2.0.1-tests.tgz
  packages/foreman/rubygem-rbvmomi/rbvmomi-2.0.1.gem
  packages/foreman/rubygem-rbvmomi/rbvmomi-2.2.0.gem
  packages/foreman/rubygem-rbvmomi/rubygem-rbvmomi.spec
Labels: Needs testing, RPM

#4029 Update rubygem-hammer_cli_foreman_ansible to 0.3.2
  packages/plugins/rubygem-hammer_cli_foreman_ansible/hammer_cli_foreman_ansible-0.3.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_ansible/hammer_cli_foreman_ansible-0.3.2.gem
  packages/plugins/rubygem-hammer_cli_foreman_ansible/rubygem-hammer_cli_foreman_ansible.spec
Labels: Needs testing, RPM

#4030 Bump rubygem-dynflow to 1.3.0-1
  packages/foreman/rubygem-dynflow/dynflow-1.2.3.gem
  packages/foreman/rubygem-dynflow/dynflow-1.3.0.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing, RPM

#4031 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#4033 don't move katello migrations when they point to a symlink
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: Needs testing, RPM

#4039 Release 1.23.0-RC2
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: Needs testing, Not yet reviewed, Stable branch

#4038 Release 1.23.0-RC2
  packages/foreman/foreman-installer/foreman-installer-1.23.0-RC1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-1.23.0-RC2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-1.23.0-RC1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-1.23.0-RC2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-1.23.0-RC1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-1.23.0-RC2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-1.23.0-RC1.tar.bz2
  packages/foreman/foreman/foreman-1.23.0-RC2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#4041 Bump rubygem-audited to 4.9.0-1
  packages/foreman/rubygem-audited/audited-4.7.1.gem
  packages/foreman/rubygem-audited/audited-4.9.0.gem
  packages/foreman/rubygem-audited/rubygem-audited.spec
Labels: Needs testing, RPM

#4043 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#4044 Refs #27727 - Run bundle install for foreman-service
  debian/bionic/foreman/foreman-service.postinst
  debian/stretch/foreman/foreman-service.postinst
  debian/xenial/foreman/foreman-service.postinst
Labels: Needs testing, Not yet reviewed

#4047 Update foreman_git_templates to 1.0.2
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.1.gem
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.2.gem
  packages/plugins/rubygem-foreman_git_templates/rubygem-foreman_git_templates.spec
Labels: Needs testing, RPM

#4048 Update foreman_supervisory_authority to 0.0.2
  packages/plugins/rubygem-foreman_supervisory_authority/foreman_supervisory_authority-0.0.1.gem
  packages/plugins/rubygem-foreman_supervisory_authority/foreman_supervisory_authority-0.0.2.gem
  packages/plugins/rubygem-foreman_supervisory_authority/rubygem-foreman_supervisory_authority.spec
Labels: Needs testing, Not yet reviewed, RPM

#4050 Release 1.22.1
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: Needs testing, Not yet reviewed, Stable branch

#4049 Release 1.22.1
  packages/foreman/foreman-installer/foreman-installer-1.22.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-1.22.1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-1.22.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-1.22.1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-1.22.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-1.22.1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-1.22.0.tar.bz2
  packages/foreman/foreman/foreman-1.22.1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#4054 Bump rubygem-smart_proxy_dhcp_infoblox to 0.0.15-1
  packages/plugins/rubygem-smart_proxy_dhcp_infoblox/rubygem-smart_proxy_dhcp_infoblox.spec
  packages/plugins/rubygem-smart_proxy_dhcp_infoblox/smart_proxy_dhcp_infoblox-0.0.14.gem
  packages/plugins/rubygem-smart_proxy_dhcp_infoblox/smart_proxy_dhcp_infoblox-0.0.15.gem
Labels: Needs testing, Not yet reviewed, RPM

#4056 rubygem-runcible update to 2.12.0
  packages/katello/rubygem-runcible/rubygem-runcible.spec
  packages/katello/rubygem-runcible/runcible-2.11.1.gem
  packages/katello/rubygem-runcible/runcible-2.12.0.gem
Labels: Needs testing, RPM
