Repository theforeman/foreman-packaging, pull requests merged in 2019-04, with the labels that each got.

#3559 Remove bastion requirement from katello
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-katello/rubygem-katello.spec
  packages/plugins/rubygem-bastion/bastion-6.1.22.gem
  packages/plugins/rubygem-bastion/rubygem-bastion.spec
  rel-eng/tito.props
Labels: After core merge, Needs testing, RPM

#3575 katello-host-tools 3.5.0
  packages/client/katello-host-tools/katello-host-tools-3.4.3.tar.gz
  packages/client/katello-host-tools/katello-host-tools-3.5.0.tar.gz
  packages/client/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#3591 Release katello-client-bootstrap 1.7.2
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.1.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.2.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap.spec
Labels: Needs testing, RPM

#3550 Update rubygem-foreman_openscap to 0.11.5
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.11.4.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.11.5.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, Not yet reviewed, RPM

#3593 Add zest dependency to katello
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#3315 Add foreman-service subpackage
  comps/comps-foreman-rhel7.xml
  packages/foreman/foreman/foreman.service
  packages/foreman/foreman/foreman.spec
  packages/foreman/foreman/foreman.sysconfig
Labels: Needs testing, RPM

#3596 Properly obsolete tfm-rubygem-bastion
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#3595 Refs #26097 - Ignore cross-env in NPM requirements
  update-requirements
Labels: Needs testing, RPM

#3554 Update foreman_asible to 2.2.14
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.13.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.14.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#3597 Update katello-selinux to 3.1.0
  packages/foreman/katello-selinux/3.0.3
  packages/foreman/katello-selinux/3.1.0
  packages/foreman/katello-selinux/katello-selinux.spec
Labels: Needs testing, Not yet reviewed

#3598 Rebuild foreman_remote_execution
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#3599 Rebuild foreman_ansible
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#3601 Update katello-selinux to 3.1.1
  packages/foreman/katello-selinux/3.1.0
  packages/foreman/katello-selinux/3.1.1
  packages/foreman/katello-selinux/katello-selinux.spec
Labels: Needs testing, RPM

#3600 Improve package addition steps
  README.md
  add_gem_package.sh
Labels: Needs testing, RPM

#3603 Drop tests package from debian builds
  debian/bionic/foreman/control
  debian/bionic/foreman/foreman-test.install
  debian/bionic/foreman/foreman-test.postinst
  debian/stretch/foreman/control
  debian/stretch/foreman/foreman-test.install
  debian/stretch/foreman/foreman-test.postinst
  debian/xenial/foreman/control
  debian/xenial/foreman/foreman-test.install
  debian/xenial/foreman/foreman-test.postinst
Labels: Needs testing, Not yet reviewed

#3607 Remove foreman-compute dependencies from plugins
  plugins/ruby-foreman-datacenter/debian/control
  plugins/ruby-foreman-digitalocean/debian/control
  plugins/ruby-foreman-docker/debian/control
Labels: DEB, Needs testing, Not yet reviewed

#3608 Use pulp 2.19 stable
  packages/katello/katello-repos/katello-repos.spec
Labels: Needs testing, RPM

#3610 Update puppetdb_foreman to 5.0.0
  plugins/ruby-puppetdb-foreman/debian/changelog
  plugins/ruby-puppetdb-foreman/debian/gem.list
  plugins/ruby-puppetdb-foreman/puppetdb_foreman.rb
Labels: DEB, Needs testing, Not yet reviewed

#3614 add foreman_git_templates plugin [1.21]
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.0.gem
  packages/plugins/rubygem-foreman_git_templates/rubygem-foreman_git_templates.spec
  rel-eng/tito.props
Labels: Needs testing, Not yet reviewed

#3613 add foreman_git_templates plugin [1.20]
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.0.gem
  packages/plugins/rubygem-foreman_git_templates/rubygem-foreman_git_templates.spec
  rel-eng/tito.props
Labels: Needs testing, Not yet reviewed

#3615 Update rubygem-foreman_scap_client to 0.4.5
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.4.3.gem
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.4.5.gem
  packages/client/rubygem-foreman_scap_client/rubygem-foreman_scap_client.spec
Labels: Needs testing, RPM

#3605 Update rubygem-hammer_cli_foreman_ansible to 0.3.0
  packages/plugins/rubygem-hammer_cli_foreman_ansible/hammer_cli_foreman_ansible-0.2.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_ansible/hammer_cli_foreman_ansible-0.3.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_ansible/rubygem-hammer_cli_foreman_ansible.spec
Labels: Needs testing, RPM

#3609 Update puppetdb_foreman to 5.0.0
  packages/plugins/rubygem-puppetdb_foreman/puppetdb_foreman-4.0.0.gem
  packages/plugins/rubygem-puppetdb_foreman/puppetdb_foreman-5.0.0.gem
  packages/plugins/rubygem-puppetdb_foreman/rubygem-puppetdb_foreman.spec
Labels: Needs testing, RPM

#3582 foreman_wreckingball: precompile assets
  packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
Labels: Needs testing, Not yet reviewed, RPM

#3581 foreman_wreckingball: precompile assets
  packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
Labels: Needs testing, Not yet reviewed, RPM

#3546 Update ansiblerole-foreman_scap_client to 0.0.2
  packages/plugins/ansiblerole-foreman_scap_client/ansiblerole-foreman_scap_client.spec
  packages/plugins/ansiblerole-foreman_scap_client/foreman_scap_client-0.0.1.tar.gz
  packages/plugins/ansiblerole-foreman_scap_client/foreman_scap_client-0.0.2.tar.gz
Labels: Needs testing, Not yet reviewed, RPM

#3621 Update rubygem-foreman_snapshot_management to 1.6.0
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.5.1.gem
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.6.0.gem
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Needs testing, RPM

#3586 Update rubygem-foreman_ansible to 2.3.3
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.3.2.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.3.3.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, Not yet reviewed, RPM

#3620 Update rubygem-foreman_openscap to 0.12.3
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.12.2.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.12.3.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#3623 Remove trollop sources
  packages/foreman/rubygem-trollop/rubygem-trollop.spec
  packages/foreman/rubygem-trollop/trollop-2.1.2.gem
Labels: Needs testing, RPM

#3622 Obsolete tfm-rubygem-extlib in tfm
  packages/foreman/tfm/tfm.spec
Labels: Needs testing, RPM

#3624 use the nightly macro in the ForemanSourceStrategy
  rel-eng/custom/custom.py
Labels: Needs testing, RPM

#3626 Remove dead packages from the manifest
  package_manifest.yaml
Labels: Needs testing, RPM

#3583 Add rubygem-vault package
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-vault/rubygem-vault.spec
  packages/plugins/rubygem-vault/vault-0.12.0.gem
  rel-eng/tito.props
Labels: Needs testing, Not yet reviewed, RPM

#3632 Fix sed command for nightly macro
  rel-eng/custom/custom.py
Labels: Needs testing, RPM

#3631 Remove sinatra from the ruby SCL prefix
  scl_prefixes.json
Labels: Needs testing, RPM

#3634 Fix releasers for client Fedora 29
  rel-eng/releasers.conf
  rel-eng/tito.props
Labels: Needs re-review, Needs testing, RPM

#3629 Update foreman-tasks to 0.15.1
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/debian/install
  plugins/ruby-foreman-tasks/debian/postinst
  plugins/ruby-foreman-tasks/debian/rules
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB, Needs testing, Not yet reviewed

#3627 Remove foreman_docker as a katello dependency
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#3630 Replace foreman-ruby with tfm-ruby
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#3642 Update rubygem-redhat_access to 2.2.4
  packages/katello/rubygem-redhat_access/redhat_access-2.2.3.gem
  packages/katello/rubygem-redhat_access/redhat_access-2.2.4.gem
  packages/katello/rubygem-redhat_access/rubygem-redhat_access.spec
Labels: Needs testing, Not yet reviewed, RPM

#3644 Update foreman_git_templates to 1.0.1
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.0.gem
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.1.gem
  packages/plugins/rubygem-foreman_git_templates/rubygem-foreman_git_templates.spec
Labels: Needs testing, RPM

#3645 Update foreman_wreckingball to 3.4.0
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-3.3.0.gem
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-3.4.0.gem
  packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
Labels: Needs testing

#3533 1651799 - moved logrotate script out of SCL
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#3635 Get foreman source from foreman-nightly-source-release
  package_manifest.yaml
Labels: Needs testing, RPM

#3654 Update foreman_fog_proxmox to 0.7.0
  plugins/ruby-foreman-fog-proxmox/debian/changelog
  plugins/ruby-foreman-fog-proxmox/debian/control
  plugins/ruby-foreman-fog-proxmox/debian/copyright
  plugins/ruby-foreman-fog-proxmox/debian/gem.list
  plugins/ruby-foreman-fog-proxmox/foreman_fog_proxmox.rb
Labels: Needs testing, Not yet reviewed

#3638 Update foreman-fog-proxmox to 0.6.0
  plugins/ruby-foreman-fog-proxmox/debian/changelog
  plugins/ruby-foreman-fog-proxmox/debian/control
  plugins/ruby-foreman-fog-proxmox/debian/copyright
  plugins/ruby-foreman-fog-proxmox/debian/gem.list
  plugins/ruby-foreman-fog-proxmox/foreman_fog_proxmox.rb
Labels: DEB, Needs testing, Not yet reviewed

#3655 Add package.json skeleton to foreman_plugin template
  gem2rpm/foreman_plugin.spec.erb
Labels: Needs testing, RPM

#3656 Blacklist surge from NPM dependencies
  update-requirements
Labels: Needs testing, RPM

#3657 Install bootstrap.py without executable bit
  packages/katello/katello-client-bootstrap/katello-client-bootstrap.spec
Labels: Needs testing, RPM

#3664 add 1.22 to template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Needs testing

#3658 Fixes #26661 - don't ship fact-plugin on modern Fedora and EL
  packages/client/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#3662 Release 1.21.3
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: Needs testing, Not yet reviewed

#3663 Release 1.21.3
  packages/foreman/foreman-installer/foreman-installer-1.21.2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-1.21.3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-1.21.2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-1.21.3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-1.21.2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-1.21.3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-1.21.2.tar.bz2
  packages/foreman/foreman/foreman-1.21.3.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing

#3661 Bump changelog to 1.23.0 to match VERSION
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: Needs testing, Waiting on contributor

#3666 update Foreman/Katello nightly versions
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  rel-eng/releasers.conf
  rel-eng/tito.props
Labels: Needs testing, Not yet reviewed, RPM

#3672 Update rubygem-katello to 3.11.1
  packages/katello/rubygem-katello/katello-3.11.0.gem
  packages/katello/rubygem-katello/katello-3.11.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#3671 Update smart_proxy_remote_execution_ssh to 0.2.1 (deb)
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/control
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: Needs testing, Not yet reviewed

#3673 Update rubygem-katello-3.10 to 3.10.1
  packages/katello-3.10/rubygem-katello-3.10/katello-3.10.0.gem
  packages/katello-3.10/rubygem-katello-3.10/katello-3.10.1.gem
  packages/katello-3.10/rubygem-katello-3.10/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#3675 Bump katello to 3.13
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#3646 sync foreman-bootloaders-redhat from downstream
  packages/foreman/foreman-bootloaders-redhat/foreman-bootloaders-redhat.spec
  packages/foreman/foreman-bootloaders-redhat/foreman-generate-bootloaders
Labels: Needs testing, RPM

#3643 Deb/develop foreman service
  debian/bionic/foreman/control
  debian/bionic/foreman/foreman-service.install
  debian/bionic/foreman/rules
  debian/stretch/foreman/control
  debian/stretch/foreman/foreman-service.install
  debian/stretch/foreman/rules
  debian/xenial/foreman/control
  debian/xenial/foreman/foreman-service.install
  debian/xenial/foreman/rules
Labels: DEB, Needs testing, Not yet reviewed

#3679 Update nightly Foreman release packages
  package_manifest.yaml
Labels: Needs testing, RPM

#3680 Release 1.22.0-RC1
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: Needs testing, Not yet reviewed

#3681 Release 1.22.0-RC1
  package_manifest.yaml
  packages/foreman/foreman-installer/foreman-installer-1.22.0-RC1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-1.22.0-RC1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-1.22.0-RC1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-1.22.0-RC1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed

#3682 Regenerate rubygem-smart_proxy_discovery spec
  packages/plugins/rubygem-smart_proxy_discovery/rubygem-smart_proxy_discovery.spec
  packages/plugins/rubygem-smart_proxy_discovery/smart_proxy_discovery-1.0.4.gem
  packages/plugins/rubygem-smart_proxy_discovery/smart_proxy_discovery-1.0.5.gem
Labels: Needs testing, RPM

#3684 also ignore .rubocop-disables.yml for gem2rpm
  gem2rpm/foreman_plugin.spec.erb
Labels: Needs testing, RPM

#3677 Sort comps files
  comps/comps-foreman-plugins-rhel7.xml
  comps/comps-foreman-rhel7.xml
Labels: Needs testing, RPM

#3670 Update rubygem-smart_proxy_remote_execution_ssh to 0.2.1 (rpm)
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.2.0.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.2.1.gem
Labels: Needs testing, RPM

#3685 Bump rubygem-little-plugger to 1.1.4-1
  packages/foreman/rubygem-little-plugger/little-plugger-1.1.3.gem
  packages/foreman/rubygem-little-plugger/little-plugger-1.1.4.gem
  packages/foreman/rubygem-little-plugger/rubygem-little-plugger.spec
Labels: Needs testing, RPM

#3686 [CP] Fixes #26661 - don't ship fact-plugin on modern Fedora and EL
  packages/client/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#3669 Foreman kubevirt dependencies
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-fog-kubevirt/fog-kubevirt-1.2.5.gem
  packages/plugins/rubygem-fog-kubevirt/rubygem-fog-kubevirt.spec
  packages/plugins/rubygem-http-form_data/http-form_data-2.1.1.gem
  packages/plugins/rubygem-http-form_data/rubygem-http-form_data.spec
  packages/plugins/rubygem-http/http-3.3.0.gem
  packages/plugins/rubygem-http/rubygem-http.spec
  packages/plugins/rubygem-http_parser.rb/http_parser.rb-0.6.0.gem
  packages/plugins/rubygem-http_parser.rb/rubygem-http_parser.rb.spec
  packages/plugins/rubygem-kubeclient/kubeclient-4.3.0.gem
  packages/plugins/rubygem-kubeclient/rubygem-kubeclient.spec
  packages/plugins/rubygem-recursive-open-struct/recursive-open-struct-1.1.0.gem
  packages/plugins/rubygem-recursive-open-struct/rubygem-recursive-open-struct.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3692 rebuild rex for webpack
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, Not yet reviewed, RPM

#3693 Rebuild Ansible for webpack
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, Not yet reviewed, RPM

#3678 foreman salt 10.2.0 release
  packages/plugins/rubygem-foreman_salt/foreman_salt-10.1.0.gem
  packages/plugins/rubygem-foreman_salt/foreman_salt-10.2.0.gem
  packages/plugins/rubygem-foreman_salt/rubygem-foreman_salt.spec
Labels: Needs testing, RPM

#3687 Add nodejs-gridster package
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/nodejs-gridster/nodejs-gridster.spec
  rel-eng/tito.props
Labels: RPM

#3694 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#3688 Use LC_TIME for generating changelogs
  add_changelog.sh
Labels: Needs testing, RPM

#3695 Release Katello RC1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.12.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM
