Repository theforeman/foreman-packaging, pull requests merged in 2019-03, with the labels that each got.

#3478 Update rubygem-redhat_access to 2.2.2
  packages/katello/rubygem-redhat_access/redhat_access-2.2.0.gem
  packages/katello/rubygem-redhat_access/redhat_access-2.2.2.gem
  packages/katello/rubygem-redhat_access/rubygem-redhat_access.spec
Labels: Needs testing, RPM

#3480 Update rubygem-foreman_maintain to 0.4.1
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.3.1.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.4.1.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#3482 Update katello-certs-tools to 2.5.2
  packages/foreman/katello-certs-tools/katello-certs-tools-2.5.1.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools-2.5.2.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools.spec
Labels: Needs testing, RPM

#3475 Also build rubygem-net-ssh for non-SCL
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-net-ssh/rubygem-net-ssh.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3486 Update rubygem-bastion to 6.1.20
  packages/plugins/rubygem-bastion/bastion-6.1.16.gem
  packages/plugins/rubygem-bastion/bastion-6.1.20.gem
  packages/plugins/rubygem-bastion/rubygem-bastion.spec
Labels: Needs testing, RPM

#3488 Update katello-certs-tools to 2.5.3
  packages/foreman/katello-certs-tools/katello-certs-tools-2.5.2.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools-2.5.3.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools.spec
Labels: RPM

#3483 add rubygem-down package
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-down/down-4.5.0.gem
  packages/plugins/rubygem-down/rubygem-down.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3493 Update foreman_ansible to 2.3.2
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing, Not yet reviewed

#3494 Update foreman_ansible to 2.2.12
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing, Not yet reviewed

#3496 Update smart_proxy_ansible to 2.1.2
  plugins/smart_proxy_ansible/ansible.rb
  plugins/smart_proxy_ansible/changelog
Labels: Needs testing, Not yet reviewed

#3492 Update rubygem-foreman_ansible to 2.2.12
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.11.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.12.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#3491 Update rubygem-foreman_ansible to 2.3.2
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.3.1.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.3.2.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#3481 Update foreman_wreckingball to 3.3.0
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-3.2.0.gem
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-3.3.0.gem
  packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
Labels: Needs testing, RPM

#3497 Update rubygem-foreman_scap_client to 0.4.3
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.4.2.gem
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.4.3.gem
  packages/client/rubygem-foreman_scap_client/rubygem-foreman_scap_client.spec
Labels: Needs testing, RPM

#3505 Update foreman_wreckingball to 3.3.0
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-3.2.0.gem
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-3.3.0.gem
  packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
Labels: Needs testing, Not yet reviewed, RPM

#3504 Update rubygem-foreman_ansible to 2.3.2
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.3.1.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.3.2.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, Not yet reviewed, RPM

#3506 Update foreman_wreckingball to 3.3.0
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-3.0.1.gem
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-3.3.0.gem
  packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
Labels: Needs testing, Not yet reviewed, RPM

#3490 Update rubygem-foreman_scc_manager to 1.6.1
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.6.0.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.6.1.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM

#3507 Update rubygem-foreman_scap_client to 0.4.3
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.4.2.gem
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.4.3.gem
  packages/client/rubygem-foreman_scap_client/rubygem-foreman_scap_client.spec
Labels: Needs testing, Not yet reviewed, RPM

#3508 Update rubygem-foreman_scc_manager to 1.6.1
  packages/katello-3.10/rubygem-foreman_scc_manager/foreman_scc_manager-1.5.1.gem
  packages/katello-3.10/rubygem-foreman_scc_manager/foreman_scc_manager-1.6.1.gem
  packages/katello-3.10/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, Not yet reviewed, RPM

#3509 Update rubygem-foreman_scc_manager to 1.6.1
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.6.0.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.6.1.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, Not yet reviewed, RPM

#3495 Update rubygem-smart_proxy_ansible to 2.1.2
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-2.1.1.gem
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-2.1.2.gem
Labels: Needs testing, RPM

#3510 Update rubygem-foreman_scc_manager to 1.6.1
  packages/katello-3.9/rubygem-foreman_scc_manager/foreman_scc_manager-1.5.1.gem
  packages/katello-3.9/rubygem-foreman_scc_manager/foreman_scc_manager-1.6.1.gem
  packages/katello-3.9/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, Not yet reviewed, RPM

#3511 Update rubygem-smart_proxy_ansible to 2.1.2
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-2.1.1.gem
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-2.1.2.gem
Labels: Needs testing, Not yet reviewed, RPM

#3489 Update rubygem-foreman_dlm to 1.1.0
  packages/plugins/rubygem-foreman_dlm/foreman_dlm-1.0.0.gem
  packages/plugins/rubygem-foreman_dlm/foreman_dlm-1.1.0.gem
  packages/plugins/rubygem-foreman_dlm/rubygem-foreman_dlm.spec
Labels: Needs testing, RPM

#3512 Update rubygem-foreman_dlm to 1.1.0
  packages/plugins/rubygem-foreman_dlm/foreman_dlm-1.0.0.gem
  packages/plugins/rubygem-foreman_dlm/foreman_dlm-1.1.0.gem
  packages/plugins/rubygem-foreman_dlm/rubygem-foreman_dlm.spec
Labels: Needs testing, Not yet reviewed, RPM

#3513 Update rubygem-foreman_dlm to 1.1.0
  packages/plugins/rubygem-foreman_dlm/foreman_dlm-1.0.0.gem
  packages/plugins/rubygem-foreman_dlm/foreman_dlm-1.1.0.gem
  packages/plugins/rubygem-foreman_dlm/rubygem-foreman_dlm.spec
Labels: Needs testing, Not yet reviewed, RPM

#3499 Update rubygem-smart_proxy_pulp to 1.4.1
  packages/plugins/rubygem-smart_proxy_pulp/rubygem-smart_proxy_pulp.spec
  packages/plugins/rubygem-smart_proxy_pulp/smart_proxy_pulp-1.3.0.gem
  packages/plugins/rubygem-smart_proxy_pulp/smart_proxy_pulp-1.4.1.gem
Labels: Needs testing, RPM

#3514 Release katello-client-boostrap 1.7.1
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.0.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.1.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap.spec
Labels: Needs testing, RPM

#3518 Update rubygem-rsec to 0.4.3
  packages/foreman/rubygem-rsec/rsec-0.4.2.gem
  packages/foreman/rubygem-rsec/rsec-0.4.3.gem
  packages/foreman/rubygem-rsec/rubygem-rsec.spec
Labels: Needs testing, RPM

#3517 Update Kafo to 3.0.0
  dependencies/bionic/kafo/changelog
  dependencies/bionic/kafo/patches/fix_require_in_puppet_module.diff
  dependencies/bionic/kafo/patches/series
  dependencies/stretch/kafo/changelog
  dependencies/stretch/kafo/patches/fix_require_in_puppet_module.diff
  dependencies/stretch/kafo/patches/series
  dependencies/xenial/kafo/changelog
  dependencies/xenial/kafo/patches/fix_require_in_puppet_module.diff
  dependencies/xenial/kafo/patches/series
Labels: DEB, Needs testing

#3516 Bump rubygem-kafo to 3.0.0-1
  packages/foreman/rubygem-kafo/kafo-2.1.0.gem
  packages/foreman/rubygem-kafo/kafo-3.0.0.gem
  packages/foreman/rubygem-kafo/rubygem-kafo.spec
Labels: Needs testing, RPM

#3519 Update foreman-installer dependencies
  debian/bionic/foreman-installer/control
  debian/stretch/foreman-installer/control
  debian/xenial/foreman-installer/control
Labels: DEB, Needs testing, Not yet reviewed

#3522 Release Katello 3.11.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello-repos/katello.repo
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.11.0.gem
  packages/katello/rubygem-katello/katello-3.11.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#3524 Do not require the tito tag on an update
  add_gem_package.sh
Labels: Needs testing, RPM

#3526 Update rubygem-bastion to 6.1.22
  packages/plugins/rubygem-bastion/bastion-6.1.20.gem
  packages/plugins/rubygem-bastion/bastion-6.1.22.gem
  packages/plugins/rubygem-bastion/rubygem-bastion.spec
Labels: Needs testing, RPM

#3531 Update katello package dependencies
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#3530 Update foreman-tasks-core to 0.2.6
  dependencies/bionic/foreman-tasks-core/changelog
  dependencies/stretch/foreman-tasks-core/changelog
  dependencies/xenial/foreman-tasks-core/changelog
Labels: DEB, Needs testing, Not yet reviewed

#3529 Update foreman-tasks-core to 0.2.6 (deb)
  plugins/ruby-foreman-tasks/debian/gem.list
Labels: DEB, Needs testing, Not yet reviewed

#3527 Update rubygem-foreman_ansible to 2.2.13
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.12.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-2.2.13.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#3528 Update rubygem-foreman-tasks-core to 0.2.6
  packages/plugins/rubygem-foreman-tasks-core/foreman-tasks-core-0.2.5.gem
  packages/plugins/rubygem-foreman-tasks-core/foreman-tasks-core-0.2.6.gem
  packages/plugins/rubygem-foreman-tasks-core/rubygem-foreman-tasks-core.spec
Labels: Needs testing, RPM

#3502 Add rubygem-ethon
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-ethon/ethon-0.12.0.gem
  packages/katello/rubygem-ethon/rubygem-ethon.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3498 Update foreman_expire_hosts to 6.0.0
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-5.1.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-6.0.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Needs testing, RPM

#3342 Add a script to add hosts to package_manifest.yaml
  add_host.py
  add_npm_package.sh
Labels: Needs testing, RPM

#3484 add foreman_git_templates plugin
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.0.gem
  packages/plugins/rubygem-foreman_git_templates/rubygem-foreman_git_templates.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3537 Refs #26404 - Update will_paginate to 3.1.7
  packages/foreman/rubygem-will_paginate/rubygem-will_paginate.spec
  packages/foreman/rubygem-will_paginate/will_paginate-3.1.5.gem
  packages/foreman/rubygem-will_paginate/will_paginate-3.1.7.gem
Labels: Needs testing, RPM

#3534 Fixes #26401 - Remove GPG key from f-release-client
  packages/foreman/foreman-release/foreman-client.repo
  packages/foreman/foreman-release/foreman-release.spec
Labels: Needs testing, RPM

#3536 Add rubygem-aws-eventstream package
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-aws-eventstream/aws-eventstream-1.0.2.gem
  packages/plugins/rubygem-aws-eventstream/rubygem-aws-eventstream.spec
  rel-eng/tito.props
Labels: Needs testing, Not yet reviewed, RPM

#3538 Update rubygem-hammer_cli_foreman_openscap to 0.1.7
  packages/plugins/rubygem-hammer_cli_foreman_openscap/hammer_cli_foreman_openscap-0.1.6.gem
  packages/plugins/rubygem-hammer_cli_foreman_openscap/hammer_cli_foreman_openscap-0.1.7.gem
  packages/plugins/rubygem-hammer_cli_foreman_openscap/rubygem-hammer_cli_foreman_openscap.spec
Labels: Needs testing, RPM

#3535 Add rubygem-aws-sigv4 package
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-aws-sigv4/aws-sigv4-1.1.0.gem
  packages/plugins/rubygem-aws-sigv4/rubygem-aws-sigv4.spec
  rel-eng/tito.props
Labels: Needs re-review, Needs testing, RPM

#3539 Update rubygem-foreman_openscap to 0.12.1
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.11.4.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.12.1.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#3542 rubygem-runcible 2.11.1
  packages/katello/rubygem-runcible/rubygem-runcible.spec
  packages/katello/rubygem-runcible/runcible-2.11.0.gem
  packages/katello/rubygem-runcible/runcible-2.11.1.gem
Labels: Needs testing, RPM

#3523 Bump rubygem-ruby2ruby to 2.4.2-1
  packages/foreman/rubygem-ruby2ruby/ruby2ruby-2.4.0.gem
  packages/foreman/rubygem-ruby2ruby/ruby2ruby-2.4.2.gem
  packages/foreman/rubygem-ruby2ruby/rubygem-ruby2ruby.spec
Labels: Needs testing, Not yet reviewed, RPM

#3553 Update rubygem-hammer_cli_foreman_ansible to 0.2.0
  packages/plugins/rubygem-hammer_cli_foreman_ansible/hammer_cli_foreman_ansible-0.1.2.gem
  packages/plugins/rubygem-hammer_cli_foreman_ansible/hammer_cli_foreman_ansible-0.2.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_ansible/rubygem-hammer_cli_foreman_ansible.spec
Labels: Needs testing, RPM

#3552 Update rubygem-redhat_access to 2.2.3
  packages/katello/rubygem-redhat_access/redhat_access-2.2.2.gem
  packages/katello/rubygem-redhat_access/redhat_access-2.2.3.gem
  packages/katello/rubygem-redhat_access/rubygem-redhat_access.spec
Labels: Needs testing, RPM

#3549 Update rubygem-foreman_openscap to 0.12.2
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.12.1.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.12.2.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#3544 Update foreman-docker to 5.0.0
  plugins/ruby-foreman-docker/debian/changelog
  plugins/ruby-foreman-docker/debian/control
  plugins/ruby-foreman-docker/debian/gem.list
  plugins/ruby-foreman-docker/foreman_docker.rb
Labels: Needs testing, Not yet reviewed

#3520 Refs #26020 - Add nodejs-file-saver package
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/nodejs-file-saver/file-saver-2.0.1.tgz
  packages/foreman/nodejs-file-saver/nodejs-file-saver.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3555 Update foreman dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#3556 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#3557 Remove foreman-compute
  debian/bionic/foreman/control
  debian/bionic/foreman/foreman-compute.install
  debian/bionic/foreman/foreman-compute.postinst
  debian/stretch/foreman/control
  debian/stretch/foreman/foreman-compute.install
  debian/stretch/foreman/foreman-compute.postinst
  debian/xenial/foreman/control
  debian/xenial/foreman/foreman-compute.install
  debian/xenial/foreman/foreman-compute.postinst
Labels: Needs testing, Not yet reviewed

#3560 use foreman-develop-release instead of test_develop for building foreman
  package_manifest.yaml
Labels: Needs testing, RPM

#3558 Drop foreman-compute requirement
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#3563 Update vsphere dependencies
  packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec
Labels: Needs testing, RPM

#3562 Bump rubygem-fog-digitalocean to 0.4.0-1
  packages/foreman/rubygem-fog-digitalocean/fog-digitalocean-0.3.0.gem
  packages/foreman/rubygem-fog-digitalocean/fog-digitalocean-0.4.0.gem
  packages/foreman/rubygem-fog-digitalocean/rubygem-fog-digitalocean.spec
Labels: Needs testing, RPM

#3561 drop rubygem-fog, we don't need it anymore
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-fog/fog-1.42.1.gem
  packages/foreman/rubygem-fog/fog-no-aliyun.patch
  packages/foreman/rubygem-fog/fog-no-atmos.patch
  packages/foreman/rubygem-fog/fog-no-brightbox.patch
  packages/foreman/rubygem-fog/fog-no-dnsimple.patch
  packages/foreman/rubygem-fog/fog-no-dynect.patch
  packages/foreman/rubygem-fog/fog-no-ecloud.patch
  packages/foreman/rubygem-fog/fog-no-internet_archive.patch
  packages/foreman/rubygem-fog/fog-no-joyent.patch
  packages/foreman/rubygem-fog/fog-no-local.patch
  packages/foreman/rubygem-fog/fog-no-powerdns.patch
  packages/foreman/rubygem-fog/fog-no-profitbricks.patch
  packages/foreman/rubygem-fog/fog-no-riakcs.patch
  packages/foreman/rubygem-fog/fog-no-sakuracloud.patch
  packages/foreman/rubygem-fog/fog-no-serverlove.patch
  packages/foreman/rubygem-fog/fog-no-softlayer.patch
  packages/foreman/rubygem-fog/fog-no-storm_on_demand.patch
  packages/foreman/rubygem-fog/fog-no-terremark.patch
  packages/foreman/rubygem-fog/fog-no-vmfusion.patch
  packages/foreman/rubygem-fog/fog-no-voxel.patch
  packages/foreman/rubygem-fog/rubygem-fog.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3564 update fog-openstack spec
  packages/foreman/rubygem-fog-openstack/rubygem-fog-openstack.spec
Labels: Needs testing, RPM

#3548 add rhel8-kickstart-setup
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rhel8-kickstart-setup/rhel8-kickstart-setup-0.0.2.tar.gz
  packages/katello/rhel8-kickstart-setup/rhel8-kickstart-setup.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3566 drop foreman-compute require from foreman-docker
  packages/plugins/rubygem-foreman_docker/rubygem-foreman_docker.spec
Labels: Needs testing, RPM

#3567 drop package compute;
  comps/comps-foreman-rhel7.xml
  gem2rpm/foreman_plugin.spec.erb
Labels: Needs testing, RPM

#3568 ignore more files and add CoC to doc
  gem2rpm/foreman_plugin.spec.erb
Labels: Needs testing, RPM

#3570 Update rubygem-faraday_middleware to 0.13.1
  packages/plugins/rubygem-faraday_middleware/faraday_middleware-0.10.0.gem
  packages/plugins/rubygem-faraday_middleware/faraday_middleware-0.13.1.gem
  packages/plugins/rubygem-faraday_middleware/rubygem-faraday_middleware.spec
Labels: Needs testing, RPM

#3573 Remove foreman_one
  plugins/ruby-foreman-one/debian/changelog
  plugins/ruby-foreman-one/debian/compat
  plugins/ruby-foreman-one/debian/control
  plugins/ruby-foreman-one/debian/copyright
  plugins/ruby-foreman-one/debian/gem.list
  plugins/ruby-foreman-one/debian/install
  plugins/ruby-foreman-one/debian/postinst
  plugins/ruby-foreman-one/debian/rules
  plugins/ruby-foreman-one/debian/source/format
  plugins/ruby-foreman-one/foreman_one.rb
Labels: Needs testing, Not yet reviewed

#3572 Remove foreman_one
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/foreman/tfm/tfm.spec
  packages/plugins/rubygem-foreman_one/foreman_one-0.4.gem
  packages/plugins/rubygem-foreman_one/rubygem-foreman_one.spec
  packages/plugins/rubygem-opennebula/opennebula-4.8.0.gem
  packages/plugins/rubygem-opennebula/rubygem-opennebula.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3571 Disable foreman_fog_proxmox
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-fog-proxmox/fog-proxmox-0.5.5.gem
  packages/plugins/rubygem-fog-proxmox/rubygem-fog-proxmox.spec
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.5.5.gem
  packages/plugins/rubygem-foreman_fog_proxmox/rubygem-foreman_fog_proxmox.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#3576 bump rex for webpack
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, Not yet reviewed, RPM

#3577 bump ansible for webpack
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, Not yet reviewed, RPM

#3578 Oboslete fog
  packages/foreman/tfm/tfm.spec
Labels: Needs testing, RPM

#3541 foreman_wreckingball: precompile assets
  packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
Labels: Needs testing, RPM

#3532 Add rubygem-vault package
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-vault/rubygem-vault.spec
  packages/plugins/rubygem-vault/vault-0.12.0.gem
  rel-eng/tito.props
Labels: Needs testing, RPM

#3580 Obsolete foreman-compute
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#3587 Update foreman_ansible to 2.3.3
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing, Not yet reviewed

#3589 Add hammer-cli-foreman-ansible
  dependencies/bionic/hammer_cli_foreman_ansible/changelog
  dependencies/bionic/hammer_cli_foreman_ansible/compat
  dependencies/bionic/hammer_cli_foreman_ansible/control
  dependencies/bionic/hammer_cli_foreman_ansible/copyright
  dependencies/bionic/hammer_cli_foreman_ansible/install
  dependencies/bionic/hammer_cli_foreman_ansible/ruby-hammer-cli-foreman-ansible.docs
  dependencies/bionic/hammer_cli_foreman_ansible/rules
  dependencies/bionic/hammer_cli_foreman_ansible/source/format
  dependencies/stretch/hammer_cli_foreman_ansible/changelog
  dependencies/stretch/hammer_cli_foreman_ansible/compat
  dependencies/stretch/hammer_cli_foreman_ansible/control
  dependencies/stretch/hammer_cli_foreman_ansible/copyright
  dependencies/stretch/hammer_cli_foreman_ansible/install
  dependencies/stretch/hammer_cli_foreman_ansible/ruby-hammer-cli-foreman-ansible.docs
  dependencies/stretch/hammer_cli_foreman_ansible/rules
  dependencies/stretch/hammer_cli_foreman_ansible/source/format
  dependencies/xenial/hammer_cli_foreman_ansible/changelog
  dependencies/xenial/hammer_cli_foreman_ansible/compat
  dependencies/xenial/hammer_cli_foreman_ansible/control
  dependencies/xenial/hammer_cli_foreman_ansible/copyright
  dependencies/xenial/hammer_cli_foreman_ansible/install
  dependencies/xenial/hammer_cli_foreman_ansible/ruby-hammer-cli-foreman-ansible.docs
  dependencies/xenial/hammer_cli_foreman_ansible/rules
  dependencies/xenial/hammer_cli_foreman_ansible/source/format
Labels: DEB, Needs testing, Not yet reviewed

#3590 Bump nodejs-react-password-strength to 2.4.0
  packages/foreman/nodejs-react-password-strength/nodejs-react-password-strength.spec
  packages/foreman/nodejs-react-password-strength/react-password-strength-2.3.1.tgz
  packages/foreman/nodejs-react-password-strength/react-password-strength-2.4.0.tgz
Labels: Needs testing, RPM
