Repository theforeman/foreman-packaging, pull requests merged in 2019-06, with the labels that each got.

#3834 Bump rubygem-foreman_ansible_core to 3.0.0-1
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-2.2.1.gem
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-3.0.0.gem
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
Labels: Needs testing, RPM, Stable branch

#3837 Drop commented NPM requirements
  update-requirements
Labels: Needs testing, RPM

#3838 rubygem-hammer_cli_katello-0.18.0
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.18.0.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM, Stable branch

#3840 Release 1.22.0
  packages/foreman/foreman-installer/foreman-installer-1.22.0-RC2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-1.22.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-1.22.0-RC2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-1.22.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-1.22.0-RC2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-1.22.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-1.22.0-RC2.tar.bz2
  packages/foreman/foreman/foreman-1.22.0.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#3839 Update foreman-ansible to 2.3.6
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: DEB, Needs testing, Not yet reviewed, Stable branch

#3841 Release Katello 3.12
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello-repos/katello.repo
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.12.0.gem
  packages/katello/rubygem-katello/katello-3.12.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#3551 Update puppet-foreman_scap_client to 0.3.20
  packages/plugins/puppet-foreman_scap_client/puppet-foreman_scap_client.spec
  packages/plugins/puppet-foreman_scap_client/theforeman-foreman_scap_client-0.3.19.tar.gz
  packages/plugins/puppet-foreman_scap_client/theforeman-foreman_scap_client-0.3.20.tar.gz
Labels: Needs testing, RPM

#3792 BZ#1710625 - updated qpidd debug paths
  packages/katello/katello/katello-debug.sh
  packages/katello/katello/katello.spec
Labels: RPM

#3832 Update foreman_openscap to 1.0.1
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-0.12.3.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-1.0.1.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, Not yet reviewed, RPM

#3842 Add proper Katello 3.12 gpg key
  packages/katello/katello-repos/RPM-GPG-KEY-katello-2015
  packages/katello/katello-repos/katello-repos.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#3818 Require python-requests in smart_proxy_ansible
  plugins/smart_proxy_ansible/changelog
  plugins/smart_proxy_ansible/control
Labels: DEB, Needs testing

#3815 Update hammer_cli_foreman_openscap to 0.1.8
  packages/plugins/rubygem-hammer_cli_foreman_openscap/hammer_cli_foreman_openscap-0.1.7.gem
  packages/plugins/rubygem-hammer_cli_foreman_openscap/hammer_cli_foreman_openscap-0.1.8.gem
  packages/plugins/rubygem-hammer_cli_foreman_openscap/rubygem-hammer_cli_foreman_openscap.spec
Labels: Needs testing, RPM

#3844 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#3847 bump pulp_file_client gem
  packages/katello/rubygem-pulp_file_client/pulp_file_client-0.0.1b10.dev.1557779852.gem
  packages/katello/rubygem-pulp_file_client/pulp_file_client-3.0.0rc2.dev.1558441126.gem
  packages/katello/rubygem-pulp_file_client/rubygem-pulp_file_client.spec
Labels: Needs testing, RPM

#3848 Add foreman-redis
  debian/bionic/foreman/control
  debian/bionic/foreman/foreman-redis.install
  debian/bionic/foreman/foreman-redis.postinst
  debian/stretch/foreman/control
  debian/stretch/foreman/foreman-redis.install
  debian/stretch/foreman/foreman-redis.postinst
  debian/xenial/foreman/control
  debian/xenial/foreman/foreman-redis.install
  debian/xenial/foreman/foreman-redis.postinst
Labels: Needs testing, Not yet reviewed

#3843 Update rubygem-foreman_maintain to 0.4.3
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.4.2.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.4.3.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM

#3849 Update rubygem-smart_proxy_dynflow to 0.2.3
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.2.2.gem
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.2.3.gem
Labels: Needs testing, RPM

#3845 Update rubygem-fog-vsphere to 3.1.1
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.0.0.gem
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.1.1.gem
  packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec
Labels: Needs testing, RPM

#3846 Updated katello gem dependencies
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#3852 change katello's pulp_file_client pin
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#3855 Fixes #27083 - Add service file for smart_proxy_dynflow_core
  plugins/smart_proxy_dynflow_core/control
  plugins/smart_proxy_dynflow_core/dirs
  plugins/smart_proxy_dynflow_core/install
  plugins/smart_proxy_dynflow_core/links
  plugins/smart_proxy_dynflow_core/postinst
  plugins/smart_proxy_dynflow_core/rules
Labels: DEB, Needs re-review, Needs testing

#3862 Fixes #26278 - GPG sign client repositories
  packages/foreman/foreman-release/foreman-release.spec
Labels: Needs testing, RPM

#3864 look at puppet for scl lookasides
  package_manifest.yaml
Labels: Needs testing, RPM

#3859 Update rubygem-net-ldap to 0.16.1
  packages/foreman/rubygem-net-ldap/net-ldap-0.15.0.gem
  packages/foreman/rubygem-net-ldap/net-ldap-0.16.1.gem
  packages/foreman/rubygem-net-ldap/rubygem-net-ldap.spec
Labels: Needs testing, Not yet reviewed, RPM

#3865 Update rubygem-foreman_ansible to 3.0.3
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-3.0.2.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-3.0.3.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#3807 Update puppet-foreman_scap_client to 0.3.21
  packages/plugins/puppet-foreman_scap_client/puppet-foreman_scap_client.spec
  packages/plugins/puppet-foreman_scap_client/theforeman-foreman_scap_client-0.3.20.tar.gz
  packages/plugins/puppet-foreman_scap_client/theforeman-foreman_scap_client-0.3.21.tar.gz
Labels: Needs testing, RPM

#3869 Update rubygem-smart_proxy_ansible to 3.0.1
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-2.1.2.gem
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-3.0.1.gem
Labels: Needs testing, RPM

#3866 Update foreman_ansible to 3.0.3
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing, Not yet reviewed

#3868 [1.22] Update foreman_ansible to 3.0.3
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing, Not yet reviewed
