Repository theforeman/foreman-packaging, pull requests merged in 2020-07, with the labels that each got.

#5499 also use our python2-libcomps
  comps/comps-katello-pulpcore-el7.xml
Labels: Needs testing, RPM

#5500 Fixes #30040 - Update foreman-proxy dependencies
  packages/foreman/foreman-proxy/foreman-proxy.spec
Labels: RPM, Stable branch

#5503 Fixes #30040 - Update foreman-proxy dependencies
  packages/foreman/foreman-proxy/foreman-proxy.spec
Labels: Needs testing, RPM, Stable branch

#5484 Update pulp 3.4 bindings and katello for them
  packages/katello/rubygem-pulp_container_client/pulp_container_client-1.3.0.gem
  packages/katello/rubygem-pulp_container_client/pulp_container_client-1.4.1.gem
  packages/katello/rubygem-pulp_container_client/rubygem-pulp_container_client.spec
  packages/katello/rubygem-pulp_file_client/pulp_file_client-0.3.0.gem
  packages/katello/rubygem-pulp_file_client/pulp_file_client-1.0.1.gem
  packages/katello/rubygem-pulp_file_client/rubygem-pulp_file_client.spec
  packages/katello/rubygem-pulp_rpm_client/pulp_rpm_client-3.3.0.gem
  packages/katello/rubygem-pulp_rpm_client/pulp_rpm_client-3.4.1.gem
  packages/katello/rubygem-pulp_rpm_client/rubygem-pulp_rpm_client.spec
  packages/katello/rubygem-pulpcore_client/pulpcore_client-3.3.0.gem
  packages/katello/rubygem-pulpcore_client/pulpcore_client-3.4.1.gem
  packages/katello/rubygem-pulpcore_client/rubygem-pulpcore_client.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#5504 Update katello-selinux to 3.3.0
  packages/foreman/katello-selinux/3.2.0
  packages/foreman/katello-selinux/3.3.0
  packages/foreman/katello-selinux/katello-selinux.spec
Labels: Needs testing, Not yet reviewed, RPM

#5497 Bump rubygem-foreman_rh_cloud to 2.0.8-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.7.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.8.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM

#5489 Update rubygem-foreman_remote_execution to 3.2.2
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-3.2.1.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-3.2.2.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, Not yet reviewed, Stable branch

#5498 Bump rubygem-foreman_rh_cloud to 1.0.8-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-1.0.7.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-1.0.8.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM

#5509 Update foreman-release to 2.1.0
  packages/foreman/foreman-installer/foreman-installer-2.1.0-rc3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.1.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.1.0-rc3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.1.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.1.0-rc3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.1.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.1.0-rc3.tar.bz2
  packages/foreman/foreman/foreman-2.1.0.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#5508 do not change hashbang on centos < 8
  packages/plugins/rubygem-smart_proxy_salt/rubygem-smart_proxy_salt.spec
Labels: Needs testing, RPM

#5510 Release 2.1.0
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: Needs testing, Not yet reviewed, Stable branch

#5506 Drop foreman-maintain dependency
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: Needs testing, RPM

#5511 Update katello to 3.16.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.16.0.rc3.1.gem
  packages/katello/rubygem-katello/katello-3.16.0.rc4.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#5512 Add sub-man rhsm to comps for pulpcore
  comps/comps-katello-pulpcore-el7.xml
Labels: Needs testing, RPM, Stable branch

#5519 check pulpcore repoclosure when katello is checked
  package_manifest.yaml
Labels: Needs testing, RPM

#5525 Fixes #30367 - Add Infoblox dependency to sp_dns_infoblox
  packages/plugins/rubygem-smart_proxy_dns_infoblox/rubygem-smart_proxy_dns_infoblox.spec
Labels: Needs testing, RPM

#5502 Update rubygem-foreman-tasks to 1.1.3
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-1.1.2.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-1.1.3.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM, Stable branch

#5526 Fixes #30367 - Add Infoblox dependency to sp_dns_infoblox
  packages/plugins/rubygem-smart_proxy_dns_infoblox/rubygem-smart_proxy_dns_infoblox.spec
Labels: Needs testing, RPM, Stable branch

#5522 Update rubygem-foreman-tasks to 2.0.2
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-2.0.1.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-2.0.2.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#5523 Update foreman-tasks to 2.0.2
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing

#5501 Update foreman-tasks to 1.1.3
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Stable branch

#5527 Fixes #30367 - Add Infoblox dependency to sp_dns_infoblox
  packages/plugins/rubygem-smart_proxy_dns_infoblox/rubygem-smart_proxy_dns_infoblox.spec
Labels: Needs testing, RPM, Stable branch

#5531 Update rubygem-foreman_openscap to 3.0.1
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-3.0.0.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-3.0.1.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM, Stable branch

#5516 Update rubygem-foreman_maintain to 0.6.8
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.6.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.8.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#5517 Update rubygem-foreman_maintain to 0.6.8
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.6.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.8.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#5538 Update katello to 3.16.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.16.0.rc4.1.gem
  packages/katello/rubygem-katello/katello-3.16.0.rc4.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#5532 Update rubygem-foreman_openscap to 4.0.1
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-3.0.0.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.0.1.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM, Stable branch

#5539 Bump rubygem-foreman_rh_cloud to 2.0.9-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.8.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.9.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM

#5540 Bump rubygem-foreman_rh_cloud to 2.0.9-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.7.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.9.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM

#5541 Fix how we deploy hammer_cli_foreman_leapp
  packages/plugins/rubygem-hammer_cli_foreman_leapp/rubygem-hammer_cli_foreman_leapp.spec
Labels: Needs testing, RPM

#5542 Add missing dependency for rubygem-foreman_bootdisk
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
Labels: Needs testing, RPM

#5535 Updated hammer_cli_foreman to 2.1.2
  dependencies/bionic/hammer_cli_foreman/changelog
  dependencies/buster/hammer_cli_foreman/changelog
Labels: Needs testing

#5534 Update rubygem-hammer_cli_foreman to 2.1.2
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-2.1.1.gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-2.1.2.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM

#5529 Update rubygem-foreman_azure_rm to 2.1.2
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.1.1.gem
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.1.2.gem
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
Labels: Needs testing

#5530 Update rubygem-foreman_azure_rm to 2.1.2
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.1.1.gem
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.1.2.gem
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
Labels: Needs testing

#5545 Fix how we deploy hammer_cli_foreman_leapp
  packages/plugins/rubygem-hammer_cli_foreman_leapp/rubygem-hammer_cli_foreman_leapp.spec
Labels: Needs testing, RPM, Stable branch

#5543 Add missing dependency for rubygem-foreman_bootdisk
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
Labels: Needs testing

#5425 Update dynflow dependency to 1.4.6
  dependencies/bionic/dynflow/changelog
  dependencies/buster/dynflow/changelog
Labels: Needs testing

#5455 Update dynflow dependency to 1.4.6
  dependencies/bionic/dynflow/changelog
  dependencies/buster/dynflow/changelog
Labels: Needs testing

#5488 Update foreman_remote_execution to 3.2.2
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB, Needs testing, Stable branch

#5546 Add missing dependencies for ruby-foreman-bootdisk
  plugins/ruby-foreman-bootdisk/debian/changelog
  plugins/ruby-foreman-bootdisk/debian/control
Labels: Needs testing

#5547 Update katello-selinux to 3.3.1
  packages/foreman/katello-selinux/3.3.0
  packages/foreman/katello-selinux/3.3.1
  packages/foreman/katello-selinux/katello-selinux.spec
Labels: Needs testing

#5554 Update rubygem-foreman-tasks to 2.0.2
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-2.0.1.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-2.0.2.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM, Stable branch

#5553 Update foreman-tasks to 2.0.2
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB, Needs testing, Stable branch

#5551 Update katello to require REX
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#5561 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#5550 Update rubygem-foreman_remote_execution_core to 1.3.1
  packages/plugins/rubygem-foreman_remote_execution_core/foreman_remote_execution_core-1.3.0.gem
  packages/plugins/rubygem-foreman_remote_execution_core/foreman_remote_execution_core-1.3.1.gem
  packages/plugins/rubygem-foreman_remote_execution_core/rubygem-foreman_remote_execution_core.spec
Labels: Needs testing, RPM, Stable branch

#5461 Update dynflow dependency to 1.4.6
  dependencies/bionic/dynflow/changelog
  dependencies/buster/dynflow/changelog
  dependencies/focal/dynflow/changelog
Labels: Needs testing

#5559 Update rubygem-pulp_rpm_client to 3.4.2
  packages/katello/rubygem-pulp_rpm_client/pulp_rpm_client-3.4.1.gem
  packages/katello/rubygem-pulp_rpm_client/pulp_rpm_client-3.4.2.gem
  packages/katello/rubygem-pulp_rpm_client/rubygem-pulp_rpm_client.spec
Labels: Needs testing, RPM

#5557 bump pulp-container to 1.4.2
  packages/pulpcore/python-pulp-container/pulp-container-1.4.1.tar.gz
  packages/pulpcore/python-pulp-container/pulp-container-1.4.2.tar.gz
  packages/pulpcore/python-pulp-container/python-pulp-container.spec
Labels: Needs testing, RPM

#5564 Update rubygem-foreman_remote_execution to 3.3.4
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-3.3.3.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-3.3.4.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#5548 Add missing dependencies for ruby-foreman-bootdisk
  plugins/ruby-foreman-bootdisk/debian/changelog
  plugins/ruby-foreman-bootdisk/debian/control
Labels: DEB, Needs testing, Stable branch

#5566 Update rubygem-foreman_remote_execution to 3.3.4
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-3.3.3.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-3.3.4.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, Stable branch

#5570 drop posttrans macros from acd, column_view, extra_validator, templates
  packages/plugins/rubygem-foreman_acd/rubygem-foreman_acd.spec
  packages/plugins/rubygem-foreman_column_view/rubygem-foreman_column_view.spec
  packages/plugins/rubygem-foreman_host_extra_validator/rubygem-foreman_host_extra_validator.spec
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
Labels: Needs testing

#5571 drop posttrans macros from column_view, extra_validator, templates
  packages/plugins/rubygem-foreman_column_view/rubygem-foreman_column_view.spec
  packages/plugins/rubygem-foreman_host_extra_validator/rubygem-foreman_host_extra_validator.spec
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
Labels: Needs testing

#5569 Update rubygem-apipie-dsl to 2.2.8
  packages/foreman/rubygem-apipie-dsl/apipie-dsl-2.2.7.gem
  packages/foreman/rubygem-apipie-dsl/apipie-dsl-2.2.8.gem
  packages/foreman/rubygem-apipie-dsl/rubygem-apipie-dsl.spec
Labels: Needs testing, RPM

#5567 Update foreman_remote_execution_core dependency to 1.3.1
  dependencies/bionic/foreman_remote_execution_core/changelog
  dependencies/buster/foreman_remote_execution_core/changelog
Labels: Needs testing

#5573 Exclude @theforeman/find-foreman npm package
  update-requirements
Labels: Needs testing, RPM

#5391 Add foreman statistics plugin
  plugins/ruby-foreman-statistics/debian/changelog
  plugins/ruby-foreman-statistics/debian/compat
  plugins/ruby-foreman-statistics/debian/control
  plugins/ruby-foreman-statistics/debian/copyright
  plugins/ruby-foreman-statistics/debian/gem.list
  plugins/ruby-foreman-statistics/debian/install
  plugins/ruby-foreman-statistics/debian/postinst
  plugins/ruby-foreman-statistics/debian/rules
  plugins/ruby-foreman-statistics/debian/source/format
  plugins/ruby-foreman-statistics/foreman_statistics.rb
Labels: DEB, Needs testing

#5576 Update rubygem-pulp_rpm_client to 3.4.2
  packages/katello/rubygem-pulp_rpm_client/pulp_rpm_client-3.4.1.gem
  packages/katello/rubygem-pulp_rpm_client/pulp_rpm_client-3.4.2.gem
  packages/katello/rubygem-pulp_rpm_client/rubygem-pulp_rpm_client.spec
Labels: Needs testing, RPM, Stable branch

#5575 Update katello to 3.16.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.16.0.rc4.1.gem
  packages/katello/rubygem-katello/katello-3.16.0.rc5.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#5583 Update rubygem-gitlab-sidekiq-fetcher to 0.6.0
  packages/foreman/rubygem-gitlab-sidekiq-fetcher/gitlab-sidekiq-fetcher-0.5.2.gem
  packages/foreman/rubygem-gitlab-sidekiq-fetcher/gitlab-sidekiq-fetcher-0.6.0.gem
  packages/foreman/rubygem-gitlab-sidekiq-fetcher/rubygem-gitlab-sidekiq-fetcher.spec
Labels: Needs testing, RPM

#5578 Update rubygem-foreman_statistics to 0.1.3
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-0.1.1.gem
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-0.1.3.gem
  packages/plugins/rubygem-foreman_statistics/rubygem-foreman_statistics.spec
Labels: Needs testing, RPM

#5524 Fix path of smart_proxy_salt (s)/bin scripts
  packages/plugins/rubygem-smart_proxy_salt/rubygem-smart_proxy_salt.spec
Labels: Needs testing, RPM

#5585 Fix pulp-ansible pyyaml depdency
  packages/pulpcore/python-pulp-ansible/python-pulp-ansible.spec
Labels: Needs testing, RPM

#5587 Patch out Ansible and ansible-lint dependencies from galaxy importer
  packages/pulpcore/python-galaxy-importer/python-galaxy-importer.spec
Labels: Needs testing, RPM

#5586 use python3-dateutil for sub-man
  packages/pulpcore/subscription-manager/subscription-manager.spec
Labels: Needs testing, RPM

#5591 Drop some selinux requires on installer and katello-selinux
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: Needs testing, RPM

#5584 rpm/2.1 cherry pick katello-selinux 3.3.1
  packages/foreman/katello-selinux/3.3.0
  packages/foreman/katello-selinux/3.3.1
  packages/foreman/katello-selinux/katello-selinux.spec
Labels: Needs testing, RPM, Stable branch

#5589 Update rubygem-hammer_cli_foreman_openscap to 0.1.11
  packages/plugins/rubygem-hammer_cli_foreman_openscap/hammer_cli_foreman_openscap-0.1.10.gem
  packages/plugins/rubygem-hammer_cli_foreman_openscap/hammer_cli_foreman_openscap-0.1.11.gem
  packages/plugins/rubygem-hammer_cli_foreman_openscap/rubygem-hammer_cli_foreman_openscap.spec
Labels: Needs testing, RPM

#5588 Update rubygem-apipie-dsl to 2.2.9
  packages/foreman/rubygem-apipie-dsl/apipie-dsl-2.2.8.gem
  packages/foreman/rubygem-apipie-dsl/apipie-dsl-2.2.9.gem
  packages/foreman/rubygem-apipie-dsl/rubygem-apipie-dsl.spec
Labels: Needs testing, RPM

#5581 Bump rubygem-fog-vsphere to 3.4.0-1
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.3.1.gem
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.4.0.gem
  packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec
Labels: Needs testing, RPM

#5593 Update downshift to 5.4.7
  packages/katello/nodejs-downshift/compute-scroll-into-view-1.0.14.tgz
  packages/katello/nodejs-downshift/downshift-1.31.15.tgz
  packages/katello/nodejs-downshift/downshift-5.4.7.tgz
  packages/katello/nodejs-downshift/js-tokens-4.0.0.tgz
  packages/katello/nodejs-downshift/loose-envify-1.4.0.tgz
  packages/katello/nodejs-downshift/nodejs-downshift-5.4.7-registry.npmjs.org.tgz
  packages/katello/nodejs-downshift/nodejs-downshift.spec
  packages/katello/nodejs-downshift/object-assign-4.1.1.tgz
  packages/katello/nodejs-downshift/prop-types-15.7.2.tgz
  packages/katello/nodejs-downshift/react-is-16.13.1.tgz
  packages/katello/nodejs-downshift/regenerator-runtime-0.13.7.tgz
  packages/katello/nodejs-downshift/runtime-7.10.5.tgz
Labels: Needs testing, RPM

#5562 Update katello package dependencies
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#5595 also set foremandist for proxy packages
  package_manifest.yaml
Labels: Needs testing, RPM

#5596 Fixes #30490 - CVE-2020-14334 world readable cache
  packages/foreman/foreman-proxy/foreman-proxy.tmpfiles
  packages/foreman/foreman/foreman.tmpfiles
Labels: RPM

#5597 Fixes #30490 - CVE-2020-14334 world readable cache
  packages/foreman/foreman-proxy/foreman-proxy.tmpfiles
  packages/foreman/foreman/foreman.tmpfiles
Labels: Needs testing, RPM

#5598 Fixes #30490 - CVE-2020-14334 world readable cache
  packages/foreman/foreman-proxy/foreman-proxy.tmpfiles
  packages/foreman/foreman/foreman.tmpfiles
Labels: Needs testing, Not yet reviewed, RPM

#5580 Update rubygem-fog-proxmox to 0.13.0
  packages/plugins/rubygem-fog-proxmox/fog-proxmox-0.12.0.gem
  packages/plugins/rubygem-fog-proxmox/fog-proxmox-0.13.0.gem
  packages/plugins/rubygem-fog-proxmox/rubygem-fog-proxmox.spec
Labels: Needs testing, RPM

#5599 Add crane-selinux sub-package
  comps/comps-foreman-el8.xml
  comps/comps-foreman-rhel7.xml
  comps/comps-katello-el8.xml
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/foreman/katello-selinux/3.3.1
  packages/katello/katello-selinux/3.4.0
  packages/katello/katello-selinux/katello-selinux.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#5600 Update rubygem-foreman_statistics to 0.1.3 (CP 2.1)
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-0.1.1.gem
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-0.1.3.gem
  packages/plugins/rubygem-foreman_statistics/rubygem-foreman_statistics.spec
Labels: Needs testing, Stable branch

#5609 Update katello to 3.16.0 rc5.1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.16.0.rc5.1.gem
  packages/katello/rubygem-katello/katello-3.16.0.rc5.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch
