Repository theforeman/foreman-packaging, pull requests merged in 2020-09, with the labels that each got.

#5743 correct script root definition
  add_pypi_package.sh
Labels: Needs testing

#5739 use new pulpcore repos in katello-repos
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello-repos/katello.repo
Labels: Needs testing, RPM

#5736 Update rubygem-foreman_ansible to 5.1.2
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-5.1.1.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-5.1.2.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, Not yet reviewed, RPM

#5735 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#5748 Update Katello GEM dependencies
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing

#5750 Update foreman-proxy package dependencies
  packages/foreman/foreman-proxy/foreman-proxy.spec
Labels: Needs testing, RPM, Waiting on contributor

#5757 Enforce tmpfiles on foreman
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#5755 Release ansible-collection-theforeman-foreman 1.2.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.1.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.2.0.tar.gz
Labels: Needs testing, RPM

#5764 Bump foreman-maintain to 0.6.10 and add yum-utils as dependency
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.10.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.9.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#5772 Bump foreman-maintain to 0.6.10 and add yum-utils as dependency
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.10.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.9.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#5771 Bump foreman-maintain to 0.6.10 and add yum-utils as dependency
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.10.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.9.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#5756 Enforce tmpfiles on foreman-proxy
  packages/foreman/foreman-proxy/foreman-proxy.spec
Labels: Needs testing, RPM

#5762 Update rubygem-hammer_cli_foreman to 2.1.3
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-2.1.2.gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-2.1.3.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM

#5758 Update rubygem-hammer_cli to 2.1.2
  packages/foreman/rubygem-hammer_cli/hammer_cli-2.1.1.gem
  packages/foreman/rubygem-hammer_cli/hammer_cli-2.1.2.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
Labels: Needs testing, RPM

#5684 Update rubygem-foreman_remote_execution to 3.3.7
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-3.3.6.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-3.3.7.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#5770 Release ansible-collection-theforeman-foreman 1.2.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.1.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.2.0.tar.gz
Labels: Needs testing, RPM, Stable branch

#5729 Update dynflow dependency to 1.4.7
  dependencies/bionic/dynflow/changelog
  dependencies/buster/dynflow/changelog
Labels: DEB, Needs testing, Stable branch

#5661 Update foreman_monitoring to 2.0.0
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-1.0.1.gem
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-2.0.0.gem
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
Labels: Needs testing, RPM

#5767 Enforce tmpfiles on foreman (CP 2.1)
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch, Waiting on contributor

#5766 Enforce tmpfiles on foreman (CP 2.2)
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#5768 Enforce tmpfiles on foreman
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#5769 Release ansible-collection-theforeman-foreman 1.2.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.1.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.2.0.tar.gz
Labels: Needs testing, RPM, Stable branch

#5776 Enforce tmpfiles on foreman-proxy
  packages/foreman/foreman-proxy/foreman-proxy.spec
Labels: Needs testing

#5773 Update rubygem-foreman_openscap to 4.0.3
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.0.2.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.0.3.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#5738 Update foreman_remote_execution to 3.3.7
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing

#5759 Updated hammer_cli to 2.1.2
  dependencies/bionic/hammer_cli/changelog
  dependencies/buster/hammer_cli/changelog
Labels: Needs testing

#5763 Updated hammer_cli_foreman to 2.1.3
  dependencies/bionic/hammer_cli_foreman/changelog
  dependencies/buster/hammer_cli_foreman/changelog
Labels: Needs testing

#5737 Update foreman_ansible to 5.1.2
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing

#5775 Enforce tmpfiles on foreman-proxy
  packages/foreman/foreman-proxy/foreman-proxy.spec
Labels: Needs testing

#5774 Enforce tmpfiles on foreman-proxy (CP 2.2)
  packages/foreman/foreman-proxy/foreman-proxy.spec
Labels: Needs testing, RPM

#5746 Update rubygem-foreman_ansible to 6.0.0
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-5.1.1.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.0.0.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#5760 Update rubygem-hammer_cli to 2.2.1
  packages/foreman/rubygem-hammer_cli/hammer_cli-2.2.0.gem
  packages/foreman/rubygem-hammer_cli/hammer_cli-2.2.1.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
Labels: Needs testing, RPM, Stable branch

#5761 Updated hammer_cli to 2.2.1
  dependencies/bionic/hammer_cli/changelog
  dependencies/buster/hammer_cli/changelog
  dependencies/focal/hammer_cli/changelog
Labels: Needs testing, Stable branch

#5741 Update rubygem-foreman_remote_execution to 4.1.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-4.0.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-4.1.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#5742 Update foreman_remote_execution to 4.1.0
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing

#5751 Bump Hammer Katello to version 0.24.premaster
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.23.0.gem
Labels: Needs testing, RPM

#5752 CP - Add Hammer Katello 0.23.0 gem and bump package
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.23.0.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM, Stable branch

#5777 Update rubygem-pulp_rpm_client to 3.6.2
  packages/katello/rubygem-pulp_rpm_client/pulp_rpm_client-3.6.1.gem
  packages/katello/rubygem-pulp_rpm_client/pulp_rpm_client-3.6.2.gem
  packages/katello/rubygem-pulp_rpm_client/rubygem-pulp_rpm_client.spec
Labels: Needs testing, RPM

#5779 Update Katello dependencies
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#5778 Update rubygem-redhat_access to 2.2.17
  packages/katello/rubygem-redhat_access/redhat_access-2.2.11.gem
  packages/katello/rubygem-redhat_access/redhat_access-2.2.17.gem
  packages/katello/rubygem-redhat_access/rubygem-redhat_access.spec
Labels: Needs testing, RPM

#5786 Remove trends counter cron job
  debian/bionic/foreman/foreman.cron.d
  debian/buster/foreman/foreman.cron.d
Labels: Needs testing

#5753 Update rubygem-foreman_openscap to 4.0.2
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.0.0.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.0.2.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#5787 Bump foreman-maintain to 0.6.11
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.10.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.11.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#5790 Update rubygem-foreman_virt_who_configure to 0.5.3
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.2.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.3.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Needs testing, Not yet reviewed

#5788 Tidy up cron
  debian/bionic/foreman/foreman.cron.d
  debian/buster/foreman/foreman.cron.d
Labels: DEB, Needs testing

#5791 Update rubygem-foreman_virt_who_configure to 0.5.3
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.2.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.3.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Needs testing, Not yet reviewed

#5780 Update rubygem-foreman_ansible to 5.1.3
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-5.1.2.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-5.1.3.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, Not yet reviewed, RPM

#5765 Update rubygem-smart_proxy_discovery_image to 1.3.0
  packages/plugins/rubygem-smart_proxy_discovery_image/rubygem-smart_proxy_discovery_image.spec
  packages/plugins/rubygem-smart_proxy_discovery_image/smart_proxy_discovery_image-1.2.1.gem
  packages/plugins/rubygem-smart_proxy_discovery_image/smart_proxy_discovery_image-1.3.0.gem
Labels: Needs testing, Not yet reviewed, RPM

#5789 Update rubygem-foreman_leapp to 0.1.5
  packages/plugins/rubygem-foreman_leapp/foreman_leapp-0.1.4.gem
  packages/plugins/rubygem-foreman_leapp/foreman_leapp-0.1.5.gem
  packages/plugins/rubygem-foreman_leapp/rubygem-foreman_leapp.spec
Labels: Needs testing

#5683 Update rubygem-foreman_remote_execution to 3.3.6, 4.0.0, 4.1.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-4.0.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-4.1.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#5795 Update katello-certs-tools to 2.7.2
  packages/foreman/katello-certs-tools/katello-certs-tools-2.7.1.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools-2.7.2.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools.spec
Labels: Needs testing, RPM

#5796 Update katello-certs-tools to 2.7.3
  packages/foreman/katello-certs-tools/katello-certs-tools-2.7.2.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools-2.7.3.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools.spec
Labels: Needs testing, RPM

#5797 Update pulp_rpm to 3.5.1
  packages/pulpcore/python-pulp-rpm/7248.patch
  packages/pulpcore/python-pulp-rpm/7284.patch
  packages/pulpcore/python-pulp-rpm/7321.patch
  packages/pulpcore/python-pulp-rpm/pulp-rpm-3.5.0.tar.gz
  packages/pulpcore/python-pulp-rpm/pulp-rpm-3.5.1.tar.gz
  packages/pulpcore/python-pulp-rpm/python-pulp-rpm.spec
Labels: Needs testing, RPM, Stable branch

#5801 Update foreman to 2.2.0-rc3
  packages/foreman/foreman-installer/foreman-installer-2.2.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.2.0-rc3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.2.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.2.0-rc3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.2.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.2.0-rc3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.2.0-rc1.tar.bz2
  packages/foreman/foreman/foreman-2.2.0-rc3.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Stable branch

#5785 Update foreman_remote_execution to 4.1.0
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing, Stable branch

#5731 Update rubygem-dynflow to 1.4.7
  packages/foreman/rubygem-dynflow/dynflow-1.4.6.gem
  packages/foreman/rubygem-dynflow/dynflow-1.4.7.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing, Stable branch

#5730 Update dynflow dependency to 1.4.7
  dependencies/bionic/dynflow/changelog
  dependencies/buster/dynflow/changelog
  dependencies/focal/dynflow/changelog
Labels: DEB, Needs testing, Stable branch

#5800 Release 2.2.0-rc3
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: DEB, Needs testing, Stable branch

#5782 Update rubygem-foreman_ansible to 6.0.0
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-5.1.1.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.0.0.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM, Stable branch

#5802 Update rubygem-foreman_leapp to 0.1.5
  packages/plugins/rubygem-foreman_leapp/foreman_leapp-0.1.4.gem
  packages/plugins/rubygem-foreman_leapp/foreman_leapp-0.1.5.gem
  packages/plugins/rubygem-foreman_leapp/rubygem-foreman_leapp.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#5781 Update foreman_ansible to 5.1.3
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: DEB, Needs testing, Stable branch

#5807 load pulpcore gpg keys from the server
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello-repos/katello.repo
Labels: Needs testing, RPM

#5806 use new pulpcore repos for 3.17
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello-repos/katello.repo
Labels: Needs testing, RPM, Stable branch

#5812 Use -fno-strict-aliasing for nio4r
  packages/foreman/rubygem-nio4r/rubygem-nio4r.spec
Labels: Needs testing, RPM

#5811 Fix license for method_source
  packages/foreman/rubygem-method_source/rubygem-method_source.spec
Labels: Needs testing, RPM

#5803 Bump rubygem-foreman_rh_cloud to 2.0.11-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.10.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.11.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM

#5804 Bump rubygem-foreman_rh_cloud to 2.0.11-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.10.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.11.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM

#5813 Bump rubygem-foreman_rh_cloud to 2.0.11-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.10.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.11.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM

#5805 Update 3.17 bindings for pulp 3.6
  packages/katello/rubygem-pulp_2to3_migration_client/pulp_2to3_migration_client-0.2.0b6.gem
  packages/katello/rubygem-pulp_2to3_migration_client/pulp_2to3_migration_client-0.3.0.gem
  packages/katello/rubygem-pulp_2to3_migration_client/rubygem-pulp_2to3_migration_client.spec
  packages/katello/rubygem-pulp_ansible_client/pulp_ansible_client-0.2.0b13.dev01588546902.gem
  packages/katello/rubygem-pulp_ansible_client/pulp_ansible_client-0.3.0.gem
  packages/katello/rubygem-pulp_ansible_client/rubygem-pulp_ansible_client.spec
  packages/katello/rubygem-pulp_certguard_client/pulp_certguard_client-0.1.0rc5.gem
  packages/katello/rubygem-pulp_certguard_client/pulp_certguard_client-1.0.2.gem
  packages/katello/rubygem-pulp_certguard_client/ruybgem-pulp_cerguard_client.spec
  packages/katello/rubygem-pulp_container_client/pulp_container_client-1.4.1.gem
  packages/katello/rubygem-pulp_container_client/pulp_container_client-2.0.0.gem
  packages/katello/rubygem-pulp_container_client/rubygem-pulp_container_client.spec
  packages/katello/rubygem-pulp_file_client/pulp_file_client-1.0.1.gem
  packages/katello/rubygem-pulp_file_client/pulp_file_client-1.2.0.gem
  packages/katello/rubygem-pulp_file_client/rubygem-pulp_file_client.spec
  packages/katello/rubygem-pulp_rpm_client/pulp_rpm_client-3.5.0.gem
  packages/katello/rubygem-pulp_rpm_client/pulp_rpm_client-3.6.2.gem
  packages/katello/rubygem-pulp_rpm_client/rubygem-pulp_rpm_client.spec
  packages/katello/rubygem-pulpcore_client/pulpcore_client-3.4.1.gem
  packages/katello/rubygem-pulpcore_client/pulpcore_client-3.6.0.gem
  packages/katello/rubygem-pulpcore_client/rubygem-pulpcore_client.spec
Labels: Needs testing, RPM, Stable branch

#5745 Update foreman-tasks to 3.0.0
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/control
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing

#5747 Update foreman_ansible to 6.0.0
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/control
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing

#5814 Update rubygem-foreman_discovery to 16.1.2 (CP 2.1 RPM)
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-16.1.0.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-16.1.2.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, RPM, Stable branch

#5820 Update rubygem-foreman_discovery to 16.2.0
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-16.1.0.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-16.2.0.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, Not yet reviewed

#5821 Update rubygem-foreman_discovery to 16.2.0 (CP 2.2)
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-16.1.0.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-16.2.0.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing

#5822 Update foreman_discovery to 16.2.0 - DEB
  plugins/ruby-foreman-discovery/debian/changelog
  plugins/ruby-foreman-discovery/debian/gem.list
  plugins/ruby-foreman-discovery/foreman_discovery.rb
Labels: Needs testing

#5823 Update foreman_discovery to 16.1.2 - DEB CP 2.2
  plugins/ruby-foreman-discovery/debian/changelog
  plugins/ruby-foreman-discovery/debian/gem.list
  plugins/ruby-foreman-discovery/foreman_discovery.rb
Labels: Needs testing

#5817 Update sinatra to 2.1.0 to match rack-protection in core.
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
Labels: DEB, Needs testing

#5818 Update sinatra to 2.1.0 to match rack-protection in core.
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
Labels: DEB, Needs testing

#5826 Update foreman-tasks to 3.0.0
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/control
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB, Needs testing, Stable branch

#5827 Update foreman_ansible to 6.0.0
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/control
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: DEB, Needs testing

#5825 Update rubygem-foreman_maintain to 0.6.12
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.10.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.12.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#5829 Update foreman to 2.0.3
  packages/foreman/foreman-installer/foreman-installer-2.0.2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.0.3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.0.2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.0.3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.0.2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.0.3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.0.2.tar.bz2
  packages/foreman/foreman/foreman-2.0.3.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#5828 Release 2.0.3
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: Needs testing

#5830 Bump hammer-cli-katello to 0.23.1
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.23.0.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.23.1.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM, Stable branch

#5816 Update rubygem-foreman_maintain to 0.6.12
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.11.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.12.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM

#5832 Update sinatra to 2.1.0 to match rack-protection in core.
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
Labels: DEB, Needs testing, Stable branch

#5833 Update rubygem-foreman_maintain to 0.6.12
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.10.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.12.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing

#5835 don't try to build scl-only gems for non-scl
  package_manifest.yaml
  rel-eng/tito.props
Labels: Needs testing, RPM

#5666 Update rubygem-logging to 2.3.0
  packages/foreman/rubygem-logging/logging-2.2.2.gem
  packages/foreman/rubygem-logging/logging-2.3.0.gem
  packages/foreman/rubygem-logging/rubygem-logging.spec
Labels: Needs testing, RPM

#5836 Update rubygem-foreman_ansible_core to 3.0.4
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-3.0.3.gem
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-3.0.4.gem
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
Labels: Needs testing, RPM

#5837 Update rubygem-foreman_maintain to 0.6.13
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.12.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.13.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#5834 Release ansible-collection-theforeman-foreman 1.3.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.2.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.3.0.tar.gz
Labels: Needs testing, RPM

#5839 Update rubygem-foreman_maintain to 0.6.13
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.12.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.13.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM, Stable branch

#5838 Update rubygem-foreman_maintain to 0.6.13
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.12.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.13.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM, Stable branch

#5843 Bump rubygem-foreman_rh_cloud to 2.0.12-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.11.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.12.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM

#5844 Bump rubygem-foreman_rh_cloud to 2.0.12-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.11.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.12.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM

#5720 Add rubygem-server_sent_events package
  comps/comps-foreman-el8.xml
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-server_sent_events/rubygem-server_sent_events.spec
  packages/foreman/rubygem-server_sent_events/server_sent_events-0.1.2.gem
  rel-eng/tito.props
Labels: Needs testing, RPM

#5824 Updated hammer_cli to 2.2.1
  dependencies/bionic/hammer_cli/changelog
  dependencies/buster/hammer_cli/changelog
  dependencies/focal/hammer_cli/changelog
Labels: Needs testing

#5847 Add rubygem-redfish_client package
  comps/comps-foreman-el8.xml
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-redfish_client/redfish_client-0.5.2.gem
  packages/foreman/rubygem-redfish_client/rubygem-redfish_client.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#5716 Update rubygem-foreman_fog_proxmox to 0.12.4
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.11.1.gem
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.12.4.gem
  packages/plugins/rubygem-foreman_fog_proxmox/rubygem-foreman_fog_proxmox.spec
Labels: Needs testing, RPM

#5849 Only enable Pulp2 repos on EL7
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello-repos/katello.repo
Labels: Needs testing, RPM

#5840 Release ansible-collection-theforeman-foreman 1.3.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.2.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.3.0.tar.gz
Labels: Needs testing, RPM, Stable branch

#5850 Update rubygem-foreman_leapp to 0.1.6
  packages/plugins/rubygem-foreman_leapp/foreman_leapp-0.1.5.gem
  packages/plugins/rubygem-foreman_leapp/foreman_leapp-0.1.6.gem
  packages/plugins/rubygem-foreman_leapp/rubygem-foreman_leapp.spec
Labels: Needs testing, RPM

#5851 Update foreman to 2.1.3
  packages/foreman/foreman-installer/foreman-installer-2.1.2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.1.3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.1.2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.1.3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.1.2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.1.3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.1.2.tar.bz2
  packages/foreman/foreman/foreman-2.1.3.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#5848 update foreman dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#5841 Release ansible-collection-theforeman-foreman 1.3.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.2.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.3.0.tar.gz
Labels: Needs testing, RPM, Stable branch

#5853 Update rubygem-nio4r to 2.5.4
  packages/foreman/rubygem-nio4r/nio4r-2.5.2.gem
  packages/foreman/rubygem-nio4r/nio4r-2.5.4.gem
  packages/foreman/rubygem-nio4r/rubygem-nio4r.spec
Labels: Needs testing, RPM

#5854 Update sinatra to 2.1.0 to match rack-protection in core.
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
Labels: DEB, Needs testing, Stable branch

#5857 Update rubygem-scoped_search to 4.1.9
  packages/foreman/rubygem-scoped_search/rubygem-scoped_search.spec
  packages/foreman/rubygem-scoped_search/scoped_search-4.1.8.gem
  packages/foreman/rubygem-scoped_search/scoped_search-4.1.9.gem
Labels: Needs testing, RPM, Stable branch

#5626 Bump foreman_statistics to 1.0
  plugins/ruby-foreman-statistics/debian/changelog
  plugins/ruby-foreman-statistics/debian/gem.list
  plugins/ruby-foreman-statistics/foreman_statistics.rb
Labels: DEB, Needs testing

#5855 Katello 3.16.1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.16.0.gem
  packages/katello/rubygem-katello/katello-3.16.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#5507 Fixes #30313 - Use case-insensitive sed for hostname change
  packages/katello/katello/hostname-change.rb
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM
