Repository theforeman/foreman-packaging, pull requests merged in 2020-12, with the labels that each got.

#6068 Release rubygem-foreman_virt_who_configure 0.5.4
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.3.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.4.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Needs testing, RPM

#6053 foreman_datacenter 2.3.0
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_datacenter/foreman_datacenter-2.3.0.gem
  packages/plugins/rubygem-foreman_datacenter/rubygem-foreman_datacenter.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#6054 foreman_datacenter 2.2.0
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_datacenter/foreman_datacenter-2.2.0.gem
  packages/plugins/rubygem-foreman_datacenter/rubygem-foreman_datacenter.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#6012 Use bundler API to get Gemfile dependencies
  get-gemfile-deps
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#6069 foreman_datacenter 2.3.0
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_datacenter/foreman_datacenter-2.3.0.gem
  packages/plugins/rubygem-foreman_datacenter/rubygem-foreman_datacenter.spec
  rel-eng/tito.props
Labels: Needs testing, Not yet reviewed, RPM

#6070 Katello 3.18.0 RC2.1
  packages/katello/rubygem-katello/katello-3.18.0.rc2.1.gem
  packages/katello/rubygem-katello/katello-3.18.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#6072 Update foreman to 2.3.0
  packages/foreman/foreman-installer/foreman-installer-2.3.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.3.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.3.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.3.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.3.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.3.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.3.0-rc2.tar.bz2
  packages/foreman/foreman/foreman-2.3.0.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Stable branch

#6073 Release rubygem-foreman_virt_who_configure 0.5.4
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.3.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.4.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Needs testing, Stable branch

#6071 Release 2.3.0
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: DEB, Needs testing, Stable branch

#6074 Update rubygem-foreman_monitoring to 2.1.0
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-2.0.0.gem
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-2.1.0.gem
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
Labels: Needs testing

#6076 Update rubygem-foreman_monitoring to 2.1.0 (rpm/2.2)
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-2.0.0.gem
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-2.1.0.gem
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
Labels: Needs testing

#6075 Update rubygem-foreman_monitoring to 2.1.0 (rpm/2.3)
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-2.0.0.gem
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-2.1.0.gem
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
Labels: Needs testing

#6077 Update foreman-monitoring to 2.1.0
  plugins/ruby-foreman-monitoring/debian/changelog
  plugins/ruby-foreman-monitoring/debian/gem.list
  plugins/ruby-foreman-monitoring/foreman_monitoring.rb
Labels: Needs testing

#5991 foreman_datacenter 2.3.0
  plugins/ruby-foreman-datacenter/debian/changelog
  plugins/ruby-foreman-datacenter/debian/control
  plugins/ruby-foreman-datacenter/debian/gem.list
  plugins/ruby-foreman-datacenter/debian/rules
  plugins/ruby-foreman-datacenter/foreman_datacenter.rb
Labels: DEB, Needs testing, Stable branch

#5990 foreman_datacenter 2.2.0
  plugins/ruby-foreman-datacenter/debian/changelog
  plugins/ruby-foreman-datacenter/debian/control
  plugins/ruby-foreman-datacenter/debian/gem.list
  plugins/ruby-foreman-datacenter/debian/rules
  plugins/ruby-foreman-datacenter/foreman_datacenter.rb
Labels: DEB, Needs testing, Stable branch

#6050 Bump rubygem-foreman_rh_cloud to 3.0.14-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.13.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.14.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM

#6078 Update foreman-monitoring to 2.1.0 (deb/2.3)
  plugins/ruby-foreman-monitoring/debian/changelog
  plugins/ruby-foreman-monitoring/debian/gem.list
  plugins/ruby-foreman-monitoring/foreman_monitoring.rb
Labels: DEB, Needs testing, Stable branch

#6079 Update foreman-monitoring to 2.1.0 (deb/2.2)
  plugins/ruby-foreman-monitoring/debian/changelog
  plugins/ruby-foreman-monitoring/debian/gem.list
  plugins/ruby-foreman-monitoring/foreman_monitoring.rb
Labels: DEB, Needs testing, Stable branch

#6080 Update rubygem-foreman_maintain to 0.7.0
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.13.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.0.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#6082 Update rubygem-foreman_maintain to 0.7.0
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.13.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.0.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM, Stable branch

#6081 Update rubygem-foreman_maintain to 0.7.0
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.13.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.0.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM, Stable branch

#6086 Update rubygem-foreman_ansible to 6.0.1
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.0.0.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.0.1.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM, Stable branch

#6090 Update rubygem-foreman_openscap to 4.1.1
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.1.0.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.1.1.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#6089 Update rubygem-foreman_openscap to 4.1.1
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.1.0.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.1.1.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#6092 Update rubygem-foreman_maintain to 0.7.1
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.0.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.1.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#6093 Update rubygem-foreman_maintain to 0.7.1
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.0.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.1.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM, Stable branch

#6094 Update rubygem-foreman_maintain to 0.7.1
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.0.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.1.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM, Stable branch

#6091 use vault.centos.org for el6 repoclosure -- CentOS 6 is done
  repoclosure/yum.conf
Labels: Needs testing, RPM

#6088 Update rubygem-foreman_ansible to 6.0.1
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.0.0.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.0.1.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#6096 add el8-ansible to client repoclosure
  package_manifest.yaml
Labels: Needs testing, RPM

#6099 Rebuild rubygem-rkerberos against new libkadm5 in EL 8.3
  packages/foreman/rubygem-rkerberos/rubygem-rkerberos.spec
Labels: Needs testing, RPM

#6107 Fixes #30653 - rebuild rubygem-rkerberos against new libkadm5 in EL 8.3
  packages/foreman/rubygem-rkerberos/rubygem-rkerberos.spec
Labels: Needs testing, RPM

#6108 Fixes #30653 - rebuild rubygem-rkerberos against new libkadm5 in EL 8.3
  packages/foreman/rubygem-rkerberos/rubygem-rkerberos.spec
Labels: Needs testing, RPM

#6111 Fixes #30653 - rebuild rubygem-rkerberos against new libkadm5 in EL 8.3
  packages/foreman/rubygem-rkerberos/rubygem-rkerberos.spec
Labels: Needs testing, RPM

#6110 [2.2] drop qpid copr again, EPEL is fixed
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello-repos/katello.repo
Labels: Needs testing, RPM, Stable branch

#6109 [2.1] drop qpid copr again, EPEL is fixed
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello-repos/katello.repo
Labels: Needs testing, RPM, Stable branch

#6116 Update rubygem-kafo to 6.1.2
  packages/foreman/rubygem-kafo/kafo-6.1.1.gem
  packages/foreman/rubygem-kafo/kafo-6.1.2.gem
  packages/foreman/rubygem-kafo/rubygem-kafo.spec
Labels: Needs testing, RPM

#6113 Update rubygem-foreman_openscap to 4.1.2
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.1.1.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.1.2.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#6114 Update rubygem-foreman_openscap to 4.1.2
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.1.1.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.1.2.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#6115 Update rubygem-foreman_ansible_core to 4.0.0
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-3.0.4.gem
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-4.0.0.gem
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
Labels: Needs testing, RPM

#6118 Update rubygem-kafo to 6.1.2
  packages/foreman/rubygem-kafo/kafo-6.1.1.gem
  packages/foreman/rubygem-kafo/kafo-6.1.2.gem
  packages/foreman/rubygem-kafo/rubygem-kafo.spec
Labels: Needs testing

#6117 Release kafo 6.1.2
  dependencies/bionic/kafo/changelog
  dependencies/buster/kafo/changelog
Labels: Needs testing

#6105 Update rubygem-hammer_cli_foreman_remote_execution to 0.2.1
  packages/plugins/rubygem-hammer_cli_foreman_remote_execution/hammer_cli_foreman_remote_execution-0.2.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_remote_execution/hammer_cli_foreman_remote_execution-0.2.1.gem
  packages/plugins/rubygem-hammer_cli_foreman_remote_execution/rubygem-hammer_cli_foreman_remote_execution.spec
Labels: Needs testing, RPM

#6106 Update rubygem-hammer_cli_foreman_remote_execution to 0.2.1
  dependencies/bionic/hammer_cli_foreman_remote_execution/changelog
  dependencies/buster/hammer_cli_foreman_remote_execution/changelog
  dependencies/focal/hammer_cli_foreman_remote_execution/changelog
Labels: Needs testing, Not yet reviewed

#6112 Update rubygem-foreman_scc_manager to 1.8.6
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.5.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.6.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM

#6119 Update rubygem-hammer_cli_foreman_remote_execution to 0.2.1
  packages/plugins/rubygem-hammer_cli_foreman_remote_execution/hammer_cli_foreman_remote_execution-0.2.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_remote_execution/hammer_cli_foreman_remote_execution-0.2.1.gem
  packages/plugins/rubygem-hammer_cli_foreman_remote_execution/rubygem-hammer_cli_foreman_remote_execution.spec
Labels: Needs testing, Not yet reviewed

#6098 Update rubygem-hammer_cli_foreman_openscap to 0.1.12
  packages/plugins/rubygem-hammer_cli_foreman_openscap/hammer_cli_foreman_openscap-0.1.11.gem
  packages/plugins/rubygem-hammer_cli_foreman_openscap/hammer_cli_foreman_openscap-0.1.12.gem
  packages/plugins/rubygem-hammer_cli_foreman_openscap/rubygem-hammer_cli_foreman_openscap.spec
Labels: Needs testing, RPM

#6097 Update rubygem-hammer_cli_foreman_openscap to 0.1.12
  packages/plugins/rubygem-hammer_cli_foreman_openscap/hammer_cli_foreman_openscap-0.1.11.gem
  packages/plugins/rubygem-hammer_cli_foreman_openscap/hammer_cli_foreman_openscap-0.1.12.gem
  packages/plugins/rubygem-hammer_cli_foreman_openscap/rubygem-hammer_cli_foreman_openscap.spec
Labels: Needs testing, RPM

#6087 foreman-ansible-modules 1.5.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.4.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.5.0.tar.gz
Labels: Needs testing, RPM

#6120 Update rubygem-hammer_cli_foreman_remote_execution to 0.2.1
  dependencies/bionic/hammer_cli_foreman_remote_execution/changelog
  dependencies/buster/hammer_cli_foreman_remote_execution/changelog
  dependencies/focal/hammer_cli_foreman_remote_execution/changelog
Labels: Needs testing, Not yet reviewed

#6122 Release rubygem-hammer_cli_katello 0.24.1
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.24.0.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.24.1.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing

#6121 Update rubygem-hammer_cli_foreman_remote_execution to 0.2.1
  dependencies/bionic/hammer_cli_foreman_remote_execution/changelog
  dependencies/buster/hammer_cli_foreman_remote_execution/changelog
  dependencies/focal/hammer_cli_foreman_remote_execution/changelog
Labels: Needs testing, Not yet reviewed

#6124 Release 2.3.1
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: Needs testing, Stable branch

#6133 Update rubygem-kafo_wizards to 0.0.2
  packages/foreman/rubygem-kafo_wizards/kafo_wizards-0.0.1.gem
  packages/foreman/rubygem-kafo_wizards/kafo_wizards-0.0.2.gem
  packages/foreman/rubygem-kafo_wizards/rubygem-kafo_wizards.spec
Labels: Needs testing, RPM

#6138 FAM 1.5.1
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.5.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.5.1.tar.gz
Labels: Needs testing

#6129 [2.2] foreman-ansible-modules 1.5.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.4.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.5.0.tar.gz
Labels: Needs testing, Stable branch

#6128 [2.3] foreman-ansible-modules 1.5.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.4.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.5.0.tar.gz
Labels: Needs testing, Stable branch

#6141 Katello 3.18.0
  packages/katello/rubygem-katello/katello-3.18.0.gem
  packages/katello/rubygem-katello/katello-3.18.0.rc2.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed

#6139 Update rubygem-hammer_cli_foreman_virt_who_configure to 0.0.7
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/hammer_cli_foreman_virt_who_configure-0.0.6.gem
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/hammer_cli_foreman_virt_who_configure-0.0.7.gem
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/rubygem-hammer_cli_foreman_virt_who_configure.spec
Labels: Needs testing

#6140 Update rubygem-foreman_virt_who_configure to 0.5.5
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.4.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.5.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Needs testing

#6143 Katello 3.18
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello-repos/katello.repo
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM, Stable branch

#6144 Update mock config for el8 to include Foreman repos
  mock/el8.cfg
Labels: Needs testing, RPM

#6146 Update foreman-release to 2.2.2
  packages/foreman/foreman-installer/foreman-installer-2.2.1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.2.2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.2.1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.2.2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.2.1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.2.2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.2.1.tar.bz2
  packages/foreman/foreman/foreman-2.2.2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6147 Release 2.2.2
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: Needs testing, Not yet reviewed, Stable branch

#6145 Release kafo 6.1.2
  dependencies/bionic/kafo/changelog
  dependencies/buster/kafo/changelog
Labels: Needs testing

#6104 Update rubygem-fog-vsphere to 3.5.0
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.4.0.gem
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.5.0.gem
  packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec
Labels: Needs testing, RPM

#6153 Clean up tito.props and comps
  comps/comps-foreman-el8.xml
  rel-eng/tito.props
Labels: Needs testing, RPM

#6152 Rewrite compare-with-tags in Python
  rel-eng/compare-with-tags
  rel-eng/compare-with-tags.rb
Labels: Needs testing, RPM

#6160 Bump foreman dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM
