Repository theforeman/foreman-packaging, pull requests merged in 2020-03, with the labels that each got.

#4782 Create /var/lib/foreman-proxy in postinst
  debian/bionic/foreman-proxy/postinst
  debian/buster/foreman-proxy/postinst
Labels: DEB, Needs testing

#4787 Update rubygem-foreman_virt_who_configure to 0.5.2
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.1.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.2.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Needs testing, RPM

#4785 Update rubygem-hammer_cli_foreman_templates to 0.2.0
  packages/plugins/rubygem-hammer_cli_foreman_templates/hammer_cli_foreman_templates-0.1.2.gem
  packages/plugins/rubygem-hammer_cli_foreman_templates/hammer_cli_foreman_templates-0.2.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_templates/rubygem-hammer_cli_foreman_templates.spec
Labels: Needs testing, RPM

#4786 Updated hammer_cli_foreman_templates to 0.2.0
  dependencies/bionic/hammer_cli_foreman_templates/changelog
  dependencies/bionic/hammer_cli_foreman_templates/control
  dependencies/buster/hammer_cli_foreman_templates/changelog
  dependencies/buster/hammer_cli_foreman_templates/control
Labels: Needs testing, Not yet reviewed

#4775 Updated hammer_cli_foreman_templates to 0.2.0
  dependencies/bionic/hammer_cli_foreman_templates/changelog
  dependencies/bionic/hammer_cli_foreman_templates/control
  dependencies/buster/hammer_cli_foreman_templates/changelog
  dependencies/buster/hammer_cli_foreman_templates/control
Labels: Needs testing, Not yet reviewed, Stable branch

#4774 Update rubygem-hammer_cli_foreman_templates to 0.2.0
  packages/plugins/rubygem-hammer_cli_foreman_templates/hammer_cli_foreman_templates-0.1.2.gem
  packages/plugins/rubygem-hammer_cli_foreman_templates/hammer_cli_foreman_templates-0.2.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_templates/rubygem-hammer_cli_foreman_templates.spec
Labels: Needs testing, RPM, Stable branch

#4790 Update rubygem-foreman_snapshot_management to 1.7.1
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.7.0.gem
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.7.1.gem
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Needs testing, RPM

#4800 Update foreman-tasks-core to 0.3.4
  dependencies/bionic/foreman-tasks-core/changelog
  dependencies/buster/foreman-tasks-core/changelog
Labels: Needs testing, Not yet reviewed

#4798 Update rubygem-foreman_snapshot_management to 1.7.1 (foreman 2.0)
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.7.0.gem
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.7.1.gem
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Needs testing, RPM, Stable branch

#4796 Update rubygem-foreman_snapshot_management to 1.7.1 (foreman 1.24)
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.6.0.gem
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.7.1.gem
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Needs testing, RPM, Stable branch

#4799 Update rubygem-foreman-tasks-core to 0.3.4
  packages/plugins/rubygem-foreman-tasks-core/foreman-tasks-core-0.3.3.gem
  packages/plugins/rubygem-foreman-tasks-core/foreman-tasks-core-0.3.4.gem
  packages/plugins/rubygem-foreman-tasks-core/rubygem-foreman-tasks-core.spec
Labels: Needs testing, RPM

#4802 update pulp 2to3 migration to 0.1.0rc1
  packages/pulpcore/python-pulp_2to3_migration/pulp-2to3-migration-0.0.1rc1.tar.gz
  packages/pulpcore/python-pulp_2to3_migration/pulp-2to3-migration-0.1.0rc1.tar.gz
  packages/pulpcore/python-pulp_2to3_migration/python-pulp_2to3_migration.spec
Labels: Needs testing, RPM

#4803 Update dynflow dependency to 1.4.3
  dependencies/bionic/dynflow/changelog
  dependencies/buster/dynflow/changelog
Labels: DEB, Needs testing, Not yet reviewed

#4808 Update rubygem-foreman_templates to 7.0.7
  packages/plugins/rubygem-foreman_templates/foreman_templates-7.0.6.gem
  packages/plugins/rubygem-foreman_templates/foreman_templates-7.0.7.gem
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
Labels: Needs testing, RPM, Stable branch

#4805 update pulp 2to3 migration to 0.1.0rc1
  packages/pulpcore/python-pulp_2to3_migration/pulp-2to3-migration-0.0.1rc1.tar.gz
  packages/pulpcore/python-pulp_2to3_migration/pulp-2to3-migration-0.1.0rc1.tar.gz
  packages/pulpcore/python-pulp_2to3_migration/python-pulp_2to3_migration.spec
Labels: Needs testing, RPM, Stable branch

#4806 Release 2.0.0-rc2
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: DEB, Needs testing, Stable branch

#4741 Add postgresql-debversion
  comps/comps-katello-pulpcore-el7.xml
  package_manifest.yaml
  packages/pulpcore/postgresql-debversion/0001-Copy-relevant-code-from-apt-pkg-to-ease-packaging.patch
  packages/pulpcore/postgresql-debversion/postgresql-debversion-v1.1.1.tar.gz
  packages/pulpcore/postgresql-debversion/postgresql-debversion.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#4795 Add postgresql evr_t type extension
  comps/comps-katello-pulpcore-el7.xml
  package_manifest.yaml
  packages/pulpcore/postgresql-evr/postgresql-evr-0.0.1.tar.gz
  packages/pulpcore/postgresql-evr/postgresql-evr.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#4809 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#4797 Update rubygem-foreman_snapshot_management to 1.7.1 (foreman 1.23)
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.6.0.gem
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.7.1.gem
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Needs testing, RPM, Stable branch

#4696 Update foreman_git_templates to 1.0.4
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.3.gem
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.4.gem
  packages/plugins/rubygem-foreman_git_templates/rubygem-foreman_git_templates.spec
Labels: Needs testing, RPM

#4810 Bump rubygem-foreman_maintain to 0.6.1
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.0.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.1.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#4815 Update fog-vsphere to 3.2.5
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.2.3.gem
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.2.5.gem
  packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec
Labels: Needs testing, RPM

#4817 Cherry pick a PostgreSQL upgrade bug
  packages/foreman/foreman-installer/foreman-installer-2.0.0-upstream-postgresql-upgrade.patch
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: Needs testing, RPM

#4818 Update fog-vsphere to v3.2.5
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.2.3.gem
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.2.5.gem
  packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec
Labels: Needs testing, RPM

#4819 Update rubygem-foreman_ansible to 5.0.1
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-5.0.0.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-5.0.1.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#4706 Fixes #28939 - change-hostname: update DNS records when changing hostname
  packages/katello/katello/helper.rb
  packages/katello/katello/hostname-change.rb
Labels: Needs testing, RPM

#4822 Update foreman_ansible to 4.0.5
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: DEB, Needs testing, Not yet reviewed

#4821 Update foreman_ansible to 5.0.1
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: DEB, Needs testing, Not yet reviewed

#4820 Update rubygem-foreman_ansible to 4.0.5
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-4.0.4.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-4.0.5.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM, Stable branch

#4826 Update rubygem-foreman_ansible to 5.0.1
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-5.0.0.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-5.0.1.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM, Stable branch

#4827 Update ansible-collection-theforeman-foreman to 0.6.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-0.4.1.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-0.6.0.tar.gz
Labels: Needs testing, RPM

#4830 Bump Katello RPM release
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#4811 Update foreman_git_templates to 1.0.4 (#4696)
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.3.gem
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.4.gem
  packages/plugins/rubygem-foreman_git_templates/rubygem-foreman_git_templates.spec
Labels: Needs testing, RPM

#4812 Update foreman_git_templates to 1.0.4 (#4696)
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.3.gem
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.4.gem
  packages/plugins/rubygem-foreman_git_templates/rubygem-foreman_git_templates.spec
Labels: Needs testing, RPM

#4776 Add ansiblerole-satellite-receptor-installer
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/ansiblerole-satellite-receptor-installer/ansiblerole-satellite-receptor-installer.spec
  packages/plugins/ansiblerole-satellite-receptor-installer/satellite_receptor_installer-0.5.0.tar.gz
  rel-eng/tito.props
Labels: Needs testing, RPM

#4709 Update rubygem-fog-proxmox to 0.11.1
  packages/plugins/rubygem-fog-proxmox/fog-proxmox-0.10.0.gem
  packages/plugins/rubygem-fog-proxmox/fog-proxmox-0.11.1.gem
  packages/plugins/rubygem-fog-proxmox/rubygem-fog-proxmox.spec
Labels: Needs testing, Not yet reviewed

#4835 Fix htmlparser2 and react-html-parser
  comps/comps-foreman-plugins-rhel7.xml
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
Labels: Needs testing, RPM

#4836 Revert "Update rubygem-sass-rails to 6.0.0"
  packages/foreman/rubygem-sass-rails/rubygem-sass-rails.spec
  packages/foreman/rubygem-sass-rails/sass-rails-5.0.7.gem
  packages/foreman/rubygem-sass-rails/sass-rails-6.0.0.gem
Labels: Needs testing, RPM

#4829 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#4831 Add ability to choose a version of the gem to the add_gem script
  add_gem_package.sh
Labels: Needs testing, RPM

#4837 Fixes #28941 - Fix dynflowd shebang
  debian/bionic/foreman/rules
  debian/buster/foreman/rules
  debian/stretch/foreman/rules
  debian/xenial/foreman/rules
Labels: DEB, Needs testing, Not yet reviewed, Stable branch

#4840 Update ansiblerole-satellite-receptor-installer to 0.6.0
  packages/plugins/ansiblerole-satellite-receptor-installer/ansiblerole-satellite-receptor-installer.spec
  packages/plugins/ansiblerole-satellite-receptor-installer/satellite_receptor_installer-0.5.0.tar.gz
  packages/plugins/ansiblerole-satellite-receptor-installer/satellite_receptor_installer-0.6.0.tar.gz
Labels: Needs testing, RPM

#4832 Add rubygem-foreman_rh_cloud package
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-foreman_inventory_upload/foreman_inventory_upload-1.0.3.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-1.0.4.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
  rel-eng/tito.props
Labels: Needs testing, RPM, Stable branch

#4834 Set mock package_manager on EL7
  mock/el7-nonscl.cfg
  mock/el7-scl.cfg
Labels: Needs testing, RPM

#4841 Fixes #28941 - Fix dynflowd shebang
  debian/bionic/foreman/rules
  debian/stretch/foreman/rules
  debian/xenial/foreman/rules
Labels: DEB, Needs testing, Not yet reviewed, Stable branch

#4843 Update rubygem-foreman_maintain to 0.5.3
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.5.2.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.5.3.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#4846 Update GH pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Needs testing

#4842 Bootdisk 16.1.0 release
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-16.0.0.gem
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-16.1.0.gem
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
Labels: Needs testing, RPM

#4847 Update ansiblerole-satellite-receptor-installer
  packages/plugins/ansiblerole-satellite-receptor-installer/ansiblerole-satellite-receptor-installer.spec
  packages/plugins/ansiblerole-satellite-receptor-installer/satellite_receptor_installer-0.6.0.tar.gz
Labels: Needs testing, RPM

#4848 Correct comps and tito props
  comps/comps-foreman-plugins-rhel7.xml
  comps/comps-foreman-rhel7.xml
  comps/comps-katello-server-rhel7.xml
  rel-eng/tito.props
Labels: Needs testing

#4801 Update information for el8 foreman packages
  comps/comps-foreman-el8.xml
  package_manifest.yaml
  rel-eng/releasers.conf
  rel-eng/tito.props
  repoclosure/yum.conf
Labels: Needs testing, RPM

#4852 Clean plugin comps
  comps/comps-foreman-plugins-rhel7.xml
Labels: Needs testing, Not yet reviewed

#4849 Update rubygem-foreman_ansible_core to 3.0.3
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-3.0.2.gem
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-3.0.3.gem
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
Labels: Needs testing

#4844 Bootdisk 16.1.0 release (DEB)
  plugins/ruby-foreman-bootdisk/debian/changelog
  plugins/ruby-foreman-bootdisk/debian/gem.list
  plugins/ruby-foreman-bootdisk/foreman_bootdisk.rb
Labels: Needs testing, Not yet reviewed

#4851 Update rubygem-foreman_ansible_core to 3.0.3
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-3.0.2.gem
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-3.0.3.gem
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
Labels: Needs testing, RPM

#4850 Update rubygem-foreman_ansible_core to 3.0.3
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-3.0.2.gem
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-3.0.3.gem
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
Labels: Needs testing, RPM

#4854 Don't add -debug{info,source} packages to comps
  add_pypi_package.sh
  comps/comps-katello-pulpcore-el7.xml
Labels: Needs testing, RPM

#4853 Add katello pulpcore el8 comps file
  comps/comps-katello-pulpcore-el8.xml
Labels: Needs testing, RPM

#4856 Adjust foreman-nightly tag to only mention el8
  package_manifest.yaml
Labels: Needs testing, RPM

#4857 Adjust el8 nightly tag to not mention rhel8
  rel-eng/tito.props
Labels: Needs testing, RPM

#4859 Update rubygem-hammer_cli_foreman_virt_who_configure to 0.0.6
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/hammer_cli_foreman_virt_who_configure-0.0.5.gem
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/hammer_cli_foreman_virt_who_configure-0.0.6.gem
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/rubygem-hammer_cli_foreman_virt_who_configure.spec
Labels: Needs testing, RPM

#4855 Update rubygem-foreman_maintain to 0.6.2
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.1.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.2.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#4864 Release 1.23.2
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/stretch/foreman-installer/changelog
  debian/stretch/foreman-proxy/changelog
  debian/stretch/foreman/changelog
  debian/xenial/foreman-installer/changelog
  debian/xenial/foreman-proxy/changelog
  debian/xenial/foreman/changelog
Labels: Needs testing, Not yet reviewed

#4865 Update rubygem-foreman_scc_manager to 1.8.1
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.0.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.1.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM

#4860 Update rubygem-foreman_vault to 0.1.0
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.0.1.gem
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.1.0.gem
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
Labels: Needs testing, RPM

#4866 Add el8 modules repo to repoclosures
  package_manifest.yaml
  repoclosure/yum.conf
Labels: Needs testing, RPM

#4868 Update rubygem-foreman_scc_manager to 1.8.2
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.1.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.2.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM

#4870 Add EL8 candlepin comps
  comps/comps-katello-candlepin-el8.xml
Labels: Needs testing, RPM

#4869 Foreman scc manager 1.8.2 2.0
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.1.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.2.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM

#4875 Fix flattened repo
  repoclosure/yum.conf
Labels: Needs testing, RPM

#4874 Bump pymongo requires on mongoengine to 3.10
  packages/pulpcore/python-mongoengine/python-mongoengine.spec
Labels: Needs testing, RPM

#4871 Update rubygem-foreman_vault to 0.1.0
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.0.1.gem
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.1.0.gem
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
Labels: Needs testing, RPM, Stable branch

#4872 Update rubygem-foreman_vault to 0.1.0
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.0.1.gem
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.1.0.gem
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
Labels: Needs testing, RPM, Stable branch

#4873 Update rubygem-puma to 4.3.3
  packages/foreman/rubygem-puma/puma-3.11.4.gem
  packages/foreman/rubygem-puma/puma-4.3.3.gem
  packages/foreman/rubygem-puma/rubygem-puma.spec
Labels: Needs testing, RPM

#4861 Update foreman_expire_hosts to 7.0.1
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-7.0.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-7.0.1.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Needs testing, RPM

#4794 Rails el8 p1
  packages/foreman/rubygem-actioncable/rubygem-actioncable.spec
  packages/foreman/rubygem-actionmailer/rubygem-actionmailer.spec
  packages/foreman/rubygem-actionpack/rubygem-actionpack.spec
  packages/foreman/rubygem-activejob/rubygem-activejob.spec
  packages/foreman/rubygem-activemodel/rubygem-activemodel.spec
  packages/foreman/rubygem-activerecord/rubygem-activerecord.spec
  packages/foreman/rubygem-activestorage/rubygem-activestorage.spec
  packages/foreman/rubygem-activesupport/rubygem-activesupport.spec
  packages/foreman/rubygem-arel/rubygem-arel.spec
  packages/foreman/rubygem-builder/rubygem-builder.spec
  packages/foreman/rubygem-coffee-rails/rubygem-coffee-rails.spec
  packages/foreman/rubygem-coffee-script-source/rubygem-coffee-script-source.spec
  packages/foreman/rubygem-coffee-script/rubygem-coffee-script.spec
  packages/foreman/rubygem-concurrent-ruby/rubygem-concurrent-ruby.spec
  packages/foreman/rubygem-crass/rubygem-crass.spec
  packages/foreman/rubygem-erubi/rubygem-erubi.spec
  packages/foreman/rubygem-execjs/rubygem-execjs.spec
  packages/foreman/rubygem-globalid/rubygem-globalid.spec
  packages/foreman/rubygem-i18n/rubygem-i18n.spec
Labels: Needs testing, RPM

#4792 Rails el8 p3
  packages/foreman/rubygem-sinatra/rubygem-sinatra.spec
  packages/foreman/rubygem-sprockets/rubygem-sprockets.spec
  packages/foreman/rubygem-sqlite3/rubygem-sqlite3.spec
  packages/foreman/rubygem-thor/rubygem-thor.spec
  packages/foreman/rubygem-thread_safe/rubygem-thread_safe.spec
  packages/foreman/rubygem-tilt/rubygem-tilt.spec
  packages/foreman/rubygem-tzinfo/rubygem-tzinfo.spec
  packages/foreman/rubygem-uglifier/rubygem-uglifier.spec
  packages/foreman/rubygem-websocket-driver/rubygem-websocket-driver.spec
  packages/foreman/rubygem-websocket-extensions/rubygem-websocket-extensions.spec
Labels: Needs testing, RPM

#4876 Update rubygem-foreman_maintain to 0.6.2
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.0.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.2.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM, Stable branch

#4793 Rails el8 p2
  packages/foreman/rubygem-loofah/rubygem-loofah.spec
  packages/foreman/rubygem-mail/rubygem-mail.spec
  packages/foreman/rubygem-marcel/rubygem-marcel.spec
  packages/foreman/rubygem-method_source/rubygem-method_source.spec
  packages/foreman/rubygem-mime-types-data/rubygem-mime-types-data.spec
  packages/foreman/rubygem-mime-types/rubygem-mime-types.spec
  packages/foreman/rubygem-mimemagic/rubygem-mimemagic.spec
  packages/foreman/rubygem-mini_mime/rubygem-mini_mime.spec
  packages/foreman/rubygem-mini_portile2/rubygem-mini_portile2.spec
  packages/foreman/rubygem-mustermann/rubygem-mustermann.spec
  packages/foreman/rubygem-nio4r/rubygem-nio4r.spec
  packages/foreman/rubygem-rack-protection/rubygem-rack-protection.spec
  packages/foreman/rubygem-rack-test/rubygem-rack-test.spec
  packages/foreman/rubygem-rack/rubygem-rack.spec
  packages/foreman/rubygem-rails-dom-testing/rubygem-rails-dom-testing.spec
  packages/foreman/rubygem-rails-html-sanitizer/rubygem-rails-html-sanitizer.spec
  packages/foreman/rubygem-rails/rubygem-rails.spec
  packages/foreman/rubygem-railties/rubygem-railties.spec
  packages/foreman/rubygem-sass-rails/rubygem-sass-rails.spec
  packages/foreman/rubygem-sass/rubygem-sass.spec
Labels: Needs testing, Not yet reviewed, RPM

#4883 Update ansible-collection-theforeman-foreman to 0.7.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-0.6.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-0.7.0.tar.gz
Labels: Needs testing, RPM

#4887 Update rubygem-hammer_cli_foreman_kubevirt to 0.1.4
  packages/plugins/rubygem-hammer_cli_foreman_kubevirt/hammer_cli_foreman_kubevirt-0.1.3.gem
  packages/plugins/rubygem-hammer_cli_foreman_kubevirt/hammer_cli_foreman_kubevirt-0.1.4.gem
  packages/plugins/rubygem-hammer_cli_foreman_kubevirt/rubygem-hammer_cli_foreman_kubevirt.spec
Labels: Needs testing, RPM

#4888 Add dist for pulpcore el8 tag
  rel-eng/tito.props
Labels: Needs testing, RPM

#4889 Update ansiblerole-satellite_receptor_installer to 0.6.2
  packages/plugins/ansiblerole-satellite-receptor-installer/ansiblerole-satellite-receptor-installer.spec
  packages/plugins/ansiblerole-satellite-receptor-installer/satellite_receptor_installer-0.6.0.tar.gz
  packages/plugins/ansiblerole-satellite-receptor-installer/satellite_receptor_installer-0.6.2.tar.gz
Labels: Needs testing, RPM

#4897 Release 2.0.0-rc3
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: Needs testing, Not yet reviewed

#4813 Fixes #29313 - require same katello-host-tools version on subpackages
  packages/client/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#4899 Update el8 comps
  comps/comps-foreman-el8.xml
Labels: Needs testing, RPM

#4900 Remove tfm prefix from el8 packages in comps
  comps/comps-foreman-el8.xml
Labels: Needs testing, RPM

#4895 Refs #29144 - Use systemd socket activation
  packages/foreman/foreman/foreman.spec
  packages/foreman/foreman/foreman.sysconfig
Labels: Needs testing, RPM

#4901 Refs #29144 - Use systemd socket activation
  debian/bionic/foreman/foreman-service.install
  debian/bionic/foreman/rules
  debian/buster/foreman/foreman-service.install
  debian/buster/foreman/rules
Labels: Needs testing, Not yet reviewed

#4903 Updated hammer_cli_foreman to 2.0.2
  dependencies/bionic/hammer_cli_foreman/changelog
  dependencies/buster/hammer_cli_foreman/changelog
Labels: Needs testing

#4902 Update rubygem-hammer_cli_foreman to 2.0.2
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-2.0.1.gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-2.0.2.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing

#4904 Build gyp
  comps/comps-foreman-el8.xml
  package_manifest.yaml
  packages/foreman/gyp/gyp-0.1-gitfcd686f1.tar.xz
  packages/foreman/gyp/gyp-fix-cmake.patch
  packages/foreman/gyp/gyp-ninja-build.patch
  packages/foreman/gyp/gyp-python3.patch
  packages/foreman/gyp/gyp-python38.patch
  packages/foreman/gyp/gyp-rpmoptflags.patch
  packages/foreman/gyp/gyp.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#4907 Don't build libsass with native CPU code tuning
  debian/bionic/foreman/rules
  debian/buster/foreman/rules
Labels: DEB, Needs testing, Not yet reviewed

#4910 Update rubygem-kafo_parsers to 1.1.0
  packages/foreman/rubygem-kafo_parsers/kafo_parsers-1.0.0.gem
  packages/foreman/rubygem-kafo_parsers/kafo_parsers-1.1.0.gem
  packages/foreman/rubygem-kafo_parsers/rubygem-kafo_parsers.spec
Labels: Needs testing

#4908 update pulp 2to3 migration to 0.1.0
  packages/pulpcore/python-pulp_2to3_migration/pulp-2to3-migration-0.1.0.tar.gz
  packages/pulpcore/python-pulp_2to3_migration/pulp-2to3-migration-0.1.0rc1.tar.gz
  packages/pulpcore/python-pulp_2to3_migration/python-pulp_2to3_migration.spec
Labels: Needs testing

#4912 Update rubygem-foreman_scc_manager to 1.8.3
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.2.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.3.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing

#4913 add version dependency also to foreman-service
  debian/bionic/foreman/control
  debian/buster/foreman/control
Labels: Needs testing

#4905 [Pulpcore 3.2] Bump python-ruamel-yaml to 0.16.10
  packages/pulpcore/python-ruamel-yaml/python-ruamel-yaml.spec
  packages/pulpcore/python-ruamel-yaml/ruamel.yaml-0.16.10.tar.gz
  packages/pulpcore/python-ruamel-yaml/ruamel.yaml-0.16.5.tar.gz
Labels: Needs testing

#4914 Update rubygem-foreman_scc_manager to 1.8.3 foreman 2.0
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.2.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.3.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing

#4909 fix katello requires for pulp 2to3
  packages/katello/rubygem-katello/katello-3.15.0.rc1.2.gem
  packages/katello/rubygem-katello/katello-3.15.0.rc1.3.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing

#4917 Add pulpcore-selinux to 2.0
  comps/comps-katello-pulpcore-el7.xml
Labels: Needs testing

#4906 update to ga releases of pulp2to3 migration
  packages/katello/rubygem-pulp_2to3_migration_client/pulp_2to3_migration_client-0.0.1rc1.gem
  packages/katello/rubygem-pulp_2to3_migration_client/pulp_2to3_migration_client-0.1.0.gem
  packages/katello/rubygem-pulp_2to3_migration_client/rubygem-pulp_2to3_migration_client.spec
Labels: Needs testing

#4916 Build the scl and nonscl packages for EL8
  comps/comps-foreman-el8.xml
  package_manifest.yaml
  packages/foreman/rubygem-clamp/rubygem-clamp.spec
  packages/foreman/rubygem-hashie/rubygem-hashie.spec
  packages/foreman/rubygem-highline/rubygem-highline.spec
  packages/foreman/rubygem-little-plugger/rubygem-little-plugger.spec
  packages/foreman/rubygem-multi_json/rubygem-multi_json.spec
  packages/foreman/rubygem-powerbar/rubygem-powerbar.spec
  rel-eng/tito.props
Labels: Needs testing

#4922 SLES requires python2-zypp-plugin
  packages/client/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#4927 Add rubygem-multi_json to EL8
  comps/comps-foreman-el8.xml
Labels: Needs testing, RPM

#4931 Bump rubygem-foreman_rh_cloud to 1.0.4.1-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-1.0.4.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-1.0.4.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM, Stable branch

#4920 Fixes #29281: Stop dynflowd service before removal
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#4915 Fixes #29281: Stop dynflow before service is removed
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch
