Repository theforeman/foreman-packaging, pull requests merged in 2020-10, with the labels that each got.

#5860 Katello 3.16.1.1
  packages/katello/rubygem-katello/katello-3.16.1.1.gem
  packages/katello/rubygem-katello/katello-3.16.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#5861 Update foreman-fog-proxmox to 0.12.4
  plugins/ruby-foreman-fog-proxmox/debian/changelog
  plugins/ruby-foreman-fog-proxmox/debian/gem.list
  plugins/ruby-foreman-fog-proxmox/foreman_fog_proxmox.rb
Labels: DEB, Needs testing

#5859 Update rubygem-foreman_statistics to 1.0.0
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-0.1.3.gem
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-1.0.0.gem
  packages/plugins/rubygem-foreman_statistics/rubygem-foreman_statistics.spec
Labels: Needs testing, Stable branch

#5863 Remove trends counter cron job
  packages/foreman/foreman/foreman.cron.d
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#5867 Update rubygem-katello to 3.16.1.2
  packages/katello/rubygem-katello/katello-3.16.1.1.gem
  packages/katello/rubygem-katello/katello-3.16.1.2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#5869 Bump supported openscap versions for rubygem-openscap
  packages/plugins/rubygem-openscap/rubygem-openscap.spec
Labels: Needs testing, RPM

#5699 Add rubygem-hocon package
  comps/comps-foreman-el8.xml
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-hocon/hocon-1.3.1.gem
  packages/foreman/rubygem-hocon/rubygem-hocon.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#5873 Update rubygem-redhat_access to 2.2.18
  packages/katello/rubygem-redhat_access/redhat_access-2.2.17.gem
  packages/katello/rubygem-redhat_access/redhat_access-2.2.18.gem
  packages/katello/rubygem-redhat_access/rubygem-redhat_access.spec
Labels: Needs testing, RPM

#5878 Release 2.1.4
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: Needs testing, Not yet reviewed

#5876 Update foreman-release to 2.1.4
  packages/foreman/foreman-installer/foreman-installer-2.1.3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.1.4.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.1.3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.1.4.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.1.3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.1.4.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.1.3.tar.bz2
  packages/foreman/foreman/foreman-2.1.4.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#5872 Update rubygem-apipie-dsl to 2.3.0
  packages/foreman/rubygem-apipie-dsl/apipie-dsl-2.2.9.gem
  packages/foreman/rubygem-apipie-dsl/apipie-dsl-2.3.0.gem
  packages/foreman/rubygem-apipie-dsl/rubygem-apipie-dsl.spec
Labels: Needs testing, RPM

#5868 Get dynaconf list into foreman-debug
  packages/katello/katello/katello-debug.sh
  packages/katello/katello/katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#5874 Update rubygem-puma to 4.3.6
  packages/foreman/rubygem-puma/puma-4.3.5.gem
  packages/foreman/rubygem-puma/puma-4.3.6.gem
  packages/foreman/rubygem-puma/rubygem-puma.spec
Labels: Needs testing, RPM

#5865 Update rubygem-foreman-tasks to 3.0.1
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-3.0.0.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-3.0.1.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#5866 Update foreman-tasks to 3.0.1
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing

#5641 Update python-psutil to 5.7.2
  packages/client/python-psutil/extras_require.patch
  packages/client/python-psutil/psutil-5.6.3.tar.gz
  packages/client/python-psutil/psutil-5.7.2.tar.gz
  packages/client/python-psutil/python-psutil.spec
Labels: Needs testing, RPM

#5879 Bump required pulp 3 client versions for rubygem-katello
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#5884 Add el7 salt-master repo for repoclosure.
  package_manifest.yaml
  repoclosure/yum.conf
Labels: Needs testing, RPM, Stable branch

#5885 Add salt to plugin repoclosure for el7
  package_manifest.yaml
Labels: Needs testing, RPM, Stable branch

#5887 Add salt master repo for el7 plugins repoclosure
  package_manifest.yaml
  repoclosure/yum.conf
Labels: Needs testing, RPM

#5886 Add salt master repo for el7 plugins repoclosure
  package_manifest.yaml
  repoclosure/yum.conf
Labels: Needs testing, RPM, Stable branch

#5891 Update foreman-release to 2.2.0
  packages/foreman/foreman-installer/foreman-installer-2.2.0-rc3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.2.0-rc4.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.2.0-rc3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.2.0-rc4.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.2.0-rc3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.2.0-rc4.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.2.0-rc3.tar.bz2
  packages/foreman/foreman/foreman-2.2.0-rc4.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#5892 Release 2.2.0-rc4
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: Needs testing, Stable branch

#5894 Katello 3.17.0 RC2.2
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.17.0.rc1.gem
  packages/katello/rubygem-katello/katello-3.17.0.rc2.2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#5888 Bump rubygem-foreman_rh_cloud to 2.0.13-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.12.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.13.1.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM

#5889 [rpm/2.2] - Bump rubygem-foreman_rh_cloud to 2.0.13-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.11.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.13.1.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM

#5890 [rpm/2.1] - Bump rubygem-foreman_rh_cloud to 2.0.13-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.12.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-2.0.13.1.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM

#5893 Update rubygem-pulp_2to3_migration_client to 0.5.0
  packages/katello/rubygem-pulp_2to3_migration_client/pulp_2to3_migration_client-0.3.0.gem
  packages/katello/rubygem-pulp_2to3_migration_client/pulp_2to3_migration_client-0.5.0.gem
  packages/katello/rubygem-pulp_2to3_migration_client/rubygem-pulp_2to3_migration_client.spec
Labels: Needs testing, RPM, Stable branch

#5895 Release ansible-collection-theforeman-foreman 1.4.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.3.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.4.0.tar.gz
Labels: Needs testing, RPM

#5899 fix katello requires on pulp_2to3_migration_client
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#5904 Update rubygem-hammer_cli_foreman_docker to 0.0.7
  packages/plugins/rubygem-hammer_cli_foreman_docker/hammer_cli_foreman_docker-0.0.5.gem
  packages/plugins/rubygem-hammer_cli_foreman_docker/hammer_cli_foreman_docker-0.0.7.gem
  packages/plugins/rubygem-hammer_cli_foreman_docker/rubygem-hammer_cli_foreman_docker.spec
Labels: Needs testing, RPM

#5903 Update rubygem-hammer_cli_foreman_docker to 0.0.7
  packages/plugins/rubygem-hammer_cli_foreman_docker/hammer_cli_foreman_docker-0.0.5.gem
  packages/plugins/rubygem-hammer_cli_foreman_docker/hammer_cli_foreman_docker-0.0.7.gem
  packages/plugins/rubygem-hammer_cli_foreman_docker/rubygem-hammer_cli_foreman_docker.spec
Labels: Needs testing, RPM, Stable branch

#5910 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#5906 also add salt repo to normal repoclosure configs
  package_manifest.yaml
Labels: Needs testing, RPM, Stable branch

#5905 also add salt repo to normal repoclosure configs
  package_manifest.yaml
Labels: Needs testing, RPM

#5911 Update foreman-proxy package dependencies
  packages/foreman/foreman-proxy/foreman-proxy.spec
Labels: Needs testing, RPM

#5900 Do not start foreman.service or foreman.socket on package install
  debian/bionic/foreman/rules
  debian/buster/foreman/rules
Labels: DEB, Needs testing

#5913 Update Rails to 6.0.3.4
  packages/foreman/rubygem-actioncable/actioncable-6.0.3.1.gem
  packages/foreman/rubygem-actioncable/actioncable-6.0.3.4.gem
  packages/foreman/rubygem-actioncable/rubygem-actioncable.spec
  packages/foreman/rubygem-actionmailbox/actionmailbox-6.0.3.1.gem
  packages/foreman/rubygem-actionmailbox/actionmailbox-6.0.3.4.gem
  packages/foreman/rubygem-actionmailbox/rubygem-actionmailbox.spec
  packages/foreman/rubygem-actionmailer/actionmailer-6.0.3.1.gem
  packages/foreman/rubygem-actionmailer/actionmailer-6.0.3.4.gem
  packages/foreman/rubygem-actionmailer/rubygem-actionmailer.spec
  packages/foreman/rubygem-actionpack/actionpack-6.0.3.1.gem
  packages/foreman/rubygem-actionpack/actionpack-6.0.3.4.gem
  packages/foreman/rubygem-actionpack/rubygem-actionpack.spec
  packages/foreman/rubygem-actiontext/actiontext-6.0.3.1.gem
  packages/foreman/rubygem-actiontext/actiontext-6.0.3.4.gem
  packages/foreman/rubygem-actiontext/rubygem-actiontext.spec
  packages/foreman/rubygem-actionview/actionview-6.0.3.1.gem
  packages/foreman/rubygem-actionview/actionview-6.0.3.4.gem
  packages/foreman/rubygem-actionview/rubygem-actionview.spec
  packages/foreman/rubygem-activejob/activejob-6.0.3.1.gem
  packages/foreman/rubygem-activejob/activejob-6.0.3.4.gem
  packages/foreman/rubygem-activejob/rubygem-activejob.spec
  packages/foreman/rubygem-activemodel/activemodel-6.0.3.1.gem
  packages/foreman/rubygem-activemodel/activemodel-6.0.3.4.gem
  packages/foreman/rubygem-activemodel/rubygem-activemodel.spec
  packages/foreman/rubygem-activerecord/activerecord-6.0.3.1.gem
  packages/foreman/rubygem-activerecord/activerecord-6.0.3.4.gem
  packages/foreman/rubygem-activerecord/rubygem-activerecord.spec
  packages/foreman/rubygem-activestorage/activestorage-6.0.3.1.gem
  packages/foreman/rubygem-activestorage/activestorage-6.0.3.4.gem
  packages/foreman/rubygem-activestorage/rubygem-activestorage.spec
  packages/foreman/rubygem-activesupport/activesupport-6.0.3.1.gem
  packages/foreman/rubygem-activesupport/activesupport-6.0.3.4.gem
  packages/foreman/rubygem-activesupport/rubygem-activesupport.spec
  packages/foreman/rubygem-rails/rails-6.0.3.1.gem
  packages/foreman/rubygem-rails/rails-6.0.3.4.gem
  packages/foreman/rubygem-rails/rubygem-rails.spec
  packages/foreman/rubygem-railties/railties-6.0.3.1.gem
  packages/foreman/rubygem-railties/railties-6.0.3.4.gem
  packages/foreman/rubygem-railties/rubygem-railties.spec
Labels: Needs testing

#5922 Update foreman-release to 2.2.0
  packages/foreman/foreman-installer/foreman-installer-2.2.0-rc4.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.2.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.2.0-rc4.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.2.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.2.0-rc4.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.2.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.2.0-rc4.tar.bz2
  packages/foreman/foreman/foreman-2.2.0.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing

#5921 Release 2.2.0
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: Needs testing

#5898 non SCL package cleanup
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-satyr/rubygem-satyr.spec
  packages/plugins/rubygem-satyr/satyr-0.2.gem
  rel-eng/tito.props
Labels: Needs testing, RPM

#5923 explicitly set OS to epel7 for pyp2rpm
  add_pypi_package.sh
Labels: Needs testing, RPM

#5918 Build kafo 6.0.0
  dependencies/bionic/kafo/changelog
  dependencies/buster/kafo/changelog
Labels: Needs testing, Not yet reviewed

#5917 Update rubygem-kafo to 6.0.0
  packages/foreman/rubygem-kafo/kafo-5.1.0.gem
  packages/foreman/rubygem-kafo/kafo-6.0.0.gem
  packages/foreman/rubygem-kafo/rubygem-kafo.spec
Labels: Needs testing, RPM

#5920 Require kafo 6.0.0 in foreman-installer
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: Needs testing, RPM

#5919 Require kafo 6 by foreman-installer
  debian/bionic/foreman-installer/control
  debian/buster/foreman-installer/control
Labels: DEB, Needs testing

#5925 Use pulpcore 3.7 repos for katello nightly
  packages/katello/katello-repos/katello-repos.spec
Labels: Needs testing, RPM

#5915 update ansible_core to 3.0.4
  dependencies/bionic/foreman_ansible_core/changelog
  dependencies/buster/foreman_ansible_core/changelog
  dependencies/focal/foreman_ansible_core/changelog
Labels: DEB, Needs testing

#5896 [2.2] Release ansible-collection-theforeman-foreman 1.4.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.3.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.4.0.tar.gz
Labels: Needs testing, RPM

#5897 [2.1] Release ansible-collection-theforeman-foreman 1.4.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.3.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.4.0.tar.gz
Labels: Needs testing, RPM

#5902 Update rubygem-smart_proxy_discovery_image to 1.3.1
  packages/plugins/rubygem-smart_proxy_discovery_image/rubygem-smart_proxy_discovery_image.spec
  packages/plugins/rubygem-smart_proxy_discovery_image/smart_proxy_discovery_image-1.3.0.gem
  packages/plugins/rubygem-smart_proxy_discovery_image/smart_proxy_discovery_image-1.3.1.gem
Labels: Needs testing
