Repository theforeman/foreman-packaging, pull requests merged in 2020-06, with the labels that each got.

#5321 [1.24] Update katello-client-bootstrap to 1.7.5
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.4.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.5.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap.spec
Labels: Needs testing, Not yet reviewed, RPM

#5320 [2.0] Update katello-client-bootstrap to 1.7.5
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.4.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.5.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap.spec
Labels: Needs testing, Not yet reviewed, RPM

#5319 [2.1] Update katello-client-bootstrap to 1.7.5
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.4.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.5.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap.spec
Labels: Needs testing, Not yet reviewed, RPM

#5339 don't build foreman-release for client-el8
  rel-eng/tito.props
Labels: Needs testing, RPM

#5340 don't build foreman-release for client-el8
  rel-eng/tito.props
Labels: Needs testing, RPM

#5342 Release 2.1.0-rc2
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: DEB, Needs testing, Stable branch

#5332 Add rubygem-amazing_print
  comps/comps-foreman-el8.xml
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-amazing_print/amazing_print-1.1.0.gem
  packages/foreman/rubygem-amazing_print/rubygem-amazing_print.spec
  rel-eng/tito.props
Labels: Needs testing, RPM, Stable branch

#5326 Update rubygem-hammer_cli to 2.1.1
  packages/foreman/rubygem-hammer_cli/hammer_cli-2.1.0.gem
  packages/foreman/rubygem-hammer_cli/hammer_cli-2.1.1.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
Labels: Needs testing, RPM, Stable branch

#5329 Update rubygem-hammer_cli_foreman to 2.1.1
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-2.1.0.gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-2.1.1.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM, Stable branch

#5352 Update rubygem-foreman_maintain to 0.6.5
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.4.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.5.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#5353 Update rubygem-foreman_maintain to 0.6.5
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.4.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.5.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#5338 Fixes #29883 - Sidekiq service wrapper for SELinux
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#5355 Add Requires on libmodulemd
  packages/pulpcore/python-pulp-rpm/python-pulp-rpm.spec
Labels: Needs testing, RPM

#5331 Adding pulp_certguard_client
  comps/comps-katello-el8.xml
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-pulp_certguard_client/pulp_certguard_client-0.1.0rc5.gem
  packages/katello/rubygem-pulp_certguard_client/ruybgem-pulp_cerguard_client.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#5337 Update foreman_remote_execution to 3.3.0
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing, Not yet reviewed

#5345 Update foreman_ansible to 5.1.0
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing, Not yet reviewed

#5349 Update rubygem-hammer_cli_katello to 0.22.1
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.22.0.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.22.1.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM, Stable branch

#5346 Update rubygem-foreman-tasks to 1.2.0
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-1.1.1.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-1.2.0.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#5336 Update rubygem-foreman_remote_execution to 3.3.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-3.2.1.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-3.3.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#5330 Update rubygem-apipie-dsl to 2.2.5
  packages/foreman/rubygem-apipie-dsl/apipie-dsl-2.2.2.gem
  packages/foreman/rubygem-apipie-dsl/apipie-dsl-2.2.5.gem
  packages/foreman/rubygem-apipie-dsl/rubygem-apipie-dsl.spec
Labels: Needs testing, RPM

#5325 Update rubygem-apipie-bindings to 0.4.0
  packages/foreman/rubygem-apipie-bindings/apipie-bindings-0.3.0.gem
  packages/foreman/rubygem-apipie-bindings/apipie-bindings-0.4.0.gem
  packages/foreman/rubygem-apipie-bindings/rubygem-apipie-bindings.spec
Labels: Needs testing, RPM

#5357 Update foreman-tasks to 2.0.0
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Not yet reviewed

#5360 Bump libcomps require to get a version with egg info
  packages/pulpcore/python-pulp-rpm/python-pulp-rpm.spec
Labels: Needs testing, RPM

#5362 Make libmodulemd dependency versioned
  packages/pulpcore/python-pulp-rpm/python-pulp-rpm.spec
Labels: Needs testing, RPM

#5348 add pulp certguard client for katello
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#5364 Update foreman_ansible to 5.1.1
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing, Not yet reviewed

#5365 Update ansible-collection-theforeman-foreman to 0.8.1
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-0.8.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-0.8.1.tar.gz
Labels: Needs testing, RPM

#5361 Update ansible-satellite-receptor-installer to 0.6.8
  packages/plugins/ansiblerole-satellite-receptor-installer/ansiblerole-satellite-receptor-installer.spec
  packages/plugins/ansiblerole-satellite-receptor-installer/satellite_receptor_installer-0.6.6.tar.gz
  packages/plugins/ansiblerole-satellite-receptor-installer/satellite_receptor_installer-0.6.8.tar.gz
Labels: Needs testing, RPM

#5356 Update rubygem-foreman-tasks to 2.0.0
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-1.2.0.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-2.0.0.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#5344 Update rubygem-foreman_ansible to 5.1.0
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-5.1.0.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-5.1.1.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#5369 Update rubygem-foreman_azure_rm to 2.1.1
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.1.0.gem
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.1.1.gem
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
Labels: Needs testing, RPM

#5370 Update rubygem-foreman_azure_rm to 2.1.1
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.1.0.gem
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.1.1.gem
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
Labels: Needs testing, RPM, Stable branch

#5368 update katello gem deps
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#5375 Fix pulp 3.4.1 solv dep
  packages/pulpcore/python-pulp-rpm/python-pulp-rpm.spec
Labels: Needs testing, RPM

#5372 Bump foreman salt version
  packages/plugins/rubygem-foreman_salt/foreman_salt-13.2.3.gem
  packages/plugins/rubygem-foreman_salt/foreman_salt-13.2.4.gem
  packages/plugins/rubygem-foreman_salt/rubygem-foreman_salt.spec
Labels: Needs testing, RPM

#5373 Update rubygem-foreman_leapp to 0.1.3
  packages/plugins/rubygem-foreman_leapp/foreman_leapp-0.1.2.gem
  packages/plugins/rubygem-foreman_leapp/foreman_leapp-0.1.3.gem
  packages/plugins/rubygem-foreman_leapp/rubygem-foreman_leapp.spec
Labels: Needs testing, RPM

#5376 make postgresql deb ext not require root
  packages/pulpcore/postgresql-debversion/0002-set_superuser.patch
  packages/pulpcore/postgresql-debversion/postgresql-debversion.spec
Labels: Needs testing, RPM

#5377 Update katello-certs-tools to 2.7.1
  packages/foreman/katello-certs-tools/katello-certs-tools-2.7.0.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools-2.7.1.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools.spec
Labels: Needs testing, RPM

#5385 Update foreman_remote_execution to 3.3.1
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing, Not yet reviewed

#5386 Update rubygem-foreman_remote_execution to 3.3.1
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-3.3.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-3.3.1.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#5387 Update satellite-receptor-installer to 0.6.9
  packages/plugins/ansiblerole-satellite-receptor-installer/ansiblerole-satellite-receptor-installer.spec
  packages/plugins/ansiblerole-satellite-receptor-installer/satellite_receptor_installer-0.6.8.tar.gz
  packages/plugins/ansiblerole-satellite-receptor-installer/satellite_receptor_installer-0.6.9.tar.gz
Labels: Needs testing, RPM

#5384 Release of rubygem-foreman_git_templates version 1.0.5
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.4.gem
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.5.gem
  packages/plugins/rubygem-foreman_git_templates/rubygem-foreman_git_templates.spec
Labels: Needs testing, RPM, Stable branch

#5383 Release of rubygem-foreman_git_templates version 1.0.5
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.4.gem
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.5.gem
  packages/plugins/rubygem-foreman_git_templates/rubygem-foreman_git_templates.spec
Labels: Needs testing, RPM

#5382 Release of rubygem-foreman_git_templates version 1.0.5
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.4.gem
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.5.gem
  packages/plugins/rubygem-foreman_git_templates/rubygem-foreman_git_templates.spec
Labels: Needs testing, RPM

#5351 Update rubygem-foreman_vault to 0.3.0
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.2.0.gem
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.3.0.gem
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
Labels: Needs testing, RPM

#5396 Add smart_proxy_dns_dnsmasq
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-smart_proxy_dns_dnsmasq/rubygem-smart_proxy_dhcp_dnsmasq.spec
  packages/plugins/rubygem-smart_proxy_dns_dnsmasq/smart_proxy_dns_dnsmasq-0.6.gem
  rel-eng/tito.props
Labels: Needs testing, RPM

#5395 Update rubygem-foreman_maintain to 0.6.5
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.2.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.5.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#5085 Fixes #29601: Drop foreman-release-scl
  comps/comps-foreman-el8.xml
  comps/comps-foreman-rhel7.xml
  extras/extras-foreman-rhel7-x86_64
  package_manifest.yaml
  packages/foreman/foreman-release-scl/foreman-release-scl.spec
  packages/foreman/tfm/tfm.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#5400 Update rubygem-foreman_bootdisk to 17.0.2
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-16.1.0.gem
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-17.0.2.gem
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
Labels: Needs testing, RPM

#5403 Update Rails dependency to 6.0.3.1
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#5401 Add smart_proxy_dns_dnsmasq
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-smart_proxy_dns_dnsmasq/rubygem-smart_proxy_dhcp_dnsmasq.spec
  packages/plugins/rubygem-smart_proxy_dns_dnsmasq/smart_proxy_dns_dnsmasq-0.6.gem
  rel-eng/tito.props
Labels: Needs testing, RPM, Stable branch

#5402 Add smart_proxy_dns_dnsmasq
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-smart_proxy_dns_dnsmasq/rubygem-smart_proxy_dhcp_dnsmasq.spec
  packages/plugins/rubygem-smart_proxy_dns_dnsmasq/smart_proxy_dns_dnsmasq-0.6.gem
  rel-eng/tito.props
Labels: Needs testing, RPM, Stable branch

#5406 bump supported openscap version
  packages/plugins/rubygem-openscap/rubygem-openscap.spec
Labels: Needs testing, RPM

#5407 bump supported openscap version
  packages/plugins/rubygem-openscap/rubygem-openscap.spec
Labels: Needs testing, Not yet reviewed, RPM

#5270 Release tracer-0.7.3-1
  packages/client/tracer/tracer-0.7.1.tar.gz
  packages/client/tracer/tracer-0.7.3.tar.gz
  packages/client/tracer/tracer.spec
Labels: Needs testing, Not yet reviewed, RPM

#5408 Update rubygem-foreman_bootdisk to 17.0.2
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-16.1.0.gem
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-17.0.2.gem
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
Labels: Needs testing, RPM

#5409 Bootdisk 17.0.2 for Foreman 2.1
  plugins/ruby-foreman-bootdisk/debian/changelog
  plugins/ruby-foreman-bootdisk/debian/gem.list
  plugins/ruby-foreman-bootdisk/foreman_bootdisk.rb
Labels: Needs testing, Not yet reviewed

#5371 Bump version of smart proxy for salt
  package_manifest.yaml
  packages/plugins/rubygem-smart_proxy_salt/rubygem-smart_proxy_salt.spec
  packages/plugins/rubygem-smart_proxy_salt/smart_proxy_salt-3.1.1.gem
  packages/plugins/rubygem-smart_proxy_salt/smart_proxy_salt-3.1.2.gem
  packages/plugins/rubygem-smart_proxy_salt_core/rubygem-smart_proxy_salt_core.spec
  packages/plugins/rubygem-smart_proxy_salt_core/smart_proxy_salt_core-0.0.2.gem
  packages/plugins/rubygem-smart_proxy_salt_core/smart_proxy_salt_core-0.0.3.gem
  repoclosure/yum.conf
Labels: Needs testing, RPM

#5393 Add update_vendor.sh
  README.md
  update_vendor.sh
Labels: Needs testing, RPM

#5418 regenerate GEM file dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#5421 fix salt repoclosure
  package_manifest.yaml
Labels: Needs testing, RPM

#5363 Adding python3-subscription-manager-rhsm for pulp builds
  comps/comps-katello-pulpcore-el7.xml
  package_manifest.yaml
  packages/pulpcore/python-iniparse/fix-issue-28.patch
  packages/pulpcore/python-iniparse/iniparse-0.4.tar.gz
  packages/pulpcore/python-iniparse/python-iniparse-python3-compat.patch
  packages/pulpcore/python-iniparse/python-iniparse-setup-fixes.patch
  packages/pulpcore/python-iniparse/python-iniparse.spec
  packages/pulpcore/subscription-manager/subscription-manager-1.27.5.tar.gz
  packages/pulpcore/subscription-manager/subscription-manager.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#5427 Move pulp-selinux req to katello-common
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#5430 [temp] use CentOS 8.1 Devel repo for closure until 8.2 one is fixed
  mock/el8.cfg
Labels: Needs testing, RPM

#5432 [temp] use CentOS 8.1 Devel repo for closure until 8.2 one is fixed
  repoclosure/yum.conf
Labels: Needs testing, RPM

#5429 Release katello-selinux 3.2.0
  packages/foreman/katello-selinux/3.1.2
  packages/foreman/katello-selinux/3.2.0
  packages/foreman/katello-selinux/katello-selinux.spec
Labels: Needs testing, RPM

#5431 Update pulp-deb to 2.4.0b1
  packages/pulpcore/python-pulp-deb/pulp-deb-2.3.0b1.tar.gz
  packages/pulpcore/python-pulp-deb/pulp-deb-2.4.0b1.tar.gz
  packages/pulpcore/python-pulp-deb/python-pulp-deb.spec
Labels: Needs testing, RPM

#5434 Update rubygem-smart_proxy_discovery_image to 1.2.0
  packages/plugins/rubygem-smart_proxy_discovery_image/rubygem-smart_proxy_discovery_image.spec
  packages/plugins/rubygem-smart_proxy_discovery_image/smart_proxy_discovery_image-1.0.9.gem
  packages/plugins/rubygem-smart_proxy_discovery_image/smart_proxy_discovery_image-1.2.0.gem
Labels: Needs testing

#5439 obsolete arel completely, we don't need it anymore
  comps/comps-foreman-el8.xml
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-arel/arel-9.0.0.gem
  packages/foreman/rubygem-arel/rubygem-arel.spec
  packages/foreman/tfm/tfm.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#5438 Release 2.1.0-rc3
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: Needs testing

#5440 Disable autorequires to prevent rich dependency auto-creation on EL8 …
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing

#5436 Update rubygem-smart_proxy_discovery_image to 1.2.0
  packages/plugins/rubygem-smart_proxy_discovery_image/rubygem-smart_proxy_discovery_image.spec
  packages/plugins/rubygem-smart_proxy_discovery_image/smart_proxy_discovery_image-1.0.9.gem
  packages/plugins/rubygem-smart_proxy_discovery_image/smart_proxy_discovery_image-1.2.0.gem
Labels: Needs testing

#5443 Add disable Autoreq to gem2rpm templates
  gem2rpm/foreman_plugin.spec.erb
  gem2rpm/hammer_plugin.spec.erb
  gem2rpm/nonscl.spec.erb
  gem2rpm/scl.spec.erb
  gem2rpm/smart_proxy_plugin.spec.erb
Labels: Needs testing

#5428 Move pulp-selinux req to katello-common
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#5404 Update sprockets to 4.0.2
  packages/foreman/rubygem-sprockets/rubygem-sprockets.spec
  packages/foreman/rubygem-sprockets/sprockets-3.7.2.gem
  packages/foreman/rubygem-sprockets/sprockets-4.0.2.gem
Labels: Needs testing, Not yet reviewed, RPM

#5444 Update ansible-collection-theforeman-foreman to 1.0.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-0.8.1.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.0.0.tar.gz
Labels: Needs testing

#5445 Update sprockets dependency
  packages/foreman/foreman/foreman.spec
Labels: Needs testing

#5424 Update dynflow dependency to 1.4.5
  dependencies/bionic/dynflow/changelog
  dependencies/buster/dynflow/changelog
  dependencies/focal/dynflow/changelog
Labels: Needs testing, Not yet reviewed

#5442 Update smart_proxy_dynflow_core to 0.2.6
  plugins/smart_proxy_dynflow_core/changelog
  plugins/smart_proxy_dynflow_core/dynflow_core.rb
Labels: Needs testing, Not yet reviewed

#5447 Fixes #30167 - Include manifest.js in Foreman
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#5441 Update rubygem-smart_proxy_dynflow_core to 0.2.6
  packages/plugins/rubygem-smart_proxy_dynflow_core/rubygem-smart_proxy_dynflow_core.spec
  packages/plugins/rubygem-smart_proxy_dynflow_core/smart_proxy_dynflow_core-0.2.5.gem
  packages/plugins/rubygem-smart_proxy_dynflow_core/smart_proxy_dynflow_core-0.2.6.gem
Labels: Needs testing, RPM

#5389 Add rubygem-foreman_statistics package
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-0.1.1.gem
  packages/plugins/rubygem-foreman_statistics/rubygem-foreman_statistics.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#5453 Update npm requirements for vendor v4.8.0
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#5452 Add rubygem-foreman_statistics package (CP 2.1)
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-0.1.1.gem
  packages/plugins/rubygem-foreman_statistics/rubygem-foreman_statistics.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#5454 Fix dynflow_core bundler.d location on EL8
  gem2rpm/smart_proxy_plugin.spec.erb
  packages/plugins/rubygem-smart-proxy-probing/rubygem-smart-proxy-probing.spec
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
  packages/plugins/rubygem-smart_proxy_chef/rubygem-smart_proxy_chef.spec
  packages/plugins/rubygem-smart_proxy_dhcp_bluecat/rubygem-smart_proxy_dhcp_bluecat.spec
  packages/plugins/rubygem-smart_proxy_dhcp_device42/rubygem-smart_proxy_dhcp_device42.spec
  packages/plugins/rubygem-smart_proxy_dhcp_dnsmasq/rubygem-smart_proxy_dhcp_dnsmasq.spec
  packages/plugins/rubygem-smart_proxy_dhcp_infoblox/rubygem-smart_proxy_dhcp_infoblox.spec
  packages/plugins/rubygem-smart_proxy_dhcp_remote_isc/rubygem-smart_proxy_dhcp_remote_isc.spec
  packages/plugins/rubygem-smart_proxy_discovery/rubygem-smart_proxy_discovery.spec
  packages/plugins/rubygem-smart_proxy_discovery_image/rubygem-smart_proxy_discovery_image.spec
  packages/plugins/rubygem-smart_proxy_dns_infoblox/rubygem-smart_proxy_dns_infoblox.spec
  packages/plugins/rubygem-smart_proxy_dns_powerdns/rubygem-smart_proxy_dns_powerdns.spec
  packages/plugins/rubygem-smart_proxy_dns_route53/rubygem-smart_proxy_dns_route53.spec
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  packages/plugins/rubygem-smart_proxy_m2/rubygem-smart_proxy_m2.spec
  packages/plugins/rubygem-smart_proxy_monitoring/rubygem-smart_proxy_monitoring.spec
  packages/plugins/rubygem-smart_proxy_omaha/rubygem-smart_proxy_omaha.spec
  packages/plugins/rubygem-smart_proxy_openscap/rubygem-smart_proxy_openscap.spec
  packages/plugins/rubygem-smart_proxy_pulp/rubygem-smart_proxy_pulp.spec
  packages/plugins/rubygem-smart_proxy_realm_ad_plugin/rubygem-smart_proxy_realm_ad_plugin.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_salt/rubygem-smart_proxy_salt.spec
  packages/plugins/rubygem-smart_proxy_spacewalk/rubygem-smart_proxy_spacewalk.spec
Labels: Needs testing, RPM

#5420 update pulp 2to3 migration plugin and bindings gem
  packages/pulpcore/python-pulp_2to3_migration/pulp-2to3-migration-0.2.0b2.tar.gz
  packages/pulpcore/python-pulp_2to3_migration/pulp-2to3-migration-0.2.0b3.tar.gz
  packages/pulpcore/python-pulp_2to3_migration/python-pulp_2to3_migration.spec
Labels: Needs testing, RPM

#5416 Put local state to /var/lib instead of /usr/com for smart proxy salt
  packages/plugins/rubygem-smart_proxy_salt/rubygem-smart_proxy_salt.spec
Labels: Needs testing, RPM

#5414 Bump version of smart proxy for salt (foreman-2.1)
  package_manifest.yaml
  packages/plugins/rubygem-smart_proxy_salt/rubygem-smart_proxy_salt.spec
  packages/plugins/rubygem-smart_proxy_salt/smart_proxy_salt-3.1.1.gem
  packages/plugins/rubygem-smart_proxy_salt/smart_proxy_salt-3.1.2.gem
  packages/plugins/rubygem-smart_proxy_salt_core/rubygem-smart_proxy_salt_core.spec
  packages/plugins/rubygem-smart_proxy_salt_core/smart_proxy_salt_core-0.0.2.gem
  packages/plugins/rubygem-smart_proxy_salt_core/smart_proxy_salt_core-0.0.3.gem
  repoclosure/yum.conf
Labels: Needs testing, RPM, Stable branch

#5415 Bump version of smart proxy for salt (foreman-2.0)
  packages/plugins/rubygem-smart_proxy_salt/rubygem-smart_proxy_salt.spec
  packages/plugins/rubygem-smart_proxy_salt/smart_proxy_salt-3.1.1.gem
  packages/plugins/rubygem-smart_proxy_salt/smart_proxy_salt-3.1.2.gem
  packages/plugins/rubygem-smart_proxy_salt_core/rubygem-smart_proxy_salt_core.spec
  packages/plugins/rubygem-smart_proxy_salt_core/smart_proxy_salt_core-0.0.2.gem
  packages/plugins/rubygem-smart_proxy_salt_core/smart_proxy_salt_core-0.0.3.gem
Labels: Needs testing, RPM, Stable branch

#5459 Require python-setuptools on EL7 for k-certs-tools
  packages/foreman/katello-certs-tools/katello-certs-tools.spec
Labels: Needs testing, RPM

#5458 Fix dynflow_core bundler.d location on EL8
  gem2rpm/smart_proxy_plugin.spec.erb
  packages/plugins/rubygem-smart-proxy-probing/rubygem-smart-proxy-probing.spec
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
  packages/plugins/rubygem-smart_proxy_chef/rubygem-smart_proxy_chef.spec
  packages/plugins/rubygem-smart_proxy_dhcp_bluecat/rubygem-smart_proxy_dhcp_bluecat.spec
  packages/plugins/rubygem-smart_proxy_dhcp_device42/rubygem-smart_proxy_dhcp_device42.spec
  packages/plugins/rubygem-smart_proxy_dhcp_dnsmasq/rubygem-smart_proxy_dhcp_dnsmasq.spec
  packages/plugins/rubygem-smart_proxy_dhcp_infoblox/rubygem-smart_proxy_dhcp_infoblox.spec
  packages/plugins/rubygem-smart_proxy_dhcp_remote_isc/rubygem-smart_proxy_dhcp_remote_isc.spec
  packages/plugins/rubygem-smart_proxy_discovery/rubygem-smart_proxy_discovery.spec
  packages/plugins/rubygem-smart_proxy_discovery_image/rubygem-smart_proxy_discovery_image.spec
  packages/plugins/rubygem-smart_proxy_dns_infoblox/rubygem-smart_proxy_dns_infoblox.spec
  packages/plugins/rubygem-smart_proxy_dns_powerdns/rubygem-smart_proxy_dns_powerdns.spec
  packages/plugins/rubygem-smart_proxy_dns_route53/rubygem-smart_proxy_dns_route53.spec
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  packages/plugins/rubygem-smart_proxy_m2/rubygem-smart_proxy_m2.spec
  packages/plugins/rubygem-smart_proxy_monitoring/rubygem-smart_proxy_monitoring.spec
  packages/plugins/rubygem-smart_proxy_omaha/rubygem-smart_proxy_omaha.spec
  packages/plugins/rubygem-smart_proxy_openscap/rubygem-smart_proxy_openscap.spec
  packages/plugins/rubygem-smart_proxy_pulp/rubygem-smart_proxy_pulp.spec
  packages/plugins/rubygem-smart_proxy_realm_ad_plugin/rubygem-smart_proxy_realm_ad_plugin.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_salt/rubygem-smart_proxy_salt.spec
  packages/plugins/rubygem-smart_proxy_spacewalk/rubygem-smart_proxy_spacewalk.spec
Labels: Needs testing, RPM

#5449 Fixes #30176 - Set foreman-proxy file owner + mode
  packages/foreman/foreman-proxy/foreman-proxy.spec
Labels: Needs testing, RPM

#5457 Update ansible-collection-theforeman-foreman to 1.0.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-0.8.1.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.0.0.tar.gz
Labels: Needs testing, RPM

#5475 rpm/develop Update rubygem-foreman_kubevirt to 0.1.8
  packages/plugins/rubygem-foreman_kubevirt/foreman_kubevirt-0.1.7.gem
  packages/plugins/rubygem-foreman_kubevirt/foreman_kubevirt-0.1.8.gem
  packages/plugins/rubygem-foreman_kubevirt/rubygem-foreman_kubevirt.spec
Labels: Needs testing, RPM

#5470 Update rubygem-foreman-foreman_kubevirt to 0.1.8
  packages/plugins/rubygem-foreman_kubevirt/foreman_kubevirt-0.1.7.gem
  packages/plugins/rubygem-foreman_kubevirt/foreman_kubevirt-0.1.8.gem
  packages/plugins/rubygem-foreman_kubevirt/rubygem-foreman_kubevirt.spec
Labels: Needs testing, RPM, Stable branch

#5476 Fix rubygem-radcli package building
  packages/plugins/rubygem-radcli/rubygem-radcli.spec
Labels: Needs testing, RPM, Stable branch

#5477 Update rubygem-katello to 3.16.0 rc3.1
  packages/katello/rubygem-katello/katello-3.16.0.rc3.1.gem
  packages/katello/rubygem-katello/katello-3.16.0.rc3.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#5478 fix salt repoclosure
  package_manifest.yaml
Labels: Needs testing, RPM, Stable branch

#5481 Update rubygem-rack to 2.2.3
  packages/foreman/rubygem-rack/rack-2.2.2.gem
  packages/foreman/rubygem-rack/rack-2.2.3.gem
  packages/foreman/rubygem-rack/rubygem-rack.spec
Labels: Needs testing, RPM

#5456 Update rubygem-dynflow to 1.4.6
  packages/foreman/rubygem-dynflow/dynflow-1.4.5.gem
  packages/foreman/rubygem-dynflow/dynflow-1.4.6.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing, RPM, Stable branch

#5465 Update rubygem-foreman_remote_execution to 3.3.2
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-3.3.1.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-3.3.2.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#5463 Update foreman_remote_execution to 3.3.2
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing

#5482 Update rubygem-rack to 2.2.3
  packages/foreman/rubygem-rack/rack-2.2.2.gem
  packages/foreman/rubygem-rack/rack-2.2.3.gem
  packages/foreman/rubygem-rack/rubygem-rack.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#5422 Update rubygem-dynflow to 1.4.6
  packages/foreman/rubygem-dynflow/dynflow-1.4.5.gem
  packages/foreman/rubygem-dynflow/dynflow-1.4.6.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing, RPM

#5423 Update rubygem-dynflow to 1.4.6
  packages/foreman/rubygem-dynflow/dynflow-1.4.5.gem
  packages/foreman/rubygem-dynflow/dynflow-1.4.6.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing, RPM

#5464 Update rubygem-foreman_remote_execution to 3.3.2
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-3.3.1.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-3.3.2.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing

#5462 Update foreman_remote_execution to 3.3.2
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing

#5412 Update foreman_vault to 0.3.0
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.1.0.gem
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.3.0.gem
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
Labels: Needs testing, RPM, Stable branch

#5411 Update foreman_vault to 0.3.0
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.1.0.gem
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.3.0.gem
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
Labels: Needs testing, RPM, Stable branch

#5410 Update foreman_vault to 0.3.0
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.1.0.gem
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.3.0.gem
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
Labels: Needs testing, RPM, Stable branch

#5473 Update rubygem-foreman-tasks to 2.0.1
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-2.0.0.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-2.0.1.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#5474 Update rubygem-foreman-tasks to 2.0.1
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-2.0.0.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-2.0.1.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing

#5471 Update foreman-tasks to 2.0.1
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB, Needs testing

#5472 Update foreman-tasks to 2.0.1
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB, Needs testing

#5466 Fix hashbangs in upload-salt-report python
  packages/plugins/rubygem-smart_proxy_salt/rubygem-smart_proxy_salt.spec
Labels: Needs testing, RPM

#5485 Fix hashbangs in upload-salt-report python foreman-2.1
  packages/plugins/rubygem-smart_proxy_salt/rubygem-smart_proxy_salt.spec
Labels: Needs testing, RPM, Stable branch

#5486 Fix hashbangs in upload-salt-report python foreman-2.0
  packages/plugins/rubygem-smart_proxy_salt/rubygem-smart_proxy_salt.spec
Labels: Needs testing, RPM, Stable branch

#4604 Update rubygem-hammer_cli_foreman to 0.19.7
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.19.6.gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-0.19.7.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM, Stable branch

#5487 Update rubygem-apipie-dsl to 2.2.7
  packages/foreman/rubygem-apipie-dsl/apipie-dsl-2.2.5.gem
  packages/foreman/rubygem-apipie-dsl/apipie-dsl-2.2.7.gem
  packages/foreman/rubygem-apipie-dsl/rubygem-apipie-dsl.spec
Labels: Needs testing, RPM

#4388 Add foreman_acd
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_acd/foreman_acd-0.2.1.gem
  packages/plugins/rubygem-foreman_acd/rubygem-foreman_acd.spec
  rel-eng/tito.props
Labels: Needs re-review, Needs testing, RPM

#5426 Add the candlepin artemis broker.xml to foreman-debug
  packages/katello/katello/katello-debug.sh
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#5492 Update ansible-collection-theforeman-foreman to 1.0.1
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.0.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.0.1.tar.gz
Labels: Needs testing, RPM

#5493 Update ansible-collection-theforeman-foreman to 1.0.1
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.0.0.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.0.1.tar.gz
Labels: Needs testing, RPM

#5495 Switch back to master devel repo, add el8-powertools to repoclosures
  package_manifest.yaml
  repoclosure/yum.conf
Labels: Needs testing, RPM

#5496 Switch back to master devel repo, add el8-powertools to repoclosures
  package_manifest.yaml
  repoclosure/yum.conf
Labels: Needs testing, RPM

#5490 Release katello-selinux 3.2.0
  packages/foreman/katello-selinux/3.1.2
  packages/foreman/katello-selinux/3.2.0
  packages/foreman/katello-selinux/katello-selinux.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#5479 Update rubygem-foreman_maintain to 0.6.6
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.5.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.6.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM

#5480 Update rubygem-foreman_maintain to 0.6.6
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.5.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.6.6.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM

#5494 make acd build on el7 and el8
  comps/comps-foreman-plugins-el8.xml
  packages/plugins/rubygem-foreman_acd/rubygem-foreman_acd.spec
  rel-eng/tito.props
Labels: Needs testing, Not yet reviewed, RPM
