Repository theforeman/foreman-packaging, pull requests merged in 2021-08, with the labels that each got.

#6965 Bump rubygem-foreman_rh_cloud to 4.0.25-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.24.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.25.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM

#6966 Bump rubygem-foreman_rh_cloud to 3.0.25-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.24.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.25.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM

#6952 Add hammer_cli_foreman_webhooks
  dependencies/bionic/hammer_cli_foreman_webhooks/changelog
  dependencies/bionic/hammer_cli_foreman_webhooks/compat
  dependencies/bionic/hammer_cli_foreman_webhooks/control
  dependencies/bionic/hammer_cli_foreman_webhooks/copyright
  dependencies/bionic/hammer_cli_foreman_webhooks/ruby-hammer-cli-foreman-webhooks.docs
  dependencies/bionic/hammer_cli_foreman_webhooks/rules
  dependencies/bionic/hammer_cli_foreman_webhooks/source/format
  dependencies/bionic/hammer_cli_foreman_webhooks/watch
  dependencies/buster/hammer_cli_foreman_webhooks/changelog
  dependencies/buster/hammer_cli_foreman_webhooks/compat
  dependencies/buster/hammer_cli_foreman_webhooks/control
  dependencies/buster/hammer_cli_foreman_webhooks/copyright
  dependencies/buster/hammer_cli_foreman_webhooks/ruby-hammer-cli-foreman-webhooks.docs
  dependencies/buster/hammer_cli_foreman_webhooks/rules
  dependencies/buster/hammer_cli_foreman_webhooks/source/format
  dependencies/buster/hammer_cli_foreman_webhooks/watch
  dependencies/focal/hammer_cli_foreman_webhooks/changelog
  dependencies/focal/hammer_cli_foreman_webhooks/compat
  dependencies/focal/hammer_cli_foreman_webhooks/control
  dependencies/focal/hammer_cli_foreman_webhooks/copyright
  dependencies/focal/hammer_cli_foreman_webhooks/ruby-hammer-cli-foreman-webhooks.docs
  dependencies/focal/hammer_cli_foreman_webhooks/rules
  dependencies/focal/hammer_cli_foreman_webhooks/source/format
  dependencies/focal/hammer_cli_foreman_webhooks/watch
Labels: DEB, Needs testing, Not yet reviewed

#6972 Fix tito tag foreman-plugins-nightly-rhel7
  add_gem_package.sh
Labels: Needs testing, Not yet reviewed, RPM

#6971 Add rubygem-hammer_cli_foreman_puppet package
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-hammer_cli_foreman_puppet/hammer_cli_foreman_puppet-0.0.2.gem
  packages/plugins/rubygem-hammer_cli_foreman_puppet/rubygem-hammer_cli_foreman_puppet.spec
  rel-eng/tito.props
Labels: Needs re-review, Needs testing, RPM

#6970 Update katello to 4.1.2.1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.1.2.1.gem
  packages/katello/rubygem-katello/katello-4.1.2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#6977 Update hammer_cli_foreman_ansible to 0.3.4
  dependencies/bionic/hammer_cli_foreman_ansible/changelog
  dependencies/buster/hammer_cli_foreman_ansible/changelog
  dependencies/focal/hammer_cli_foreman_ansible/changelog
Labels: DEB, Needs testing, Not yet reviewed

#6976 Update rubygem-hammer_cli_foreman_ansible to 0.3.4
  packages/plugins/rubygem-hammer_cli_foreman_ansible/hammer_cli_foreman_ansible-0.3.3.gem
  packages/plugins/rubygem-hammer_cli_foreman_ansible/hammer_cli_foreman_ansible-0.3.4.gem
  packages/plugins/rubygem-hammer_cli_foreman_ansible/rubygem-hammer_cli_foreman_ansible.spec
Labels: Needs testing, Not yet reviewed

#6978 Update hammer-cli{,-foreman} packages
  dependencies/bionic/hammer_cli/changelog
  dependencies/bionic/hammer_cli_foreman/changelog
  dependencies/bionic/hammer_cli_foreman/control
  dependencies/buster/hammer_cli/changelog
  dependencies/buster/hammer_cli_foreman/changelog
  dependencies/buster/hammer_cli_foreman/control
  dependencies/focal/hammer_cli/changelog
  dependencies/focal/hammer_cli_foreman/changelog
  dependencies/focal/hammer_cli_foreman/control
Labels: DEB, Needs testing, Not yet reviewed

#6973 Update rubygem-foreman_remote_execution to 4.7.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-4.6.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-4.7.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, Not yet reviewed, RPM

#6974 Update foreman_remote_execution to 4.7.0
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/control
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB, Needs testing, Not yet reviewed

#6951 Patch RbNaCl to find system libsodium
  packages/plugins/rubygem-rbnacl/0001-Added-support-for-Heroku.patch
  packages/plugins/rubygem-rbnacl/rubygem-rbnacl.spec
Labels: Needs testing, RPM

#6981 Update katello to 4.0.2.1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.0.2.1.gem
  packages/katello/rubygem-katello/katello-4.0.2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#6985 Update rubygem-hammer_cli_foreman_puppet to 0.0.3
  packages/plugins/rubygem-hammer_cli_foreman_puppet/hammer_cli_foreman_puppet-0.0.2.gem
  packages/plugins/rubygem-hammer_cli_foreman_puppet/hammer_cli_foreman_puppet-0.0.3.gem
  packages/plugins/rubygem-hammer_cli_foreman_puppet/rubygem-hammer_cli_foreman_puppet.spec
Labels: Needs testing, RPM

#6987 Update hammer-cli{,-foreman} packages to 3.0.0
  dependencies/bionic/hammer_cli/changelog
  dependencies/bionic/hammer_cli_foreman/changelog
  dependencies/buster/hammer_cli/changelog
  dependencies/buster/hammer_cli_foreman/changelog
  dependencies/focal/hammer_cli/changelog
  dependencies/focal/hammer_cli_foreman/changelog
Labels: DEB, Needs testing, Not yet reviewed

#6984 Bump rubygem-foreman_rh_cloud to 4.0.25.1-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.25.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.25.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM

#6986 Update rubygem-hammer_cli_foreman_ansible to 0.3.4
  packages/plugins/rubygem-hammer_cli_foreman_ansible/hammer_cli_foreman_ansible-0.3.3.gem
  packages/plugins/rubygem-hammer_cli_foreman_ansible/hammer_cli_foreman_ansible-0.3.4.gem
  packages/plugins/rubygem-hammer_cli_foreman_ansible/rubygem-hammer_cli_foreman_ansible.spec
Labels: Needs testing, Not yet reviewed, RPM

#6969 Bump rubygem-foreman_rh_cloud to 4.0.25-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.24.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.25.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM

#6988 Add hammer-cli-foreman-puppet
  dependencies/bionic/hammer_cli_foreman_puppet/changelog
  dependencies/bionic/hammer_cli_foreman_puppet/compat
  dependencies/bionic/hammer_cli_foreman_puppet/control
  dependencies/bionic/hammer_cli_foreman_puppet/copyright
  dependencies/bionic/hammer_cli_foreman_puppet/ruby-hammer-cli-foreman-puppet.docs
  dependencies/bionic/hammer_cli_foreman_puppet/rules
  dependencies/bionic/hammer_cli_foreman_puppet/source/format
  dependencies/bionic/hammer_cli_foreman_puppet/watch
  dependencies/buster/hammer_cli_foreman_puppet/changelog
  dependencies/buster/hammer_cli_foreman_puppet/compat
  dependencies/buster/hammer_cli_foreman_puppet/control
  dependencies/buster/hammer_cli_foreman_puppet/copyright
  dependencies/buster/hammer_cli_foreman_puppet/ruby-hammer-cli-foreman-puppet.docs
  dependencies/buster/hammer_cli_foreman_puppet/rules
  dependencies/buster/hammer_cli_foreman_puppet/source/format
  dependencies/buster/hammer_cli_foreman_puppet/watch
  dependencies/focal/hammer_cli_foreman_puppet/changelog
  dependencies/focal/hammer_cli_foreman_puppet/compat
  dependencies/focal/hammer_cli_foreman_puppet/control
  dependencies/focal/hammer_cli_foreman_puppet/copyright
  dependencies/focal/hammer_cli_foreman_puppet/ruby-hammer-cli-foreman-puppet.docs
  dependencies/focal/hammer_cli_foreman_puppet/rules
  dependencies/focal/hammer_cli_foreman_puppet/source/format
  dependencies/focal/hammer_cli_foreman_puppet/watch
Labels: Needs testing, Not yet reviewed, DEB

#6992 Install missing foreman_puppet.yml for hammer_cli_foreman_puppet
  dependencies/bionic/hammer_cli_foreman_puppet/changelog
  dependencies/bionic/hammer_cli_foreman_puppet/install
  dependencies/buster/hammer_cli_foreman_puppet/changelog
  dependencies/buster/hammer_cli_foreman_puppet/install
  dependencies/focal/hammer_cli_foreman_puppet/changelog
  dependencies/focal/hammer_cli_foreman_puppet/install
Labels: Needs testing, Not yet reviewed, DEB

#6990 Foreman 3.0 config updates
  mock/el7-nonscl.cfg
  mock/el7-scl.cfg
  mock/el8.cfg
  package_manifest.yaml
  packages/foreman/foreman-release/foreman.gpg
  rel-eng/releasers.conf
  rel-eng/tito.props
  repoclosure/yum.conf
Labels: Needs testing, RPM, Stable branch

#6995 Foreman 3.1 debian nightly updates
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: Needs testing, DEB

#6989 Foreman 3.1 nightly updates
  package_manifest.yaml
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
  rel-eng/releasers.conf
  rel-eng/tito.props
Labels: Needs testing, Not yet reviewed, RPM

#6998 Fix "nightly" releasers and repoclosures
  package_manifest.yaml
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6996 Release 3.0.0-rc1
  packages/foreman/foreman-installer/foreman-installer-3.0.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.0.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.0.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.0.0-rc1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#6997 Release 3.0.0-rc1
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: Needs testing

#7001 Update hammer_cli_foreman_templates requires on hammer_cli_foreman
  dependencies/bionic/hammer_cli_foreman_templates/changelog
  dependencies/bionic/hammer_cli_foreman_templates/control
  dependencies/buster/hammer_cli_foreman_templates/changelog
  dependencies/buster/hammer_cli_foreman_templates/control
  dependencies/focal/hammer_cli_foreman_templates/changelog
  dependencies/focal/hammer_cli_foreman_templates/control
Labels: Needs testing, DEB

#7004 Fix katello nightly vs 4.2 references on 3.0 branch
  rel-eng/releasers.conf
  rel-eng/tito.props
  repoclosure/yum.conf
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7003 Katello 4.3 version bump for nightly
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#6991 Update rubygem-foreman_ansible to 6.3.2
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.3.1.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.3.2.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, Not yet reviewed

#6999 Update rubygem-smart_proxy_ansible to 3.1.1
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-3.1.0.gem
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-3.1.1.gem
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7007 Katello 4.2.0 RC1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.2.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#7005 Update rubygem-dynflow to 1.4.9
  packages/foreman/rubygem-dynflow/dynflow-1.4.8.gem
  packages/foreman/rubygem-dynflow/dynflow-1.4.9.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7012 Update rubygem-foreman_ansible to 6.3.3
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.3.2.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.3.3.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7016 Update rubygem-foreman_ansible_core to 4.1.2
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-4.1.1.gem
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-4.1.2.gem
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7015 Update rubygem-foreman-tasks to 4.1.4
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-4.1.2.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-4.1.4.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7010 Update rubygem-foreman_statistics to 1.2.0
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-1.1.1.gem
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-1.2.0.gem
  packages/plugins/rubygem-foreman_statistics/rubygem-foreman_statistics.spec
Labels: Needs testing, RPM

#7025 Update katello to 4.1.3
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.1.2.1.gem
  packages/katello/rubygem-katello/katello-4.1.3.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7024 load excludes from foreman.git
  update-requirements
Labels: Needs testing, RPM

#7006 Update dynflow dependency to 1.4.9
  dependencies/bionic/dynflow/changelog
  dependencies/buster/dynflow/changelog
  dependencies/focal/dynflow/changelog
Labels: Needs testing, Not yet reviewed, DEB, Stable branch

#7027 Bump rubygem-foreman_rh_cloud to 4.0.26-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.25.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.26.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing

#7011 Update rubygem-foreman_statistics to 1.2.0
  plugins/ruby-foreman-statistics/debian/changelog
  plugins/ruby-foreman-statistics/debian/gem.list
  plugins/ruby-foreman-statistics/foreman_statistics.rb
Labels: Needs testing, Not yet reviewed

#7008 Update rubygem-foreman_puppet to 1.0.0.rc.2
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.0.rc.1.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.0.rc.2.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing, RPM

#7022 drop node dependencies which are unused for building
  debian/bionic/foreman/rules
  debian/buster/foreman/rules
  debian/focal/foreman/rules
Labels: Needs testing, Not yet reviewed, DEB

#7009 Update rubygem-foreman_puppet to 1.0.0.rc.2
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: Needs testing, Not yet reviewed

#7028 Update rubygem-foreman_puppet to 1.0.0.rc.2
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.0.rc.1.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.0.rc.2.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing, RPM, Stable branch

#7031 Update rubygem-foreman_puppet to 1.0.0.rc.2
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: Needs testing, DEB

#7032 drop node dependencies which are unused for building
  debian/bionic/foreman/rules
  debian/buster/foreman/rules
  debian/focal/foreman/rules
Labels: Needs testing, DEB, Stable branch

#7033 Update rubygem-foreman_ansible to 6.3.4
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.3.3.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.3.4.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7019 Update ruby-foreman-tasks to 4.1.4
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Not yet reviewed, Stable branch

#7030 speedup installation of foreman by multi-threading bundle install
  debian/bionic/foreman/foreman-assets.postinst
  debian/bionic/foreman/foreman-console.postinst
  debian/bionic/foreman/foreman-dynflow-sidekiq.postinst
  debian/bionic/foreman/foreman-ec2.postinst
  debian/bionic/foreman/foreman-gce.postinst
  debian/bionic/foreman/foreman-journald.postinst
  debian/bionic/foreman/foreman-libvirt.postinst
  debian/bionic/foreman/foreman-nulldb.postinst
  debian/bionic/foreman/foreman-openstack.postinst
  debian/bionic/foreman/foreman-ovirt.postinst
  debian/bionic/foreman/foreman-postgresql.postinst
  debian/bionic/foreman/foreman-redis.postinst
  debian/bionic/foreman/foreman-service.postinst
  debian/bionic/foreman/foreman-telemetry.postinst
  debian/bionic/foreman/foreman-vmware.postinst
  debian/bionic/foreman/foreman.postinst
  debian/buster/foreman/foreman-assets.postinst
  debian/buster/foreman/foreman-console.postinst
  debian/buster/foreman/foreman-dynflow-sidekiq.postinst
  debian/buster/foreman/foreman-ec2.postinst
  debian/buster/foreman/foreman-gce.postinst
  debian/buster/foreman/foreman-journald.postinst
  debian/buster/foreman/foreman-libvirt.postinst
  debian/buster/foreman/foreman-nulldb.postinst
  debian/buster/foreman/foreman-openstack.postinst
  debian/buster/foreman/foreman-ovirt.postinst
  debian/buster/foreman/foreman-postgresql.postinst
  debian/buster/foreman/foreman-redis.postinst
  debian/buster/foreman/foreman-service.postinst
  debian/buster/foreman/foreman-telemetry.postinst
  debian/buster/foreman/foreman-vmware.postinst
  debian/buster/foreman/foreman.postinst
  debian/focal/foreman/foreman-assets.postinst
  debian/focal/foreman/foreman-console.postinst
  debian/focal/foreman/foreman-dynflow-sidekiq.postinst
  debian/focal/foreman/foreman-ec2.postinst
  debian/focal/foreman/foreman-gce.postinst
  debian/focal/foreman/foreman-journald.postinst
  debian/focal/foreman/foreman-libvirt.postinst
  debian/focal/foreman/foreman-nulldb.postinst
  debian/focal/foreman/foreman-openstack.postinst
  debian/focal/foreman/foreman-ovirt.postinst
  debian/focal/foreman/foreman-postgresql.postinst
  debian/focal/foreman/foreman-redis.postinst
  debian/focal/foreman/foreman-service.postinst
  debian/focal/foreman/foreman-telemetry.postinst
  debian/focal/foreman/foreman-vmware.postinst
  debian/focal/foreman/foreman.postinst
Labels: Needs testing, DEB

#7029 don't generate dbgsym packages
  debian/bionic/foreman/rules
  debian/buster/foreman/rules
  debian/focal/foreman/rules
Labels: Needs testing, DEB

#6240 try use shared plugin mk
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/rules
  plugins/ruby-foreman-chef/debian/changelog
  plugins/ruby-foreman-chef/debian/install
  plugins/ruby-foreman-chef/debian/rules
Labels: Needs testing, DEB

#7036 Update rubygem-foreman_maintain to 0.8.11
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.10.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.11.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM

#7035 Release ansible-collection-theforeman-foreman 2.2.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-2.1.2.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-2.2.0.tar.gz
Labels: Needs testing, Not yet reviewed

#7034 ansible-collection-theforeman-foreman 2.2.0
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: Needs testing, Not yet reviewed, DEB

#7013 generate SCL-enabled python specs
  add_pypi_package.sh
Labels: Needs testing, Not yet reviewed, RPM

#7048 Bump rubygem-foreman_rh_cloud to 3.0.26-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.25.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.26.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7053 Update rubygem-foreman_maintain to 0.8.13
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.12.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.13.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#7057 Drop requires on facter for foreman_maintain
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM
