Repository theforeman/foreman-packaging, pull requests merged in 2021-10, with the labels that each got.

#7147 Update rubygem-foreman_maintain to 0.8.18
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.17.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.18.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#7131 Update bootdisk to 18.0
  plugins/ruby-foreman-bootdisk/debian/changelog
  plugins/ruby-foreman-bootdisk/debian/gem.list
  plugins/ruby-foreman-bootdisk/foreman_bootdisk.rb
Labels: Needs testing, DEB

#7146 Add rubygem-msgpack package
  comps/comps-foreman-el8.xml
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-msgpack/msgpack-1.3.3.gem
  packages/foreman/rubygem-msgpack/rubygem-msgpack.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#7114 Update rubygem-dynflow to 1.6.0
  packages/foreman/rubygem-dynflow/dynflow-1.6.0.gem
  packages/foreman/rubygem-dynflow/dynflow-1.6.1.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing, Not yet reviewed, RPM

#7135 Release katello-client-bootstrap 1.7.7
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.6.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.7.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap.spec
Labels: Needs testing, RPM, Stable branch

#7137 Release katello-client-bootstrap 1.7.7
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.6.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.7.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap.spec
Labels: Needs testing, RPM, Stable branch

#7141 Update rubygem-foreman_puppet to 1.0.3
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.1.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.3.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing, RPM, Stable branch

#7155 drop build_vars.sh from core projects
  debian/bionic/foreman-installer/build_vars.sh
  debian/bionic/foreman-proxy/build_vars.sh
  debian/bionic/foreman/build_vars.sh
  debian/buster/foreman-installer/build_vars.sh
  debian/buster/foreman-proxy/build_vars.sh
  debian/buster/foreman/build_vars.sh
  debian/focal/foreman-installer/build_vars.sh
  debian/focal/foreman-proxy/build_vars.sh
  debian/focal/foreman/build_vars.sh
Labels: Needs testing

#7153 add rubygem-pulp_ostree_client
  comps/comps-katello-el8.xml
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-pulp_ostree_client/pulp_ostree_client-2.0.0a1.gem
  packages/katello/rubygem-pulp_ostree_client/rubygem-pulp_ostree_client.spec
  rel-eng/tito.props
Labels: Needs testing, RPM
