Repository theforeman/foreman-packaging, pull requests merged in 2021-06, with the labels that each got.

#6723 Update ACD and its components
  packages/plugins/rubygem-foreman_acd/foreman_acd-0.6.0.gem
  packages/plugins/rubygem-foreman_acd/foreman_acd-0.7.0.gem
  packages/plugins/rubygem-foreman_acd/rubygem-foreman_acd.spec
  packages/plugins/rubygem-smart_proxy_acd/rubygem-smart_proxy_acd.spec
  packages/plugins/rubygem-smart_proxy_acd/smart_proxy_acd-0.1.0.gem
  packages/plugins/rubygem-smart_proxy_acd/smart_proxy_acd-0.2.0.gem
  packages/plugins/rubygem-smart_proxy_acd_core/rubygem-smart_proxy_acd_core.spec
  packages/plugins/rubygem-smart_proxy_acd_core/smart_proxy_acd_core-0.1.0.gem
  packages/plugins/rubygem-smart_proxy_acd_core/smart_proxy_acd_core-0.2.0.gem
Labels: Needs testing, RPM

#6728 - Use suse_version instead of sles_version to make sure python2-zypp-…
  packages/client/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#6675 Require puppet-agent 6.15.0+ in foreman-installer
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: Needs testing, RPM

#6732 Update rubygem-hammer_cli_katello to 1.1.2
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.1.1.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.1.2.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#6676 Require puppet-agent 6.15.0+ in foreman-installer
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-installer/control
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-installer/control
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-installer/control
Labels: Needs testing

#6735 Update foreman to 2.5.0
  packages/foreman/foreman-installer/foreman-installer-2.5.0-rc3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.5.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.5.0-rc3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.5.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.5.0-rc3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.5.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.5.0-rc3.tar.bz2
  packages/foreman/foreman/foreman-2.5.0.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#6726 Update rubygem-foreman_remote_execution to 4.5.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-4.4.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-4.5.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, Not yet reviewed

#6739 Add rubygem-acts_as_list to el8
  comps/comps-foreman-plugins-el8.xml
  rel-eng/tito.props
Labels: Needs testing, RPM

#6740 Add rubygem-acts_as_list to el8
  comps/comps-foreman-plugins-el8.xml
  rel-eng/tito.props
Labels: Needs testing, RPM

#6734 Release 2.5.0
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: DEB, Needs testing, Stable branch

#6653 Update rubygem-foreman_ansible to 6.3.0
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.2.0.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.3.0.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs re-review, Needs testing, RPM

#6654 Update rubygem-foreman_ansible to 6.3.0
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.2.0.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.3.0.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6741 Update katello to 4.1.0.rc2.2
  packages/katello/rubygem-katello/katello-4.1.0.rc2.1.gem
  packages/katello/rubygem-katello/katello-4.1.0.rc2.2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#6694 Add nodejs-graphql-tag package
  comps/comps-foreman-el8.xml
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/nodejs-graphql-tag/graphql-tag-2.11.0.tgz
  packages/foreman/nodejs-graphql-tag/nodejs-graphql-tag.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#6623 Update foreman_remote_execution to 4.5.0
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB, Needs testing

#6743 Update foreman_remote_execution to 4.5.0
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB, Needs testing, Stable branch

#6700 Bump foreman_puppet to 0.1.0
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: DEB, Needs testing

#6736 Update rubygem-hammer_cli_foreman_admin to 0.0.10
  packages/plugins/rubygem-hammer_cli_foreman_admin/hammer_cli_foreman_admin-0.0.10.gem
  packages/plugins/rubygem-hammer_cli_foreman_admin/hammer_cli_foreman_admin-0.0.9.gem
  packages/plugins/rubygem-hammer_cli_foreman_admin/rubygem-hammer_cli_foreman_admin.spec
Labels: Needs testing

#6730 Update webhooks to 2.0.0
  plugins/ruby-foreman-webhooks/debian/changelog
  plugins/ruby-foreman-webhooks/debian/gem.list
  plugins/ruby-foreman-webhooks/foreman_webhooks.rb
Labels: DEB, Needs testing

#6744 Update rubygem-foreman_rh_cloud to 3.0.21.1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.21.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.21.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed

#6725 Update rubygem-foreman_remote_execution_core to 1.4.3
  packages/plugins/rubygem-foreman_remote_execution_core/foreman_remote_execution_core-1.4.2.gem
  packages/plugins/rubygem-foreman_remote_execution_core/foreman_remote_execution_core-1.4.3.gem
  packages/plugins/rubygem-foreman_remote_execution_core/rubygem-foreman_remote_execution_core.spec
Labels: Needs testing, Not yet reviewed

#6745 Update katello-certs-tools to 2.8.0
  packages/foreman/katello-certs-tools/katello-certs-tools-2.7.3.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools-2.8.0.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools.spec
Labels: Needs testing, RPM

#6748 add crypt gems to el8 comps
  comps/comps-foreman-plugins-el8.xml
Labels: Needs testing, RPM

#6742 Bump rubygem-foreman_rh_cloud to 3.0.21.1-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.19.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.21.1.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6747 rh_cloud 3.0.21.1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.21.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.21.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM

#6746 rh_cloud 3.0.21.1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.21.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.21.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM

#6750 Bump rubygem-foreman_rh_cloud to 4.0.21.1-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.21.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.21.1.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM

#6749 Fixes #32725 - Make delete_puppet_certs handle all input
  packages/katello/katello/hostname-change.rb
Labels: Needs testing, RPM

#6760 Update rubygem-foreman_maintain to 0.7.10
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.10.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.9.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM

#6759 Fixes #32743 - Correct scenario answers file
  packages/katello/katello/helper.rb
Labels: Needs testing, RPM

#6752 Update rubygem-foreman_remote_execution_core to 1.4.3
  packages/plugins/rubygem-foreman_remote_execution_core/foreman_remote_execution_core-1.4.2.gem
  packages/plugins/rubygem-foreman_remote_execution_core/foreman_remote_execution_core-1.4.3.gem
  packages/plugins/rubygem-foreman_remote_execution_core/rubygem-foreman_remote_execution_core.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6761 Update rubygem-hammer_cli to 2.5.1
  packages/foreman/rubygem-hammer_cli/hammer_cli-2.5.0.gem
  packages/foreman/rubygem-hammer_cli/hammer_cli-2.5.1.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
Labels: Needs testing, RPM, Stable branch

#6764 Update rubygem-foreman_templates to 9.1.0
  packages/plugins/rubygem-foreman_templates/foreman_templates-9.0.2.gem
  packages/plugins/rubygem-foreman_templates/foreman_templates-9.1.0.gem
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
Labels: Needs testing, RPM

#6762 Update rubygem-hammer_cli_foreman to 2.5.1
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-2.5.0.gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-2.5.1.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM, Stable branch

#6769 Update foreman to 2.3.5
  packages/foreman/foreman-installer/foreman-installer-2.3.4.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.3.5.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.3.4.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.3.5.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.3.4.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.3.5.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.3.4.tar.bz2
  packages/foreman/foreman/foreman-2.3.5.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#6770 Release 2.3.5
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: Needs testing, Stable branch

#6766 Update rubygem-foreman_azure_rm to 2.2.5
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.2.4.gem
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.2.5.gem
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
Labels: Needs testing, RPM

#6731 add optimize-css-assets-webpack-plugin
  packages/foreman/foreman/foreman.spec
Labels: Needs re-review, Needs testing, RPM

#6768 Update rubygem-foreman_azure_rm to 2.2.5
  plugins/ruby-foreman-azure-rm/debian/changelog
  plugins/ruby-foreman-azure-rm/debian/gem.list
  plugins/ruby-foreman-azure-rm/foreman_azure_rm.rb
Labels: DEB, Needs testing, Not yet reviewed

#6755 Update rubygem-smart_proxy_remote_execution_ssh to 0.4.0
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.3.1.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.4.0.gem
Labels: Needs testing, Not yet reviewed

#6765 Add nodejs-graphql package
  comps/comps-foreman-el8.xml
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/nodejs-graphql/graphql-15.5.0.tgz
  packages/foreman/nodejs-graphql/nodejs-graphql.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#6771 Update rubygem-foreman_webhooks to 2.0.0
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-1.0.0.gem
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-2.0.0.gem
  packages/plugins/rubygem-foreman_webhooks/rubygem-foreman_webhooks.spec
Labels: Needs testing, RPM, Stable branch

#6692 Update rubygem-foreman_openscap to 4.3.2
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.3.0.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.3.2.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#6773 Update rubygem-pulp_ansible_client to 0.7.3
  packages/katello/rubygem-pulp_ansible_client/pulp_ansible_client-0.7.1.gem
  packages/katello/rubygem-pulp_ansible_client/pulp_ansible_client-0.7.3.gem
  packages/katello/rubygem-pulp_ansible_client/rubygem-pulp_ansible_client.spec
Labels: Needs testing, RPM

#6775 Update rubygem-pulp_ansible_client to 0.7.3
  packages/katello/rubygem-pulp_ansible_client/pulp_ansible_client-0.7.1.gem
  packages/katello/rubygem-pulp_ansible_client/pulp_ansible_client-0.7.3.gem
  packages/katello/rubygem-pulp_ansible_client/rubygem-pulp_ansible_client.spec
Labels: Needs testing, RPM, Stable branch

#6774 Fixes #32725 - Make delete_puppet_certs handle all input on rpm/2.5
  packages/katello/katello/hostname-change.rb
Labels: Needs testing, RPM, Stable branch

#6778 Update rubygem-foreman_openscap to 4.3.2
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.3.0.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.3.2.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM, Stable branch

#6779 Fixes #32743 - Correct scenario answers file
  packages/katello/katello/helper.rb
Labels: Needs testing, RPM, Stable branch

#6772 correct nodejs-graphql-tag comps on el7
  comps/comps-foreman-rhel7.xml
Labels: Needs testing, Not yet reviewed, RPM

#6781 Update rubygem-katello to 3.18.3.1
  packages/katello/rubygem-katello/katello-3.18.3.1.gem
  packages/katello/rubygem-katello/katello-3.18.3.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#6780 Update rubygem-smart_proxy_container_gateway to 1.0.5
  packages/plugins/rubygem-smart_proxy_container_gateway/rubygem-smart_proxy_container_gateway.spec
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-1.0.4.gem
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-1.0.5.gem
Labels: Needs testing, Not yet reviewed, RPM

#6782 Update rubygem-smart_proxy_container_gateway to 1.0.5
  packages/plugins/rubygem-smart_proxy_container_gateway/rubygem-smart_proxy_container_gateway.spec
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-1.0.4.gem
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-1.0.5.gem
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6789 Update rubygem-smart_proxy_container_gateway to 1.0.5
  packages/plugins/rubygem-smart_proxy_container_gateway/rubygem-smart_proxy_container_gateway.spec
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-1.0.3.gem
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-1.0.5.gem
Labels: Needs testing, RPM, Stable branch

#6786 Bump rubygem-foreman_rh_cloud to 4.0.22-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.21.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.22.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM

#6791 Update rubygem-foreman_discovery to 17.0.1 (2.5)
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-17.0.0.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-17.0.1.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, RPM, Stable branch

#6783 Update rubygem-smart_proxy_dynflow to 0.5.1
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.5.0.gem
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.5.1.gem
Labels: Needs testing, Not yet reviewed

#6794 Update rubygem-foreman_maintain to 0.8.2
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.1.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.2.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing

#6793 Update rubygem-foreman_discovery to 17.0.1 (2.4)
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-17.0.0.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-17.0.1.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, RPM, Stable branch

#6792 Update discovery to 17.0.1 (2.5)
  plugins/ruby-foreman-discovery/debian/changelog
  plugins/ruby-foreman-discovery/debian/gem.list
  plugins/ruby-foreman-discovery/foreman_discovery.rb
Labels: DEB, Needs testing, Stable branch

#6795 Update foreman_discovery to 16.3.6 (2.4)
  plugins/ruby-foreman-discovery/debian/changelog
  plugins/ruby-foreman-discovery/debian/gem.list
  plugins/ruby-foreman-discovery/foreman_discovery.rb
Labels: Needs testing

#6788 [CP 2.5] Bump rubygem-foreman_rh_cloud to 4.0.22-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.21.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.22.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM, Stable branch

#6798 drop rubygem-mimemagic
  comps/comps-foreman-el8.xml
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/rubygem-mimemagic/mimemagic-0.3.5.gem
  packages/foreman/rubygem-mimemagic/rubygem-mimemagic.spec
  packages/foreman/tfm/tfm.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#6799 Add foremandist to rubygem-smart_proxy_container_gateway
  packages/plugins/rubygem-smart_proxy_container_gateway/rubygem-smart_proxy_container_gateway.spec
Labels: Needs testing, RPM

#6801 Add foremandist to rubygem-smart_proxy_container_gateway
  packages/plugins/rubygem-smart_proxy_container_gateway/rubygem-smart_proxy_container_gateway.spec
Labels: Needs testing, RPM, Stable branch

#6800 Add foremandist to rubygem-smart_proxy_container_gateway
  packages/plugins/rubygem-smart_proxy_container_gateway/rubygem-smart_proxy_container_gateway.spec
Labels: Needs testing, RPM, Stable branch

#6790 Add rubygem-pulp_python_client package
  comps/comps-katello-el8.xml
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-pulp_python_client/pulp_python_client-3.2.0.gem
  packages/katello/rubygem-pulp_python_client/rubygem-pulp_python_client.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#6796 Update rubygem-foreman_maintain to 0.8.2
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.1.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.2.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM, Stable branch

#6797 Update rubygem-foreman_maintain to 0.8.2
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.1.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.2.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM, Stable branch

#6802 Katello 4.0.1.2
  packages/katello/rubygem-katello/katello-4.0.1.1.gem
  packages/katello/rubygem-katello/katello-4.0.1.2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6804 Update rubygem-foreman-tasks to 3.0.6
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-3.0.5.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-3.0.6.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6805 Update foreman-tasks to 3.0.6
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Stable branch

#6803 Update ruby-foreman-tasks to 4.1.2
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Not yet reviewed

#6757 Update smart_proxy_remote_execution_ssh to 0.4.0
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: Needs testing

#6808 Update rubygem-foreman-tasks to 4.1.2
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-4.1.1.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-4.1.2.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing

#6809 Update rubygem-smart_proxy_pulp to 3.1.0
  packages/plugins/rubygem-smart_proxy_pulp/rubygem-smart_proxy_pulp.spec
  packages/plugins/rubygem-smart_proxy_pulp/smart_proxy_pulp-3.0.0.gem
  packages/plugins/rubygem-smart_proxy_pulp/smart_proxy_pulp-3.1.0.gem
Labels: Needs testing, RPM

#6813 Update foreman-release to 2.4.1
  packages/foreman/foreman-installer/foreman-installer-2.4.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.4.1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.4.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.4.1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.4.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.4.1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.4.0.tar.bz2
  packages/foreman/foreman/foreman-2.4.1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#6812 Release 2.4.1
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: DEB, Needs testing, Stable branch

#6817 fixes #32859 - fix crontab format
  packages/foreman/foreman/foreman.cron.d
Labels: Needs testing, RPM

#6818 Fixes #32859 - fix cron syntax
  debian/bionic/foreman/foreman.cron.d
  debian/buster/foreman/foreman.cron.d
  debian/focal/foreman/foreman.cron.d
Labels: Needs testing

#6820 fixes #32859 - fix crontab format
  packages/foreman/foreman/foreman.cron.d
Labels: Needs testing

#6822 Fixes #32859 - fix cron syntax
  debian/bionic/foreman/foreman.cron.d
  debian/buster/foreman/foreman.cron.d
  debian/focal/foreman/foreman.cron.d
Labels: DEB, Needs testing, Stable branch

#6825 Update foreman-release to 2.5.1
  packages/foreman/foreman-installer/foreman-installer-2.5.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.5.1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.5.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.5.1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.5.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.5.1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.5.0.tar.bz2
  packages/foreman/foreman/foreman-2.5.1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing

#6824 Release 2.5.1
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: Needs testing

#6814 Release ansible-collection-theforeman-foreman 2.1.1
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-2.1.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-2.1.1.tar.gz
Labels: Needs testing, Not yet reviewed

#6815 foreman-ansible-modules 2.1.1
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: Needs testing, Not yet reviewed

#6816 Update rubygem-smart_proxy_ansible to 3.2.1
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-4.1.0.gem
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-3.1.0.gem
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-3.2.1.gem
Labels: Needs testing, RPM

#6829 Update rubygem-ldap_fluff to 0.6.0
  packages/foreman/rubygem-ldap_fluff/ldap_fluff-0.5.0.gem
  packages/foreman/rubygem-ldap_fluff/ldap_fluff-0.6.0.gem
  packages/foreman/rubygem-ldap_fluff/rubygem-ldap_fluff.spec
Labels: Needs testing, Not yet reviewed, RPM

#6821 Update rubygem-foreman_ansible to 6.4.1
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.3.0.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.4.1.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#6830 Drop foreman ansible core
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  rel-eng/tito.props
Labels: Needs testing, RPM

#6831 Update katello-selinux to 4.0.2
  packages/katello/katello-selinux/4.0.0
  packages/katello/katello-selinux/4.0.2
  packages/katello/katello-selinux/katello-selinux.spec
Labels: Needs testing, RPM
