Repository theforeman/foreman-packaging, pull requests merged in 2021-07, with the labels that each got.

#6838 Update foreman_rh_cloud to 3.0.23
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.21.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.23.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6837 Update package testing instructions
  README.md
Labels: Needs testing, RPM

#6835 Bump rubygem-foreman_rh_cloud to 3.0.23-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.21.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.23.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM, Stable branch

#6833 Bump rubygem-foreman_rh_cloud to 4.0.23-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.22.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.23.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM

#6834 Bump rubygem-foreman_rh_cloud to 4.0.23-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.22.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.23.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM

#6844 Add nodejs-use-deep-compare-effect package
  comps/comps-foreman-el8.xml
  comps/comps-foreman-rhel7.xml
  package_manifest.yaml
  packages/foreman/nodejs-use-deep-compare-effect/csstype-3.0.8.tgz
  packages/foreman/nodejs-use-deep-compare-effect/dequal-2.0.2.tgz
  packages/foreman/nodejs-use-deep-compare-effect/nodejs-use-deep-compare-effect-1.6.1-registry.npmjs.org.tgz
  packages/foreman/nodejs-use-deep-compare-effect/nodejs-use-deep-compare-effect.spec
  packages/foreman/nodejs-use-deep-compare-effect/prop-types-15.7.3.tgz
  packages/foreman/nodejs-use-deep-compare-effect/react-17.0.13.tgz
  packages/foreman/nodejs-use-deep-compare-effect/regenerator-runtime-0.13.8.tgz
  packages/foreman/nodejs-use-deep-compare-effect/runtime-7.14.6.tgz
  packages/foreman/nodejs-use-deep-compare-effect/scheduler-0.16.1.tgz
  packages/foreman/nodejs-use-deep-compare-effect/use-deep-compare-effect-1.6.1.tgz
  rel-eng/tito.props
Labels: Needs testing, RPM

#6843 Update gem dependencies of Katello
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#6839 Update redhat_access to 2.9.1
  packages/katello/rubygem-redhat_access/redhat_access-2.2.19.gem
  packages/katello/rubygem-redhat_access/redhat_access-2.9.1.gem
  packages/katello/rubygem-redhat_access/rubygem-redhat_access.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6845 Update redhat_access to 2.9.1
  packages/katello/rubygem-redhat_access/redhat_access-2.2.19.gem
  packages/katello/rubygem-redhat_access/redhat_access-2.9.1.gem
  packages/katello/rubygem-redhat_access/rubygem-redhat_access.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6846 Update rubygem-foreman_maintain to 0.8.3
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.2.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.3.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM

#6847 Update rubygem-foreman_maintain to 0.8.3
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.2.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.3.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6848 Update rubygem-foreman_maintain to 0.8.3
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.2.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.3.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM, Stable branch

#6840 Update katello to user pulpcore 3.14, part 1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/rubygem-pulp_ansible_client/pulp_ansible_client-0.7.3.gem
  packages/katello/rubygem-pulp_ansible_client/pulp_ansible_client-0.8.0.gem
  packages/katello/rubygem-pulp_ansible_client/rubygem-pulp_ansible_client.spec
  packages/katello/rubygem-pulp_certguard_client/pulp_certguard_client-1.0.3.gem
  packages/katello/rubygem-pulp_certguard_client/pulp_certguard_client-1.4.0.gem
  packages/katello/rubygem-pulp_certguard_client/rubygem-pulp_certguard_client.spec
  packages/katello/rubygem-pulp_container_client/pulp_container_client-2.4.0.gem
  packages/katello/rubygem-pulp_container_client/pulp_container_client-2.7.0.gem
  packages/katello/rubygem-pulp_container_client/rubygem-pulp_container_client.spec
  packages/katello/rubygem-pulp_deb_client/pulp_deb_client-2.11.1.gem
  packages/katello/rubygem-pulp_deb_client/pulp_deb_client-2.13.0.gem
  packages/katello/rubygem-pulp_deb_client/rubygem-pulp_deb_client.spec
  packages/katello/rubygem-pulp_file_client/pulp_file_client-1.6.1.gem
  packages/katello/rubygem-pulp_file_client/pulp_file_client-1.8.1.gem
  packages/katello/rubygem-pulp_file_client/rubygem-pulp_file_client.spec
  packages/katello/rubygem-pulp_python_client/pulp_python_client-3.2.0.gem
  packages/katello/rubygem-pulp_python_client/pulp_python_client-3.4.0.gem
  packages/katello/rubygem-pulp_python_client/rubygem-pulp_python_client.spec
  packages/katello/rubygem-pulp_rpm_client/pulp_rpm_client-3.10.0.gem
  packages/katello/rubygem-pulp_rpm_client/pulp_rpm_client-3.13.3.gem
  packages/katello/rubygem-pulp_rpm_client/rubygem-pulp_rpm_client.spec
  packages/katello/rubygem-pulpcore_client/pulpcore_client-3.11.0.gem
  packages/katello/rubygem-pulpcore_client/pulpcore_client-3.14.1.gem
  packages/katello/rubygem-pulpcore_client/rubygem-pulpcore_client.spec
Labels: Needs testing, RPM

#6850 update Katello dependencies for Pulpcore 3.14
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#6853 Update rubygem-foreman_maintain to 0.8.4
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.3.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.4.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM

#6854 Update rubygem-foreman_maintain to 0.8.5
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.4.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.5.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#6851 Bump rubygem-addressable to 2.8.0-1
  packages/foreman/rubygem-addressable/addressable-2.6.0.gem
  packages/foreman/rubygem-addressable/addressable-2.8.0.gem
  packages/foreman/rubygem-addressable/rubygem-addressable.spec
Labels: Needs testing, RPM

#6857 Update rubygem-smart_proxy_remote_execution_ssh to 0.3.2
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.3.1.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.3.2.gem
Labels: Needs testing, RPM, Stable branch

#6859 Update rubygem-smart_proxy_remote_execution_ssh to 0.3.2
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.3.1.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.3.2.gem
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6860 Bump rubygem-addressable to 2.8.0-1
  packages/foreman/rubygem-addressable/addressable-2.6.0.gem
  packages/foreman/rubygem-addressable/addressable-2.8.0.gem
  packages/foreman/rubygem-addressable/rubygem-addressable.spec
Labels: Needs testing, RPM, Stable branch

#6861 Do not Obsolete foreman_remote_execution_core from smart_proxy_remote_execution_ssh
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
Labels: Needs testing, RPM

#6862 Do not obsolete ansible_core from smart_proxy_ansible
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
Labels: Needs testing, Not yet reviewed, RPM

#6867 Do not depend on smart_proxy_dynflow_core
  plugins/smart_proxy_dynflow/changelog
  plugins/smart_proxy_dynflow/control
Labels: Needs testing

#6864 Update rubygem-foreman_ansible to 6.3.1
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.3.0.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.3.1.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM, Stable branch

#6866 Do not depend on smart_proxy_dynflow_core
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
Labels: Needs testing, RPM

#6823 Update foreman_ansible to 6.4.0
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: DEB, Needs testing, Not yet reviewed

#6724 Update foreman_remote_execution_core to 1.4.3
  dependencies/bionic/foreman_remote_execution_core/changelog
  dependencies/buster/foreman_remote_execution_core/changelog
  dependencies/focal/foreman_remote_execution_core/changelog
Labels: DEB, Needs testing, Stable branch

#6868 Update hammer_cli_foreman_virt_who_configure to 0.0.8
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/hammer_cli_foreman_virt_who_configure-0.0.7.gem
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/hammer_cli_foreman_virt_who_configure-0.0.8.gem
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/rubygem-hammer_cli_foreman_virt_who_configure.spec
Labels: Needs testing, Not yet reviewed, RPM

#6869 Update hammer_cli_foreman_virt_who_configure to 0.0.8
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/hammer_cli_foreman_virt_who_configure-0.0.7.gem
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/hammer_cli_foreman_virt_who_configure-0.0.8.gem
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/rubygem-hammer_cli_foreman_virt_who_configure.spec
Labels: Needs testing, RPM, Stable branch

#6858 Update smart_proxy_remote_execution_ssh to 0.3.2
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: Needs re-review, Needs testing

#6873 Bump foreman-js
  packages/foreman/nodejs-theforeman-vendor/nodejs-theforeman-vendor.spec
  packages/foreman/nodejs-theforeman-vendor/vendor-8.7.0.tgz
  packages/foreman/nodejs-theforeman-vendor/vendor-8.8.0.tgz
Labels: Needs testing, Not yet reviewed, RPM

#6876 drop foreman-tasks-core
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman-tasks-core/foreman-tasks-core-0.4.0.gem
  packages/plugins/rubygem-foreman-tasks-core/rubygem-foreman-tasks-core.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#6877 Update rubygem-foreman_maintain to 0.8.6
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.5.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.6.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#6871 Update rubygem-foreman_openscap to 4.3.3
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.3.2.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.3.3.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#6872 Update rubygem-foreman_openscap to 4.3.3
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.3.2.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.3.3.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM, Stable branch

#6879 foreman-ansible-modules 2.1.2
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-2.1.1.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-2.1.2.tar.gz
Labels: Needs testing, RPM

#6878 Update rubygem-foreman_maintain to 0.8.6
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.5.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.6.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM, Stable branch

#6881 Katello 4.1.1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.1.0.gem
  packages/katello/rubygem-katello/katello-4.1.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#6884 foreman ansible collection 2.1.2
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-2.1.1.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-2.1.2.tar.gz
Labels: Needs testing, RPM, Stable branch

#6885 Update rubygem-foreman_scc_manager to 1.8.10
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.10.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.9.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, Not yet reviewed, RPM

#6882 Update rubygem-smart_proxy_openscap to 0.9.1
  packages/plugins/rubygem-smart_proxy_openscap/rubygem-smart_proxy_openscap.spec
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.9.0.gem
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.9.1.gem
Labels: Needs testing, Not yet reviewed, RPM

#6883 Update rubygem-smart_proxy_openscap to 0.9.1
  packages/plugins/rubygem-smart_proxy_openscap/rubygem-smart_proxy_openscap.spec
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.9.0.gem
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.9.1.gem
Labels: Needs testing, Not yet reviewed, RPM

#6890 Update rubygem-kafo to 6.4.0
  packages/foreman/rubygem-kafo/kafo-6.3.0.gem
  packages/foreman/rubygem-kafo/kafo-6.4.0.gem
  packages/foreman/rubygem-kafo/rubygem-kafo.spec
Labels: Needs testing, RPM, Stable branch

#6889 Update katello-selinux to 3.5.0.1
  packages/katello/katello-selinux/3.5.0
  packages/katello/katello-selinux/3.5.0.1
  packages/katello/katello-selinux/katello-selinux.spec
Labels: Needs testing, RPM, Stable branch

#6888 Update rubygem-foreman_scc_manager to 1.8.10 (Foreman 2.5)
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.10.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.9.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6892 Release kafo 6.4.0
  dependencies/bionic/kafo/changelog
  dependencies/buster/kafo/changelog
  dependencies/focal/kafo/changelog
Labels: Needs testing, Stable branch

#6894 Refs #32532: Require kafo 6.4+ for foreman-installer
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: Needs testing, RPM, Stable branch

#6895 Refs #32532: Require kafo 6.4+ from foreman-installer
  debian/bionic/foreman-installer/control
  debian/buster/foreman-installer/control
  debian/focal/foreman-installer/control
Labels: Needs testing, Stable branch

#6896 Update rubygem-hammer_cli_foreman_admin to 1.1.0
  packages/plugins/rubygem-hammer_cli_foreman_admin/hammer_cli_foreman_admin-0.0.10.gem
  packages/plugins/rubygem-hammer_cli_foreman_admin/hammer_cli_foreman_admin-1.1.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_admin/rubygem-hammer_cli_foreman_admin.spec
Labels: Needs testing, RPM

#6897 Update foreman-release to 2.5.2
  packages/foreman/foreman-installer/foreman-installer-2.5.1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.5.2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.5.1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.5.2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.5.1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.5.2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.5.1.tar.bz2
  packages/foreman/foreman/foreman-2.5.2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#6865 Update foreman_ansible to 6.3.1
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: DEB, Needs re-review, Needs testing, Stable branch

#6899 Update rubygem-foreman_puppet to 1.0.0.rc.1
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-0.1.0.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.0.rc.1.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing, Not yet reviewed

#6898 Release 2.5.2
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: Needs testing, Stable branch

#6901 Katello 3.18.4
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.18.3.1.gem
  packages/katello/rubygem-katello/katello-3.18.4.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#6880 foreman-ansible-modules 2.1.2
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: Needs testing

#6886 Update rubygem-foreman_scc_manager to 1.8.10 (Foreman 2.3)
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.10.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.9.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6887 Update rubygem-foreman_scc_manager to 1.8.10 (Foreman 2.4)
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.10.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.9.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6893 Update rubygem-foreman_snapshot_management to 2.0.1
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-2.0.0.gem
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-2.0.1.gem
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Needs testing, Not yet reviewed, RPM

#6903 Update rubygem-foreman_snapshot_management to 2.0.1 foreman-2.5
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-2.0.0.gem
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-2.0.1.gem
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Needs testing, Not yet reviewed, RPM

#6906 Add a conflicts on installer-katello with Pulp < 3.14
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: Needs testing, RPM

#6907 Add a conflicts on installer-katello with Katello < 4.1.1
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: Needs testing, RPM

#6902 Correct rubygem-arel obsolete statement
  packages/foreman/tfm/tfm.spec
Labels: Needs testing, Not yet reviewed, RPM

#6912 Update rubygem-foreman_maintain to 0.8.7
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.6.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.7.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#6909 Update foreman_puppet to 1.0.0.rc.1
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: DEB, Needs testing

#6917 Update rubygem-foreman_ansible_core to 4.1.1
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-4.1.0.gem
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-4.1.1.gem
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
Labels: Needs testing, RPM, Stable branch

#6923 add ruby-version and coveralls.yml to gem2rpm ignores
  gem2rpm/scl.spec.erb
Labels: Needs testing, Not yet reviewed, RPM

#6920 Bump rubygem-foreman_rh_cloud to 4.0.24-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.23.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.24.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing

#6921 Bump rubygem-foreman_rh_cloud to 3.0.24-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.23.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.24.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed

#6925 Bump rubygem-foreman_rh_cloud to 4.0.24.1-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.24.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.24.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM

#6919 Update rubygem-foreman_maintain to 0.8.7
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.6.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.7.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM, Stable branch

#6924 Bump rubygem-foreman_rh_cloud to 4.0.24-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.24.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.24.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM

#6926 Bump rubygem-foreman_rh_cloud to 3.0.24.1-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.24.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.24.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM

#6927 Update rubygem-fog-libvirt to 0.9.0
  packages/foreman/rubygem-fog-libvirt/fog-libvirt-0.8.0.gem
  packages/foreman/rubygem-fog-libvirt/fog-libvirt-0.9.0.gem
  packages/foreman/rubygem-fog-libvirt/rubygem-fog-libvirt.spec
Labels: Needs testing, RPM

#6932 Update nightly versions to 3.0
  package_manifest.yaml
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
  rel-eng/releasers.conf
  rel-eng/tito.props
Labels: Needs testing, Not yet reviewed, RPM

#6930 Update rubygem-foreman_fog_proxmox to 0.13.4
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.13.3.gem
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.13.4.gem
  packages/plugins/rubygem-foreman_fog_proxmox/rubygem-foreman_fog_proxmox.spec
Labels: Needs testing, Not yet reviewed, RPM

#6931 Update rubygem-foreman_fog_proxmox to 0.13.4
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.13.3.gem
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.13.4.gem
  packages/plugins/rubygem-foreman_fog_proxmox/rubygem-foreman_fog_proxmox.spec
Labels: Needs testing, Not yet reviewed, RPM

#6904 Update rubygem-foreman_snapshot_management to 2.0.1 foreman-2.4
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-2.0.0.gem
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-2.0.1.gem
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6905 Update rubygem-foreman_snapshot_management to 2.0.1 foreman-2.3
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-2.0.0.gem
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-2.0.1.gem
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Needs testing, Not yet reviewed, RPM

#6934 Update Katello requirement on Foreman
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#6933 Update nightly version to 3.0
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: Needs testing

#6937 build hammer-leapp on el8
  comps/comps-foreman-plugins-el8.xml
  rel-eng/tito.props
Labels: Needs testing, RPM

#6938 Update rubygem-hammer_cli_foreman_openscap to 0.1.13
  packages/plugins/rubygem-hammer_cli_foreman_openscap/hammer_cli_foreman_openscap-0.1.12.gem
  packages/plugins/rubygem-hammer_cli_foreman_openscap/hammer_cli_foreman_openscap-0.1.13.gem
  packages/plugins/rubygem-hammer_cli_foreman_openscap/rubygem-hammer_cli_foreman_openscap.spec
Labels: Needs testing, RPM

#6939 Update rubygem-hammer_cli_foreman_webhooks to 0.0.2
  packages/plugins/rubygem-hammer_cli_foreman_webhooks/hammer_cli_foreman_webhooks-0.0.1.gem
  packages/plugins/rubygem-hammer_cli_foreman_webhooks/hammer_cli_foreman_webhooks-0.0.2.gem
  packages/plugins/rubygem-hammer_cli_foreman_webhooks/rubygem-hammer_cli_foreman_webhooks.spec
Labels: Needs testing, RPM

#6940 build hammer webhooks on el8
  comps/comps-foreman-plugins-el8.xml
  rel-eng/tito.props
Labels: Needs testing, RPM

#6941 Update rubygem-hammer_cli_foreman_admin to 1.1.0
  packages/plugins/rubygem-hammer_cli_foreman_admin/hammer_cli_foreman_admin-0.0.10.gem
  packages/plugins/rubygem-hammer_cli_foreman_admin/hammer_cli_foreman_admin-1.1.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_admin/rubygem-hammer_cli_foreman_admin.spec
Labels: Needs testing, Not yet reviewed, RPM

#6943 Update rubygem-fog-libvirt to 0.9.0
  packages/foreman/rubygem-fog-libvirt/fog-libvirt-0.8.0.gem
  packages/foreman/rubygem-fog-libvirt/fog-libvirt-0.9.0.gem
  packages/foreman/rubygem-fog-libvirt/rubygem-fog-libvirt.spec
Labels: Needs testing

#6949 Update rubygem-kafo_parsers to 1.2.1
  packages/foreman/rubygem-kafo_parsers/kafo_parsers-1.2.0.gem
  packages/foreman/rubygem-kafo_parsers/kafo_parsers-1.2.1.gem
  packages/foreman/rubygem-kafo_parsers/rubygem-kafo_parsers.spec
Labels: Needs testing, Not yet reviewed, RPM

#6950 Release kafo-parsers 1.2.1
  dependencies/bionic/kafo_parsers/changelog
  dependencies/buster/kafo_parsers/changelog
  dependencies/focal/kafo_parsers/changelog
Labels: DEB, Needs testing

#6947 Update rubygem-foreman_fog_proxmox to 0.14.0
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.13.4.gem
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.14.0.gem
  packages/plugins/rubygem-foreman_fog_proxmox/rubygem-foreman_fog_proxmox.spec
Labels: Needs testing, Not yet reviewed

#6946 Update plugin foreman-fog-proxmox to 0.14.0
  plugins/ruby-foreman-fog-proxmox/debian/changelog
  plugins/ruby-foreman-fog-proxmox/debian/gem.list
  plugins/ruby-foreman-fog-proxmox/foreman_fog_proxmox.rb
Labels: Needs testing, Not yet reviewed

#6945 Update plugin foreman-fog-proxmox to 0.14.0
  plugins/ruby-foreman-fog-proxmox/debian/changelog
  plugins/ruby-foreman-fog-proxmox/debian/gem.list
  plugins/ruby-foreman-fog-proxmox/foreman_fog_proxmox.rb
Labels: Needs testing, Not yet reviewed

#6918 Update ruby-foreman-ansible-core to 4.1.1
  dependencies/bionic/foreman_ansible_core/changelog
  dependencies/buster/foreman_ansible_core/changelog
  dependencies/focal/foreman_ansible_core/changelog
Labels: Needs testing, Not yet reviewed, Stable branch

#6953 Update rubygem-foreman_maintain to 0.8.8
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.7.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.8.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#6955 Update rubygem-foreman_maintain to 0.8.9
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.8.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.9.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM

#6954 Update rubygem-foreman_maintain to 0.8.9
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.8.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.9.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6957 Update Katello to 4.1.2
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.1.1.gem
  packages/katello/rubygem-katello/katello-4.1.2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6962 Update Katello to 4.0.2
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.0.1.2.gem
  packages/katello/rubygem-katello/katello-4.0.2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed

#6964 Fixes #33193 - Add logrotate configuration file
  packages/foreman/rubygem-foreman_maintain/foreman_maintain.logrotate
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#6956 Update rubygem-foreman_virt_who_configure to 0.5.7
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.6.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.7.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Needs testing, RPM

#6960 Update rubygem-foreman-tasks-core to 0.3.6
  packages/plugins/rubygem-foreman-tasks-core/foreman-tasks-core-0.3.5.gem
  packages/plugins/rubygem-foreman-tasks-core/foreman-tasks-core-0.3.6.gem
  packages/plugins/rubygem-foreman-tasks-core/rubygem-foreman-tasks-core.spec
Labels: Needs testing, RPM, Stable branch
