Repository theforeman/foreman-packaging, pull requests merged in 2021-01, with the labels that each got.

#6159 Update rubygem-foreman_maintain to 0.7.2
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.1.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.2.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed

#6163 Update rubygem-kafo to 6.2.0
  packages/foreman/rubygem-kafo/kafo-6.1.2.gem
  packages/foreman/rubygem-kafo/kafo-6.2.0.gem
  packages/foreman/rubygem-kafo/rubygem-kafo.spec
Labels: Needs testing, RPM

#6168 Update katello to 3.18.1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.18.0.gem
  packages/katello/rubygem-katello/katello-3.18.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6167 Release rubygem-hammer_cli_katello 0.24.2
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.24.1.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.24.2.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#6172 bump_rpm.sh dependency handling
  bump_rpm.sh
Labels: Needs testing, RPM

#6175 Drop puma-plugin-systemd-doc from comps
  comps/comps-foreman-el8.xml
  comps/comps-foreman-rhel7.xml
Labels: Needs testing, RPM

#6174 Update rubygem-foreman_maintain to 0.7.2
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.1.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.2.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6173 Update rubygem-foreman_maintain to 0.7.2
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.1.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.2.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM, Stable branch

#6162 Update rubygem-foreman_vault to 0.4.0
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.3.0.gem
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.4.0.gem
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
Labels: Needs testing, RPM

#6161 Update rubygem-foreman_openscap to 4.0.5
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.0.4.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.0.5.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#6164 Update katello-selinux to 3.5.1
  packages/katello/katello-selinux/3.5.0
  packages/katello/katello-selinux/3.5.1
  packages/katello/katello-selinux/katello-selinux.spec
Labels: Needs testing, RPM

#6179 Update rubygem-foreman_maintain to 0.7.4
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.2.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.4.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM

#6178 Update rubygem-foreman_vault to 1.0.0
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.4.0.gem
  packages/plugins/rubygem-foreman_vault/foreman_vault-1.0.0.gem
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
Labels: Needs testing, Not yet reviewed, RPM

#6176 Fixes #31598 - Don't recreate AAAA record as A
  packages/katello/katello/hostname-change.rb
Labels: Needs testing, RPM

#6177 Update rubygem-foreman_vault to 0.4.0
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.3.0.gem
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.4.0.gem
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6180 Update rubygem-hammer_cli_foreman_ansible to 0.3.3
  packages/plugins/rubygem-hammer_cli_foreman_ansible/hammer_cli_foreman_ansible-0.3.2.gem
  packages/plugins/rubygem-hammer_cli_foreman_ansible/hammer_cli_foreman_ansible-0.3.3.gem
  packages/plugins/rubygem-hammer_cli_foreman_ansible/rubygem-hammer_cli_foreman_ansible.spec
Labels: Needs testing, Not yet reviewed, RPM

#6181 Update hammer-cli-foreman-ansible to 0.3.3
  dependencies/bionic/hammer_cli_foreman_ansible/changelog
  dependencies/buster/hammer_cli_foreman_ansible/changelog
  dependencies/focal/hammer_cli_foreman_ansible/changelog
Labels: Needs testing, Not yet reviewed

#6186 Bump Katello to 4.0.0-0.2
  packages/katello/katello/katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#6184 Update rubygem-foreman_maintain to 0.7.4
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.2.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.4.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed

#6185 Update rubygem-foreman_maintain to 0.7.4
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.2.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.4.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed

#6193 Update foreman to 2.3.2
  packages/foreman/foreman-installer/foreman-installer-2.3.1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.3.2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.3.1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.3.2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.3.1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.3.2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.3.1.tar.bz2
  packages/foreman/foreman/foreman-2.3.2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing

#6192 Release 2.3.2
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: Needs testing

#6197 Add rubygem-qpid_messaging
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-qpid_messaging/qpid_messaging-1.39.0.gem
  packages/katello/rubygem-qpid_messaging/rubygem-qpid_messaging.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#6202 Update rubygem-fog-ovirt to 2.0.1
  packages/foreman/rubygem-fog-ovirt/fog-ovirt-2.0.0.gem
  packages/foreman/rubygem-fog-ovirt/fog-ovirt-2.0.1.gem
  packages/foreman/rubygem-fog-ovirt/rubygem-fog-ovirt.spec
Labels: Needs testing, RPM

#6189 Update foreman_remote_execution to 4.2.2
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing, Not yet reviewed

#6191 Update rubygem-foreman_ansible to 6.1.0
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.0.1.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.1.0.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, Not yet reviewed

#6187 Update foreman_ansible to 6.1.0
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: DEB, Needs testing, Not yet reviewed

#6194 Update rubygem-foreman_ansible_core to 4.0.0
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-3.0.4.gem
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-4.0.0.gem
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
Labels: Needs testing, Not yet reviewed

#6195 Update rubygem-foreman_ansible_core to 4.0.0
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-3.0.4.gem
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-4.0.0.gem
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
Labels: Needs testing, Not yet reviewed

#6148 Update rubygem-smart_proxy_discovery_image to 1.3.2
  packages/plugins/rubygem-smart_proxy_discovery_image/rubygem-smart_proxy_discovery_image.spec
  packages/plugins/rubygem-smart_proxy_discovery_image/smart_proxy_discovery_image-1.3.1.gem
  packages/plugins/rubygem-smart_proxy_discovery_image/smart_proxy_discovery_image-1.3.2.gem
Labels: Needs testing, RPM

#6209 Update rubygem-smart_proxy_discovery_image to 1.3.2 (CP 2.3)
  packages/plugins/rubygem-smart_proxy_discovery_image/rubygem-smart_proxy_discovery_image.spec
  packages/plugins/rubygem-smart_proxy_discovery_image/smart_proxy_discovery_image-1.3.1.gem
  packages/plugins/rubygem-smart_proxy_discovery_image/smart_proxy_discovery_image-1.3.2.gem
Labels: Needs testing

#6210 Update puppet-agent-oauth to 0.5.5
  packages/foreman/puppet-agent-oauth/oauth-0.5.1.gem
  packages/foreman/puppet-agent-oauth/oauth-0.5.5.gem
  packages/foreman/puppet-agent-oauth/puppet-agent-oauth.spec
Labels: Needs testing

#6204 Update rubygem-foreman_kubevirt to 0.1.9
  packages/plugins/rubygem-foreman_kubevirt/foreman_kubevirt-0.1.8.gem
  packages/plugins/rubygem-foreman_kubevirt/foreman_kubevirt-0.1.9.gem
  packages/plugins/rubygem-foreman_kubevirt/rubygem-foreman_kubevirt.spec
Labels: Needs testing, RPM

#6203 Update rubygem-fog-libvirt to 0.8.0
  packages/foreman/rubygem-fog-libvirt/fog-libvirt-0.7.0.gem
  packages/foreman/rubygem-fog-libvirt/fog-libvirt-0.8.0.gem
  packages/foreman/rubygem-fog-libvirt/rubygem-fog-libvirt.spec
Labels: Needs testing, RPM

#6216 Update rubygem-foreman_ansible to 6.1.1
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.1.0.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.1.1.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#6206 Update rubygem-foreman_ansible to 6.1.1
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.1.0.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-6.1.1.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#6211 Update rubygem-kafo to 6.2.1
  packages/foreman/rubygem-kafo/kafo-6.2.0.gem
  packages/foreman/rubygem-kafo/kafo-6.2.1.gem
  packages/foreman/rubygem-kafo/rubygem-kafo.spec
Labels: Needs testing, RPM

#6215 Update foreman_ansible to 6.1.1
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing

#6207 Update foreman_remote_execution to 4.2.2
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB, Needs testing, Stable branch

#6208 Update rubygem-foreman_remote_execution to 4.2.2
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-4.2.1.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-4.2.2.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM, Stable branch

#6205 Update foreman_ansible to 6.1.0
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: DEB, Needs testing, Stable branch

#6223 Update rubygem-hammer_cli_foreman to 2.3.1
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-2.3.0.gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-2.3.1.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM, Stable branch

#6224 Updated hammer_cli_foreman to 2.3.1
  dependencies/bionic/hammer_cli_foreman/changelog
  dependencies/buster/hammer_cli_foreman/changelog
  dependencies/focal/hammer_cli_foreman/changelog
Labels: Needs testing, Stable branch

#6196 Bump openscap_parser to 1.0.2
  packages/plugins/rubygem-openscap_parser/openscap_parser-1.0.0.gem
  packages/plugins/rubygem-openscap_parser/openscap_parser-1.0.2.gem
  packages/plugins/rubygem-openscap_parser/rubygem-openscap_parser.spec
Labels: Needs testing, RPM

#6190 Update rubygem-foreman_vault to 1.0.0
  packages/plugins/rubygem-foreman_vault/foreman_vault-0.3.0.gem
  packages/plugins/rubygem-foreman_vault/foreman_vault-1.0.0.gem
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
Labels: Needs testing, RPM, Stable branch

#6198 Bump version to 0.5.0
  packages/plugins/rubygem-foreman_acd/foreman_acd-0.3.0.gem
  packages/plugins/rubygem-foreman_acd/foreman_acd-0.5.0.gem
  packages/plugins/rubygem-foreman_acd/rubygem-foreman_acd.spec
Labels: Needs testing, RPM

#6130 Update rubygem-foreman_scc_manager to 1.8.6 (foreman-2.3)
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.5.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.6.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM, Stable branch

#6131 Update rubygem-foreman_scc_manager to 1.8.6 (foreman-2.2)
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.5.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.6.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM, Stable branch

#6132 Update rubygem-foreman_scc_manager to 1.8.6 (foreman-2.1)
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.5.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.6.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM, Stable branch

#6217 Added foreman_webhooks 0.0.1 (RPM)
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-0.0.1.gem
  packages/plugins/rubygem-foreman_webhooks/rubygem-foreman_webhooks.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#6150 Update rubygem-net-ldap to 0.17.0
  packages/foreman/rubygem-net-ldap/net-ldap-0.16.1.gem
  packages/foreman/rubygem-net-ldap/net-ldap-0.17.0.gem
  packages/foreman/rubygem-net-ldap/rubygem-net-ldap.spec
Labels: Needs testing, RPM

#6170 Update rubygem-foreman-tasks to 3.0.3
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-3.0.2.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-3.0.3.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#6171 Update foreman-tasks to 3.0.3
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing

#6225 Update rubygem-foreman-tasks to 3.0.3
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-3.0.2.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-3.0.3.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM, Stable branch

#6229 Add jsoncpp
  package_manifest.yaml
  packages/katello/jsoncpp/jsoncpp-1.8.4.tar.gz
  packages/katello/jsoncpp/jsoncpp.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#6227 Update foreman_wreckingball to 3.4.1
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-3.4.0.gem
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-3.4.1.gem
  packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
Labels: Needs testing, RPM

#6231 Add qpid-proton 0.32.0
  .rpmlintrc
  package_manifest.yaml
  packages/katello/qpid-proton/0001-Temporary-patch-to-enable-installed-examples-to-buil.patch
  packages/katello/qpid-proton/licenses.xml
  packages/katello/qpid-proton/proton.patch
  packages/katello/qpid-proton/qpid-proton-0.32.0.tar.gz
  packages/katello/qpid-proton/qpid-proton.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#6137 Add rubygem-hammer_cli_foreman_scc_manager package
  comps/comps-katello-el8.xml
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/hammer_cli_foreman_scc_manager-0.1.0.gem
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/rubygem-hammer_cli_foreman_scc_manager.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#6060 introduce a shared foreman-plugin.mk that can be used to build plugins
  debian/bionic/foreman/foreman-plugin.mk
  debian/bionic/foreman/foreman.install
  debian/buster/foreman/foreman-plugin.mk
  debian/buster/foreman/foreman.install
Labels: DEB, Needs testing

#6232 Update foreman_wreckingball to 3.4.1
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-3.4.0.gem
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-3.4.1.gem
  packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
Labels: Needs testing, RPM

#6233 Update foreman_wreckingball to 3.4.1
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-3.4.0.gem
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-3.4.1.gem
  packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
Labels: Needs testing, RPM, Stable branch

#6234 Build qpid-cpp for EL8
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/qpid-cpp/amq.patch
  packages/katello/qpid-cpp/licenses.xml
  packages/katello/qpid-cpp/qpid-cpp-1.39.0.tar.gz
  packages/katello/qpid-cpp/qpid-cpp.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#6221 Add rubygem-qpid_proton gem package
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-qpid_proton/qpid_proton-0.32.0.gem
  packages/katello/rubygem-qpid_proton/rubygem-qpid_proton.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#6236 Revert "Add rubygem-qpid_messaging"
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-qpid_messaging/qpid_messaging-1.39.0.gem
  packages/katello/rubygem-qpid_messaging/rubygem-qpid_messaging.spec
  rel-eng/tito.props
Labels: Needs testing, RPM
