Repository theforeman/foreman-packaging, pull requests merged in 2021-09, with the labels that each got.

#7062 don't force rake and minitest on bionic
  debian/bionic/foreman/rules
Labels: Needs testing

#7063 make bundle packaging more explicit
  debian/bionic/foreman/rules
  debian/buster/foreman/rules
  debian/focal/foreman/rules
Labels: Needs testing, DEB

#7064 don't ship JS and CSS maps in the package
  debian/bionic/foreman/rules
  debian/buster/foreman/rules
  debian/focal/foreman/rules
Labels: Needs testing, DEB

#7065 Update katello package dependencies
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#7066 Update rubygem-smart_proxy_pulp to 3.2.0
  packages/plugins/rubygem-smart_proxy_pulp/rubygem-smart_proxy_pulp.spec
  packages/plugins/rubygem-smart_proxy_pulp/smart_proxy_pulp-3.1.0.gem
  packages/plugins/rubygem-smart_proxy_pulp/smart_proxy_pulp-3.2.0.gem
Labels: Needs testing, RPM

#7067 Update katello to 4.2.0.1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.2.0.1.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#7058 Update rubygem-foreman_webhooks to 3.0.0
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-2.0.0.gem
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-3.0.0.gem
  packages/plugins/rubygem-foreman_webhooks/rubygem-foreman_webhooks.spec
Labels: Needs testing, Not yet reviewed, RPM

#7054 Update rubygem-foreman_remote_execution to 4.5.6
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-4.5.5.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-4.5.6.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, Not yet reviewed, RPM

#7050 Update rubygem-foreman-tasks to 4.1.5
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-4.1.4.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-4.1.5.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7060 Update rubygem-foreman-tasks to 5.1.0
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-5.0.0.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-5.1.0.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, Not yet reviewed

#7059 Update Webhooks to 3.0.0
  plugins/ruby-foreman-webhooks/debian/changelog
  plugins/ruby-foreman-webhooks/debian/gem.list
  plugins/ruby-foreman-webhooks/foreman_webhooks.rb
Labels: Needs testing, Not yet reviewed

#7077 make deb compare packages more robust
  scripts/compare_deb_repo.py
Labels: Needs testing, DEB

#7076 drop foreman-docker
  plugins/ruby-foreman-docker/debian/changelog
  plugins/ruby-foreman-docker/debian/compat
  plugins/ruby-foreman-docker/debian/control
  plugins/ruby-foreman-docker/debian/copyright
  plugins/ruby-foreman-docker/debian/gem.list
  plugins/ruby-foreman-docker/debian/install
  plugins/ruby-foreman-docker/debian/postinst
  plugins/ruby-foreman-docker/debian/rules
  plugins/ruby-foreman-docker/debian/source/format
  plugins/ruby-foreman-docker/foreman_docker.rb
Labels: Needs testing, DEB

#7078 only report latest version from repo when comparing
  scripts/compare_deb_repo.py
Labels: Needs testing, DEB

#7079 document how to remove packages from freight
  README.md
Labels: Needs testing, DEB

#7080 Update rubygem-foreman_maintain to 0.8.14
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.13.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.14.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#7081 Update foreman-release to 3.0.0
  packages/foreman/foreman-installer/foreman-installer-3.0.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.0.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.0.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.0.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.0.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.0.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.0.0-rc2.tar.bz2
  packages/foreman/foreman/foreman-3.0.0.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#7069 Update rubygem-foreman_webhooks to 3.0.0 CP 3.0
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-2.0.0.gem
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-3.0.0.gem
  packages/plugins/rubygem-foreman_webhooks/rubygem-foreman_webhooks.spec
Labels: Needs testing, Not yet reviewed

#7070 Update Webhooks to 3.0.0 CP 3.0
  plugins/ruby-foreman-webhooks/debian/changelog
  plugins/ruby-foreman-webhooks/debian/gem.list
  plugins/ruby-foreman-webhooks/foreman_webhooks.rb
Labels: Needs testing, Not yet reviewed

#7074 Update rubygem-foreman-tasks to 5.1.0
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-5.0.0.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-5.1.0.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7083 Remove dangling katello 4.2.0 rc1 gem
  packages/katello/rubygem-katello/katello-4.2.0.rc1.gem
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7072 Update rubygem-foreman_webhooks to 2.0.1 CP 2.5 (RPM)
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-2.0.0.gem
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-2.0.1.gem
  packages/plugins/rubygem-foreman_webhooks/rubygem-foreman_webhooks.spec
Labels: Needs testing, RPM, Stable branch

#7082 Release 3.0.0
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: Needs testing, DEB, Stable branch

#7084 Update rubygem-foreman_maintain to 0.8.15
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.14.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.15.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#7085 Update rubygem-foreman_maintain to 0.8.16
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.15.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.16.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#7088 Build rubygem-qpid_proton 0.35.0
  packages/katello/rubygem-qpid_proton/qpid_proton-0.34.0.gem
  packages/katello/rubygem-qpid_proton/qpid_proton-0.35.0.gem
  packages/katello/rubygem-qpid_proton/rubygem-qpid_proton.spec
Labels: Needs testing, RPM

#7089 Build rubygem-qpid_proton 0.35.0
  packages/katello/rubygem-qpid_proton/qpid_proton-0.34.0.gem
  packages/katello/rubygem-qpid_proton/qpid_proton-0.35.0.gem
  packages/katello/rubygem-qpid_proton/rubygem-qpid_proton.spec
Labels: Needs testing, Not yet reviewed

#7086 Update rubygem-foreman_puppet to 1.0.0
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.0.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.0.rc.2.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing, RPM

#7087 Update rubygem-foreman_puppet to 1.0.0
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: Needs testing

#7090 Build rubygem-qpid_proton 0.35.0
  packages/katello/rubygem-qpid_proton/qpid_proton-0.34.0.gem
  packages/katello/rubygem-qpid_proton/qpid_proton-0.35.0.gem
  packages/katello/rubygem-qpid_proton/rubygem-qpid_proton.spec
Labels: Needs testing, Not yet reviewed

#7093 Rebuild rubygem-qpid_proton against Ruby 2.5 for Foreman 2.4
  packages/katello/rubygem-qpid_proton/qpid_proton-0.34.0.gem
  packages/katello/rubygem-qpid_proton/qpid_proton-0.35.0.gem
  packages/katello/rubygem-qpid_proton/rubygem-qpid_proton.spec
Labels: Needs testing, RPM, Stable branch

#7091 Update rubygem-foreman_puppet to 1.0.0
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.0.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.0.rc.2.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing, Not yet reviewed

#7092 Update rubygem-foreman_puppet to 1.0.0
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: Needs testing, Not yet reviewed

#7094 Update rubygem-foreman_puppet to 1.0.1
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.0.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.1.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing, RPM

#7096 Bump rubygem-foreman-puppet to 1.0.1
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: Needs testing, DEB

#7095 Update rubygem-foreman_puppet to 1.0.1
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.0.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.1.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing, RPM, Stable branch

#7097 Update Katello to 3.18.5
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.18.4.gem
  packages/katello/rubygem-katello/katello-3.18.5.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#7100 Update rubygem-pulp_deb_client to 2.13.1
  packages/katello/rubygem-pulp_deb_client/pulp_deb_client-2.13.0.gem
  packages/katello/rubygem-pulp_deb_client/pulp_deb_client-2.13.1.gem
  packages/katello/rubygem-pulp_deb_client/rubygem-pulp_deb_client.spec
Labels: Needs testing, RPM

#7101 Update rubygem-foreman_virt_who_configure to 0.5.7
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.6.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.7.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Needs testing, RPM, Stable branch

#7119 Update rubygem-foreman_maintain to 0.8.17
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.16.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.17.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing

#7122 Update katello-host-tools to 3.5.6
  packages/client/katello-host-tools/katello-host-tools-3.5.5.tar.gz
  packages/client/katello-host-tools/katello-host-tools-3.5.6.tar.gz
  packages/client/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#7110 Update rubygem-foreman_discovery to 18.0.0
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-17.0.0.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-18.0.0.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, RPM

#7125 Update rubygem-foreman_discovery to 18.0.0
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-17.0.0.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-18.0.0.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7121 Update Katello to 4.0.3
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.0.2.1.gem
  packages/katello/rubygem-katello/katello-4.0.3.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#7128 Update Katello-repos to 4.0.3
  packages/katello/katello-repos/katello-repos.spec
Labels: Needs testing, RPM, Stable branch

#7126 Update rubygem-foreman_maintain to 0.8.17
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.16.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.17.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM, Stable branch

#7129 Update katello to 4.2.0.1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.2.0.1.rc2.gem
  packages/katello/rubygem-katello/katello-4.2.0.1.rc3.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#7108 Update rubygem-foreman_puppet to 1.0.3
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.1.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.3.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: RPM

#7133 Release katello-client-bootstrap 1.7.7
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.6.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.7.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap.spec
Labels: Needs testing, RPM

#7134 Bump bootstrap-select dep for katello
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#7132 Stop calling gem compare in bump_rpm.sh
  README.md
  bump_rpm.sh
Labels: Needs testing, RPM

#7130 Update rubygem-foreman_bootdisk to 18.0.0
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-17.1.0.gem
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-18.0.0.gem
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
Labels: Needs testing, RPM

#7138 Update katello to 4.1.4
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.1.3.gem
  packages/katello/rubygem-katello/katello-4.1.4.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#7120 Bump hammer-cli-katello to 1.1.3
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.1.2.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.1.3.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7140 Fixes #33580 - Suggest new --puppet-server-foreman-url with hostname …
  packages/katello/katello/hostname-change.rb
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM
