Repository theforeman/foreman-packaging, pull requests merged in 2021-11, with the labels that each got.

#7213 Update rubygem-foreman_statistics to 2.0.0
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-1.2.0.gem
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-2.0.0.gem
  packages/plugins/rubygem-foreman_statistics/rubygem-foreman_statistics.spec
Labels: Needs testing, RPM

#7215 Update rubygem-foreman_openscap to 5.1.0
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-5.0.0.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-5.1.0.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#7214 Update ruby-foreman-statistics to 2.0.0
  plugins/ruby-foreman-puppet/debian/control
  plugins/ruby-foreman-statistics/debian/changelog
  plugins/ruby-foreman-statistics/debian/gem.list
  plugins/ruby-foreman-statistics/foreman_statistics.rb
Labels: Needs testing

#7194 Update rubygem-smart_proxy_host_reports to 0.0.5
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-smart_proxy_host_reports/smart_proxy_host_reports-0.0.3.gem
  packages/plugins/rubygem-smart_proxy_reports/rubygem-smart_proxy_reports.spec
  packages/plugins/rubygem-smart_proxy_reports/smart_proxy_reports-0.0.5.gem
  rel-eng/tito.props
Labels: Needs testing, RPM

#7211 Add source_location in build_vars.sh for nightly packages
  debian/buster/foreman-installer/build_vars.sh
  debian/buster/foreman-proxy/build_vars.sh
  debian/buster/foreman/build_vars.sh
  debian/focal/foreman-installer/build_vars.sh
  debian/focal/foreman-proxy/build_vars.sh
  debian/focal/foreman/build_vars.sh
  dependencies/buster/hammer_cli/build_vars.sh
  dependencies/buster/hammer_cli_foreman/build_vars.sh
  dependencies/focal/hammer_cli/build_vars.sh
  dependencies/focal/hammer_cli_foreman/build_vars.sh
Labels: Needs testing, DEB

#7201 Bump tracer package to 0.7.8
  packages/client/tracer/tracer-0.7.3.tar.gz
  packages/client/tracer/tracer-0.7.8.tar.gz
  packages/client/tracer/tracer.spec
Labels: Needs testing, RPM

#7212 Bump Hammer Foreman Azure_RM to 0.2.2
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/hammer_cli_foreman_azure_rm-0.2.1.gem
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/hammer_cli_foreman_azure_rm-0.2.2.gem
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/rubygem-hammer_cli_foreman_azure_rm.spec
Labels: Needs testing, RPM

#7219 Updated hammer_cli to 3.0.1
  dependencies/buster/hammer_cli/changelog
  dependencies/focal/hammer_cli/changelog
Labels: Needs testing

#7220 Updated hammer_cli to 3.0.1
  dependencies/bionic/hammer_cli/changelog
  dependencies/buster/hammer_cli/changelog
  dependencies/focal/hammer_cli/changelog
Labels: Needs testing

#7218 Update rubygem-hammer_cli to 3.0.1
  packages/foreman/rubygem-hammer_cli/hammer_cli-3.0.0.gem
  packages/foreman/rubygem-hammer_cli/hammer_cli-3.0.1.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
Labels: Needs testing

#7216 Restart Foreman services after package upgrade on Debian
  debian/buster/foreman/changelog
  debian/buster/foreman/rules
  debian/focal/foreman/changelog
  debian/focal/foreman/rules
Labels: Needs testing, DEB

#7222 Update rubygem-hammer_cli_foreman_kubevirt to 0.1.5
  packages/plugins/rubygem-hammer_cli_foreman_kubevirt/hammer_cli_foreman_kubevirt-0.1.4.gem
  packages/plugins/rubygem-hammer_cli_foreman_kubevirt/hammer_cli_foreman_kubevirt-0.1.5.gem
  packages/plugins/rubygem-hammer_cli_foreman_kubevirt/rubygem-hammer_cli_foreman_kubevirt.spec
Labels: Needs testing

#7223 Do not restart Dynflow services on package upgrade, let systemd handl…
  debian/buster/foreman/changelog
  debian/buster/foreman/rules
  debian/focal/foreman/changelog
  debian/focal/foreman/rules
Labels: Needs testing

#7228 Update katello to 4.2.1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.2.0.1.gem
  packages/katello/rubygem-katello/katello-4.2.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing

#7225 foreman-puppet: don't run db:migrate in postinst
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/postinst
Labels: Needs testing, DEB

#7237 foreman-tasks: use foreman-plugin.postinst-lib
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/control
  plugins/ruby-foreman-tasks/debian/postinst
Labels: Needs testing

#7236 foreman-remote-execution: use foreman-plugin.postinst-lib
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/control
  plugins/ruby-foreman-remote-execution/debian/postinst
Labels: Needs testing, DEB

#7235 foreman-discovery: use foreman-plugin.postinst-lib
  plugins/ruby-foreman-discovery/debian/changelog
  plugins/ruby-foreman-discovery/debian/control
  plugins/ruby-foreman-discovery/debian/postinst
Labels: Needs testing, DEB

#7231 foreman-bootdisk: use foreman-plugin.postinst-lib
  plugins/ruby-foreman-bootdisk/debian/changelog
  plugins/ruby-foreman-bootdisk/debian/control
  plugins/ruby-foreman-bootdisk/debian/postinst
Labels: Needs testing, DEB

#7233 foreman-chef: use foreman-plugin.postinst-lib
  plugins/ruby-foreman-chef/debian/changelog
  plugins/ruby-foreman-chef/debian/control
  plugins/ruby-foreman-chef/debian/postinst
Labels: Needs testing, DEB

#7230 foreman-azure-rm: use foreman-plugin.postinst-lib
  plugins/ruby-foreman-azure-rm/debian/changelog
  plugins/ruby-foreman-azure-rm/debian/control
  plugins/ruby-foreman-azure-rm/debian/postinst
Labels: Needs testing, DEB

#7229 foreman-ansible: use foreman-plugin.postinst-lib
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/control
  plugins/ruby-foreman-ansible/debian/postinst
Labels: Needs testing, DEB

#7244 foreman-monitoring: use foreman-plugin.postinst-lib
  plugins/ruby-foreman-monitoring/debian/changelog
  plugins/ruby-foreman-monitoring/debian/control
  plugins/ruby-foreman-monitoring/debian/postinst
Labels: Needs testing, DEB

#7239 foreman-templates: use foreman-plugin.postins-lib
  plugins/ruby-foreman-templates/debian/changelog
  plugins/ruby-foreman-templates/debian/control
  plugins/ruby-foreman-templates/debian/postinst
Labels: Needs testing, DEB

#7241 foreman-statistics: use foreman-plugin.postinst-lib
  plugins/ruby-foreman-statistics/debian/changelog
  plugins/ruby-foreman-statistics/debian/control
  plugins/ruby-foreman-statistics/debian/postinst
Labels: Needs testing, DEB

#7242 foreman-salt: use foreman-plugin.postinst-lib
  plugins/ruby-foreman-salt/debian/changelog
  plugins/ruby-foreman-salt/debian/control
  plugins/ruby-foreman-salt/debian/postinst
Labels: Needs testing, DEB

#7245 foreman-setup: use foreman-plugin.postinst-lib
  plugins/ruby-foreman-setup/debian/changelog
  plugins/ruby-foreman-setup/debian/control
  plugins/ruby-foreman-setup/debian/postinst
Labels: Needs testing, DEB

#7247 foreman-fog-proxmox: use foreman-plugin.postinst-lib
  plugins/ruby-foreman-fog-proxmox/debian/changelog
  plugins/ruby-foreman-fog-proxmox/debian/control
  plugins/ruby-foreman-fog-proxmox/debian/postinst
Labels: Needs testing, DEB

#7250 puppetdb-foreman: use foreman-plugin.postinst-lib
  plugins/ruby-puppetdb-foreman/debian/changelog
  plugins/ruby-puppetdb-foreman/debian/control
  plugins/ruby-puppetdb-foreman/debian/postinst
Labels: Needs testing, DEB

#7248 foreman-expire-hosts: use foreman-plugin.postinst-lib
  plugins/ruby-foreman-expire-hosts/debian/changelog
  plugins/ruby-foreman-expire-hosts/debian/control
  plugins/ruby-foreman-expire-hosts/debian/postinst
Labels: Needs testing, DEB

#7259 Update rubygem-foreman_maintain to 0.9.2
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.9.1.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.9.2.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#7227 Bump rubygem-foreman_rh_cloud to 5.0.28-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-4.0.26.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-5.0.28.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM

#7255 Update rubygem-hammer_cli_foreman_puppet to 0.0.4
  packages/plugins/rubygem-hammer_cli_foreman_puppet/hammer_cli_foreman_puppet-0.0.3.gem
  packages/plugins/rubygem-hammer_cli_foreman_puppet/hammer_cli_foreman_puppet-0.0.4.gem
  packages/plugins/rubygem-hammer_cli_foreman_puppet/rubygem-hammer_cli_foreman_puppet.spec
Labels: Needs testing

#7256 Updated hammer-cli-foreman-puppet to 0.0.4
  dependencies/buster/hammer_cli_foreman_puppet/changelog
  dependencies/focal/hammer_cli_foreman_puppet/changelog
Labels: Needs testing

#7171 Bump discovery to 18.0.4
  plugins/ruby-foreman-discovery/debian/changelog
  plugins/ruby-foreman-discovery/debian/gem.list
  plugins/ruby-foreman-discovery/foreman_discovery.rb
Labels: Needs testing, DEB

#7257 Swap wget for curl dependency on foreman-proxy
  packages/foreman/foreman-proxy/foreman-proxy.spec
Labels: Needs testing

#7258 Swap wget for curl dependency on foreman-proxy
  debian/buster/foreman-proxy/control
  debian/focal/foreman-proxy/control
Labels: Needs testing

#7275 Update foreman-packaging deb/develop to ensure nightlies build
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: Needs testing, Not yet reviewed, DEB

#7274 Update foreman-packaging rpm/develop to ensure nightlies build
  package_manifest.yaml
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
  rel-eng/releasers.conf
  rel-eng/tito.props
Labels: Needs testing, Not yet reviewed, RPM

#7273 Prepare build systems for 3.1 release
  mock/el7-nonscl.cfg
  mock/el7-scl.cfg
  mock/el8.cfg
  package_manifest.yaml
  packages/foreman/foreman-release/foreman.gpg
  rel-eng/releasers.conf
  rel-eng/tito.props
  repoclosure/yum.conf
Labels: Needs testing, RPM, Stable branch

#7278 Update rubygem-foreman_puppet to 1.0.5
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.4.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-1.0.5.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing, RPM, Stable branch

#7280 Update rubygem-foreman_puppet to 1.0.5
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: Needs testing, Stable branch

#7281 Update foreman-release to 3.1.0
  packages/foreman/foreman-installer/foreman-installer-3.1.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.1.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.1.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.1.0-rc1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#7282 Release 3.1.0-rc1
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: Needs testing, DEB, Stable branch

#7286 don't use nightly releasers for 3.1
  package_manifest.yaml
Labels: Needs testing, RPM, Stable branch

#7285 Removing EL6 and FC29
  rel-eng/tito.props
Labels: Needs testing, RPM, Stable branch

#7287 drop rhel6 and f29 from manifest
  package_manifest.yaml
Labels: Needs testing, RPM, Stable branch

#7270 Bump Foreman Azure_rm to 2.2.6
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.2.5.gem
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.2.6.gem
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
Labels: Needs testing, RPM, Stable branch

#7271 Release ansible-collection-theforeman-foreman 3.0.0
  plugins/ansible-collection-theforeman-foreman/debian/changelog
  plugins/ansible-collection-theforeman-foreman/debian/control
Labels: Needs testing, DEB

#7272 Release ansible-collection-theforeman-foreman 3.0.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-2.2.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.0.0.tar.gz
Labels: Needs testing

#7295 Update katello to 4.3.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.3.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#7283 Bump virt-who-configure to 0.5.8
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.7.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.8.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Needs testing, RPM, Stable branch

#7294 Release ansible-collection-theforeman-foreman 3.0.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-2.2.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.0.0.tar.gz
Labels: Needs testing, RPM, Stable branch

#7296 Katello 4.4 version bump for nightly
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#7284 Update rubygem-hammer_cli_foreman_virt_who_configure to 0.0.9
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/hammer_cli_foreman_virt_who_configure-0.0.8.gem
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/hammer_cli_foreman_virt_who_configure-0.0.9.gem
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/rubygem-hammer_cli_foreman_virt_who_configure.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7290 Update rubygem-smart_proxy_acd to 0.3.0
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-smart_proxy_acd/rubygem-smart_proxy_acd.spec
  packages/plugins/rubygem-smart_proxy_acd/smart_proxy_acd-0.2.0.gem
  packages/plugins/rubygem-smart_proxy_acd/smart_proxy_acd-0.3.0.gem
  packages/plugins/rubygem-smart_proxy_acd_core/rubygem-smart_proxy_acd_core.spec
  packages/plugins/rubygem-smart_proxy_acd_core/smart_proxy_acd_core-0.2.0.gem
  rel-eng/tito.props
Labels: Needs testing, RPM

#7293 Release ansible-collection-theforeman-foreman 3.0.0
  plugins/ansible-collection-theforeman-foreman/debian/changelog
  plugins/ansible-collection-theforeman-foreman/debian/control
Labels: Needs testing

#7303 Drop el8-devel from repoclosure
  package_manifest.yaml
  repoclosure/yum.conf
Labels: Needs testing, RPM

#7304 exclude ruby 3 packages from repoclosure
  repoclosure/yum.conf
Labels: Needs testing, Not yet reviewed

#7297 Update Katello and Katello repos to use Pulpcore 3.16
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#7305 Release katello-certs-tools 2.8.2
  packages/foreman/katello-certs-tools/katello-certs-tools-2.8.1.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools-2.8.2.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools.spec
Labels: Needs testing, RPM

#7306 Release katello-certs-tools 2.8.2
  packages/foreman/katello-certs-tools/katello-certs-tools-2.8.1.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools-2.8.2.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools.spec
Labels: Needs testing, RPM, Stable branch

#7307 Release katello-certs-tools 2.8.2
  packages/foreman/katello-certs-tools/katello-certs-tools-2.8.1.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools-2.8.2.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools.spec
Labels: Needs testing, RPM, Stable branch

#7312 bump supported openscap version
  packages/plugins/rubygem-openscap/rubygem-openscap.spec
Labels: Needs testing

#7313 bump supported openscap version
  packages/plugins/rubygem-openscap/rubygem-openscap.spec
Labels: Needs testing, RPM, Stable branch

#7314 bump supported openscap version
  packages/plugins/rubygem-openscap/rubygem-openscap.spec
Labels: Needs testing, RPM, Stable branch

#7315 bump supported openscap version
  packages/plugins/rubygem-openscap/rubygem-openscap.spec
Labels: Needs testing, RPM, Stable branch

#7298 Update rubygem-smart_proxy_acd to 0.3.0
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-smart_proxy_acd/rubygem-smart_proxy_acd.spec
  packages/plugins/rubygem-smart_proxy_acd/smart_proxy_acd-0.2.0.gem
  packages/plugins/rubygem-smart_proxy_acd/smart_proxy_acd-0.3.0.gem
  packages/plugins/rubygem-smart_proxy_acd_core/rubygem-smart_proxy_acd_core.spec
  packages/plugins/rubygem-smart_proxy_acd_core/smart_proxy_acd_core-0.2.0.gem
  rel-eng/tito.props
Labels: Needs testing, RPM, Stable branch

#7309 Release rubygem-foreman_maintain 0.8.21
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.20.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.21.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM, Stable branch

#7310 Release rubygem-foreman_maintain 0.8.21
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.20.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.21.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM, Stable branch

#7267 Update smart_proxy_dynflow to 0.6.0
  plugins/smart_proxy_dynflow/changelog
  plugins/smart_proxy_dynflow/control
  plugins/smart_proxy_dynflow/dynflow.rb
Labels: Needs testing

#7316 Update rubygem-foreman_discovery to 18.0.5
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-18.0.4.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-18.0.5.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, RPM

#7277 Update rubygem-foreman_puppet to 2.0.0
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-2.0.0.alpha.2.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-2.0.0.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing, RPM

#7279 Update rubygem-foreman_puppet to 2.0.0
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: Needs testing

#7311 build kafo for bullseye
  dependencies/bullseye/kafo/changelog
  dependencies/bullseye/kafo/compat
  dependencies/bullseye/kafo/control
  dependencies/bullseye/kafo/copyright
  dependencies/bullseye/kafo/install
  dependencies/bullseye/kafo/ruby-kafo.docs
  dependencies/bullseye/kafo/rules
  dependencies/bullseye/kafo/source/format
  dependencies/bullseye/kafo/watch
Labels: Needs testing, DEB

#7319 add more deps for bullseye
  dependencies/bullseye/amazing_print/changelog
  dependencies/bullseye/amazing_print/compat
  dependencies/bullseye/amazing_print/control
  dependencies/bullseye/amazing_print/copyright
  dependencies/bullseye/amazing_print/ruby-amazing-print.docs
  dependencies/bullseye/amazing_print/ruby-tests.rake
  dependencies/bullseye/amazing_print/rules
  dependencies/bullseye/amazing_print/source/format
  dependencies/bullseye/apipie-bindings/changelog
  dependencies/bullseye/apipie-bindings/compat
  dependencies/bullseye/apipie-bindings/control
  dependencies/bullseye/apipie-bindings/copyright
  dependencies/bullseye/apipie-bindings/ruby-apipie-bindings.docs
  dependencies/bullseye/apipie-bindings/rules
  dependencies/bullseye/apipie-bindings/source/format
  dependencies/bullseye/apipie-bindings/watch
  dependencies/bullseye/apipie-params/changelog
  dependencies/bullseye/apipie-params/compat
  dependencies/bullseye/apipie-params/control
  dependencies/bullseye/apipie-params/copyright
  dependencies/bullseye/apipie-params/rules
  dependencies/bullseye/apipie-params/source/format
  dependencies/bullseye/bundler_ext/changelog
  dependencies/bullseye/bundler_ext/compat
  dependencies/bullseye/bundler_ext/control
  dependencies/bullseye/bundler_ext/copyright
  dependencies/bullseye/bundler_ext/ruby-tests.rb
  dependencies/bullseye/bundler_ext/rules
  dependencies/bullseye/bundler_ext/source/format
  dependencies/bullseye/bundler_ext/watch
  dependencies/bullseye/kafo_parsers/changelog
  dependencies/bullseye/kafo_parsers/compat
  dependencies/bullseye/kafo_parsers/control
  dependencies/bullseye/kafo_parsers/copyright
  dependencies/bullseye/kafo_parsers/ruby-kafo-parsers.docs
  dependencies/bullseye/kafo_parsers/rules
  dependencies/bullseye/kafo_parsers/source/format
  dependencies/bullseye/kafo_parsers/watch
  dependencies/bullseye/kafo_wizards/changelog
  dependencies/bullseye/kafo_wizards/compat
  dependencies/bullseye/kafo_wizards/control
  dependencies/bullseye/kafo_wizards/copyright
  dependencies/bullseye/kafo_wizards/ruby-kafo-wizards.docs
  dependencies/bullseye/kafo_wizards/rules
  dependencies/bullseye/kafo_wizards/source/format
Labels: Needs testing, Not yet reviewed

#7238 Remove unused python-beautifulsoup dependency
  comps/comps-foreman-client-el8.xml
  comps/comps-foreman-client-rhel7.xml
  package_manifest.yaml
  packages/client/python-beautifulsoup4/beautifulsoup4-4.6.3.tar.gz
  packages/client/python-beautifulsoup4/python-beautifulsoup4.spec
  rel-eng/tito.props
Labels: Needs testing

#7261 Update rubygem-foreman_virt_who_configure to 0.5.8
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.7.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.8.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Needs testing

#7262 Update rubygem-hammer_cli_foreman_virt_who_configure to 0.0.9
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/hammer_cli_foreman_virt_who_configure-0.0.8.gem
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/hammer_cli_foreman_virt_who_configure-0.0.9.gem
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/rubygem-hammer_cli_foreman_virt_who_configure.spec
Labels: Needs testing

#7325 foreman-installer for bullseye
  debian/bullseye/foreman-installer/build_vars.sh
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-installer/compat
  debian/bullseye/foreman-installer/control
  debian/bullseye/foreman-installer/copyright
  debian/bullseye/foreman-installer/postinst
  debian/bullseye/foreman-installer/rules
  debian/bullseye/foreman-installer/source/format
Labels: Needs testing

#7326 build foreman for bullseye
  debian/bullseye/foreman/build_vars.sh
  debian/bullseye/foreman/changelog
  debian/bullseye/foreman/compat
  debian/bullseye/foreman/control
  debian/bullseye/foreman/copyright
  debian/bullseye/foreman/database.yml.pgsql-example
  debian/bullseye/foreman/dirs
  debian/bullseye/foreman/docs
  debian/bullseye/foreman/foreman-assets.install
  debian/bullseye/foreman/foreman-assets.postinst
  debian/bullseye/foreman/foreman-console.install
  debian/bullseye/foreman/foreman-console.postinst
  debian/bullseye/foreman/foreman-debug.dirs
  debian/bullseye/foreman/foreman-debug.install
  debian/bullseye/foreman/foreman-dynflow-sidekiq.install
  debian/bullseye/foreman/foreman-dynflow-sidekiq.postinst
  debian/bullseye/foreman/foreman-ec2.install
  debian/bullseye/foreman/foreman-ec2.postinst
  debian/bullseye/foreman/foreman-gce.install
  debian/bullseye/foreman/foreman-gce.postinst
  debian/bullseye/foreman/foreman-journald.install
  debian/bullseye/foreman/foreman-journald.postinst
  debian/bullseye/foreman/foreman-libvirt.install
  debian/bullseye/foreman/foreman-libvirt.postinst
  debian/bullseye/foreman/foreman-nulldb.install
  debian/bullseye/foreman/foreman-nulldb.postinst
  debian/bullseye/foreman/foreman-openstack.install
  debian/bullseye/foreman/foreman-openstack.postinst
  debian/bullseye/foreman/foreman-ovirt.install
  debian/bullseye/foreman/foreman-ovirt.postinst
  debian/bullseye/foreman/foreman-plugin.mk
  debian/bullseye/foreman/foreman-plugin.postinst-lib
  debian/bullseye/foreman/foreman-postgresql.install
  debian/bullseye/foreman/foreman-postgresql.postinst
  debian/bullseye/foreman/foreman-redis.install
  debian/bullseye/foreman/foreman-redis.postinst
  debian/bullseye/foreman/foreman-service.install
  debian/bullseye/foreman/foreman-service.postinst
  debian/bullseye/foreman/foreman-telemetry.install
  debian/bullseye/foreman/foreman-telemetry.postinst
  debian/bullseye/foreman/foreman-vmware.install
  debian/bullseye/foreman/foreman-vmware.postinst
  debian/bullseye/foreman/foreman.cron.d
  debian/bullseye/foreman/foreman.install
  debian/bullseye/foreman/foreman.logrotate
  debian/bullseye/foreman/foreman.postinst
  debian/bullseye/foreman/foreman.postrm
  debian/bullseye/foreman/foreman.preinst
  debian/bullseye/foreman/foreman.prerm
  debian/bullseye/foreman/links
  debian/bullseye/foreman/rules
  debian/bullseye/foreman/source/format
Labels: Needs testing, Not yet reviewed

#7320 Update rubygem-foreman_maintain to 0.9.3
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.9.2.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.9.3.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing

#7323 Update rubygem-foreman_puppet to 2.0.0
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: Needs testing

#7321 Update rubygem-foreman_puppet to 2.0.0
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-2.0.0.alpha.2.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-2.0.0.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing

#7317 Discovery 18.0.5
  plugins/ruby-foreman-discovery/debian/changelog
  plugins/ruby-foreman-discovery/debian/gem.list
  plugins/ruby-foreman-discovery/foreman_discovery.rb
Labels: Needs testing

#7308 Release katello-certs-tools 2.8.2
  packages/foreman/katello-certs-tools/katello-certs-tools-2.8.1.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools-2.8.2.tar.gz
  packages/foreman/katello-certs-tools/katello-certs-tools.spec
Labels: Needs testing, RPM, Stable branch

#7268 Bump Foreman Azure_rm to 2.2.6
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.2.5.gem
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.2.6.gem
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
Labels: Needs testing, RPM

#7266 Update rubygem-smart_proxy_dynflow to 0.6.0
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.5.2.gem
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.6.0.gem
Labels: Needs testing, RPM

#7265 Update ruby-foreman-tasks to 5.2.0
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing

#7264 Update rubygem-foreman-tasks to 5.2.0
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-5.1.1.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-5.2.0.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#7263 Update discovery to 18.0.4 (CP 3.0)
  plugins/ruby-foreman-discovery/debian/changelog
  plugins/ruby-foreman-discovery/debian/gem.list
  plugins/ruby-foreman-discovery/foreman_discovery.rb
Labels: Needs testing

#7328 Update rubygem-foreman_discovery to 19.0.0
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-18.0.5.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-19.0.0.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, RPM

#7329 Discovery 19.0.0
  plugins/ruby-foreman-discovery/debian/changelog
  plugins/ruby-foreman-discovery/debian/gem.list
  plugins/ruby-foreman-discovery/foreman_discovery.rb
Labels: Needs testing

#7331 add journald-native to bullseye
  dependencies/bullseye/journald-native/changelog
  dependencies/bullseye/journald-native/compat
  dependencies/bullseye/journald-native/control
  dependencies/bullseye/journald-native/copyright
  dependencies/bullseye/journald-native/ruby-journald-native.docs
  dependencies/bullseye/journald-native/rules
  dependencies/bullseye/journald-native/source/format
  dependencies/bullseye/journald-native/watch
Labels: Needs testing, Not yet reviewed, DEB

#7332 add journald-logger to bullseye
  dependencies/bullseye/journald-logger/changelog
  dependencies/bullseye/journald-logger/compat
  dependencies/bullseye/journald-logger/control
  dependencies/bullseye/journald-logger/copyright
  dependencies/bullseye/journald-logger/ruby-journald-logger.docs
  dependencies/bullseye/journald-logger/ruby-tests.rake
  dependencies/bullseye/journald-logger/rules
  dependencies/bullseye/journald-logger/source/format
  dependencies/bullseye/journald-logger/watch
Labels: Needs testing, Not yet reviewed, DEB

#7333 add logging-journald to bullseye
  dependencies/bullseye/logging-journald/changelog
  dependencies/bullseye/logging-journald/compat
  dependencies/bullseye/logging-journald/control
  dependencies/bullseye/logging-journald/copyright
  dependencies/bullseye/logging-journald/ruby-logging-journald.docs
  dependencies/bullseye/logging-journald/ruby-logging-journald.examples
  dependencies/bullseye/logging-journald/ruby-tests.rake
  dependencies/bullseye/logging-journald/rules
  dependencies/bullseye/logging-journald/source/format
  dependencies/bullseye/logging-journald/watch
Labels: Needs testing, Not yet reviewed, DEB

#7338 Update rubygem-foreman_discovery to 19.0.1 (CP 3.1)
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-18.0.4.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-19.0.1.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, RPM, Stable branch

#7340 Update discovery to 19.0.1 for 3.1
  plugins/ruby-foreman-discovery/debian/changelog
  plugins/ruby-foreman-discovery/debian/gem.list
  plugins/ruby-foreman-discovery/foreman_discovery.rb
Labels: Needs testing, DEB, Stable branch

#7342 Update discovery to 20.0.0
  plugins/ruby-foreman-discovery/debian/changelog
  plugins/ruby-foreman-discovery/debian/gem.list
  plugins/ruby-foreman-discovery/foreman_discovery.rb
Labels: Needs testing

#7341 Update rubygem-foreman_discovery to 20.0.0
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-19.0.0.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-20.0.0.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing

#7344 Update rubygem-foreman_discovery to 18.0.5
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-18.0.4.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-18.0.5.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, Not yet reviewed

#7345 Discovery 18.0.5
  plugins/ruby-foreman-discovery/debian/changelog
  plugins/ruby-foreman-discovery/debian/gem.list
  plugins/ruby-foreman-discovery/foreman_discovery.rb
Labels: Needs testing, Not yet reviewed

#7327 Add rubygem-mqtt package
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-mqtt/mqtt-0.5.0.gem
  packages/plugins/rubygem-mqtt/rubygem-mqtt.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#7346 Update rubygem-foreman_puppet to 3.0.0
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-2.0.0.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-3.0.0.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing

#7347 Update rubygem-foreman_puppet to 3.0.0
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: Needs testing

#7288 Update rubygem-smart_proxy_remote_execution_ssh to 0.5.0
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.4.1.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.5.0.gem
Labels: Needs testing, Not yet reviewed, RPM

#7334 Update rubygem-foreman-tasks to 5.2.0
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-5.1.1.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-5.2.0.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM, Stable branch

#7335 Update rubygem-smart_proxy_dynflow to 0.6.0
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.5.2.gem
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.6.0.gem
Labels: Needs testing, RPM, Stable branch

#7336 Update ruby-foreman-tasks to 5.2.0
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Stable branch

#7350 Add rubygem-mqtt package
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-mqtt/mqtt-0.5.0.gem
  packages/plugins/rubygem-mqtt/rubygem-mqtt.spec
  rel-eng/tito.props
Labels: Needs testing, Not yet reviewed

#7349 Update rubygem-smart_proxy_remote_execution_ssh to 0.5.0
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.4.1.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.5.0.gem
Labels: Needs testing

#7339 document how to add new debian releases
  README.md
Labels: Needs testing

#7351 Update rubygem-scoped_search to 4.1.10
  packages/foreman/rubygem-scoped_search/rubygem-scoped_search.spec
  packages/foreman/rubygem-scoped_search/scoped_search-4.1.10.gem
  packages/foreman/rubygem-scoped_search/scoped_search-4.1.9.gem
Labels: Needs testing, Not yet reviewed, RPM

#7289 Update smart_proxy_remote_execution_ssh to 0.5.0
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/control
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: Needs testing, Not yet reviewed

#7354 Update rubygem-scoped_search to 4.1.10
  packages/foreman/rubygem-scoped_search/rubygem-scoped_search.spec
  packages/foreman/rubygem-scoped_search/scoped_search-4.1.10.gem
  packages/foreman/rubygem-scoped_search/scoped_search-4.1.9.gem
Labels: Needs testing

#7355 Update smart_proxy_remote_execution_ssh to 0.5.0
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/control
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: Needs testing

#7343 compare_deb_repo support for stagingdeb, json output and release detection
  scripts/compare_deb_repo.py
Labels: Needs testing, DEB

#7360 Release 3.1.0-rc2
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: Needs testing

#7359 Update foreman-release to 3.1.0-rc2
  packages/foreman/foreman-installer/foreman-installer-3.1.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.1.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.1.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.1.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.1.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.1.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.1.0-rc1.tar.bz2
  packages/foreman/foreman/foreman-3.1.0-rc2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing

#7361 Bump hammer to version 1.3.0
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.3.0.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM

#7362 Bump hammer cli katello to 1.3.1
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.3.0.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.3.1.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM

#7363 Release katello 4.3.0 rc2
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.3.0.rc1.gem
  packages/katello/rubygem-katello/katello-4.3.0.rc2.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM
