Repository theforeman/foreman-packaging, pull requests merged in 2021-02, with the labels that each got.

#6237 Only install pulp-selinux on Katello server for now
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#6238 Remove katello-{backup,restore} stubs
  packages/katello/katello/katello-backup
  packages/katello/katello/katello-backup-rotate-tar.sh
  packages/katello/katello/katello-restore
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#6235 depend on ansible-core
  plugins/smart_proxy_ansible/changelog
  plugins/smart_proxy_ansible/control
  plugins/smart_proxy_ansible/rules
Labels: DEB, Needs testing

#6239 Bump rubygem-qpid_proton to 0.33.0
  packages/katello/rubygem-qpid_proton/qpid_proton-0.32.0.gem
  packages/katello/rubygem-qpid_proton/qpid_proton-0.33.0.gem
  packages/katello/rubygem-qpid_proton/rubygem-qpid_proton.spec
Labels: Needs testing, RPM

#6245 Move qpid comps to katello EL8 comps
  comps/comps-katello-el8.xml
  comps/comps-katello-server-rhel7.xml
Labels: Needs testing, RPM

#6244 Bump rubygem-qpid_proton to 0.33.0
  packages/katello/rubygem-qpid_proton/qpid_proton-0.32.0.gem
  packages/katello/rubygem-qpid_proton/qpid_proton-0.33.0.gem
  packages/katello/rubygem-qpid_proton/rubygem-qpid_proton.spec
Labels: Needs testing, RPM, Stable branch

#6254 reconfig packaging for 2.4
  mock/el7-nonscl.cfg
  mock/el7-scl.cfg
  mock/el8.cfg
  package_manifest.yaml
  rel-eng/releasers.conf
  rel-eng/tito.props
  repoclosure/yum.conf
Labels: Needs testing, RPM, Stable branch

#6253 bump debian to 2.5
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: DEB, Needs testing

#6252 bump packaging to 2.5
  package_manifest.yaml
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
  rel-eng/releasers.conf
  rel-eng/tito.props
Labels: Needs testing, RPM

#6250 Add rubygem-hammer_cli_foreman_scc_manager package (foreman-2.2)
  comps/comps-katello-el8.xml
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/hammer_cli_foreman_scc_manager-0.1.0.gem
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/rubygem-hammer_cli_foreman_scc_manager.spec
  rel-eng/tito.props
Labels: Needs testing, RPM, Stable branch

#6251 Add rubygem-hammer_cli_foreman_scc_manager package (foreman-2.1)
  comps/comps-katello-el8.xml
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/hammer_cli_foreman_scc_manager-0.1.0.gem
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/rubygem-hammer_cli_foreman_scc_manager.spec
  rel-eng/tito.props
Labels: Needs testing, RPM, Stable branch

#6249 Add rubygem-hammer_cli_foreman_scc_manager package (foreman-2.3)
  comps/comps-katello-el8.xml
  comps/comps-katello-server-rhel7.xml
  package_manifest.yaml
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/hammer_cli_foreman_scc_manager-0.1.0.gem
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/rubygem-hammer_cli_foreman_scc_manager.spec
  rel-eng/tito.props
Labels: Needs testing, RPM, Stable branch

#6228 Update foreman_expire_hosts to 7.0.4
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-7.0.1.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-7.0.4.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Needs testing, RPM

#6243 Require container-selinux by Katello
  packages/katello/katello/katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#6255 Delete truststore when running katello-change-hostname
  packages/katello/katello/hostname-change.rb
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#6259 Add libwebsockets needed by qpid-dispatch
  comps/comps-katello-el8.xml
  package_manifest.yaml
  packages/katello/libwebsockets/libwebsockets-2.4.2.tar.gz
  packages/katello/libwebsockets/libwebsockets.spec
  rel-eng/tito.props
Labels: Needs testing

#6246 Require qpid and dispatch-router on EL8 and EL7
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#6261 Fixes #31793 - Container Gateway missing bundler.d file.
  packages/plugins/rubygem-smart_proxy_container_gateway/rubygem-smart_proxy_container_gateway.spec
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-1.0.1.gem
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-1.0.2.gem
Labels: Needs testing, RPM

#6264 Update foreman_expire_hosts to 7.0.4
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-7.0.1.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-7.0.4.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Needs testing, RPM, Stable branch

#6263 Update foreman_expire_hosts to 7.0.4
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-7.0.1.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-7.0.4.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Needs testing, RPM, Stable branch

#6265 Update foreman_expire_hosts to 7.0.4
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-7.0.1.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-7.0.4.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Needs testing, RPM, Stable branch

#6262 Add rubygem-qpid_proton to EL8 comps
  comps/comps-katello-el8.xml
Labels: Needs testing, RPM

#6266 Update foreman-tasks to 3.0.3
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB, Needs testing, Stable branch

#6271 Update katello-selinux to 3.6.0
  packages/katello/katello-selinux/3.5.1
  packages/katello/katello-selinux/3.6.0
  packages/katello/katello-selinux/katello-selinux.spec
Labels: Needs testing

#6269 [2.4] - Update rubygem-foreman_rh_cloud to 3.0.15
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.14.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.15.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM, Stable branch

#5955 Refs #27239: Add timestamps to cron actions in Foreman
  debian/bionic/foreman/control
  debian/bionic/foreman/foreman.cron.d
  debian/buster/foreman/control
  debian/buster/foreman/foreman.cron.d
Labels: Needs testing

#6272 Release 2.4.0-rc1
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: DEB, Needs testing, Stable branch

#6277 Bump minimum foreman version for rubygem-katello
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#6276 Update rubygem-foreman_maintain to 0.7.5
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.4.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.5.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#6200 Add qpid_proton dependency to Katello
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#6280 Update rubygem-hammer_cli to 2.4.0
  packages/foreman/rubygem-hammer_cli/hammer_cli-2.4.0.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
Labels: Needs testing, RPM

#6274 Update rubygem-foreman_statistics to 1.1.1
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-1.0.0.gem
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-1.1.1.gem
  packages/plugins/rubygem-foreman_statistics/rubygem-foreman_statistics.spec
Labels: Needs testing, RPM

#6278 Update rubygem-foreman_maintain to 0.7.5
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.4.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.7.5.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#6281 Drop Pulp 2 requires from katello
  packages/katello/katello/katello.cron
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#6283 Update katello-selinux to 4.0.0
  comps/comps-katello-el8.xml
  comps/comps-katello-server-rhel7.xml
  packages/katello/katello-selinux/3.6.0
  packages/katello/katello-selinux/4.0.0
  packages/katello/katello-selinux/katello-selinux.spec
Labels: Needs testing, RPM

#6285 Update rubygem-hammer_cli_foreman to 2.4.0
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-2.4.0.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM, Stable branch

#6270 [develop] - Update rubygem-foreman_rh_cloud to 3.0.15
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.14.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.15.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM

#6286 Updated hammer_cli to 2.4.0
  dependencies/bionic/hammer_cli/changelog
  dependencies/buster/hammer_cli/changelog
  dependencies/focal/hammer_cli/changelog
Labels: DEB, Needs testing, Stable branch

#6287 Updated hammer_cli_foreman to 2.4.0
  dependencies/bionic/hammer_cli_foreman/changelog
  dependencies/buster/hammer_cli_foreman/changelog
  dependencies/focal/hammer_cli_foreman/changelog
Labels: DEB, Needs testing, Stable branch

#6199 Smart Proxy (and core) for ACD
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-smart_proxy_acd/rubygem-smart_proxy_acd.spec
  packages/plugins/rubygem-smart_proxy_acd/smart_proxy_acd-0.0.1.gem
  packages/plugins/rubygem-smart_proxy_acd_core/rubygem-smart_proxy_acd_core.spec
  packages/plugins/rubygem-smart_proxy_acd_core/smart_proxy_acd_core-0.0.1.gem
  rel-eng/tito.props
Labels: Needs testing, RPM

#6256 Add rubygem-foreman_puppet package
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-0.0.2.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#6289 Update rubygem-foreman_statistics to 1.1.1 (CP 2.4)
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-1.0.0.gem
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-1.1.1.gem
  packages/plugins/rubygem-foreman_statistics/rubygem-foreman_statistics.spec
Labels: Needs testing, RPM, Stable branch

#6288 Add rubygem-foreman_puppet package (CP 2.4)
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-0.0.2.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
  rel-eng/tito.props
Labels: Needs testing

#6275 Update rubygem-foreman_statistics to 1.1.1
  plugins/ruby-foreman-statistics/debian/changelog
  plugins/ruby-foreman-statistics/debian/gem.list
  plugins/ruby-foreman-statistics/foreman_statistics.rb
Labels: DEB, Needs testing

#6292 Fix duplicate powertools entries
  package_manifest.yaml
Labels: Needs testing, RPM

#6258 Add foreman_puppet plugin
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/compat
  plugins/ruby-foreman-puppet/debian/control
  plugins/ruby-foreman-puppet/debian/copyright
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/debian/install
  plugins/ruby-foreman-puppet/debian/postinst
  plugins/ruby-foreman-puppet/debian/rules
  plugins/ruby-foreman-puppet/debian/source/format
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: Needs testing

#6218 Add foreman_webhooks 0.0.1 - DEB
  plugins/ruby-foreman-webhooks/debian/changelog
  plugins/ruby-foreman-webhooks/debian/compat
  plugins/ruby-foreman-webhooks/debian/control
  plugins/ruby-foreman-webhooks/debian/copyright
  plugins/ruby-foreman-webhooks/debian/gem.list
  plugins/ruby-foreman-webhooks/debian/install
  plugins/ruby-foreman-webhooks/debian/postinst
  plugins/ruby-foreman-webhooks/debian/rules
  plugins/ruby-foreman-webhooks/debian/source/format
  plugins/ruby-foreman-webhooks/foreman_webhooks.rb
Labels: DEB, Needs testing

#6183 Add smart_proxy_shellhooks (DEB)
  README.md
  plugins/smart_proxy_shellhooks/changelog
  plugins/smart_proxy_shellhooks/compat
  plugins/smart_proxy_shellhooks/control
  plugins/smart_proxy_shellhooks/copyright
  plugins/smart_proxy_shellhooks/install
  plugins/smart_proxy_shellhooks/ruby-smart-proxy-shellhooks.docs
  plugins/smart_proxy_shellhooks/rules
  plugins/smart_proxy_shellhooks/source/format
  plugins/smart_proxy_shellhooks/watch
Labels: DEB, Needs testing

#6295 Update rubygem-foreman_statistics to 1.1.1 (CP 2.4)
  plugins/ruby-foreman-statistics/debian/changelog
  plugins/ruby-foreman-statistics/debian/gem.list
  plugins/ruby-foreman-statistics/foreman_statistics.rb
Labels: DEB, Needs testing, Stable branch

#6294 Add foreman_puppet plugin (CP 2.4)
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/compat
  plugins/ruby-foreman-puppet/debian/control
  plugins/ruby-foreman-puppet/debian/copyright
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/debian/install
  plugins/ruby-foreman-puppet/debian/postinst
  plugins/ruby-foreman-puppet/debian/rules
  plugins/ruby-foreman-puppet/debian/source/format
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: DEB, Needs testing, Stable branch

#6151 Add smart_proxy_shellhooks (RPM)
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-smart_proxy_shellhooks/rubygem-smart_proxy_shellhooks.spec
  packages/plugins/rubygem-smart_proxy_shellhooks/smart_proxy_shellhooks-0.9.1.gem
  rel-eng/tito.props
Labels: Needs testing, RPM

#6268 only copy webpack if it exists
  debian/bionic/foreman/foreman-plugin.mk
  debian/buster/foreman/foreman-plugin.mk
Labels: DEB, Needs testing

#6297 create a workdir for ansible on the proxy
  plugins/smart_proxy_ansible/changelog
  plugins/smart_proxy_ansible/links
  plugins/smart_proxy_ansible/postinst
Labels: DEB, Needs testing

#6296 only copy webpack if it exists [2.4]
  debian/bionic/foreman/foreman-plugin.mk
  debian/buster/foreman/foreman-plugin.mk
Labels: DEB, Needs testing, Stable branch

#6298 Bump rubygem-foreman_rh_cloud to 3.0.16-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.15.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.16.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing

#6299 Bump rubygem-foreman_rh_cloud to 3.0.16-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.15.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.16.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM, Stable branch

#6302 Bump rubygem-foreman_rh_cloud to 3.0.16-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.15.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.16.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM

#6304 make ansible core work on debian OOTB
  dependencies/bionic/foreman_ansible_core/changelog
  dependencies/bionic/foreman_ansible_core/control
  dependencies/buster/foreman_ansible_core/changelog
  dependencies/buster/foreman_ansible_core/control
  dependencies/focal/foreman_ansible_core/changelog
  dependencies/focal/foreman_ansible_core/control
Labels: Needs testing

#6290 Bump @theforeman/vendor
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#6308 Drop container-selinux work around
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#6309 Drop container-selinux work around
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM, Stable branch

#6311 Katello 3.17.2
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.17.1.gem
  packages/katello/rubygem-katello/katello-3.17.2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#6317 Drop workaround for puppet/selinux installer module
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: Needs testing, RPM

#6310 Update rubygem-pulp_2to3_migration_client to 0.7.0
  packages/katello/rubygem-pulp_2to3_migration_client/pulp_2to3_migration_client-0.6.0.gem
  packages/katello/rubygem-pulp_2to3_migration_client/pulp_2to3_migration_client-0.7.0.gem
  packages/katello/rubygem-pulp_2to3_migration_client/rubygem-pulp_2to3_migration_client.spec
Labels: Needs testing, RPM

#6314 Add rubygem-hammer_cli_foreman_webhooks package
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-hammer_cli_foreman_webhooks/hammer_cli_foreman_webhooks-0.0.1.gem
  packages/plugins/rubygem-hammer_cli_foreman_webhooks/rubygem-hammer_cli_foreman_webhooks.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#6318 Update katello for new pulp 2to3 migration gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#6320 Update rubygem-pulp_2to3_migration_client to 0.7.0
  packages/katello/rubygem-pulp_2to3_migration_client/pulp_2to3_migration_client-0.5.0.gem
  packages/katello/rubygem-pulp_2to3_migration_client/pulp_2to3_migration_client-0.7.0.gem
  packages/katello/rubygem-pulp_2to3_migration_client/rubygem-pulp_2to3_migration_client.spec
Labels: Needs testing, RPM, Stable branch

#6321 Update rubygem-katello to 3.18.1.1 for internal testing
  packages/katello/rubygem-katello/katello-3.18.1.1.gem
  packages/katello/rubygem-katello/katello-3.18.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#6324 Bump rubygem-hammer_cli_katello to 1.0.0
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM

#6332 Release 2.4.0-rc2
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: Needs testing, Not yet reviewed, Stable branch

#6336 Release ansible-collection-theforeman-foreman 2.0.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.5.1.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-2.0.0.tar.gz
Labels: Needs testing, RPM

#6325 foreman-bootloaders-redhat: Add efinet only on *-efi platforms.
  packages/foreman/foreman-bootloaders-redhat/foreman-bootloaders-redhat.spec
  packages/foreman/foreman-bootloaders-redhat/foreman-generate-bootloaders
Labels: Needs testing, RPM

#6337 [2.4] Release ansible-collection-theforeman-foreman 2.0.0
  packages/client/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-1.5.1.tar.gz
  packages/client/ansible-collection-theforeman-foreman/theforeman-foreman-2.0.0.tar.gz
Labels: Needs testing, RPM

#6339 Rails 6.0.3.5
  packages/foreman/rubygem-actioncable/actioncable-6.0.3.4.gem
  packages/foreman/rubygem-actioncable/actioncable-6.0.3.5.gem
  packages/foreman/rubygem-actioncable/rubygem-actioncable.spec
  packages/foreman/rubygem-actionmailbox/actionmailbox-6.0.3.4.gem
  packages/foreman/rubygem-actionmailbox/actionmailbox-6.0.3.5.gem
  packages/foreman/rubygem-actionmailbox/rubygem-actionmailbox.spec
  packages/foreman/rubygem-actionmailer/actionmailer-6.0.3.4.gem
  packages/foreman/rubygem-actionmailer/actionmailer-6.0.3.5.gem
  packages/foreman/rubygem-actionmailer/rubygem-actionmailer.spec
  packages/foreman/rubygem-actionpack/actionpack-6.0.3.4.gem
  packages/foreman/rubygem-actionpack/actionpack-6.0.3.5.gem
  packages/foreman/rubygem-actionpack/rubygem-actionpack.spec
  packages/foreman/rubygem-actiontext/actiontext-6.0.3.4.gem
  packages/foreman/rubygem-actiontext/actiontext-6.0.3.5.gem
  packages/foreman/rubygem-actiontext/rubygem-actiontext.spec
  packages/foreman/rubygem-actionview/actionview-6.0.3.4.gem
  packages/foreman/rubygem-actionview/actionview-6.0.3.5.gem
  packages/foreman/rubygem-actionview/rubygem-actionview.spec
  packages/foreman/rubygem-activejob/activejob-6.0.3.4.gem
  packages/foreman/rubygem-activejob/activejob-6.0.3.5.gem
  packages/foreman/rubygem-activejob/rubygem-activejob.spec
  packages/foreman/rubygem-activemodel/activemodel-6.0.3.4.gem
  packages/foreman/rubygem-activemodel/activemodel-6.0.3.5.gem
  packages/foreman/rubygem-activemodel/rubygem-activemodel.spec
  packages/foreman/rubygem-activerecord/activerecord-6.0.3.4.gem
  packages/foreman/rubygem-activerecord/activerecord-6.0.3.5.gem
  packages/foreman/rubygem-activerecord/rubygem-activerecord.spec
  packages/foreman/rubygem-activestorage/activestorage-6.0.3.4.gem
  packages/foreman/rubygem-activestorage/activestorage-6.0.3.5.gem
  packages/foreman/rubygem-activestorage/rubygem-activestorage.spec
  packages/foreman/rubygem-activesupport/activesupport-6.0.3.4.gem
  packages/foreman/rubygem-activesupport/activesupport-6.0.3.5.gem
  packages/foreman/rubygem-activesupport/rubygem-activesupport.spec
  packages/foreman/rubygem-rails/rails-6.0.3.4.gem
  packages/foreman/rubygem-rails/rails-6.0.3.5.gem
  packages/foreman/rubygem-rails/rubygem-rails.spec
  packages/foreman/rubygem-railties/railties-6.0.3.4.gem
  packages/foreman/rubygem-railties/railties-6.0.3.5.gem
  packages/foreman/rubygem-railties/rubygem-railties.spec
Labels: Needs testing, RPM

#6338 Katello 4.0.0 RC2
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.0.0.rc1.gem
  packages/katello/rubygem-katello/katello-4.0.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#6342 Katello 4.0.0 RC2
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.0.0.rc1.gem
  packages/katello/rubygem-katello/katello-4.0.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#6315 Drop Pulp 2 from katello-debug
  packages/katello/katello/katello-debug.sh
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#6352 Update rubygem-smart_proxy_container_gateway to 1.0.2
  packages/plugins/rubygem-smart_proxy_container_gateway/rubygem-smart_proxy_container_gateway.spec
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-1.0.1.gem
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-1.0.2.gem
Labels: Needs testing, RPM

#6345 Bump rubygem-redhat_access to 2.2.19-1
  packages/katello/rubygem-redhat_access/redhat_access-2.2.18.gem
  packages/katello/rubygem-redhat_access/redhat_access-2.2.19.gem
  packages/katello/rubygem-redhat_access/rubygem-redhat_access.spec
Labels: Needs testing, RPM

#6351 Update foreman-release to 2.3.3
  packages/foreman/foreman-installer/foreman-installer-2.3.2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.3.3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.3.2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.3.3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.3.2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.3.3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.3.2.tar.bz2
  packages/foreman/foreman/foreman-2.3.3.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#6353 Release 2.3.3
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: Needs testing, Not yet reviewed

#6356 Update foreman-release to 2.2.3
  packages/foreman/foreman-installer/foreman-installer-2.2.2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.2.3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.2.2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.2.3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.2.2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.2.3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.2.2.tar.bz2
  packages/foreman/foreman/foreman-2.2.3.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#6357 Release 2.2.3
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: Needs testing, Not yet reviewed

#6358 Update katello package dependencies
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM
