Repository theforeman/foreman-packaging, pull requests merged in 2021-05, with the labels that each got.

#6589 Update rubygem-foreman_discovery to 17.0.0
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-16.3.5.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-17.0.0.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, RPM

#6590 Update rubygem-foreman_discovery to 17.0.0 CP-2.4
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-16.3.4.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-17.0.0.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, RPM

#6584 add script to compare git and debian repo
  scripts/compare_deb_repo.py
Labels: DEB, Needs testing

#6561 package foreman operations collection
  plugins/ansible-collection-theforeman-operations/build_vars.sh
  plugins/ansible-collection-theforeman-operations/debian/changelog
  plugins/ansible-collection-theforeman-operations/debian/compat
  plugins/ansible-collection-theforeman-operations/debian/control
  plugins/ansible-collection-theforeman-operations/debian/copyright
  plugins/ansible-collection-theforeman-operations/debian/docs
  plugins/ansible-collection-theforeman-operations/debian/install
  plugins/ansible-collection-theforeman-operations/debian/rules
  plugins/ansible-collection-theforeman-operations/debian/source/format
Labels: DEB, Needs testing

#6587 Update rubygem-pulp_deb_client to 2.9.1 for Katello 4.0
  packages/katello/rubygem-pulp_deb_client/pulp_deb_client-2.8.0.gem
  packages/katello/rubygem-pulp_deb_client/pulp_deb_client-2.9.1.gem
  packages/katello/rubygem-pulp_deb_client/rubygem-pulp_deb_client.spec
Labels: Needs testing, RPM, Stable branch

#6596 Update foreman release to 2.6.0
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: DEB, Needs testing

#6597 Add package to all distros
  add_gem_package.sh
Labels: Needs testing, RPM

#6594 Update rubygem-foreman_azure_rm to 2.2.3
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.2.2.gem
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.2.3.gem
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
Labels: Needs testing

#6593 Update azure_rm to 2.2.3
  plugins/ruby-foreman-azure-rm/debian/changelog
  plugins/ruby-foreman-azure-rm/debian/gem.list
  plugins/ruby-foreman-azure-rm/foreman_azure_rm.rb
Labels: DEB, Needs testing

#6600 Update rubygem-smart_proxy_dynflow_core to 0.3.3
  packages/plugins/rubygem-smart_proxy_dynflow_core/rubygem-smart_proxy_dynflow_core.spec
  packages/plugins/rubygem-smart_proxy_dynflow_core/smart_proxy_dynflow_core-0.3.2.gem
  packages/plugins/rubygem-smart_proxy_dynflow_core/smart_proxy_dynflow_core-0.3.3.gem
Labels: Needs testing, RPM

#6606 drop all nightly releases from manifest
  package_manifest.yaml
Labels: Needs testing, RPM, Stable branch

#6604 Update foreman-release to 2.5.0
  packages/foreman/foreman-installer/foreman-installer-2.5.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.5.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.5.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.5.0-rc1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#6591 Update hammer_cli, hammer_cli_foreman to 2.5.0
  packages/foreman/rubygem-hammer_cli/hammer_cli-2.5.0.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-2.5.0.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM, Stable branch

#6605 Release 2.5.0-rc1
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: DEB, Needs testing, Stable branch

#6608 Update rubygem-hammer_cli_katello to 1.1.1
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM

#6601 Update smart_proxy_dynflow_core to 0.3.3
  plugins/smart_proxy_dynflow_core/changelog
  plugins/smart_proxy_dynflow_core/dynflow_core.rb
Labels: DEB, Needs testing

#6592 Update hammer_cli, hamer_cli_foreman to 2.5.0
  dependencies/bionic/hammer_cli/changelog
  dependencies/bionic/hammer_cli_foreman/changelog
  dependencies/buster/hammer_cli/changelog
  dependencies/buster/hammer_cli_foreman/changelog
  dependencies/focal/hammer_cli/changelog
  dependencies/focal/hammer_cli_foreman/changelog
Labels: DEB, Needs testing, Stable branch

#6612 Update rubygem-foreman_maintain to 0.8.1
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.0.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.1.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#6615 Update rubygem-puma to 5.3.0
  packages/foreman/rubygem-puma/puma-5.1.1.gem
  packages/foreman/rubygem-puma/puma-5.3.0.gem
  packages/foreman/rubygem-puma/rdoc-issue-14617-workaround.patch
  packages/foreman/rubygem-puma/rubygem-puma.spec
Labels: Needs testing

#6611 Prevent end of line whitespace in scl gem2rpm template
  gem2rpm/foreman_plugin.spec.erb
  gem2rpm/hammer_plugin.spec.erb
  gem2rpm/nonscl.spec.erb
  gem2rpm/scl.spec.erb
  gem2rpm/smart_proxy_plugin.spec.erb
Labels: Needs testing, RPM

#6613 Release 2.5.0-rc2
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: DEB, Needs testing

#6619 Update rubygem-puma to 5.3.0
  packages/foreman/rubygem-puma/puma-5.1.1.gem
  packages/foreman/rubygem-puma/puma-5.3.0.gem
  packages/foreman/rubygem-puma/rdoc-issue-14617-workaround.patch
  packages/foreman/rubygem-puma/rubygem-puma.spec
Labels: Needs testing

#6617 Refs #32532: Require kafo 6.4+ for foreman-installer
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: Needs testing, RPM

#6628 Fixes #32576: Update Rails stack to 6.0.3.7
  packages/foreman/rubygem-actioncable/actioncable-6.0.3.5.gem
  packages/foreman/rubygem-actioncable/actioncable-6.0.3.7.gem
  packages/foreman/rubygem-actioncable/rubygem-actioncable.spec
  packages/foreman/rubygem-actionmailbox/actionmailbox-6.0.3.5.gem
  packages/foreman/rubygem-actionmailbox/actionmailbox-6.0.3.7.gem
  packages/foreman/rubygem-actionmailbox/rubygem-actionmailbox.spec
  packages/foreman/rubygem-actionmailer/actionmailer-6.0.3.5.gem
  packages/foreman/rubygem-actionmailer/actionmailer-6.0.3.7.gem
  packages/foreman/rubygem-actionmailer/rubygem-actionmailer.spec
  packages/foreman/rubygem-actionpack/actionpack-6.0.3.5.gem
  packages/foreman/rubygem-actionpack/actionpack-6.0.3.7.gem
  packages/foreman/rubygem-actionpack/rubygem-actionpack.spec
  packages/foreman/rubygem-actiontext/actiontext-6.0.3.5.gem
  packages/foreman/rubygem-actiontext/actiontext-6.0.3.7.gem
  packages/foreman/rubygem-actiontext/rubygem-actiontext.spec
  packages/foreman/rubygem-actionview/actionview-6.0.3.5.gem
  packages/foreman/rubygem-actionview/actionview-6.0.3.7.gem
  packages/foreman/rubygem-actionview/rubygem-actionview.spec
  packages/foreman/rubygem-activejob/activejob-6.0.3.5.gem
  packages/foreman/rubygem-activejob/activejob-6.0.3.7.gem
  packages/foreman/rubygem-activejob/rubygem-activejob.spec
  packages/foreman/rubygem-activemodel/activemodel-6.0.3.5.gem
  packages/foreman/rubygem-activemodel/activemodel-6.0.3.7.gem
  packages/foreman/rubygem-activemodel/rubygem-activemodel.spec
  packages/foreman/rubygem-activerecord/activerecord-6.0.3.5.gem
  packages/foreman/rubygem-activerecord/activerecord-6.0.3.7.gem
  packages/foreman/rubygem-activerecord/rubygem-activerecord.spec
  packages/foreman/rubygem-activestorage/activestorage-6.0.3.5.gem
  packages/foreman/rubygem-activestorage/activestorage-6.0.3.7.gem
  packages/foreman/rubygem-activestorage/rubygem-activestorage.spec
  packages/foreman/rubygem-activesupport/activesupport-6.0.3.5.gem
  packages/foreman/rubygem-activesupport/activesupport-6.0.3.7.gem
  packages/foreman/rubygem-activesupport/rubygem-activesupport.spec
  packages/foreman/rubygem-rails/rails-6.0.3.5.gem
  packages/foreman/rubygem-rails/rails-6.0.3.7.gem
  packages/foreman/rubygem-rails/rubygem-rails.spec
  packages/foreman/rubygem-railties/railties-6.0.3.5.gem
  packages/foreman/rubygem-railties/railties-6.0.3.7.gem
  packages/foreman/rubygem-railties/rubygem-railties.spec
Labels: Needs testing

#6610 Release kafo 6.4.0
  dependencies/bionic/kafo/changelog
  dependencies/buster/kafo/changelog
  dependencies/focal/kafo/changelog
Labels: DEB, Needs testing

#6626 Update rubygem-smart_proxy_dynflow_core to 0.3.3
  packages/plugins/rubygem-smart_proxy_dynflow_core/rubygem-smart_proxy_dynflow_core.spec
  packages/plugins/rubygem-smart_proxy_dynflow_core/smart_proxy_dynflow_core-0.3.2.gem
  packages/plugins/rubygem-smart_proxy_dynflow_core/smart_proxy_dynflow_core-0.3.3.gem
Labels: Needs testing

#6632 Refs #32576: Update rubygem-marcel to 1.0.1
  packages/foreman/rubygem-marcel/marcel-0.3.3.gem
  packages/foreman/rubygem-marcel/marcel-1.0.1.gem
  packages/foreman/rubygem-marcel/rubygem-marcel.spec
Labels: Needs testing, RPM

#6633 Update rubygem-foreman-tasks to 4.1.1
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-4.1.0.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-4.1.1.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#6618 Refs #32532: Require kafo 6.4+ from foreman-installer
  debian/bionic/foreman-installer/control
  debian/buster/foreman-installer/control
  debian/focal/foreman-installer/control
Labels: DEB, Needs testing

#6631 Update rubygem-foreman_virt_who_configure to 0.5.6
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.5.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.6.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Needs testing, RPM

#6647 Katello 4.1.0-rc1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.0.1.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
  packages/katello/rubygem-katello/katello-4.1.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#6646 azure_rm 2.2.4
  plugins/ruby-foreman-azure-rm/debian/changelog
  plugins/ruby-foreman-azure-rm/debian/gem.list
  plugins/ruby-foreman-azure-rm/foreman_azure_rm.rb
Labels: Needs testing, Not yet reviewed

#6645 Update rubygem-foreman_azure_rm to 2.2.4
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.2.3.gem
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.2.4.gem
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
Labels: Needs testing, Not yet reviewed, RPM

#6643 Updated hammer_cli_foreman to 2.3.2
  dependencies/bionic/hammer_cli_foreman/changelog
  dependencies/bionic/hammer_cli_foreman/control
  dependencies/buster/hammer_cli_foreman/changelog
  dependencies/buster/hammer_cli_foreman/control
  dependencies/focal/hammer_cli_foreman/changelog
  dependencies/focal/hammer_cli_foreman/control
Labels: Needs testing, Not yet reviewed, Stable branch

#6642 Updated hammer_cli to 2.3.1
  dependencies/bionic/hammer_cli/changelog
  dependencies/buster/hammer_cli/changelog
  dependencies/focal/hammer_cli/changelog
Labels: Needs testing, Not yet reviewed, Stable branch

#6640 Update rubygem-hammer_cli to 2.3.1
  packages/foreman/rubygem-hammer_cli/hammer_cli-2.3.0.gem
  packages/foreman/rubygem-hammer_cli/hammer_cli-2.3.1.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6641 Update rubygem-hammer_cli_foreman to 2.3.2
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-2.3.1.gem
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-2.3.2.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6638 Update rubygem-dynflow to 1.4.8
  packages/foreman/rubygem-dynflow/dynflow-1.4.7.gem
  packages/foreman/rubygem-dynflow/dynflow-1.4.8.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing, Not yet reviewed

#6639 Update dynflow dependency to 1.4.8
  dependencies/bionic/dynflow/changelog
  dependencies/buster/dynflow/changelog
  dependencies/focal/dynflow/changelog
Labels: Needs testing, Not yet reviewed

#6652 Update rubygem-hammer_cli_katello to 1.1.1
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.0.1.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.1.1.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, Stable branch

#6659 katello 4.1.0 rc1.1
  packages/katello/rubygem-katello/katello-4.1.0.rc1.1.gem
  packages/katello/rubygem-katello/katello-4.1.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6636 Update rubygem-dynflow to 1.5.0
  packages/foreman/rubygem-dynflow/dynflow-1.4.7.gem
  packages/foreman/rubygem-dynflow/dynflow-1.5.0.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing, RPM

#6655 Update rubygem-foreman_ansible_core to 4.1.0
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-4.0.0.gem
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-4.1.0.gem
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
Labels: Needs testing, RPM

#6657 Update rubygem-smart_proxy_ansible to 3.1.0
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-3.0.1.gem
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-3.1.0.gem
Labels: Needs testing, RPM

#6663 Update rubygem-foreman_openscap to 4.3.0
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.2.0.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.3.0.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#6665 Update ansiblerole-foreman_scap_client to 0.2.0
  packages/plugins/ansiblerole-foreman_scap_client/ansiblerole-foreman_scap_client.spec
  packages/plugins/ansiblerole-foreman_scap_client/foreman_scap_client-0.1.0.tar.gz
  packages/plugins/ansiblerole-foreman_scap_client/foreman_scap_client-0.2.0.tar.gz
Labels: Needs testing, RPM

#6664 Update rubygem-smart_proxy_openscap to 0.9.0
  packages/plugins/rubygem-smart_proxy_openscap/rubygem-smart_proxy_openscap.spec
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.8.1.gem
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.9.0.gem
Labels: Needs testing, RPM

#6666 Update rubygem-foreman_scap_client to 0.5.0
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.4.7.gem
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.5.0.gem
  packages/client/rubygem-foreman_scap_client/rubygem-foreman_scap_client.spec
Labels: Needs testing, RPM

#6630 Update rubygem-foreman_snapshot_management to 2.0.0
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.7.1.gem
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-2.0.0.gem
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Needs testing, RPM

#6667 Update rubygem-foreman_openscap to 4.3.0
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.2.0.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-4.3.0.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#6669 Update rubygem-smart_proxy_openscap to 0.9.0
  packages/plugins/rubygem-smart_proxy_openscap/rubygem-smart_proxy_openscap.spec
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.8.1.gem
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.9.0.gem
Labels: Needs testing, RPM

#6668 Update ansiblerole-foreman_scap_client to 0.2.0
  packages/plugins/ansiblerole-foreman_scap_client/ansiblerole-foreman_scap_client.spec
  packages/plugins/ansiblerole-foreman_scap_client/foreman_scap_client-0.1.0.tar.gz
  packages/plugins/ansiblerole-foreman_scap_client/foreman_scap_client-0.2.0.tar.gz
Labels: Needs testing, RPM

#6670 Update rubygem-foreman_scap_client to 0.5.0
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.4.7.gem
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.5.0.gem
  packages/client/rubygem-foreman_scap_client/rubygem-foreman_scap_client.spec
Labels: Needs testing, RPM

#6658 Update rubygem-smart_proxy_ansible to 3.1.0
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-3.0.1.gem
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-3.1.0.gem
Labels: Needs testing, RPM

#6656 Update rubygem-foreman_ansible_core to 4.1.0
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-4.0.0.gem
  packages/plugins/rubygem-foreman_ansible_core/foreman_ansible_core-4.1.0.gem
  packages/plugins/rubygem-foreman_ansible_core/rubygem-foreman_ansible_core.spec
Labels: Needs testing, RPM

#6673 Update rubygem-foreman_snapshot_management to 2.0.0 foreman-2.4
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.7.1.gem
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-2.0.0.gem
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Needs testing, RPM

#6672 Update rubygem-foreman_snapshot_management to 2.0.0 foreman-2.5
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-1.7.1.gem
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-2.0.0.gem
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Needs testing, RPM

#6602 Update rubygem-foreman_azure_rm to 2.2.4
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.2.3.gem
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.2.4.gem
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
Labels: Needs testing, Not yet reviewed, Stable branch

#6603 Update azure_rm to 2.2.4
  plugins/ruby-foreman-azure-rm/debian/changelog
  plugins/ruby-foreman-azure-rm/debian/gem.list
  plugins/ruby-foreman-azure-rm/foreman_azure_rm.rb
Labels: DEB, Needs testing, Stable branch

#6649 Update rubygem-dynflow to 1.4.8
  packages/foreman/rubygem-dynflow/dynflow-1.4.7.gem
  packages/foreman/rubygem-dynflow/dynflow-1.4.8.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing, RPM, Stable branch

#6651 Update dynflow dependency to 1.4.8
  dependencies/bionic/dynflow/changelog
  dependencies/buster/dynflow/changelog
  dependencies/focal/dynflow/changelog
Labels: Needs testing, Stable branch

#6648 Update rubygem-dynflow to 1.4.8
  packages/foreman/rubygem-dynflow/dynflow-1.4.7.gem
  packages/foreman/rubygem-dynflow/dynflow-1.4.8.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing, RPM, Stable branch

#6650 Update dynflow dependency to 1.4.8
  dependencies/bionic/dynflow/changelog
  dependencies/buster/dynflow/changelog
  dependencies/focal/dynflow/changelog
Labels: Needs testing, Stable branch

#6625 Update smart_proxy_dynflow_core to 0.3.3
  plugins/smart_proxy_dynflow_core/changelog
  plugins/smart_proxy_dynflow_core/dynflow_core.rb
Labels: Needs testing

#6624 Update smart_proxy_dynflow_core to 0.3.3
  plugins/smart_proxy_dynflow_core/changelog
  plugins/smart_proxy_dynflow_core/dynflow_core.rb
Labels: Needs testing

#6637 Update dynflow dependency to 1.5.0
  dependencies/bionic/dynflow/changelog
  dependencies/buster/dynflow/changelog
  dependencies/focal/dynflow/changelog
Labels: DEB, Needs testing

#6677 release ansible-collection-theforeman-foreman 2.1.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-2.0.1.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-2.1.0.tar.gz
Labels: Needs testing, RPM

#6678 ansible-collection-theforeman-foreman 2.1.0
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: Needs testing

#6685 Update rubygem-qpid_proton to 0.34.0
  packages/katello/rubygem-qpid_proton/qpid_proton-0.33.0.gem
  packages/katello/rubygem-qpid_proton/qpid_proton-0.34.0.gem
  packages/katello/rubygem-qpid_proton/rubygem-qpid_proton.spec
Labels: Needs testing, RPM

#6687 Update rubygem-qpid_proton to 0.34.0
  packages/katello/rubygem-qpid_proton/qpid_proton-0.33.0.gem
  packages/katello/rubygem-qpid_proton/qpid_proton-0.34.0.gem
  packages/katello/rubygem-qpid_proton/rubygem-qpid_proton.spec
Labels: Needs testing, RPM, Stable branch

#6688 Update rubygem-qpid_proton to 0.34.0
  packages/katello/rubygem-qpid_proton/rubygem-qpid_proton.spec
Labels: Needs testing, RPM

#6686 Update rubygem-qpid_proton to 0.34.0
  packages/katello/rubygem-qpid_proton/qpid_proton-0.33.0.gem
  packages/katello/rubygem-qpid_proton/qpid_proton-0.34.0.gem
  packages/katello/rubygem-qpid_proton/rubygem-qpid_proton.spec
Labels: Needs testing, RPM, Stable branch

#6684 Update rubygem-hammer_cli_katello to 0.24.4
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.24.3.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-0.24.4.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, RPM, Stable branch

#6682 release ansible-collection-theforeman-foreman 2.1.0 [2.5]
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-2.0.1.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-2.1.0.tar.gz
Labels: Needs testing, RPM

#6680 ansible-collection-theforeman-foreman 2.1.0 [2.5]
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: Needs testing

#6689 Update rubygem-foreman_puppet to 0.1.0
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-0.0.2.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-0.1.0.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing, RPM, Stable branch

#6693 rebuild pulp-rpm-client against ruby 2.5
  packages/katello/rubygem-pulp_rpm_client/rubygem-pulp_rpm_client.spec
Labels: Needs testing, RPM, Stable branch

#6691 Rebuild hammer_cli_katello for Ruby 2.5
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6690 Katello 3.18.3
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-3.18.2.1.gem
  packages/katello/rubygem-katello/katello-3.18.3.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#6696 Update foreman-release to 2.5.0
  packages/foreman/foreman-installer/foreman-installer-2.5.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.5.0-rc3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.5.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.5.0-rc3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.5.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.5.0-rc3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.5.0-rc2.tar.bz2
  packages/foreman/foreman/foreman-2.5.0-rc3.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#6697 Release 2.5.0-rc3
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: Needs testing, Not yet reviewed, Stable branch

#6699 Release 2.3.4
  debian/bionic/foreman-installer/changelog
  debian/bionic/foreman-proxy/changelog
  debian/bionic/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
Labels: Needs testing, Not yet reviewed, Stable branch

#6698 Update foreman-release to 2.3.4
  packages/foreman/foreman-installer/foreman-installer-2.3.3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-2.3.4.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-2.3.3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-2.3.4.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-2.3.3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-2.3.4.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-2.3.3.tar.bz2
  packages/foreman/foreman/foreman-2.3.4.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, Stable branch

#6701 Update rubygem-foreman_maintain to 0.8.1
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.0.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.1.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM, Stable branch

#6575 Update rubygem-foreman_scc_manager to 1.8.9 (Foreman 2.3)
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.8.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.9.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM, Stable branch

#6355 Bump rubygem-redhat_access to 2.2.19-1
  packages/katello/rubygem-redhat_access/redhat_access-2.2.18.gem
  packages/katello/rubygem-redhat_access/redhat_access-2.2.19.gem
  packages/katello/rubygem-redhat_access/rubygem-redhat_access.spec
Labels: Needs testing, RPM, Stable branch

#6716 Update rubygem-hammer_cli_foreman_azure_rm to 0.2.1
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/hammer_cli_foreman_azure_rm-0.2.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/hammer_cli_foreman_azure_rm-0.2.1.gem
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/rubygem-hammer_cli_foreman_azure_rm.spec
Labels: Needs testing, RPM

#6717 Only build rubygem-racc on EL7
  comps/comps-foreman-el8.xml
  package_manifest.yaml
  rel-eng/tito.props
Labels: Needs testing, RPM

#6718 fix yaml
  package_manifest.yaml
Labels: Needs testing, Not yet reviewed, RPM

#6719 Update rubygem-hammer_cli_foreman_azure_rm to 0.2.1
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/hammer_cli_foreman_azure_rm-0.2.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/hammer_cli_foreman_azure_rm-0.2.1.gem
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/rubygem-hammer_cli_foreman_azure_rm.spec
Labels: Needs testing, RPM

#6681 Update katello to 4.1.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.1.0.rc1.1.gem
  packages/katello/rubygem-katello/katello-4.1.0.rc2.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#6583 Update rubygem-nokogiri to 1.11.3
  packages/foreman/rubygem-nokogiri/nokogiri-1.10.9.gem
  packages/foreman/rubygem-nokogiri/nokogiri-1.11.3.gem
  packages/foreman/rubygem-nokogiri/rubygem-nokogiri.spec
Labels: Needs testing, RPM

#6721 Do not generate auto requires for rubygem-nokogiri
  packages/foreman/rubygem-nokogiri/rubygem-nokogiri.spec
Labels: Needs testing, RPM

#6720 Update rubygem-puma to 5.3.2
  packages/foreman/rubygem-puma/puma-5.3.0.gem
  packages/foreman/rubygem-puma/puma-5.3.2.gem
  packages/foreman/rubygem-puma/rubygem-puma.spec
Labels: Needs testing, RPM

#6708 Update rubygem-foreman_default_hostgroup to 6.0.0
  packages/plugins/rubygem-foreman_default_hostgroup/foreman_default_hostgroup-5.0.0.gem
  packages/plugins/rubygem-foreman_default_hostgroup/foreman_default_hostgroup-6.0.0.gem
  packages/plugins/rubygem-foreman_default_hostgroup/rubygem-foreman_default_hostgroup.spec
Labels: Needs testing, RPM

#6709 Update rubygem-foreman_default_hostgroup to 6.0.0
  packages/plugins/rubygem-foreman_default_hostgroup/foreman_default_hostgroup-5.0.0.gem
  packages/plugins/rubygem-foreman_default_hostgroup/foreman_default_hostgroup-6.0.0.gem
  packages/plugins/rubygem-foreman_default_hostgroup/rubygem-foreman_default_hostgroup.spec
Labels: Needs testing, RPM

#6702 Update rubygem-foreman_maintain to 0.8.1
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.0.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-0.8.1.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM, Stable branch

#6707 Update rubygem-foreman_default_hostgroup to 6.0.0
  packages/plugins/rubygem-foreman_default_hostgroup/foreman_default_hostgroup-5.0.0.gem
  packages/plugins/rubygem-foreman_default_hostgroup/foreman_default_hostgroup-6.0.0.gem
  packages/plugins/rubygem-foreman_default_hostgroup/rubygem-foreman_default_hostgroup.spec
Labels: Needs testing, RPM

#6706 Update rubygem-foreman_default_hostgroup to 6.0.0
  packages/plugins/rubygem-foreman_default_hostgroup/foreman_default_hostgroup-5.0.0.gem
  packages/plugins/rubygem-foreman_default_hostgroup/foreman_default_hostgroup-6.0.0.gem
  packages/plugins/rubygem-foreman_default_hostgroup/rubygem-foreman_default_hostgroup.spec
Labels: Needs testing, RPM

#6704 Update rubygem-foreman_templates to 9.1.0
  packages/plugins/rubygem-foreman_templates/foreman_templates-9.0.2.gem
  packages/plugins/rubygem-foreman_templates/foreman_templates-9.1.0.gem
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
Labels: Needs testing, RPM

#6703 Update rubygem-foreman_webhooks to 2.0.0
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-1.0.0.gem
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-2.0.0.gem
  packages/plugins/rubygem-foreman_webhooks/rubygem-foreman_webhooks.spec
Labels: Needs testing, RPM

#6714 Update foreman_default_hostgroup to 6.0.0
  plugins/ruby-foreman-default-hostgroup/debian/changelog
  plugins/ruby-foreman-default-hostgroup/debian/gem.list
  plugins/ruby-foreman-default-hostgroup/foreman_default_hostgroup.rb
Labels: Needs testing

#6713 Update foreman_default_hostgroup to 6.0.0
  plugins/ruby-foreman-default-hostgroup/debian/changelog
  plugins/ruby-foreman-default-hostgroup/debian/gem.list
  plugins/ruby-foreman-default-hostgroup/foreman_default_hostgroup.rb
Labels: Needs testing

#6712 Update foreman_default_hostgroup to 6.0.0
  plugins/ruby-foreman-default-hostgroup/debian/changelog
  plugins/ruby-foreman-default-hostgroup/debian/gem.list
  plugins/ruby-foreman-default-hostgroup/foreman_default_hostgroup.rb
Labels: Needs testing

#6711 Update foreman_default_hostgroup to 6.0.0
  plugins/ruby-foreman-default-hostgroup/debian/changelog
  plugins/ruby-foreman-default-hostgroup/debian/gem.list
  plugins/ruby-foreman-default-hostgroup/foreman_default_hostgroup.rb
Labels: Needs testing

#6705 Update foreman_remote_execution_core to 1.4.1
  dependencies/bionic/foreman_remote_execution_core/changelog
  dependencies/buster/foreman_remote_execution_core/changelog
  dependencies/focal/foreman_remote_execution_core/changelog
Labels: DEB, Needs testing, Stable branch

#6722 Update rubygem-puma to 5.3.2
  packages/foreman/rubygem-puma/puma-5.3.0.gem
  packages/foreman/rubygem-puma/puma-5.3.2.gem
  packages/foreman/rubygem-puma/rubygem-puma.spec
Labels: Needs testing, RPM

#6622 Update rubygem-foreman_remote_execution to 4.5.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-4.4.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-4.5.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#6727 Bump rubygem-foreman_rh_cloud to 3.0.21-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.20.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-3.0.21.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM
