Repository theforeman/foreman-packaging, pull requests merged in 2022-05, with the labels that each got.

#7854 Update rubygem-foreman_acd to 0.9.2.X
  packages/plugins/rubygem-foreman_acd/foreman_acd-0.9.0.gem
  packages/plugins/rubygem-foreman_acd/foreman_acd-0.9.2.3.gem
  packages/plugins/rubygem-foreman_acd/rubygem-foreman_acd.spec
Labels: Needs testing, RPM

#7859 Fixes #34855 - add psql dependency for rubygem-foreman_maintain
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#7860 Update rubygem-smart_proxy_monitoring to 0.2.0
  packages/plugins/rubygem-smart_proxy_monitoring/rubygem-smart_proxy_monitoring.spec
  packages/plugins/rubygem-smart_proxy_monitoring/smart_proxy_monitoring-0.1.2.gem
  packages/plugins/rubygem-smart_proxy_monitoring/smart_proxy_monitoring-0.2.0.gem
Labels: Needs testing, Not yet reviewed, RPM

#7861 Update rubygem-smart_proxy_monitoring to 0.2.0
  plugins/smart_proxy_monitoring/changelog
Labels: Needs testing, Not yet reviewed, DEB

#7857 Cherry picks of rubygem-foreman_maintain
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.0.7.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.0.8.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM

#7858 Cherry picks of rubygem-foreman_maintain
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.0.7.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.0.8.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM

#7852 Update rubygem-foreman_scc_manager to 1.8.19 Foreman 3.1
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.18.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.19.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, Not yet reviewed, RPM

#7851 Update rubygem-foreman_scc_manager to 1.8.19 Foreman 3.2
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.18.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.19.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, Not yet reviewed, RPM

#7846 Update rubygem-foreman_bootdisk to 19.0.5
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-19.0.4.gem
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-19.0.5.gem
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
Labels: Needs testing, RPM

#7828 Update rubygem-foreman_ansible to 7.0.4
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-7.0.2.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-7.0.4.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM

#7837 Update rubygem-foreman_discovery to 21.0.1
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-21.0.0.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-21.0.1.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Needs testing, Not yet reviewed

#7838 Update rubygem-foreman_puppet to 2.0.6 Foreman 3.1
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-2.0.4.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-2.0.6.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7839 Update rubygem-foreman_puppet to 3.0.6 Foreman 3.2
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-3.0.5.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-3.0.6.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7840 Update rubygem-foreman_puppet to 3.0.6
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-3.0.5.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-3.0.6.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing, Not yet reviewed, RPM

#7841 Update ruby-foreman-puppet to 2.0.6 Foreman 3.1
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: Needs testing, Not yet reviewed, DEB, Stable branch

#7843 Update ruby-foreman-puppet to 3.0.6 Foreman 3.2
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: Needs testing, Not yet reviewed, DEB, Stable branch

#7842 Update ruby-foreman-puppet to 3.0.6
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: Needs testing, Not yet reviewed, DEB

#7850 Update rubygem-foreman_scc_manager to 1.8.19
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.18.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.19.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, Not yet reviewed, RPM

#7864 Fix extra space in ruby-foreman-puppet changelog
  plugins/ruby-foreman-puppet/debian/changelog
Labels: Needs testing, DEB, Stable branch

#7865 Refs #34855 - adjust psql package for EL7
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing

#7836 Update rubygem-pulp_deb_client to 2.18.0
  packages/katello/rubygem-pulp_deb_client/pulp_deb_client-2.17.1.gem
  packages/katello/rubygem-pulp_deb_client/pulp_deb_client-2.18.0.gem
  packages/katello/rubygem-pulp_deb_client/rubygem-pulp_deb_client.spec
Labels: Needs testing, RPM

#7856 Katello: Update pulp_deb gem dependency
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#7853 Refs #34602 - log plugin installations
  debian/bullseye/foreman/changelog
  debian/bullseye/foreman/foreman-plugin.postinst-lib
  debian/buster/foreman/changelog
  debian/buster/foreman/foreman-plugin.postinst-lib
  debian/focal/foreman/changelog
  debian/focal/foreman/foreman-plugin.postinst-lib
Labels: Needs testing

#7867 Update rubygem-sqlite3 to 1.4.2
  packages/foreman/rubygem-sqlite3/rubygem-sqlite3.spec
  packages/foreman/rubygem-sqlite3/sqlite3-1.3.13.gem
  packages/foreman/rubygem-sqlite3/sqlite3-1.4.2.gem
Labels: Needs testing, RPM

#7855 Refs #34602 - log plugin installations
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#7866 Update rubygem-foreman_maintain to 1.0.9
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.0.8.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.0.9.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7875 add logging of plugin installation to template
  gem2rpm/foreman_plugin.spec.erb
Labels: Needs testing, RPM

#7885 Update rubygem-apipie-bindings to 0.5.0
  packages/foreman/rubygem-apipie-bindings/apipie-bindings-0.4.0.gem
  packages/foreman/rubygem-apipie-bindings/apipie-bindings-0.5.0.gem
  packages/foreman/rubygem-apipie-bindings/rubygem-apipie-bindings.spec
Labels: Needs testing, Not yet reviewed, RPM

#7886 Update rubygem-apipie-bindings to 0.5.0
  packages/foreman/rubygem-apipie-bindings/apipie-bindings-0.4.0.gem
  packages/foreman/rubygem-apipie-bindings/apipie-bindings-0.5.0.gem
  packages/foreman/rubygem-apipie-bindings/rubygem-apipie-bindings.spec
Labels: Needs testing, Not yet reviewed, RPM

#7887 Update rubygem-foreman_maintain to latest
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.0.10.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.0.9.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7889 Build qpid-proton 0.37
  packages/katello/qpid-proton/licenses.xml
  packages/katello/qpid-proton/qpid-proton-0.36.0.tar.gz
  packages/katello/qpid-proton/qpid-proton-0.37.0.tar.gz
  packages/katello/qpid-proton/qpid-proton.spec
Labels: Needs testing, RPM

#7891 Bump rubygem-foreman_rh_cloud to 5.0.35-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-5.0.34.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-5.0.35.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM

#7882 Bump foreman nightly deb pacpackages to 3.4
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: Needs testing, DEB

#7892 Adding Foreman-selinux back to package_manifests, it was wrongly deleted
  package_manifest.yaml
Labels: Needs testing, RPM, Stable branch

#7894 Release 3.3.0-rc1 DEB
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: Needs testing, Stable branch

#7880 Release hammer-cli and hammer-cli-foreman 3.3.0
  packages/foreman/rubygem-hammer_cli/hammer_cli-3.3.0.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-3.3.0.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, RPM

#7884 Bumped katello nightly to 4.6
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#7888 Fixes #34896 - properly detect default_program in k-c-h
  packages/katello/katello/hostname-change.rb
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#7920 Change version from el7-katello-pulp-4.6 to el7-katello-pulp-4.5
  repoclosure/yum.conf
Labels: Needs testing, RPM, Stable branch

#7919 Update rubygem-fog-vsphere to 3.5.1
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.5.0.gem
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.5.1.gem
  packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec
Labels: Needs testing, RPM

#7903 Update rubygem-hammer_cli_foreman_puppet to 0.0.6
  packages/plugins/rubygem-hammer_cli_foreman_puppet/hammer_cli_foreman_puppet-0.0.5.gem
  packages/plugins/rubygem-hammer_cli_foreman_puppet/hammer_cli_foreman_puppet-0.0.6.gem
  packages/plugins/rubygem-hammer_cli_foreman_puppet/rubygem-hammer_cli_foreman_puppet.spec
Labels: Needs testing, RPM

#7904 Update hammer_cli_foreman_puppet to 0.0.6
  dependencies/bullseye/hammer_cli_foreman_puppet/changelog
  dependencies/buster/hammer_cli_foreman_puppet/changelog
  dependencies/focal/hammer_cli_foreman_puppet/changelog
Labels: Needs testing

#7923 Release ansible-collection-theforeman-foreman 3.4.0
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: Needs testing

#7871 Update rubygem-smart_proxy_monitoring to 0.2.0
  plugins/smart_proxy_monitoring/changelog
Labels: Needs testing, DEB, Stable branch

#7922 Release ansible-collection-theforeman-foreman 3.4.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.3.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.4.0.tar.gz
Labels: Needs testing

#7870 Update rubygem-smart_proxy_monitoring to 0.2.0
  plugins/smart_proxy_monitoring/changelog
Labels: Needs testing, DEB, Stable branch

#7869 Update rubygem-smart_proxy_monitoring to 0.2.0
  packages/plugins/rubygem-smart_proxy_monitoring/rubygem-smart_proxy_monitoring.spec
  packages/plugins/rubygem-smart_proxy_monitoring/smart_proxy_monitoring-0.1.2.gem
  packages/plugins/rubygem-smart_proxy_monitoring/smart_proxy_monitoring-0.2.0.gem
Labels: Needs testing, RPM, Stable branch

#7868 Update rubygem-smart_proxy_monitoring to 0.2.0
  packages/plugins/rubygem-smart_proxy_monitoring/rubygem-smart_proxy_monitoring.spec
  packages/plugins/rubygem-smart_proxy_monitoring/smart_proxy_monitoring-0.1.2.gem
  packages/plugins/rubygem-smart_proxy_monitoring/smart_proxy_monitoring-0.2.0.gem
Labels: Needs testing, RPM, Stable branch

#7873 Update rubygem-pulpcore_client to 3.16.7
  packages/katello/rubygem-pulpcore_client/pulpcore_client-3.16.0.gem
  packages/katello/rubygem-pulpcore_client/pulpcore_client-3.16.7.gem
  packages/katello/rubygem-pulpcore_client/rubygem-pulpcore_client.spec
Labels: Needs testing, RPM, Stable branch

#7896 Update rubygem-foreman-tasks to 6.0.2
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-6.0.1.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-6.0.2.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#7927 Update rubygem-foreman-tasks to 6.0.2
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-6.0.1.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-6.0.2.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM

#7899 Update ruby-foreman-tasks to 6.0.2
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing

#7902 Update foreman_ygg_worker to 0.1.0
  packages/client/foreman_ygg_worker/foreman_ygg_worker-0.0.3.tar.gz
  packages/client/foreman_ygg_worker/foreman_ygg_worker-0.1.0.tar.gz
  packages/client/foreman_ygg_worker/foreman_ygg_worker.spec
Labels: Needs testing

#7900 Update rubygem-smart_proxy_remote_execution_ssh to 0.7.0
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.6.0.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.7.0.gem
Labels: Needs testing, Not yet reviewed

#7901 Update smart_proxy_remote_execution_ssh to 0.7.0
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: Needs testing, DEB

#7905 Update rubygem-rabl to 0.15.0
  packages/foreman/rubygem-rabl/rabl-0.14.3.gem
  packages/foreman/rubygem-rabl/rabl-0.15.0.gem
  packages/foreman/rubygem-rabl/rubygem-rabl.spec
Labels: Needs testing, RPM

#7906 Update rubygem-mini_portile2 to 2.8.0
  packages/foreman/rubygem-mini_portile2/mini_portile2-2.5.1.gem
  packages/foreman/rubygem-mini_portile2/mini_portile2-2.8.0.gem
  packages/foreman/rubygem-mini_portile2/rubygem-mini_portile2.spec
Labels: Needs testing, RPM

#7908 Update rubygem-foreman_remote_execution to 7.0.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-6.2.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-7.0.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#7909 Update foreman_remote_execution to 7.0.0
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing

#7910 Update rubygem-foreman_templates to 9.3.0
  packages/plugins/rubygem-foreman_templates/foreman_templates-9.2.0.gem
  packages/plugins/rubygem-foreman_templates/foreman_templates-9.3.0.gem
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
Labels: Needs testing

#7912 Update ruby-foreman-templates to 9.3.0
  plugins/ruby-foreman-templates/debian/changelog
  plugins/ruby-foreman-templates/debian/gem.list
  plugins/ruby-foreman-templates/foreman_templates.rb
Labels: Needs testing

#7914 Update rubygem-foreman_ansible to 8.0.0
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-7.1.0.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-8.0.0.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing

#7915 Updated foreman-ansible to 8.0.0
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing

#7917 Update rubygem-mini_mime to 1.1.2
  packages/foreman/rubygem-mini_mime/mini_mime-1.0.2.gem
  packages/foreman/rubygem-mini_mime/mini_mime-1.1.2.gem
  packages/foreman/rubygem-mini_mime/rubygem-mini_mime.spec
Labels: Needs testing, RPM

#7918 Update rubygem-zeitwerk to 2.5.4
  packages/foreman/rubygem-zeitwerk/rubygem-zeitwerk.spec
  packages/foreman/rubygem-zeitwerk/zeitwerk-2.2.2.gem
  packages/foreman/rubygem-zeitwerk/zeitwerk-2.5.4.gem
Labels: Needs testing, RPM

#7934 drop last places referring to "katello-pulp" repo
  package_manifest.yaml
  repoclosure/yum.conf
Labels: Needs testing, RPM

#7938 Add back disable of Autoreq for nokogiri
  packages/foreman/rubygem-nokogiri/rubygem-nokogiri.spec
Labels: Needs testing, RPM

#7943 Update foreman-release to 3.1.3
  packages/foreman/foreman-installer/foreman-installer-3.1.2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.1.3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.1.2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.1.3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.1.2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.1.3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.1.2.tar.bz2
  packages/foreman/foreman/foreman-3.1.3.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#7944 Release 3.1.3
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: Needs testing

#7946 correct apipie, hammer and hammer-foreman versions
  dependencies/bullseye/apipie-bindings/changelog
  dependencies/bullseye/hammer_cli/changelog
  dependencies/bullseye/hammer_cli_foreman/changelog
  dependencies/buster/apipie-bindings/changelog
  dependencies/buster/hammer_cli/changelog
  dependencies/buster/hammer_cli_foreman/changelog
  dependencies/focal/apipie-bindings/changelog
  dependencies/focal/hammer_cli/changelog
  dependencies/focal/hammer_cli_foreman/changelog
Labels: Needs testing, DEB

#7924 Release ansible-collection-theforeman-operations 1.2.0
  packages/plugins/ansible-collection-theforeman-operations/ansible-collection-theforeman-operations.spec
  packages/plugins/ansible-collection-theforeman-operations/theforeman-operations-1.1.0.tar.gz
  packages/plugins/ansible-collection-theforeman-operations/theforeman-operations-1.2.0.tar.gz
Labels: Needs testing

#7925 Update rubygem-safemode to 1.3.7
  packages/foreman/rubygem-safemode/rubygem-safemode.spec
  packages/foreman/rubygem-safemode/safemode-1.3.6.gem
  packages/foreman/rubygem-safemode/safemode-1.3.7.gem
Labels: Needs testing, RPM

#7926 Drop use of module_hotfixes
  packages/foreman/foreman-release/foreman-plugins.repo
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-release/foreman.repo
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello-repos/katello.repo
Labels: Needs testing

#7936 Update rubygem-puma to 5.6.4
  packages/foreman/rubygem-puma/puma-5.6.2.gem
  packages/foreman/rubygem-puma/puma-5.6.4.gem
  packages/foreman/rubygem-puma/rubygem-puma.spec
Labels: Needs testing, RPM

#7948 correct apipie, hammer and hammer-foreman versions
  dependencies/bullseye/apipie-bindings/changelog
  dependencies/bullseye/hammer_cli/changelog
  dependencies/bullseye/hammer_cli_foreman/changelog
  dependencies/buster/apipie-bindings/changelog
  dependencies/buster/hammer_cli/changelog
  dependencies/buster/hammer_cli_foreman/changelog
  dependencies/focal/apipie-bindings/changelog
  dependencies/focal/hammer_cli/changelog
  dependencies/focal/hammer_cli_foreman/changelog
Labels: Needs testing

#7947 Update Foreman GEM requirements
  packages/foreman/foreman/foreman.spec
Labels: Needs testing

#7949 Update rubygem-dynflow to 1.6.5
  packages/foreman/rubygem-dynflow/dynflow-1.6.4.gem
  packages/foreman/rubygem-dynflow/dynflow-1.6.5.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing, RPM

#7951 automatically set revision to 1 when bumping packages
  scripts/changelog.rb
Labels: Needs testing

#7950 Update dynflow dependency to 1.6.5
  dependencies/bullseye/dynflow/changelog
  dependencies/buster/dynflow/changelog
  dependencies/focal/dynflow/changelog
Labels: Needs testing

#7952 Update rubygem-dynflow to 1.6.6
  packages/foreman/rubygem-dynflow/dynflow-1.6.5.gem
  packages/foreman/rubygem-dynflow/dynflow-1.6.6.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Needs testing

#7953 Update dynflow dependency to 1.6.6
  dependencies/bullseye/dynflow/changelog
  dependencies/buster/dynflow/changelog
  dependencies/focal/dynflow/changelog
Labels: Needs testing

#7956 Update foreman-release to 3.2.1
  packages/foreman/foreman-installer/foreman-installer-3.2.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.2.1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.2.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.2.1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.2.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.2.1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.2.0.tar.bz2
  packages/foreman/foreman/foreman-3.2.1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#7955 Release 3.2.1
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: Needs testing, DEB, Stable branch

#7958 Update rubygem-audited to 4.10.0
  packages/foreman/rubygem-audited/audited-4.10.0.gem
  packages/foreman/rubygem-audited/audited-4.9.0.gem
  packages/foreman/rubygem-audited/rubygem-audited.spec
Labels: Needs testing

#7921 Fixes#34927 - incorrect argument error handling in katello-change-hos…
  packages/katello/katello/hostname-change.rb
  packages/katello/katello/katello.spec
Labels: Needs testing, RPM

#7913 Update ruby-foreman-templates to 9.3.0
  plugins/ruby-foreman-templates/debian/changelog
  plugins/ruby-foreman-templates/debian/gem.list
  plugins/ruby-foreman-templates/foreman_templates.rb
Labels: Needs testing

#7911 Update rubygem-foreman_templates to 9.3.0
  packages/plugins/rubygem-foreman_templates/foreman_templates-9.2.0.gem
  packages/plugins/rubygem-foreman_templates/foreman_templates-9.3.0.gem
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
Labels: Needs testing

#7964 rebuild foreman for new dynflow
  debian/bullseye/foreman/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman/changelog
Labels: Needs testing

#7965 Update rubygem-apipie-dsl to 2.5.0
  packages/foreman/rubygem-apipie-dsl/apipie-dsl-2.4.0.gem
  packages/foreman/rubygem-apipie-dsl/apipie-dsl-2.5.0.gem
  packages/foreman/rubygem-apipie-dsl/rubygem-apipie-dsl.spec
Labels: Needs testing

#7940 Update rubygem-pulpcore_client to 3.18.5
  packages/katello/rubygem-pulpcore_client/pulpcore_client-3.17.7.gem
  packages/katello/rubygem-pulpcore_client/pulpcore_client-3.18.5.gem
  packages/katello/rubygem-pulpcore_client/rubygem-pulpcore_client.spec
Labels: Needs testing, RPM

#7966 Update rubygem-foreman_puppet to 4.0.0
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-3.0.6.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-4.0.0.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing

#7967 Update foreman_puppet to 4.0.0 deb
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: Needs testing

#7968 Update foreman_puppet to 4.0.0 deb 3.3
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: Needs testing

#7969 Update rubygem-foreman_puppet to 4.0.0 rpm 3.3
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-3.0.6.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-4.0.0.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing

#7932 Update rubygem-smart_proxy_remote_execution_ssh to 0.7.0
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.6.0.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.7.0.gem
Labels: Needs testing

#7930 Update ruby-foreman-tasks to 6.0.2
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing

#7928 Update foreman_remote_execution to 7.0.0
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing

#7929 Update smart_proxy_remote_execution_ssh to 0.7.0
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: Needs testing

#7987 Updating rubygem-activerecord-nulldb-adapter to 0.7.0
  packages/foreman/rubygem-activerecord-nulldb-adapter/activerecord-nulldb-adapter-0.4.0.gem
  packages/foreman/rubygem-activerecord-nulldb-adapter/activerecord-nulldb-adapter-0.8.0.gem
  packages/foreman/rubygem-activerecord-nulldb-adapter/rubygem-activerecord-nulldb-adapter.spec
Labels: Needs testing, RPM

#7985 Update foreman-release to 3.3.0
  packages/foreman/foreman-installer/foreman-installer-3.3.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.3.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.3.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.3.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.3.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.3.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.3.0-rc1.tar.bz2
  packages/foreman/foreman/foreman-3.3.0-rc2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#7986 Release 3.3.0-rc2
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: Needs testing, Stable branch

#7988 Update rubygem-foreman_omaha to 5.0.1
  packages/plugins/rubygem-foreman_omaha/foreman_omaha-4.0.1.gem
  packages/plugins/rubygem-foreman_omaha/foreman_omaha-5.0.1.gem
  packages/plugins/rubygem-foreman_omaha/rubygem-foreman_omaha.spec
Labels: Needs testing, RPM, Stable branch

#7989 Update rubygem-foreman_omaha to 5.0.1
  packages/plugins/rubygem-foreman_omaha/foreman_omaha-4.0.1.gem
  packages/plugins/rubygem-foreman_omaha/foreman_omaha-5.0.1.gem
  packages/plugins/rubygem-foreman_omaha/rubygem-foreman_omaha.spec
Labels: Needs testing, RPM, Stable branch

#7990 Update rubygem-foreman_omaha to 5.0.1
  packages/plugins/rubygem-foreman_omaha/foreman_omaha-4.0.1.gem
  packages/plugins/rubygem-foreman_omaha/foreman_omaha-5.0.1.gem
  packages/plugins/rubygem-foreman_omaha/rubygem-foreman_omaha.spec
Labels: Needs testing, RPM, Stable branch

#7984 Set default value to empty list if no matrix is calculated
  .github/workflows/bump_packages.yml
Labels: Needs testing

#7991 Update rubygem-rack to 2.2.3.1
  packages/foreman/rubygem-rack/rack-2.2.3.1.gem
  packages/foreman/rubygem-rack/rack-2.2.3.gem
  packages/foreman/rubygem-rack/rubygem-rack.spec
Labels: Needs testing, RPM

#7774 Update rubygem-foreman_kernel_care to 1.1.1
  packages/katello/rubygem-foreman_kernel_care/foreman_kernel_care-1.0.0.gem
  packages/katello/rubygem-foreman_kernel_care/foreman_kernel_care-1.1.1.gem
  packages/katello/rubygem-foreman_kernel_care/rubygem-foreman_kernel_care.spec
Labels: Needs testing, RPM

#7992 Revert "Set default value to empty list if no matrix is calculated"
  .github/workflows/bump_packages.yml
Labels: Needs testing, Not yet reviewed

#7993 only run bump steps if matrix is not empty
  .github/workflows/bump_packages.yml
Labels: Needs testing, Not yet reviewed

#7997 Update rubygem-kafo to 6.4.1
  packages/foreman/rubygem-kafo/kafo-6.4.0.gem
  packages/foreman/rubygem-kafo/kafo-6.4.1.gem
  packages/foreman/rubygem-kafo/rubygem-kafo.spec
Labels: Needs testing

#7999 Update rubygem-kafo to 6.5.0
  packages/foreman/rubygem-kafo/kafo-6.4.1.gem
  packages/foreman/rubygem-kafo/kafo-6.5.0.gem
  packages/foreman/rubygem-kafo/rubygem-kafo.spec
Labels: Needs testing, RPM

#8000 Release kafo 6.5.0
  dependencies/bullseye/kafo/changelog
  dependencies/buster/kafo/changelog
  dependencies/focal/kafo/changelog
Labels: Needs testing

#7996 Updated hammer_cli_foreman_ansible to 0.4.0
  dependencies/bullseye/hammer_cli_foreman_ansible/changelog
  dependencies/buster/hammer_cli_foreman_ansible/changelog
  dependencies/focal/hammer_cli_foreman_ansible/changelog
Labels: Needs testing

#7970 Add katello-pull-transport-migrate RPM
  comps/comps-foreman-client-el8.xml
  comps/comps-foreman-client-rhel7.xml
  package_manifest.yaml
  packages/client/katello-pull-transport-migrate/katello-pull-transport-migrate-1.0.1.tar.gz
  packages/client/katello-pull-transport-migrate/katello-pull-transport-migrate.spec
  rel-eng/tito.props
Labels: Needs testing, RPM
