Repository theforeman/foreman-packaging, pull requests merged in 2022-08, with the labels that each got.

#8281 Bump hammer_cli_katello to match git
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Needs testing, Not yet reviewed, RPM

#8282 Update rubygem-smart_proxy_remote_execution_ssh to 0.7.1
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.7.0.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.7.1.gem
Labels: Needs testing, RPM, Stable branch

#8283 Update smart_proxy_remote_execution_ssh to 0.7.1
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: Needs testing, Stable branch

#8284 Update rubygem-friendly_id to 5.4.2
  packages/foreman/rubygem-friendly_id/friendly_id-5.3.0.gem
  packages/foreman/rubygem-friendly_id/friendly_id-5.4.2.gem
  packages/foreman/rubygem-friendly_id/rubygem-friendly_id.spec
Labels: Needs testing, Not yet reviewed, RPM

#8285 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#8286 Drop PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Needs testing, RPM

#8290 Updated foreman-ansible to 7.1.2
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing, DEB, Stable branch

#8289 Update rubygem-foreman_ansible to 7.1.2
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-7.1.1.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-7.1.2.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Needs testing, RPM, Stable branch

#8288 Update foreman_remote_execution to 7.1.1
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing, DEB, Stable branch

#8287 Update rubygem-foreman_remote_execution to 7.1.1
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-7.1.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-7.1.1.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM, Stable branch

#8292 Refs #35149 - Remove katello subdirectory from installer
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: Needs testing, RPM

#8280 Add smart-proxy into dependency calculation
  list_updatable_packages
Labels: Needs testing, RPM

#8321 Update keyring for 3.4
  debian/bullseye/foreman-release/theforeman-archive-keyring.asc
  debian/focal/foreman-release/theforeman-archive-keyring.asc
Labels: Needs testing

#8323 Update theforeman-archive-keyring.asc
  debian/bullseye/foreman-release/theforeman-archive-keyring.asc
  debian/focal/foreman-release/theforeman-archive-keyring.asc
Labels: Needs testing

#8324 Whitelist foreman-release for el7 client
  rel-eng/tito.props
Labels: Needs testing

#8318 Bump versions to 3.5-develop
  package_manifest.yaml
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
  rel-eng/releasers.conf
  rel-eng/tito.props
Labels: Needs testing

#8320 Foreman 3.4 build updates
  mock/el8.cfg
  package_manifest.yaml
  packages/foreman/foreman-release/foreman.gpg
  rel-eng/releasers.conf
  rel-eng/tito.props
  repoclosure/yum.conf
Labels: Needs testing

#8327 Update katello to 4.6.0-rc1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.6.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing

#8348 Skip nightly packages in listing updatable pkgs
  list_updatable_packages
Labels: Needs testing, RPM

#8350 use github not env context to get run details
  .github/workflows/bump_packages.yml
Labels: Needs testing

#8319 Bump versions to 3.5
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
Labels: Needs testing

#8352 Bump Katello to 4.7
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#8349 Fixes #35366 - make foreman-protector work as non-root
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#8353 only use X.Y version in sources file
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman-release/rules
Labels: Needs testing

#8351 Warn about conflicts in updating spec files
  list_updatable_packages
Labels: Needs testing, RPM

#8354 only use X.Y version in sources file
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman-release/rules
Labels: Needs testing

#8355 only use X.Y version in sources file - focal
  debian/focal/foreman-release/changelog
  debian/focal/foreman-release/rules
Labels: Needs testing, Not yet reviewed, DEB

#8357 only use X.Y version in sources file - focal
  debian/focal/foreman-release/changelog
  debian/focal/foreman-release/rules
Labels: Needs testing

#8356 Make list_updatable_packages Python 3.8 compatible
  list_updatable_packages
Labels: Needs testing

#8359 Remove rubygem-hirb*
  comps/comps-foreman-el8.xml
  package_manifest.yaml
  packages/foreman/rubygem-hirb-unicode-steakknife/hirb-unicode-steakknife-0.0.7.gem
  packages/foreman/rubygem-hirb-unicode-steakknife/rubygem-hirb-unicode-steakknife.spec
  packages/foreman/rubygem-hirb/hirb-0.7.0.gem
  packages/foreman/rubygem-hirb/rubygem-hirb.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#8366 Update rubygem-foreman_vault to 1.2.0
  packages/plugins/rubygem-foreman_vault/foreman_vault-1.1.0.gem
  packages/plugins/rubygem-foreman_vault/foreman_vault-1.2.0.gem
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
Labels: Needs testing, RPM

#8369 Update rubygem-foreman_vault to 1.2.0 (#8366)
  packages/plugins/rubygem-foreman_vault/foreman_vault-1.1.0.gem
  packages/plugins/rubygem-foreman_vault/foreman_vault-1.2.0.gem
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
Labels: Needs testing, RPM

#8367 Update rubygem-foreman_vault to 1.2.0 (#8366)
  packages/plugins/rubygem-foreman_vault/foreman_vault-1.1.0.gem
  packages/plugins/rubygem-foreman_vault/foreman_vault-1.2.0.gem
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
Labels: Needs testing, RPM

#8368 Update rubygem-foreman_vault to 1.2.0 (#8366)
  packages/plugins/rubygem-foreman_vault/foreman_vault-1.1.0.gem
  packages/plugins/rubygem-foreman_vault/foreman_vault-1.2.0.gem
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
Labels: Needs testing, RPM

#8370 explicitly vendor sinatra
  debian/bullseye/foreman/changelog
  debian/bullseye/foreman/rules
  debian/focal/foreman/changelog
  debian/focal/foreman/rules
Labels: Needs testing, DEB

#8362 Update rubygem-foreman_webhooks to 3.0.4
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-3.0.3.gem
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-3.0.4.gem
  packages/plugins/rubygem-foreman_webhooks/rubygem-foreman_webhooks.spec
Labels: Needs testing, RPM

#8363 Update rubygem-foreman_webhooks to 3.0.4
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-3.0.3.gem
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-3.0.4.gem
  packages/plugins/rubygem-foreman_webhooks/rubygem-foreman_webhooks.spec
Labels: Needs testing, RPM

#8364 Update rubygem-foreman_webhooks to 3.0.4
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-3.0.3.gem
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-3.0.4.gem
  packages/plugins/rubygem-foreman_webhooks/rubygem-foreman_webhooks.spec
Labels: Needs testing, RPM

#8371 add simplecov to exclude list
  gem2rpm/default.spec.erb
Labels: Needs testing, RPM

#8372 Add Salt automatic report upload reactor
  packages/plugins/rubygem-smart_proxy_salt/rubygem-smart_proxy_salt.spec
Labels: Needs testing, RPM

#8379 Drop /var/lib/foreman/tmp
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#8382 Refs #35409 - Include sprockets-based assets in plugin macros
  gem2rpm/foreman_plugin.spec.erb
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#8383 Refs #35409 - Include legacy assets in foreman_remote_execution
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#8377 Fixes #35409 - symlink legacy katello assets from foreman assets
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#8386 drop host_reports
  dependencies/bullseye/hammer_cli_foreman_host_reports/changelog
  dependencies/bullseye/hammer_cli_foreman_host_reports/control
  dependencies/bullseye/hammer_cli_foreman_host_reports/copyright
  dependencies/bullseye/hammer_cli_foreman_host_reports/ruby-hammer-cli-foreman-host-reports.docs
  dependencies/bullseye/hammer_cli_foreman_host_reports/rules
  dependencies/bullseye/hammer_cli_foreman_host_reports/source/format
  dependencies/bullseye/hammer_cli_foreman_host_reports/upstream/metadata
  dependencies/bullseye/hammer_cli_foreman_host_reports/watch
  dependencies/focal/hammer_cli_foreman_host_reports/changelog
  dependencies/focal/hammer_cli_foreman_host_reports/control
  dependencies/focal/hammer_cli_foreman_host_reports/copyright
  dependencies/focal/hammer_cli_foreman_host_reports/ruby-hammer-cli-foreman-host-reports.docs
  dependencies/focal/hammer_cli_foreman_host_reports/rules
  dependencies/focal/hammer_cli_foreman_host_reports/source/format
  dependencies/focal/hammer_cli_foreman_host_reports/upstream/metadata
  dependencies/focal/hammer_cli_foreman_host_reports/watch
  plugins/ruby-foreman-host-reports/debian/changelog
  plugins/ruby-foreman-host-reports/debian/compat
  plugins/ruby-foreman-host-reports/debian/control
  plugins/ruby-foreman-host-reports/debian/copyright
  plugins/ruby-foreman-host-reports/debian/gem.list
  plugins/ruby-foreman-host-reports/debian/install
  plugins/ruby-foreman-host-reports/debian/postinst
  plugins/ruby-foreman-host-reports/debian/rules
  plugins/ruby-foreman-host-reports/debian/source/format
  plugins/ruby-foreman-host-reports/foreman_host_reports.rb
  plugins/smart_proxy_reports/changelog
  plugins/smart_proxy_reports/compat
  plugins/smart_proxy_reports/control
  plugins/smart_proxy_reports/copyright
  plugins/smart_proxy_reports/install
  plugins/smart_proxy_reports/reports.rb
  plugins/smart_proxy_reports/ruby-smart-proxy-reports.docs
  plugins/smart_proxy_reports/rules
  plugins/smart_proxy_reports/source/format
  plugins/smart_proxy_reports/watch
Labels: Needs testing

#8380 Update rubygem-net-ssh to 7.0.1
  packages/foreman/rubygem-net-ssh/net-ssh-4.2.0.gem
  packages/foreman/rubygem-net-ssh/net-ssh-7.0.1.gem
  packages/foreman/rubygem-net-ssh/rubygem-net-ssh.spec
Labels: Needs testing, Not yet reviewed, RPM

#8387 Refs #35422 - Update rubygem-audited to 5.0.2
  packages/foreman/rubygem-audited/audited-4.10.0.gem
  packages/foreman/rubygem-audited/audited-5.0.2.gem
  packages/foreman/rubygem-audited/rubygem-audited.spec
Labels: Needs testing, RPM

#8388 Fixes #35423 - Update rubygem-ancestry to 4.2.0
  packages/foreman/rubygem-ancestry/ancestry-3.2.1.gem
  packages/foreman/rubygem-ancestry/ancestry-4.2.0.gem
  packages/foreman/rubygem-ancestry/rubygem-ancestry.spec
Labels: Needs testing, Not yet reviewed, RPM

#8394 Release ansible-collection-theforeman-foreman 3.5.0
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: Needs testing

#8393 Release ansible-collection-theforeman-foreman 3.5.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.4.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.5.0.tar.gz
Labels: Needs testing, RPM

#8397 Fixes #35264 - Update rubygem-net-ssh to 6.1.0
  packages/foreman/rubygem-net-ssh/net-ssh-6.1.0.gem
  packages/foreman/rubygem-net-ssh/net-ssh-7.0.1.gem
  packages/foreman/rubygem-net-ssh/rubygem-net-ssh.spec
Labels: Needs testing

#8390 drop host_reports
  dependencies/bullseye/hammer_cli_foreman_host_reports/changelog
  dependencies/bullseye/hammer_cli_foreman_host_reports/control
  dependencies/bullseye/hammer_cli_foreman_host_reports/copyright
  dependencies/bullseye/hammer_cli_foreman_host_reports/ruby-hammer-cli-foreman-host-reports.docs
  dependencies/bullseye/hammer_cli_foreman_host_reports/rules
  dependencies/bullseye/hammer_cli_foreman_host_reports/source/format
  dependencies/bullseye/hammer_cli_foreman_host_reports/upstream/metadata
  dependencies/bullseye/hammer_cli_foreman_host_reports/watch
  dependencies/focal/hammer_cli_foreman_host_reports/changelog
  dependencies/focal/hammer_cli_foreman_host_reports/control
  dependencies/focal/hammer_cli_foreman_host_reports/copyright
  dependencies/focal/hammer_cli_foreman_host_reports/ruby-hammer-cli-foreman-host-reports.docs
  dependencies/focal/hammer_cli_foreman_host_reports/rules
  dependencies/focal/hammer_cli_foreman_host_reports/source/format
  dependencies/focal/hammer_cli_foreman_host_reports/upstream/metadata
  dependencies/focal/hammer_cli_foreman_host_reports/watch
  plugins/ruby-foreman-host-reports/debian/changelog
  plugins/ruby-foreman-host-reports/debian/compat
  plugins/ruby-foreman-host-reports/debian/control
  plugins/ruby-foreman-host-reports/debian/copyright
  plugins/ruby-foreman-host-reports/debian/gem.list
  plugins/ruby-foreman-host-reports/debian/install
  plugins/ruby-foreman-host-reports/debian/postinst
  plugins/ruby-foreman-host-reports/debian/rules
  plugins/ruby-foreman-host-reports/debian/source/format
  plugins/ruby-foreman-host-reports/foreman_host_reports.rb
  plugins/smart_proxy_reports/changelog
  plugins/smart_proxy_reports/compat
  plugins/smart_proxy_reports/control
  plugins/smart_proxy_reports/copyright
  plugins/smart_proxy_reports/install
  plugins/smart_proxy_reports/reports.rb
  plugins/smart_proxy_reports/ruby-smart-proxy-reports.docs
  plugins/smart_proxy_reports/rules
  plugins/smart_proxy_reports/source/format
  plugins/smart_proxy_reports/watch
Labels: Needs testing, DEB, Stable branch

#8399 Update foreman-release to 3.4.0
  packages/foreman/foreman-installer/foreman-installer-3.4.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.4.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.4.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.4.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.4.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.4.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.4.0-rc1.tar.bz2
  packages/foreman/foreman/foreman-3.4.0-rc2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#8395 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#8404 Don't ship the vendor dir, it's only need during build
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM

#8402 Release ansible-collection-theforeman-foreman 3.5.0
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: Needs testing, DEB, Stable branch

#8403 Release ansible-collection-theforeman-foreman 3.5.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.4.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.5.0.tar.gz
Labels: Needs testing, Stable branch

#8398 Update rubygem-pulpcore_client to 3.18.8
  packages/katello/rubygem-pulpcore_client/pulpcore_client-3.18.5.gem
  packages/katello/rubygem-pulpcore_client/pulpcore_client-3.18.8.gem
  packages/katello/rubygem-pulpcore_client/rubygem-pulpcore_client.spec
Labels: Needs testing, RPM

#8317 Update rubygem-foreman_kernel_care to 1.1.1
  packages/katello/rubygem-foreman_kernel_care/foreman_kernel_care-1.0.0.gem
  packages/katello/rubygem-foreman_kernel_care/foreman_kernel_care-1.1.1.gem
  packages/katello/rubygem-foreman_kernel_care/rubygem-foreman_kernel_care.spec
Labels: Needs testing

#8411 Update foreman's rails-i18n dependency
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, Not yet reviewed, RPM

#8291 Fetch gems for Ruby platform when adding
  add_gem_package.sh
Labels: Needs testing, RPM

#8422 Refs #34647 - Update rubygem-apipie-rails to 0.8.1
  packages/foreman/rubygem-apipie-rails/apipie-rails-0.5.20.gem
  packages/foreman/rubygem-apipie-rails/apipie-rails-0.8.1.gem
  packages/foreman/rubygem-apipie-rails/rubygem-apipie-rails.spec
Labels: Needs testing, After core merge, RPM

#8426 Update foreman package dependencies
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#8430 Drop unused rubygem-net-ssh-krb
  comps/comps-foreman-plugins-el8.xml
  package_manifest.yaml
  packages/plugins/rubygem-net-ssh-krb/net-ssh-krb-0.4.0.gem
  packages/plugins/rubygem-net-ssh-krb/rubygem-net-ssh-krb.spec
  rel-eng/tito.props
Labels: Needs testing

#8425 Refs #29539 - Depend on websockify if needed
  debian/bullseye/foreman/control
  debian/focal/foreman/control
Labels: Needs testing

#8427 Update katello to 4.6.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.6.0.rc1.gem
  packages/katello/rubygem-katello/katello-4.6.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#8435 Fixes #35461 - Require /usr/sbin/sendmail to be available
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#8436 Fixes #35461 - Require /usr/sbin/sendmail to be available
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#8437 Fixes #35461 - Require /usr/sbin/sendmail to be available
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#8438 Update katello package dependencies
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM
