Repository theforeman/foreman-packaging, pull requests merged in 2022-02, with the labels that each got.

#7530 Update rubygem-foreman_openscap to 5.2.1
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-5.2.0.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-5.2.1.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, RPM

#7555 Add module_hotfixes=1 to katello nighlty el8 repo
  repoclosure/yum.conf
Labels: Needs testing, RPM

#7553 Use centos vault for el8 content
  repoclosure/yum.conf
Labels: Needs testing, RPM, Stable branch

#7533 Update rubygem-foreman_scc_manager to 1.8.17
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.16.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.17.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM

#7172 Add yggdrasil package
  comps/comps-foreman-client-el8.xml
  comps/comps-foreman-client-rhel7.xml
  package_manifest.yaml
  packages/client/yggdrasil/Use-gzip-c-instead-of-k.patch
  packages/client/yggdrasil/build-Remove-the-Makefile-preamble.patch
  packages/client/yggdrasil/yggdrasil-0.2.0.tar.gz
  packages/client/yggdrasil/yggdrasil.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#7559 Update rubygem-foreman_maintain to 1.0.3
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.0.2.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.0.3.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#7534 Update rubygem-foreman_scc_manager to 1.8.17 Foreman 3.1
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.16.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.17.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM, Stable branch

#7535 Update rubygem-foreman_scc_manager to 1.8.17 Foreman 3.0
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.16.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.17.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM, Stable branch

#7562 Fixup 2.5 repoclosure file
  repoclosure/yum.conf
Labels: Needs testing, RPM, Stable branch

#7563 Update katello-host-tools spec python macros
  packages/client/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#7542 Updated hammer_cli to 3.1.1
  dependencies/buster/hammer_cli/changelog
  dependencies/focal/hammer_cli/changelog
Labels: Needs testing, Not yet reviewed, Stable branch

#7541 Updated hammer_cli to 3.0.2
  dependencies/bionic/hammer_cli/changelog
  dependencies/buster/hammer_cli/changelog
  dependencies/focal/hammer_cli/changelog
Labels: Needs testing, Not yet reviewed, Stable branch

#7538 Updated hammer_cli_foreman to 2.5.2
  dependencies/bionic/hammer_cli_foreman/changelog
  dependencies/buster/hammer_cli_foreman/changelog
  dependencies/focal/hammer_cli_foreman/changelog
Labels: Needs testing, Not yet reviewed, Stable branch

#7551 Update smart_proxy_ansible to 3.2.2
  plugins/smart_proxy_ansible/ansible.rb
  plugins/smart_proxy_ansible/changelog
Labels: Needs testing, Not yet reviewed

#7549 Update smart_proxy_remote_execution_ssh to 0.5.2
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: Needs testing, Not yet reviewed

#7565 Update ruby-foreman-templates to 9.2.0
  plugins/ruby-foreman-templates/debian/changelog
  plugins/ruby-foreman-templates/debian/gem.list
  plugins/ruby-foreman-templates/foreman_templates.rb
Labels: Needs testing, Not yet reviewed, DEB

#7561 Update rubygem-sequel to 5.53.0
  packages/foreman/rubygem-sequel/rubygem-sequel.spec
  packages/foreman/rubygem-sequel/sequel-5.42.0.gem
  packages/foreman/rubygem-sequel/sequel-5.53.0.gem
Labels: Needs testing, Not yet reviewed, RPM

#7558 Update rubygem-smart_proxy_ansible to 3.3.1
  plugins/smart_proxy_ansible/ansible.rb
  plugins/smart_proxy_ansible/changelog
Labels: Needs testing, Not yet reviewed, DEB

#7557 Update rubygem-smart_proxy_ansible to 3.3.1
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-3.3.0.gem
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-3.3.1.gem
Labels: Needs testing, Not yet reviewed, RPM

#7528 Bump rubygem-foreman_rh_cloud to 5.0.31-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-5.0.30.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-5.0.31.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM

#7566 Add in epoch to ensure priority over distro packages
  packages/foreman/rubygem-sinatra/rubygem-sinatra.spec
Labels: Needs testing, RPM

#7568 Update rubygem-foreman_puppet to 2.0.3
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-2.0.0.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-2.0.3.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Needs testing, Not yet reviewed

#7570 Release hammer-cli and hammer-cli-foreman 3.2.0
  packages/foreman/rubygem-hammer_cli/hammer_cli-3.2.0.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-3.2.0.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Needs testing, Not yet reviewed

#7569 Release hammer-cli and hammer-cli-foreman 3.2.0
  dependencies/bullseye/hammer_cli/changelog
  dependencies/bullseye/hammer_cli_foreman/changelog
  dependencies/bullseye/hammer_cli_foreman/control
  dependencies/buster/hammer_cli/changelog
  dependencies/buster/hammer_cli_foreman/changelog
  dependencies/buster/hammer_cli_foreman/control
  dependencies/focal/hammer_cli/changelog
  dependencies/focal/hammer_cli_foreman/changelog
  dependencies/focal/hammer_cli_foreman/control
Labels: Needs testing, Not yet reviewed

#7547 [rpm/3.1] - Update rubygem-foreman_openscap to 5.1.1
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-5.1.0.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-5.1.1.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing, Stable branch

#7573 Update configurations up to 3.2 and 4.4
  mock/el7-nonscl.cfg
  mock/el7-scl.cfg
  mock/el8.cfg
  package_manifest.yaml
  packages/foreman/foreman-release/foreman.gpg
  rel-eng/releasers.conf
  rel-eng/tito.props
  repoclosure/yum.conf
Labels: Needs testing, RPM, Stable branch

#7571 Update to foreman 3.3.0
  package_manifest.yaml
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
  rel-eng/releasers.conf
  rel-eng/tito.props
Labels: Needs testing, RPM

#7572 Bump packages to 3.3.0
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: Needs testing

#7574 Remove fedora29 from releasers config
  add_gem_package.sh
  package_manifest.yaml
  rel-eng/releasers.conf
  rel-eng/tito.props
Labels: Needs testing, RPM

#7581 Remove fedora29 from 3.2 rpm branch
  add_gem_package.sh
  package_manifest.yaml
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7580 Release 3.2.0-rc1
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman/changelog
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: Needs testing, Not yet reviewed

#7584 Update katello to 4.4.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.4.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7590 make installer explicitly depend on hostname
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: Needs testing, RPM

#7602 Standardize go_arches for yggdrasil
  packages/client/yggdrasil/yggdrasil.spec
Labels: Needs testing, RPM

#7576 Update rubygem-smart_proxy_salt to 5.0.0
  packages/plugins/rubygem-smart_proxy_salt/rubygem-smart_proxy_salt.spec
  packages/plugins/rubygem-smart_proxy_salt/smart_proxy_salt-4.0.0.gem
  packages/plugins/rubygem-smart_proxy_salt/smart_proxy_salt-5.0.0.gem
Labels: Needs testing, Not yet reviewed, RPM

#7583 Update ruby-foreman-statistics to 2.0.1
  plugins/ruby-foreman-statistics/debian/changelog
  plugins/ruby-foreman-statistics/debian/gem.list
  plugins/ruby-foreman-statistics/foreman_statistics.rb
Labels: Needs testing, Not yet reviewed

#7578 Update smart_proxy_salt to 5.0.0
  plugins/smart_proxy_salt/changelog
  plugins/smart_proxy_salt/salt.rb
Labels: Needs testing, Not yet reviewed

#7606 Release 3.1.2
  debian/buster/foreman-installer/changelog
  debian/buster/foreman-proxy/changelog
  debian/buster/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman/changelog
Labels: Needs testing, Stable branch

#7605 Update foreman-release to 3.1.2
  packages/foreman/foreman-installer/foreman-installer-3.1.1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.1.2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.1.1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.1.2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.1.1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.1.2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.1.1.tar.bz2
  packages/foreman/foreman/foreman-3.1.2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#7529 Bump rubygem-foreman_rh_cloud to 5.0.31-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-5.0.29.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-5.0.31.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM

#7519 Update rubygem-foreman-tasks to 5.2.1
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-5.2.0.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-5.2.1.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7540 Update rubygem-hammer_cli to 3.1.1
  packages/foreman/rubygem-hammer_cli/hammer_cli-3.1.0.gem
  packages/foreman/rubygem-hammer_cli/hammer_cli-3.1.1.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7598 Update smart_proxy_remote_execution_ssh to 0.5.2
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: Needs testing, Not yet reviewed

#7597 Update rubygem-smart_proxy_remote_execution_ssh to 0.5.2
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.5.1.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.5.2.gem
Labels: Needs testing, RPM, Stable branch

#7599 Update rubygem-smart_proxy_dynflow to 0.6.2
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.6.1.gem
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.6.2.gem
Labels: Needs testing, Stable branch

#7607 Compatibility with semver < 2.7.0
  update-requirements
Labels: Needs testing, RPM

#7596 Update smart_proxy_dynflow to 0.7.0
  plugins/smart_proxy_dynflow/changelog
  plugins/smart_proxy_dynflow/dynflow.rb
Labels: Needs testing

#7586 Update rubygem-smart_proxy_reports to 1.0.0
  packages/plugins/rubygem-smart_proxy_reports/rubygem-smart_proxy_reports.spec
  packages/plugins/rubygem-smart_proxy_reports/smart_proxy_reports-0.0.7.gem
  packages/plugins/rubygem-smart_proxy_reports/smart_proxy_reports-1.0.0.gem
Labels: Needs testing, RPM

#7595 Update rubygem-smart_proxy_dynflow to 0.7.0
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.6.1.gem
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.7.0.gem
Labels: Needs testing

#7615 Move repoclosure for 3.1 from vault to stream-8
  package_manifest.yaml
  repoclosure/yum.conf
Labels: Needs testing, RPM, Stable branch

#7619 Fixes #34507 - Drop Foreman's nodejs dependency
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#7627 Cleaning Vault mirror and moving to Centos 8 Stream
  package_manifest.yaml
  repoclosure/yum.conf
Labels: Needs testing, RPM

#7628 Cleaning Vault mirror and moving to Centos 8 Stream
  package_manifest.yaml
  repoclosure/yum.conf
Labels: Needs testing, RPM, Stable branch

#7626 Cleaning Vault mirror and moving to Centos 8 Stream
  package_manifest.yaml
  repoclosure/yum.conf
Labels: Needs testing, RPM, Stable branch

#7622 Fixes #34507 - Drop Foreman's nodejs dependency
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#7629 Updated hammer_cli_foreman to 3.1.0
  dependencies/buster/hammer_cli_foreman/changelog
  dependencies/buster/hammer_cli_foreman/control
  dependencies/focal/hammer_cli_foreman/changelog
  dependencies/focal/hammer_cli_foreman/control
Labels: Needs testing, Stable branch

#7630 Fix typo in katello tag
  rel-eng/tito.props
Labels: Needs testing, Stable branch

#7624 Fixes #34507 - Drop Foreman's nodejs dependency
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#7623 Fixes #34507 - Drop Foreman's nodejs dependency
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM, Stable branch

#7621 Update rubygem-pulp_rpm_client to 3.17.3
  packages/katello/rubygem-pulp_rpm_client/pulp_rpm_client-3.16.1.gem
  packages/katello/rubygem-pulp_rpm_client/pulp_rpm_client-3.17.4.gem
  packages/katello/rubygem-pulp_rpm_client/rubygem-pulp_rpm_client.spec
Labels: Needs testing, RPM

#7634 bump openscap compatibility again - 1.3.6 is OK
  packages/plugins/rubygem-openscap/rubygem-openscap.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7637 Update ruby-foreman-puppet to 2.0.4
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: Needs testing, Not yet reviewed

#7636 Update ruby-foreman-puppet to 3.0.3
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: Needs testing, Not yet reviewed, DEB

#7618 Add rubygem-hammer_cli_foreman_host_reports package
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-rhel7.xml
  package_manifest.yaml
  packages/plugins/rubygem-hammer_cli_foreman_host_reports/hammer_cli_foreman_host_reports-0.1.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_host_reports/rubygem-hammer_cli_foreman_host_reports.spec
  rel-eng/tito.props
Labels: Needs testing, RPM

#7642 Update dynflow dependency to 1.6.4
  dependencies/bullseye/dynflow/changelog
  dependencies/buster/dynflow/changelog
  dependencies/focal/dynflow/changelog
Labels: Needs testing

#7617 Update smart_proxy_dynflow to 0.7.0
  plugins/smart_proxy_dynflow/changelog
  plugins/smart_proxy_dynflow/dynflow.rb
Labels: Needs testing, Not yet reviewed

#7616 Update rubygem-smart_proxy_dynflow to 0.7.0
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.6.1.gem
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.7.0.gem
Labels: Needs testing, Not yet reviewed

#7603 Update rubygem-foreman_host_reports to 1.0.1
  packages/plugins/rubygem-foreman_host_reports/foreman_host_reports-0.0.4.gem
  packages/plugins/rubygem-foreman_host_reports/foreman_host_reports-1.0.1.gem
  packages/plugins/rubygem-foreman_host_reports/rubygem-foreman_host_reports.spec
Labels: Needs testing, Not yet reviewed, RPM

#7643 bump pulp-rpm bindings requires for katello
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM
