Repository theforeman/foreman-packaging, pull requests merged in 2022-11, with the labels that each got.

#8675 Update rubygem-foreman_monitoring to 3.0.0
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-2.1.0.gem
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-3.0.0.gem
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
Labels: RPM

#8674 Release rubygem-foreman_maintain 1.2.0
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.1.8.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.2.0.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: RPM

#8676 Update rubygem-foreman_monitoring to 3.0.0
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-2.1.0.gem
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-3.0.0.gem
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
Labels: RPM

#8677 Update ruby-foreman-monitoring to 3.0.0
  plugins/ruby-foreman-monitoring/debian/changelog
  plugins/ruby-foreman-monitoring/debian/gem.list
  plugins/ruby-foreman-monitoring/foreman_monitoring.rb
Labels: DEB

#8678 Update ruby-foreman-monitoring to 3.0.0
  plugins/ruby-foreman-monitoring/debian/changelog
  plugins/ruby-foreman-monitoring/debian/gem.list
  plugins/ruby-foreman-monitoring/foreman_monitoring.rb
Labels: DEB, Stable branch

#8680 Update rubygem-foreman_bootdisk to 19.0.7
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-19.0.5.gem
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-19.0.7.gem
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
Labels: RPM, Stable branch

#8679 Update rubygem-foreman_discovery to 21.0.4
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-21.0.1.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-21.0.4.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: RPM, Stable branch

#8681 Update rubygem-foreman_bootdisk to 21.0.2
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-21.0.0.gem
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-21.0.2.gem
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
Labels: RPM

#8695 Update rubygem-puppetdb_foreman to 6.0.1
  packages/plugins/rubygem-puppetdb_foreman/puppetdb_foreman-6.0.0.gem
  packages/plugins/rubygem-puppetdb_foreman/puppetdb_foreman-6.0.1.gem
  packages/plugins/rubygem-puppetdb_foreman/rubygem-puppetdb_foreman.spec
Labels: Not yet reviewed

#8696 Update ruby-puppetdb-foreman to 6.0.1
  plugins/ruby-puppetdb-foreman/debian/changelog
  plugins/ruby-puppetdb-foreman/debian/gem.list
  plugins/ruby-puppetdb-foreman/puppetdb_foreman.rb
Labels: Not yet reviewed

#8700 add back pulp_ostree_client source
  packages/katello/rubygem-pulp_ostree_client/pulp_ostree_client-2.0.0a1.gem
Labels: RPM

#8703 Update rubygem-foreman_host_extra_validator to 0.2.1
  packages/plugins/rubygem-foreman_host_extra_validator/foreman_host_extra_validator-0.2.0.gem
  packages/plugins/rubygem-foreman_host_extra_validator/foreman_host_extra_validator-0.2.1.gem
  packages/plugins/rubygem-foreman_host_extra_validator/rubygem-foreman_host_extra_validator.spec
Labels: RPM

#8666 Refs #35088 - Remove foreman-gce and mark foreman_google as replacement
  comps/comps-foreman-el8.xml
  packages/foreman/foreman/foreman.spec
  packages/plugins/rubygem-foreman_google/rubygem-foreman_google.spec
Labels: RPM

#8667 Refs #35088 - Replace foreman_gce with foreman_google
  debian/bullseye/foreman/changelog
  debian/bullseye/foreman/control
  debian/bullseye/foreman/foreman-gce.install
  debian/bullseye/foreman/foreman-gce.postinst
  debian/focal/foreman/changelog
  debian/focal/foreman/control
  debian/focal/foreman/foreman-gce.install
  debian/focal/foreman/foreman-gce.postinst
  plugins/ruby-foreman-google/debian/changelog
  plugins/ruby-foreman-google/debian/control
Labels: DEB

#8579 Allow foreman-ygg-worker to work with newer yggdrasil
  packages/client/foreman_ygg_worker/foreman_ygg_worker.spec
Labels: RPM

#8715 Update ruby-foreman-discovery to 21.0.4
  plugins/ruby-foreman-discovery/debian/changelog
  plugins/ruby-foreman-discovery/debian/gem.list
  plugins/ruby-foreman-discovery/foreman_discovery.rb
Labels: DEB

#8706 Remove json >= 2.5 dependency
  packages/foreman/rubygem-gitlab-sidekiq-fetcher/rubygem-gitlab-sidekiq-fetcher.spec
Labels: RPM

#8716 vendor faraday
  debian/bullseye/foreman/changelog
  debian/bullseye/foreman/rules
  debian/focal/foreman/changelog
  debian/focal/foreman/rules
Labels: DEB

#8711 Update ruby-foreman-google to 1.0.0
  plugins/ruby-foreman-google/debian/changelog
  plugins/ruby-foreman-google/debian/gem.list
  plugins/ruby-foreman-google/foreman_google.rb
Labels: DEB

#8717 Bump develop to 3.6.0-develop
  package_manifest.yaml
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: RPM

#8723 Update rubygem-foreman_ansible to 10.1.0
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-10.0.1.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-10.1.0.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: RPM

#8724 Update ruby-foreman-ansible to 10.1.0
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: DEB

#8729 bump katello related packages to their 4.8 versions
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed

#8741 Release hammer_cli_katello 1.7.0
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Not yet reviewed

#8740 Update ruby-foreman-remote-execution to 8.1.0
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/control
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Not yet reviewed

#8744 Update rubygem-foreman_ansible to 10.1.0
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-10.0.1.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-10.1.0.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: RPM, Stable branch

#8745 Updated foreman-ansible to 10.1.0
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Stable branch

#8748 drop fog-google from packaging
  comps/comps-foreman-el8.xml
  package_manifest.yaml
  packages/foreman/rubygem-fog-google/fog-google-1.19.0.gem
  packages/foreman/rubygem-fog-google/rubygem-fog-google.spec
Labels: Not yet reviewed

#8762 Fixes #35756 - do not use --disable-system-checks as it is gone
  packages/katello/katello/hostname-change.rb
Labels: RPM

#8759 Update rubygem-foreman_scc_manager to 2.1.0
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-2.0.0.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-2.1.0.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: RPM

#8757 Update rubygem-smart_proxy_remote_execution_ssh to 0.9.0
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.8.0.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.9.0.gem
Labels: RPM

#8764 Fixes #35756 - do not use --disable-system-checks as it is gone
  packages/katello/katello/hostname-change.rb
  packages/katello/katello/katello.spec
Labels: RPM

#8763 Fixes #35756 - do not use --disable-system-checks as it is gone
  packages/katello/katello/hostname-change.rb
Labels: RPM

#8766 Update ruby-smart-proxy-remote-execution-ssh to 0.9.0
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: DEB, Stable branch

#8785 Update rubygem-foreman_maintain to 1.2.1
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.2.0.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.2.1.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Not yet reviewed

#8790 Use python39 packages with ansible-core 2.13+
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
Labels: Not yet reviewed, RPM, Stable branch

#8791 Update rubygem-foreman_puppet to 5.0.0
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-4.0.3.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-5.0.0.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: RPM

#8799 Update foreman-maintain to 1.2.1
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.2.0.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.2.1.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: RPM, Stable branch

#8800 Update rubygem-foreman_maintain to 1.2.1
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.2.0.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.2.1.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: RPM, Stable branch

#8803 Release 3.4.1
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
Labels: Stable branch

#8802 Release 3.4.1
  packages/foreman/foreman-installer/foreman-installer-3.4.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.4.1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.4.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.4.1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.4.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.4.1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.4.0.tar.bz2
  packages/foreman/foreman/foreman-3.4.1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: RPM, Stable branch

#8801 Update rubygem-smart_proxy_salt to 5.0.1
  packages/plugins/rubygem-smart_proxy_salt/rubygem-smart_proxy_salt.spec
  packages/plugins/rubygem-smart_proxy_salt/smart_proxy_salt-5.0.0.gem
  packages/plugins/rubygem-smart_proxy_salt/smart_proxy_salt-5.0.1.gem
Labels: RPM

#8807 Use _sharedstatedir macro in smart proxy plugin template
  gem2rpm/smart_proxy_plugin.spec.erb
Labels: RPM

#8806 Update katello to 4.7.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.7.0.rc1.gem
  packages/katello/rubygem-katello/katello-4.7.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM
