Repository theforeman/foreman-packaging, pull requests merged in 2022-04, with the labels that each got.

#7778 Update rubygem-smart_proxy_remote_execution_ssh to 0.5.3
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.5.2.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.5.3.gem
Labels: Needs testing, RPM, Stable branch

#7770 Update ruby-foreman-tasks to 6.0.1
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing

#7769 Update rubygem-foreman-tasks to 6.0.1
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-6.0.0.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-6.0.1.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing

#7787 Release ansible-collection-theforeman-foreman 3.3.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.2.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.3.0.tar.gz
Labels: Needs testing

#7788 Release ansible-collection-theforeman-foreman 3.3.0 [DEB]
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: Needs testing

#7786 Update smart_proxy_remote_execution_ssh to 0.5.3
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: Needs testing, DEB, Stable branch

#7784 Update rubygem-smart_proxy_remote_execution_ssh to 0.5.3
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.5.2.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.5.3.gem
Labels: Needs testing, RPM, Stable branch

#7783 Update rubygem-foreman-tasks to 6.0.1
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-6.0.0.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-6.0.1.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM, Stable branch

#7785 Update ruby-foreman-tasks to 6.0.1
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Stable branch

#7782 Update foreman_remote_execution to 5.0.5
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing, DEB, Stable branch

#7790 Update rubygem-qpid_proton to 0.37.0
  packages/katello/rubygem-qpid_proton/qpid_proton-0.36.0.gem
  packages/katello/rubygem-qpid_proton/qpid_proton-0.37.0.gem
  packages/katello/rubygem-qpid_proton/rubygem-qpid_proton.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7775 Update Katello to 4.4.0.1
  packages/katello/rubygem-katello/katello-4.4.0.1.gem
  packages/katello/rubygem-katello/katello-4.4.0.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#7792 Update rubygem-qpid_proton to 0.37.0
  packages/katello/rubygem-qpid_proton/qpid_proton-0.36.0.gem
  packages/katello/rubygem-qpid_proton/qpid_proton-0.37.0.gem
  packages/katello/rubygem-qpid_proton/rubygem-qpid_proton.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7791 Update rubygem-qpid_proton to 0.37.0
  packages/katello/rubygem-qpid_proton/qpid_proton-0.36.0.gem
  packages/katello/rubygem-qpid_proton/qpid_proton-0.37.0.gem
  packages/katello/rubygem-qpid_proton/rubygem-qpid_proton.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7765 Update katello to 4.3.1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.3.0.gem
  packages/katello/rubygem-katello/katello-4.3.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#7797 Update to Katello 4.4.0.2
  packages/katello/rubygem-katello/katello-4.4.0.1.gem
  packages/katello/rubygem-katello/katello-4.4.0.2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7798 Rebuild katello 4.4.0.2
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing, RPM, Stable branch

#7796 Bump foreman salt to 15.1.0
  plugins/ruby-foreman-salt/debian/changelog
  plugins/ruby-foreman-salt/debian/gem.list
  plugins/ruby-foreman-salt/foreman_salt.rb
Labels: Needs testing

#7799 Update smart_proxy_remote_execution_ssh identity directory permission…
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
Labels: Needs testing, RPM

#7794 Bump nightly Katello to use Pulpcore 3.17 repos
  packages/katello/katello-repos/katello-repos.spec
Labels: Needs testing, RPM

#7757 Update rubygem-foreman_maintain to 1.0.5
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.0.6.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.0.7.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#7800 Bump rubygem-foreman_rh_cloud to 5.0.33-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-5.0.32.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-5.0.33.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM

#7802 Bump rubygem-foreman_rh_cloud to 5.0.33-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-5.0.32.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-5.0.33.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, Not yet reviewed, RPM

#7801 Bump rubygem-foreman_rh_cloud to 5.0.33-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-5.0.32.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-5.0.33.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM, Stable branch

#7781 Update rubygem-foreman_remote_execution to 5.0.5
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-5.0.3.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-5.0.5.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, Not yet reviewed, RPM, Stable branch

#7807 Require nftables for newer than EL7 operating systems
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#7808 Release katello-client-bootstrap 1.7.9
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.8.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap-1.7.9.tar.gz
  packages/katello/katello-client-bootstrap/katello-client-bootstrap.spec
Labels: Needs testing, RPM

#7806 Update smart_proxy_remote_execution_ssh to 0.6.0
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: Needs testing

#7805 Update rubygem-smart_proxy_remote_execution_ssh to 0.6.0
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.5.2.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.6.0.gem
Labels: Needs testing, RPM

#7804 Update foreman_remote_execution to 6.2.0
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Needs testing

#7803 Update rubygem-foreman_remote_execution to 6.2.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-6.1.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-6.2.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Needs testing, RPM

#7821 Fixes #34641 - Stop generating apipie cache for Foreman
  packages/foreman/foreman/foreman.spec
Labels: Needs testing, RPM

#7822 Refs #34641 - drop apipie generation
  debian/bullseye/foreman/changelog
  debian/bullseye/foreman/foreman-plugin.mk
  debian/bullseye/foreman/foreman-plugin.postinst-lib
  debian/bullseye/foreman/foreman.postinst
  debian/bullseye/foreman/rules
  debian/buster/foreman/changelog
  debian/buster/foreman/foreman-plugin.mk
  debian/buster/foreman/foreman-plugin.postinst-lib
  debian/buster/foreman/foreman.postinst
  debian/buster/foreman/rules
  debian/focal/foreman/changelog
  debian/focal/foreman/foreman-plugin.mk
  debian/focal/foreman/foreman-plugin.postinst-lib
  debian/focal/foreman/foreman.postinst
  debian/focal/foreman/rules
  plugins/ruby-foreman-ansible/debian/install
  plugins/ruby-foreman-azure-rm/debian/changelog
  plugins/ruby-foreman-azure-rm/debian/install
  plugins/ruby-foreman-azure-rm/debian/rules
  plugins/ruby-foreman-bootdisk/debian/install
  plugins/ruby-foreman-discovery/debian/changelog
  plugins/ruby-foreman-discovery/debian/install
  plugins/ruby-foreman-discovery/debian/rules
  plugins/ruby-foreman-expire-hosts/debian/changelog
  plugins/ruby-foreman-expire-hosts/debian/install
  plugins/ruby-foreman-expire-hosts/debian/rules
  plugins/ruby-foreman-fog-proxmox/debian/changelog
  plugins/ruby-foreman-fog-proxmox/debian/install
  plugins/ruby-foreman-fog-proxmox/debian/rules
  plugins/ruby-foreman-host-reports/debian/install
  plugins/ruby-foreman-monitoring/debian/changelog
  plugins/ruby-foreman-monitoring/debian/install
  plugins/ruby-foreman-monitoring/debian/rules
  plugins/ruby-foreman-omaha/debian/install
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/install
  plugins/ruby-foreman-puppet/debian/rules
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/install
  plugins/ruby-foreman-remote-execution/debian/rules
  plugins/ruby-foreman-salt/debian/changelog
  plugins/ruby-foreman-salt/debian/install
  plugins/ruby-foreman-salt/debian/rules
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/install
  plugins/ruby-foreman-tasks/debian/rules
  plugins/ruby-foreman-templates/debian/changelog
  plugins/ruby-foreman-templates/debian/install
  plugins/ruby-foreman-templates/debian/rules
  plugins/ruby-foreman-webhooks/debian/changelog
  plugins/ruby-foreman-webhooks/debian/install
  plugins/ruby-foreman-webhooks/debian/rules
  plugins/ruby-puppetdb-foreman/debian/changelog
  plugins/ruby-puppetdb-foreman/debian/install
  plugins/ruby-puppetdb-foreman/debian/rules
Labels: Needs testing, DEB

#7820 Refs #34641 - Stop generating apipie cache in plugins
  gem2rpm/foreman_plugin.spec.erb
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
  packages/plugins/rubygem-foreman_datacenter/rubygem-foreman_datacenter.spec
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
  packages/plugins/rubygem-foreman_dlm/rubygem-foreman_dlm.spec
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
  packages/plugins/rubygem-foreman_fog_proxmox/rubygem-foreman_fog_proxmox.spec
  packages/plugins/rubygem-foreman_host_reports/rubygem-foreman_host_reports.spec
  packages/plugins/rubygem-foreman_kubevirt/rubygem-foreman_kubevirt.spec
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
  packages/plugins/rubygem-foreman_omaha/rubygem-foreman_omaha.spec
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
  packages/plugins/rubygem-foreman_salt/rubygem-foreman_salt.spec
  packages/plugins/rubygem-foreman_statistics/rubygem-foreman_statistics.spec
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
  packages/plugins/rubygem-foreman_webhooks/rubygem-foreman_webhooks.spec
  packages/plugins/rubygem-puppetdb_foreman/rubygem-puppetdb_foreman.spec
Labels: Needs testing, RPM

#7819 Fixes #34801 - update foreman-protector file paths
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.0.7.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.0.8.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#7809 Update rubygem-hammer_cli_foreman_discovery to 1.1.0
  packages/plugins/rubygem-hammer_cli_foreman_discovery/hammer_cli_foreman_discovery-1.0.2.gem
  packages/plugins/rubygem-hammer_cli_foreman_discovery/hammer_cli_foreman_discovery-1.1.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_discovery/rubygem-hammer_cli_foreman_discovery.spec
Labels: Needs testing, RPM, Stable branch

#7810 Updated hammer_cli_foreman_discovery to 1.1.0
  dependencies/bullseye/hammer_cli_foreman_discovery/changelog
  dependencies/buster/hammer_cli_foreman_discovery/changelog
  dependencies/focal/hammer_cli_foreman_discovery/changelog
Labels: Needs testing, Stable branch

#7812 Update rubygem-hammer_cli_foreman_puppet to 0.0.5
  packages/plugins/rubygem-hammer_cli_foreman_puppet/hammer_cli_foreman_puppet-0.0.4.gem
  packages/plugins/rubygem-hammer_cli_foreman_puppet/hammer_cli_foreman_puppet-0.0.5.gem
  packages/plugins/rubygem-hammer_cli_foreman_puppet/rubygem-hammer_cli_foreman_puppet.spec
Labels: Needs testing, Stable branch

#7811 Updated hammer_cli_foreman_puppet to 0.0.5
  dependencies/bullseye/hammer_cli_foreman_puppet/changelog
  dependencies/buster/hammer_cli_foreman_puppet/changelog
  dependencies/focal/hammer_cli_foreman_puppet/changelog
Labels: Needs testing, Stable branch

#7815 Update rubygem-foreman-tasks to 5.2.3
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-5.2.2.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-5.2.3.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: Needs testing, RPM, Stable branch

#7816 Update ruby-foreman-tasks to 5.2.3
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Needs testing, Stable branch

#7824 Update rubygem-foreman_scc_manager to 1.8.18
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.17.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.18.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM

#7827 Update rubygem-foreman_scc_manager to 1.8.18 Foreman 3.2
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.17.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.18.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM

#7826 Update rubygem-foreman_scc_manager to 1.8.18 Foreman 3.1
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.17.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-1.8.18.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Needs testing, RPM, Stable branch

#7835 Update rubygem-foreman_maintain to 1.1.1
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.0.8.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.1.1.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Needs testing, RPM

#7833 Bump rubygem-foreman_rh_cloud to 5.0.34-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-5.0.33.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-5.0.34.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM, Stable branch

#7832 Bump rubygem-foreman_rh_cloud to 5.0.34-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-5.0.33.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-5.0.34.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Needs testing, RPM

#7829 Update rubygem-foreman_ansible to 7.0.4
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Needs testing

#7552 Fix wrong rubygem wrapper script for shell script 'salt_python_wrapper'
  packages/plugins/rubygem-smart_proxy_salt/rubygem-smart_proxy_salt.spec
Labels: Needs testing, RPM

#7500 Improve regular expression in katello-host-tools
  packages/client/katello-host-tools/katello-host-tools.spec
Labels: Needs testing, RPM

#7849 katello: update gem deps
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs testing

#7844 foreman-statistics: Drop apipie cache generation
  plugins/ruby-foreman-statistics/debian/changelog
  plugins/ruby-foreman-statistics/debian/install
  plugins/ruby-foreman-statistics/debian/rules
Labels: Needs testing

#7847 Update rubygem-foreman_openscap to 5.2.2
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-5.2.1.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-5.2.2.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: Needs testing
