Repository theforeman/foreman-packaging, pull requests merged in 2023-11, with the labels that each got.

#9941 Release 3.7.1
  packages/foreman/foreman-installer/foreman-installer-3.7.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.7.1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.7.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.7.1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.7.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.7.1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.7.0.tar.bz2
  packages/foreman/foreman/foreman-3.7.1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Not yet reviewed, RPM, Stable branch

#9940 Release 3.7.1
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
Labels: Not yet reviewed, DEB, Stable branch

#9952 Refs #36827 - Update rubygem-smart_proxy_container_gateway to 1.1.0
  packages/plugins/rubygem-smart_proxy_container_gateway/rubygem-smart_proxy_container_gateway.spec
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-1.0.9.gem
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-1.1.0.gem
Labels: RPM

#9954 Update rubygem-apipie-dsl to 2.6.1
  packages/foreman/rubygem-apipie-dsl/apipie-dsl-2.6.0.gem
  packages/foreman/rubygem-apipie-dsl/apipie-dsl-2.6.1.gem
  packages/foreman/rubygem-apipie-dsl/rubygem-apipie-dsl.spec
Labels: Not yet reviewed, RPM

#9899 Bump yggdrasil to 0.2.3
  packages/client/yggdrasil/Propagate-FOREMAN_REX_WORKDIR-to-workers.patch
  packages/client/yggdrasil/yggdrasil-0.2.0.tar.gz
  packages/client/yggdrasil/yggdrasil-0.2.3.tar.gz
  packages/client/yggdrasil/yggdrasil.spec
Labels: Needs re-review, RPM, Stable branch

#9956 Correctly identify license file for puppet-foreman_scap_client
  packages/plugins/puppet-foreman_scap_client/puppet-foreman_scap_client.spec
Labels: RPM

#9963 Update rubygem-foreman_rh_cloud to 9.0.52
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-9.0.51.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-9.0.52.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: RPM

#9964 Bump puppetlabs-stdlib to 9.4.1
  packages/plugins/puppetlabs-stdlib/puppetlabs-stdlib-5.2.0.tar.gz
  packages/plugins/puppetlabs-stdlib/puppetlabs-stdlib-9.4.1.tar.gz
  packages/plugins/puppetlabs-stdlib/puppetlabs-stdlib.spec
Labels: RPM

#9965 foreman_statistics: Regenerate RPM spec based on latest template
  packages/plugins/rubygem-foreman_statistics/rubygem-foreman_statistics.spec
Labels: RPM

#9966 Update rubygem-kafo to 7.3.0
  packages/foreman/rubygem-kafo/kafo-7.2.0.gem
  packages/foreman/rubygem-kafo/kafo-7.3.0.gem
  packages/foreman/rubygem-kafo/rubygem-kafo.spec
Labels: RPM

#9967 Update ruby-kafo to 7.3.0
  dependencies/bullseye/kafo/changelog
  dependencies/focal/kafo/changelog
Labels: DEB

#9971 Update ruby-foreman-statistics to 2.1.0
  plugins/ruby-foreman-statistics/debian/changelog
  plugins/ruby-foreman-statistics/debian/gem.list
  plugins/ruby-foreman-statistics/foreman_statistics.rb
Labels: Not yet reviewed, DEB, Stable branch

#9972 Update ruby-foreman-statistics to 2.1.0
  plugins/ruby-foreman-statistics/debian/changelog
  plugins/ruby-foreman-statistics/debian/gem.list
  plugins/ruby-foreman-statistics/foreman_statistics.rb
Labels: Not yet reviewed, DEB, Stable branch

#9974 Update rubygem-foreman_statistics to 2.1.0
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-2.0.1.gem
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-2.1.0.gem
  packages/plugins/rubygem-foreman_statistics/rubygem-foreman_statistics.spec
Labels: Not yet reviewed, RPM, Stable branch

#9973 Update rubygem-foreman_statistics to 2.1.0
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-2.0.1.gem
  packages/plugins/rubygem-foreman_statistics/foreman_statistics-2.1.0.gem
  packages/plugins/rubygem-foreman_statistics/rubygem-foreman_statistics.spec
Labels: Not yet reviewed, RPM, Stable branch

#9980 manually patch in the downstream assets
  packages/satellite/rubygem-foreman_theme_satellite/rubygem-foreman_theme_satellite.spec
Labels: RPM

#9976 Update rubygem-smart_proxy_remote_execution_ssh to 0.10.3
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.10.2.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.10.3.gem
Labels: RPM

#9978 Update rubygem-foreman_remote_execution to 10.1.1
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-10.1.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-10.1.1.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM, Stable branch

#9977 Update rubygem-foreman_remote_execution to 11.1.1
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-11.1.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-11.1.1.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM

#9981 Update rubygem-foreman_openscap to 7.1.0
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-7.0.0.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-7.1.0.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: RPM

#9982 Bump rubygem-hammer_cli_foreman_rh_cloud to 1.0.2
  packages/katello/rubygem-hammer_cli_foreman_rh_cloud/hammer_cli_foreman_rh_cloud-1.0.1.gem
  packages/katello/rubygem-hammer_cli_foreman_rh_cloud/hammer_cli_foreman_rh_cloud-1.0.2.gem
  packages/katello/rubygem-hammer_cli_foreman_rh_cloud/rubygem-hammer_cli_foreman_rh_cloud.spec
Labels: RPM

#9942 Update rubygem-foreman_rh_cloud to 8.0.52
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-8.0.50.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-8.0.52.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: RPM, Stable branch

#9988 Require kafo >= 7.3.0
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-installer/control
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-installer/control
Labels: DEB

#9987 Require kafo >= 7.3.0
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: RPM

#9986 Update rubygem-fog-libvirt to 0.12.0
  packages/foreman/rubygem-fog-libvirt/fog-libvirt-0.11.0.gem
  packages/foreman/rubygem-fog-libvirt/fog-libvirt-0.12.0.gem
  packages/foreman/rubygem-fog-libvirt/rubygem-fog-libvirt.spec
Labels: RPM

#9984 Update rubygem-smart_proxy_remote_execution_ssh to 0.10.3
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.10.1.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.10.3.gem
Labels: RPM, Stable branch

#9985 Update rubygem-smart_proxy_remote_execution_ssh to 0.10.3
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.10.1.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.10.3.gem
Labels: RPM, Stable branch

#9975 Update rubygem-dynflow to 1.8.1
  packages/foreman/rubygem-dynflow/dynflow-1.8.0.gem
  packages/foreman/rubygem-dynflow/dynflow-1.8.1.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: RPM

#9983 Update rubygem-foreman_webhooks to 3.2.2
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-3.2.1.gem
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-3.2.2.gem
  packages/plugins/rubygem-foreman_webhooks/rubygem-foreman_webhooks.spec
Labels: RPM

#10000 Add how to remove a Copr package
  README.md
Labels: RPM

#10002 Fix dependency on racc in gettext
  packages/foreman/rubygem-gettext/rubygem-gettext.spec
Labels: Not yet reviewed, RPM

#10006 Update rubygem-foreman-tasks to 8.2.1
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-8.2.0.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-8.2.1.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: RPM, Stable branch

#10003 Update rubygem-foreman-tasks to 8.1.4
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-8.1.1.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-8.1.4.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: RPM, Stable branch

#10009 Update ruby-foreman-remote-execution to 11.1.1
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB, Stable branch

#10010 Update rubygem-dynflow to 1.8.1
  packages/foreman/rubygem-dynflow/dynflow-1.8.0.gem
  packages/foreman/rubygem-dynflow/dynflow-1.8.1.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: RPM, Stable branch

#10007 Update rubygem-foreman_ansible to 13.0.0
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-12.0.7.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-13.0.0.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: RPM

#10012 Update ruby-dynflow to 1.8.1
  dependencies/bullseye/dynflow/changelog
  dependencies/focal/dynflow/changelog
Labels: DEB, Stable branch

#10008 Updated ruby-foreman-ansible to 13.0.0
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: DEB

#10014 more granular package grouping in the manifest
  package_manifest.yaml
Labels: RPM

#10011 Update ruby-smart-proxy-remote-execution-ssh to 0.10.3
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: DEB, Stable branch

#10013 Update ruby-smart-proxy-remote-execution-ssh to 0.10.3
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: DEB, Stable branch

#10017 Update rubygem-foreman_remote_execution to 11.1.1
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-11.1.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-11.1.1.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM, Stable branch

#8413 Use rich dependencies when updating dependencies
  get-gemfile-deps
  update-requirements
Labels: Needs testing, RPM

#10025 Implement rich dependencies in gem2rpm templates
  gem2rpm/default.spec.erb
  gem2rpm/foreman_plugin.spec.erb
  gem2rpm/hammer_plugin.spec.erb
  gem2rpm/smart_proxy_plugin.spec.erb
Labels: RPM

#9989 Update katello-repos to use Pulpcore 3.39
  packages/katello/katello-repos/katello-repos.spec
Labels: RPM

#10023 Update rubygem-foreman-tasks to 9.0.0
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-8.3.2.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-9.0.0.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: RPM

#10022 Update ruby-foreman-tasks to 9.0.0
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB

#10020 Update rubygem-foreman-tasks to 8.3.3
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-8.2.1.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-8.3.3.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: RPM, Stable branch

#10021 Update ruby-foreman-tasks to 8.3.3
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB, Stable branch

#10033 Update rubygem-hammer_cli_foreman_ansible to 0.6.0
  packages/plugins/rubygem-hammer_cli_foreman_ansible/hammer_cli_foreman_ansible-0.5.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_ansible/hammer_cli_foreman_ansible-0.6.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_ansible/rubygem-hammer_cli_foreman_ansible.spec
Labels: RPM

#10039 Fix copr version in package_manifest for copr katello
  package_manifest.yaml
Labels: RPM

#10040 Fix katello-copr version in package manifest
  package_manifest.yaml
Labels: RPM, Stable branch

#10038 Update rubygem-foreman_salt to 15.2.3
  packages/plugins/rubygem-foreman_salt/foreman_salt-15.2.2.gem
  packages/plugins/rubygem-foreman_salt/foreman_salt-15.2.3.gem
  packages/plugins/rubygem-foreman_salt/rubygem-foreman_salt.spec
Labels: RPM

#10036 Bump hammer-cli-katello to 1.12.0-0.1.pre.master
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: RPM

#10046 Change Katello Repo URL for Copr Scratch builds
  package_manifest.yaml
Labels: RPM, Stable branch

#9930 receptor based cloud connector is no longer used
  comps/comps-foreman-plugins-el8.xml
  package_manifest.yaml
  packages/plugins/ansiblerole-satellite-receptor-installer/ansiblerole-satellite-receptor-installer.spec
  packages/plugins/ansiblerole-satellite-receptor-installer/satellite_receptor_installer-0.6.13.tar.gz
Labels: RPM

#10054 Update rubygem-dynflow to 1.8.2
  packages/foreman/rubygem-dynflow/dynflow-1.8.1.gem
  packages/foreman/rubygem-dynflow/dynflow-1.8.2.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: RPM

#10048 Updated hammer_cli[_foreman] to 3.9.0
  dependencies/bullseye/hammer_cli/changelog
  dependencies/bullseye/hammer_cli_foreman/changelog
  dependencies/bullseye/hammer_cli_foreman/control
  dependencies/focal/hammer_cli/changelog
  dependencies/focal/hammer_cli_foreman/changelog
  dependencies/focal/hammer_cli_foreman/control
Labels: DEB

#10049 Updated hammer_cli[_foreman] to 3.9.0
  dependencies/bullseye/hammer_cli/changelog
  dependencies/bullseye/hammer_cli_foreman/changelog
  dependencies/bullseye/hammer_cli_foreman/control
  dependencies/focal/hammer_cli/changelog
  dependencies/focal/hammer_cli_foreman/changelog
  dependencies/focal/hammer_cli_foreman/control
Labels: DEB, Stable branch

#10060 Update rubygem-foreman_ansible to 13.0.1
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-13.0.0.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-13.0.1.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: RPM

#10044 Bump changelog to 3.10.0 to match VERSION
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
Labels: DEB

#10057 Update ruby-dynflow to 1.8.2
  dependencies/bullseye/dynflow/changelog
  dependencies/focal/dynflow/changelog
Labels: Not yet reviewed, DEB, Stable branch

#10056 Update ruby-dynflow to 1.8.2
  dependencies/bullseye/dynflow/changelog
  dependencies/focal/dynflow/changelog
Labels: Not yet reviewed, DEB, Stable branch

#10062 Release 3.9.0-rc2
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
Labels: DEB, Stable branch

#10043 Release 3.9.0-rc2
  packages/foreman/foreman-installer/foreman-installer-3.9.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.9.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.9.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.9.0-rc2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: RPM, Stable branch

#10051 Release 4.11.0-rc1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.11.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM, Stable branch
