Repository theforeman/foreman-packaging, pull requests merged in 2023-09, with the labels that each got.

#9755 Release ansible-collection-theforeman-operations 2.1.0
  plugins/ansible-collection-theforeman-operations/debian/changelog
Labels: Not yet reviewed

#9765 Depend on libopenscap.so.25 explicitly
  packages/plugins/rubygem-openscap/rubygem-openscap.spec
Labels: Not yet reviewed

#9766 Release 3.8.0-rc1
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
Labels: Not yet reviewed

#9767 Release 3.8.0-rc1
  packages/foreman/foreman-installer/foreman-installer-3.8.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.8.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.8.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.8.0-rc1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Not yet reviewed

#9749 [3.8] Update rubygem-foreman-tasks to 8.2.0
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-8.1.2.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-8.2.0.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: RPM, Stable branch

#9750 Update rubygem-foreman_remote_execution to 11.0.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-10.0.6.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-11.0.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM, Stable branch

#9701 Release ansible-collection-theforeman-foreman 3.13.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.12.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.13.0.tar.gz
Labels: Not yet reviewed, RPM

#9770 Release ansible-collection-theforeman-operations 2.1.0
  plugins/ansible-collection-theforeman-operations/debian/changelog
Labels: Not yet reviewed

#9769 Release ansible-collection-theforeman-foreman 3.13.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.12.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.13.0.tar.gz
Labels: Not yet reviewed

#9771 Release ansible-collection-theforeman-foreman 3.13.0
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: Not yet reviewed

#9778 Update rubygem-foreman_ansible to 12.0.7
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-12.0.6.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-12.0.7.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: RPM, Stable branch

#9779 Update ruby-foreman-ansible to 12.0.7
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Stable branch

#9620 Drop SCL from nodejs-node-gyp spec
  packages/foreman/nodejs-node-gyp/addon-rpm.gypi
  packages/foreman/nodejs-node-gyp/node-gyp-node-dirs-scl.patch
  packages/foreman/nodejs-node-gyp/nodejs-node-gyp.spec
Labels: Not yet reviewed

#9780 Update katello to 4.10.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.10.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Stable branch

#9787 Update rubygem-foreman_salt to 15.2.2
  packages/plugins/rubygem-foreman_salt/foreman_salt-15.2.1.gem
  packages/plugins/rubygem-foreman_salt/foreman_salt-15.2.2.gem
  packages/plugins/rubygem-foreman_salt/rubygem-foreman_salt.spec
Labels: Not yet reviewed

#9788 Update ruby-foreman-salt to 15.2.2
  plugins/ruby-foreman-salt/debian/changelog
  plugins/ruby-foreman-salt/debian/gem.list
  plugins/ruby-foreman-salt/foreman_salt.rb
Labels: Not yet reviewed

#9789 Release mosquitto 2.0.10
  packages/plugins/mosquitto/mosquitto-2.0.14.tar.gz
  packages/plugins/mosquitto/mosquitto-2.0.17.tar.gz
  packages/plugins/mosquitto/mosquitto.spec
Labels: Not yet reviewed

#9792 Release ansible-collection-theforeman-foreman 3.14.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.13.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.14.0.tar.gz
Labels: Not yet reviewed

#9793 Release ansible-collection-theforeman-foreman 3.14.0
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: Not yet reviewed

#9794 Release ansible-collection-theforeman-foreman 3.14.0
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: Not yet reviewed

#9795 Release ansible-collection-theforeman-foreman 3.14.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.13.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.14.0.tar.gz
Labels: Not yet reviewed

#9796 Update katello to 4.10.0 rc2
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.10.0.rc1.gem
  packages/katello/rubygem-katello/katello-4.10.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM, Stable branch

#9799 Add nodejs-tslib package
  comps/comps-foreman-el8.xml
  package_manifest.yaml
  packages/foreman/nodejs-tslib/nodejs-tslib.spec
  packages/foreman/nodejs-tslib/tslib-2.6.2.tgz
Labels: Not yet reviewed

#9773 Update to pulp_deb 3.0
  packages/katello/rubygem-pulp_deb_client/pulp_deb_client-2.21.1.gem
  packages/katello/rubygem-pulp_deb_client/pulp_deb_client-3.0.0.gem
  packages/katello/rubygem-pulp_deb_client/rubygem-pulp_deb_client.spec
Labels: RPM

#9809 Bump rubygem-foreman_rh_cloud to 8.0.49-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-7.0.46.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-8.0.49.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: RPM

#9808 Katello: Update pulp_deb gem dependency
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM

#9812 Update rubygem-foreman_puppet to 5.1.3
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-5.1.2.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-5.1.3.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: RPM, Stable branch

#9816 nodejs-node-sass needs to include vendor directory
  packages/foreman/nodejs-node-sass/nodejs-node-sass.spec
Labels: Not yet reviewed, RPM

#9818 Release 3.8.0-rc2
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
Labels: DEB, Stable branch

#9819 Release 3.8.0-rc2
  packages/foreman/foreman-installer/foreman-installer-3.8.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.8.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.8.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.8.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.8.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.8.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.8.0-rc1.tar.bz2
  packages/foreman/foreman/foreman-3.8.0-rc2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Stable branch

#9811 Bump rubygem-foreman_rh_cloud to 8.0.50-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-8.0.49.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-8.0.50.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Not yet reviewed, RPM, Stable branch

#9822 Update rubygem-google-protobuf to 3.24.3
  packages/plugins/rubygem-google-protobuf/google-protobuf-3.21.6.gem
  packages/plugins/rubygem-google-protobuf/google-protobuf-3.24.3.gem
  packages/plugins/rubygem-google-protobuf/rubygem-google-protobuf.spec
Labels: RPM

#9821 Update rubygem-grpc to 1.58.0
  packages/plugins/rubygem-grpc/grpc-1.49.1.gem
  packages/plugins/rubygem-grpc/grpc-1.58.0.gem
  packages/plugins/rubygem-grpc/rubygem-grpc.spec
Labels: RPM

#9820 Bump foreman_ygg_worker to 0.2.1
  packages/client/foreman_ygg_worker/foreman_ygg_worker-0.2.0.tar.gz
  packages/client/foreman_ygg_worker/foreman_ygg_worker-0.2.1.tar.gz
  packages/client/foreman_ygg_worker/foreman_ygg_worker.spec
Labels: Not yet reviewed, RPM

#9817 Patch yggdrasil to pass FOREMAN_REX_WORKDIR env var to the workers
  packages/client/yggdrasil/Propagate-FOREMAN_REX_WORKDIR-to-workers.patch
  packages/client/yggdrasil/yggdrasil.spec
Labels: RPM

#9828 Patch yggdrasil to pass FOREMAN_REX_WORKDIR env var to the workers
  packages/client/yggdrasil/Propagate-FOREMAN_REX_WORKDIR-to-workers.patch
  packages/client/yggdrasil/yggdrasil.spec
Labels: Not yet reviewed

#9830 Patch yggdrasil to pass FOREMAN_REX_WORKDIR env var to the workers
  packages/client/yggdrasil/Propagate-FOREMAN_REX_WORKDIR-to-workers.patch
  packages/client/yggdrasil/yggdrasil.spec
Labels: Not yet reviewed

#9835 Update rubygem-kafo to 7.2.0
  packages/foreman/rubygem-kafo/kafo-7.1.0.gem
  packages/foreman/rubygem-kafo/kafo-7.2.0.gem
  packages/foreman/rubygem-kafo/rubygem-kafo.spec
Labels: RPM

#9836 Bump container gateway to 1.0.9
  packages/plugins/rubygem-smart_proxy_container_gateway/rubygem-smart_proxy_container_gateway.spec
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-1.0.8.gem
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-1.0.9.gem
Labels: RPM

#9837 Update rubygem-foreman_virt_who_configure to 0.5.18
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.17.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.18.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: RPM

#9839 Remove cert RPMs refeference from change-hostname
  packages/katello/katello/hostname-change.rb
  packages/katello/katello/katello.spec
Labels: RPM

#9841 Update katello to 4.9.2
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.9.1.gem
  packages/katello/rubygem-katello/katello-4.9.2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM, Stable branch

#9834 Use an absolute path to the spec file
  bump_rpm.sh
Labels: RPM
