Repository theforeman/foreman-packaging, pull requests merged in 2023-02, with the labels that each got.

#9013 Update rubygem-foreman_maintain to 1.2.4
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.2.3.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.2.4.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Not yet reviewed

#9012 Update rubygem-foreman_maintain to 1.2.4
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.2.3.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.2.4.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Not yet reviewed

#9004 Update rubygem-foreman_google to 1.0.2
  packages/plugins/rubygem-foreman_google/foreman_google-1.0.1.gem
  packages/plugins/rubygem-foreman_google/foreman_google-1.0.2.gem
  packages/plugins/rubygem-foreman_google/rubygem-foreman_google.spec
Labels: RPM, Stable branch

#9015 Update ruby-foreman-maintain to 1.2.4
  dependencies/bullseye/foreman_maintain/changelog
  dependencies/focal/foreman_maintain/changelog
Labels: Not yet reviewed

#9022 Update rubygem-foreman_google to 1.0.3
  packages/plugins/rubygem-foreman_google/foreman_google-1.0.2.gem
  packages/plugins/rubygem-foreman_google/foreman_google-1.0.3.gem
  packages/plugins/rubygem-foreman_google/rubygem-foreman_google.spec
Labels: Not yet reviewed

#9023 Update rubygem-foreman_leapp to 0.1.13
  packages/plugins/rubygem-foreman_leapp/foreman_leapp-0.1.12.gem
  packages/plugins/rubygem-foreman_leapp/foreman_leapp-0.1.13.gem
  packages/plugins/rubygem-foreman_leapp/rubygem-foreman_leapp.spec
Labels: Not yet reviewed, RPM

#9025 Update theforeman-vendor dependency to version 12
  packages/foreman/foreman/foreman.spec
Labels: RPM

#9035 Update rubygem-foreman_ansible to 10.4.0
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-10.3.0.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-10.4.0.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: RPM

#9042 Update katello to 4.7.2
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.7.1.gem
  packages/katello/rubygem-katello/katello-4.7.2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM, Stable branch

#9045 Release foreman_maintain 1.1.10
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.1.10.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.1.8.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Not yet reviewed

#9046 Fixes #36086 - Allow openscap 1.3.7
  packages/plugins/rubygem-openscap/rubygem-openscap.spec
Labels: Not yet reviewed

#8928 Update rubygem-foreman_scc_manager to 2.2.0 Foreman 3.3
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-2.1.0.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-2.2.0.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: RPM, Stable branch

#9044 Updated ruby-foreman-ansible to 11.1.0
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: DEB

#9047 Set foreman_min_version on gem creation
  add_gem_package.sh
  bump_rpm.sh
  gem2rpm/foreman_plugin.spec.erb
Labels: RPM

#9050 Update rubygem-foreman_snapshot_management to 2.0.3
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-2.0.2.gem
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-2.0.3.gem
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: RPM

#9060 Release ansible-collection-theforeman-foreman 3.9.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.8.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.9.0.tar.gz
Labels: RPM

#9063 Release ansible-collection-theforeman-foreman 3.9.0
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: Not yet reviewed

#9062 Release ansible-collection-theforeman-foreman 3.9.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.8.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.9.0.tar.gz
Labels: Not yet reviewed, RPM

#9073 Drop EL7 compatibility form foreman-tasks
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: RPM

#9043 Update rubygem-foreman_ansible to 11.1.0
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-11.0.0.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-11.1.0.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: RPM

#9075 consider hammer dependencies when bumping
  list_updatable_packages
Labels: RPM

#9085 Update katello to 4.7.3
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.7.2.gem
  packages/katello/rubygem-katello/katello-4.7.3.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed

#9086 Update rubygem-foreman_snapshot_management to 2.0.3
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-2.0.2.gem
  packages/plugins/rubygem-foreman_snapshot_management/foreman_snapshot_management-2.0.3.gem
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Not yet reviewed

#9076 don't downgrade packages
  list_updatable_packages
Labels: RPM

#9097 Release 3.6.0-rc1
  packages/foreman/foreman-installer/foreman-installer-3.6.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.6.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.6.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.6.0-rc1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Not yet reviewed

#9098 Release 3.6.0-rc1
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
Labels: Not yet reviewed

#9088 Bump to 3.7.0-develop
  package_manifest.yaml
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Not yet reviewed

#9074 Bump katello related packages to their 4.9 versions
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM

#9112 Release Hammmer CLI 3.6.0
  packages/foreman/rubygem-hammer_cli/hammer_cli-3.6.0.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-3.6.0.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Not yet reviewed
