Repository theforeman/foreman-packaging, pull requests merged in 2023-06, with the labels that each got.

#9443 Remove SCL macros for hammer-cli-foreman develop
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: RPM

#9457 Update rubygem-foreman_azure_rm to 2.2.10
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.2.10.gem
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.2.9.gem
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
Labels: RPM

#9472 Release 3.7.0-rc3
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
Labels: Not yet reviewed, Stable branch

#9458 Update rubygem-foreman_azure_rm to 2.2.10
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.2.10.gem
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-2.2.9.gem
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
Labels: Not yet reviewed, RPM

#9473 Update katello to 4.9.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.9.0.rc1.gem
  packages/katello/rubygem-katello/katello-4.9.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, Stable branch

#9471 Update foreman-release to 3.7.0
  packages/foreman/foreman-installer/foreman-installer-3.7.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.7.0-rc3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.7.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.7.0-rc3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.7.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.7.0-rc3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.7.0-rc2.tar.bz2
  packages/foreman/foreman/foreman-3.7.0-rc3.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Not yet reviewed, RPM, Stable branch

#9484 Release ansible-collection-theforeman-foreman 3.11.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.10.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.11.0.tar.gz
Labels: RPM

#9482 Update rubygem-foreman_puppet to 6.0.0
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-5.1.2.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-6.0.0.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: RPM

#9483 Update rubygem-hammer_cli_foreman_azure_rm to 0.2.4
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/hammer_cli_foreman_azure_rm-0.2.3.gem
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/hammer_cli_foreman_azure_rm-0.2.4.gem
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/rubygem-hammer_cli_foreman_azure_rm.spec
Labels: RPM

#9499 Release ansible-collection-theforeman-foreman 3.11.0
  plugins/ansible-collection-theforeman-foreman/debian/changelog
  plugins/ansible-collection-theforeman-foreman/debian/rules
Labels: Not yet reviewed

#9498 Release ansible-collection-theforeman-foreman 3.11.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.10.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.11.0.tar.gz
Labels: Not yet reviewed

#9477 Update rubygem-foreman_scc_manager to 2.3.0 Foreman 3.7
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-2.2.3.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-2.3.0.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: RPM

#9481 Update rubygem-foreman_rh_cloud to 8.0.46
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-7.0.46.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-8.0.46.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Not yet reviewed, RPM

#9510 Update rubygem-hammer_cli_katello to 1.8.2
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.8.1.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.8.2.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Not yet reviewed

#9515 Update rubygem-foreman_puppet to 6.0.0
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-5.1.2.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-6.0.0.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: RPM, Stable branch

#9476 Update rubygem-foreman_scc_manager to 2.3.0 Foreman 3.6
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-2.2.3.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-2.3.0.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: RPM

#9518 foreman_openscap - regenerate the spec
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: RPM

#9519 Regenerate scc_manager spec based on latest template
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: RPM

#9521 Update katello to 4.8.2
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.8.1.gem
  packages/katello/rubygem-katello/katello-4.8.2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM

#9523 Update rubygem-foreman_webhooks to 3.2.0
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-3.1.0.gem
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-3.2.0.gem
  packages/plugins/rubygem-foreman_webhooks/rubygem-foreman_webhooks.spec
Labels: RPM

#9522 Update rubygem-foreman_webhooks to 3.2.0
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-3.1.0.gem
  packages/plugins/rubygem-foreman_webhooks/foreman_webhooks-3.2.0.gem
  packages/plugins/rubygem-foreman_webhooks/rubygem-foreman_webhooks.spec
Labels: Not yet reviewed, RPM

#9520 Regenerate RPM spec based on latest template
  packages/plugins/rubygem-foreman_leapp/rubygem-foreman_leapp.spec
Labels: RPM

#9524 Update katello to 4.7.6
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.7.5.gem
  packages/katello/rubygem-katello/katello-4.7.6.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM

#9533 Regenerate foreman_acd RPM spec based on latest template
  packages/plugins/rubygem-foreman_acd/rubygem-foreman_acd.spec
Labels: RPM

#9534 Regenerate foreman_salt RPM spec based on latest template
  packages/plugins/rubygem-foreman_salt/rubygem-foreman_salt.spec
Labels: RPM
