Repository theforeman/foreman-packaging, pull requests merged in 2023-03, with the labels that each got.

#9114 Update katello to 4.8.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.8.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM, Stable branch

#9101 Update rubygem-foreman_virt_who_configure to 0.5.13
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.12.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.13.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: Not yet reviewed

#9099 Release hammer_cli_katello 1.8.0
  hammer_cli_katello-1.8.0.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Not yet reviewed, Stable branch

#9121 Update rubygem-hammer_cli_katello to 1.7.3
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.7.2.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.7.3.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: RPM, Stable branch

#9119 Update rubygem-foreman_puppet to 4.1.1 Foreman 3.4 RPM
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-4.1.0.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-4.1.1.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: RPM, Stable branch

#9120 Update foreman_puppet to v4.1.1 Foreman 3.4 Debian
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: Stable branch

#9131 compare_deb_repo cherry-picks for 3.4
  scripts/compare_deb_repo.py
Labels: Not yet reviewed, DEB, Stable branch

#9136 Update ruby-foreman-expire-hosts to 8.1.0
  plugins/ruby-foreman-expire-hosts/debian/changelog
  plugins/ruby-foreman-expire-hosts/debian/gem.list
  plugins/ruby-foreman-expire-hosts/foreman_expire_hosts.rb
Labels: Not yet reviewed

#9134 Update ruby-foreman-expire-hosts to 8.1.0
  plugins/ruby-foreman-expire-hosts/debian/changelog
  plugins/ruby-foreman-expire-hosts/debian/gem.list
  plugins/ruby-foreman-expire-hosts/foreman_expire_hosts.rb
Labels: Not yet reviewed

#9135 Update ruby-foreman-expire-hosts to 8.1.0
  plugins/ruby-foreman-expire-hosts/debian/changelog
  plugins/ruby-foreman-expire-hosts/debian/gem.list
  plugins/ruby-foreman-expire-hosts/foreman_expire_hosts.rb
Labels: Not yet reviewed

#9137 Update rubygem-foreman_expire_hosts to 8.1.0
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-8.0.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-8.1.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Not yet reviewed

#9138 Update rubygem-foreman_expire_hosts to 8.1.0
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-8.0.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-8.1.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Not yet reviewed

#9139 Update rubygem-foreman_expire_hosts to 8.1.0
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-8.0.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-8.1.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Not yet reviewed

#9159 Update rubygem-foreman_discovery to 22.0.4
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-22.0.2.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-22.0.4.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: RPM

#9084 Update rubygem-fog-proxmox to 0.15.0
  packages/plugins/rubygem-fog-proxmox/fog-proxmox-0.14.0.gem
  packages/plugins/rubygem-fog-proxmox/fog-proxmox-0.15.0.gem
  packages/plugins/rubygem-fog-proxmox/rubygem-fog-proxmox.spec
Labels: Not yet reviewed

#9166 Release 3.6.0-rc2
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
Labels: Not yet reviewed

#9169 Update rubygem-foreman_discovery to 22.0.4 (#9159)
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-22.0.2.gem
  packages/plugins/rubygem-foreman_discovery/foreman_discovery-22.0.4.gem
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
Labels: Not yet reviewed, RPM, Stable branch

#9172 Updated ruby-foreman-ansible to 11.1.1
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: Stable branch

#9154 Update rubygem-foreman_openscap to 5.2.3
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-5.2.2.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-5.2.3.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: RPM

#9170 Update rubygem-foreman_openscap to 5.2.3
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-5.2.2.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-5.2.3.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: RPM, Stable branch

#9180 Release 3.5.2
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
Labels: Stable branch

#9179 Update foreman-release to 3.5.2
  packages/foreman/foreman-installer/foreman-installer-3.5.1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.5.2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.5.1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.5.2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.5.1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.5.2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.5.1.tar.bz2
  packages/foreman/foreman/foreman-3.5.2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: RPM, Stable branch

#9183 Update rubygem-foreman_maintain to 1.2.7
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.2.6.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.2.7.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: RPM, Stable branch

#9184 Update rubygem-foreman_maintain to 1.2.7
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.2.6.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.2.7.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: RPM, Stable branch

#9178 Update rubygem-smart_proxy_ansible to 3.5.3
  packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-3.5.2.gem
  packages/plugins/rubygem-smart_proxy_ansible/smart_proxy_ansible-3.5.3.gem
Labels: Stable branch

#9185 Update ruby-foreman-maintain to 1.2.7
  dependencies/bullseye/foreman_maintain/changelog
  dependencies/focal/foreman_maintain/changelog
Labels: Not yet reviewed, Stable branch

#9177 Update ruby-smart-proxy-ansible to 3.5.3
  plugins/smart_proxy_ansible/ansible.rb
  plugins/smart_proxy_ansible/changelog
Labels: Stable branch

#9186 Update ruby-foreman-maintain to 1.2.7
  dependencies/bullseye/foreman_maintain/changelog
  dependencies/focal/foreman_maintain/changelog
Labels: Not yet reviewed, Stable branch

#9051 Depend on libopenscap.so.25 explicitly
  packages/plugins/rubygem-openscap/rubygem-openscap.spec
Labels: RPM

#9188 Update katello to 4.7.4
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.7.3.gem
  packages/katello/rubygem-katello/katello-4.7.4.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM

#9156 Drop rubygem-ovirt_provision_plugin
  comps/comps-foreman-plugins-el8.xml
  package_manifest.yaml
  packages/plugins/rubygem-ovirt_provision_plugin/ovirt_provision_plugin-2.0.3.gem
  packages/plugins/rubygem-ovirt_provision_plugin/rubygem-ovirt_provision_plugin.spec
Labels: Not yet reviewed, RPM

#9155 Remove rubygem-foreman_noenv
  comps/comps-foreman-plugins-el8.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_noenv/foreman_noenv-0.0.7.gem
  packages/plugins/rubygem-foreman_noenv/rubygem-foreman_noenv.spec
Labels: Not yet reviewed, RPM

#9207 Correct the puppet-agent minimum version
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: RPM

#9217 Release 3.6.0
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
Labels: Not yet reviewed

#9224 Update rubygem-foreman_ansible to 11.1.2
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-11.1.1.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-11.1.2.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: RPM

#9228 Update rubygem-foreman_maintain to 1.2.8
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.2.7.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.2.8.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Not yet reviewed

#9229 Update ruby-foreman-maintain to 1.2.8
  dependencies/bullseye/foreman_maintain/changelog
  dependencies/focal/foreman_maintain/changelog
Labels: Not yet reviewed

#9232 Update rubygem-foreman_openscap to 6.0.0
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-5.2.3.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-6.0.0.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: RPM

#9233 Update rubygem-foreman_openscap to 6.0.0
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-5.2.3.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-6.0.0.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: RPM

#9234 Update rubygem-foreman_openscap to 6.0.0
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-5.2.2.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-6.0.0.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: RPM

#9236 fix yggdrasil-worker-forwarder entry in comps
  comps/comps-foreman-plugins-el8.xml
Labels: RPM

#9239 fix yggdrasil-worker-forwarder entry in comps
  comps/comps-foreman-plugins-el8.xml
Labels: Not yet reviewed, RPM

#9241 Update rubygem-foreman_remote_execution to 9.1.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-9.0.1.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-9.1.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM, Stable branch

#9242 Update ruby-foreman-remote-execution to 9.1.0
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: Stable branch

#9250 Update rubygem-foreman_maintain to 1.3.0
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.2.8.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.3.0.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Not yet reviewed, RPM

#9253 Release 3.6.1
  packages/foreman/foreman-installer/foreman-installer-3.6.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.6.1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.6.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.6.1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.6.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.6.1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.6.0.tar.bz2
  packages/foreman/foreman/foreman-3.6.1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Not yet reviewed

#9262 Update rubygem-hammer_cli_katello to 1.8.1
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.8.0.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.8.1.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: RPM, Stable branch
