Repository theforeman/foreman-packaging, pull requests merged in 2023-10, with the labels that each got.

#9849 Update rubygem-foreman_kernel_care packaging
  packages/katello/rubygem-foreman_kernel_care/rubygem-foreman_kernel_care.spec
Labels: Not yet reviewed, RPM

#9442 include foreman_assets_* in files also when webpack only
  gem2rpm/foreman_plugin.spec.erb
Labels: RPM

#9851 Refs #36694 - Require Kafo 7.2+ to show failed resources
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-installer/control
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-installer/control
Labels: DEB

#9850 Refs #36694 - Require Kafo 7.2+ to show failed resources
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: RPM

#9853 Update ruby-kafo to 7.2.0
  dependencies/bullseye/kafo/changelog
  dependencies/focal/kafo/changelog
Labels: DEB, Stable branch

#9852 Update rubygem-kafo to 7.2.0
  packages/foreman/rubygem-kafo/kafo-7.1.0.gem
  packages/foreman/rubygem-kafo/kafo-7.2.0.gem
  packages/foreman/rubygem-kafo/rubygem-kafo.spec
Labels: RPM, Stable branch

#9854 Drop foreman- prefix on project names in Copr
  package_manifest.yaml
Labels: RPM

#9862 Add katello nodejs packages to list of updateable
  list_updatable_packages
Labels: Not yet reviewed, RPM

#9865 Call add_npm_package with UPDATE=true from bump_rpm
  bump_rpm.sh
Labels: RPM

#9868 update gem dependencies
  packages/foreman/foreman/foreman.spec
Labels: RPM

#9798 Support wide line lengths in package_manifest with add_host
  add_host.py
Labels: Not yet reviewed

#9872 add PCP subpackage
  comps/comps-foreman-el8.xml
  packages/foreman/foreman/foreman.spec
Labels: RPM

#9873 add PCP subpackage
  debian/bullseye/foreman/changelog
  debian/bullseye/foreman/control
  debian/bullseye/foreman/foreman-pcp.dirs
  debian/bullseye/foreman/foreman-pcp.install
  debian/focal/foreman/changelog
  debian/focal/foreman/control
  debian/focal/foreman/foreman-pcp.dirs
  debian/focal/foreman/foreman-pcp.install
Labels: DEB

#9874 Update rubygem-foreman-tasks to 8.3.0
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-8.2.0.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-8.3.0.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: RPM

#9875 Release 3.8.0
  packages/foreman/foreman-installer/foreman-installer-3.8.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.8.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.8.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.8.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.8.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.8.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.8.0-rc2.tar.bz2
  packages/foreman/foreman/foreman-3.8.0.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: RPM, Stable branch

#9876 Release 3.8.0
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
Labels: DEB, Stable branch

#9879 Bump rubygem-foreman_rh_cloud to 9.0.51-1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-8.0.48.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-9.0.51.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Not yet reviewed, RPM

#9880 Refs #36694 - Require Kafo 7.2+ to show failed resources
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: RPM, Stable branch

#9881 Refs #36694 - Require Kafo 7.2+ to show failed resources
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-installer/control
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-installer/control
Labels: DEB, Stable branch

#9878 Fix how add_npm_package determines if an update is needed
  add_npm_package.sh
  bump_rpm.sh
Labels: RPM

#9888 Update rubygem-apipie-dsl to 2.6.0
  packages/foreman/rubygem-apipie-dsl/apipie-dsl-2.5.0.gem
  packages/foreman/rubygem-apipie-dsl/apipie-dsl-2.6.0.gem
  packages/foreman/rubygem-apipie-dsl/rubygem-apipie-dsl.spec
Labels: RPM

#9855 Add fapolicyd policy for Foreman and Foreman Proxy
  comps/comps-foreman-el8.xml
  package_manifest.yaml
  packages/foreman/foreman-fapolicyd/foreman-fapolicyd-1.0.1.tar.gz
  packages/foreman/foreman-fapolicyd/foreman-fapolicyd.spec
Labels: RPM

#9890 Release foreman_ygg_worker 0.2.2
  packages/client/foreman_ygg_worker/foreman_ygg_worker-0.2.1.tar.gz
  packages/client/foreman_ygg_worker/foreman_ygg_worker-0.2.2.tar.gz
  packages/client/foreman_ygg_worker/foreman_ygg_worker.spec
Labels: Not yet reviewed, RPM

#9889 Require fapolicyd rules packages if fapolicyd present
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman/foreman.spec
Labels: RPM

#9887 Add property to denote from what repository to fork in Copr for releases
  package_manifest.yaml
Labels: RPM

#9897 Bump yggdrasil to 0.2.3
  packages/client/yggdrasil/Propagate-FOREMAN_REX_WORKDIR-to-workers.patch
  packages/client/yggdrasil/yggdrasil-0.2.0.tar.gz
  packages/client/yggdrasil/yggdrasil-0.2.3.tar.gz
  packages/client/yggdrasil/yggdrasil.spec
Labels: RPM

#9901 Drop the requires from foreman-policyd to foreman-proxy-policyd
  packages/foreman/foreman-fapolicyd/foreman-fapolicyd.spec
Labels: RPM

#9898 Bump yggdrasil to 0.2.3
  packages/client/yggdrasil/Propagate-FOREMAN_REX_WORKDIR-to-workers.patch
  packages/client/yggdrasil/yggdrasil-0.2.0.tar.gz
  packages/client/yggdrasil/yggdrasil-0.2.3.tar.gz
  packages/client/yggdrasil/yggdrasil.spec
Labels: RPM, Stable branch

#9895 Release yggdrasil-worker-forwarder 0.0.3
  packages/plugins/yggdrasil-worker-forwarder/yggdrasil-worker-forwarder-0.0.1.tar.gz
  packages/plugins/yggdrasil-worker-forwarder/yggdrasil-worker-forwarder-0.0.3.tar.gz
  packages/plugins/yggdrasil-worker-forwarder/yggdrasil-worker-forwarder.spec
Labels: Not yet reviewed, RPM

#9914 Rebuild nodejs-node-sass against Node 14
  packages/foreman/nodejs-node-sass/nodejs-node-sass.spec
Labels: Not yet reviewed, RPM

#9869 Update katello to 4.10.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.10.0.gem
  packages/katello/rubygem-katello/katello-4.10.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM, Stable branch

#9916 Remove duplicated required_ruby_version block
  gem2rpm/foreman_plugin.spec.erb
Labels: RPM

#9917 Add foreman-build to Copr chroots
  package_manifest.yaml
Labels: RPM

#9915 Swap to NodeJS 14
  modulemd/modulemd-foreman-el8.yaml
  package_manifest.yaml
Labels: RPM

#9934 Update rubygem-foreman_remote_execution to 11.1.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-11.0.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-11.1.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM, Stable branch

#9600 Regenerate rubygem-smart_proxy_remote_execution_ssh spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
Labels: RPM

#9937 Update ruby-dynflow to 1.8.0
  dependencies/bullseye/dynflow/changelog
  dependencies/focal/dynflow/changelog
Labels: DEB, Stable branch

#9938 Update ruby-smart-proxy-dynflow to 0.9.1
  plugins/smart_proxy_dynflow/changelog
  plugins/smart_proxy_dynflow/dynflow.rb
Labels: DEB, Stable branch

#9929 Update ruby-foreman-remote-execution to 10.1.0
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB, Stable branch

#9926 Update rubygem-foreman_remote_execution to 10.1.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-10.0.7.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-10.1.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM, Stable branch

#9924 Fixes #36868 - Automatically depend on the correct SELinux policy
  packages/foreman/foreman/foreman.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM

#9911 add foreman_theme_satellite
  package_manifest.yaml
  packages/satellite/rubygem-foreman_theme_satellite/foreman_theme_satellite-13.1.0.gem
  packages/satellite/rubygem-foreman_theme_satellite/rubygem-foreman_theme_satellite.spec
Labels: RPM

#9939 introduce a foreman-devel module
  modulemd/modulemd-foreman-el8.yaml
Labels: RPM
