Repository theforeman/foreman-packaging, pull requests merged in 2023-08, with the labels that each got.

#9470 Report conflicting projects in updateable list
  list_updatable_packages
Labels: RPM

#9610 Revert "Ensure maven:3.8 is enabled on EL8 for Katello"
  modulemd/modulemd-katello-el8.yaml
Labels: RPM

#9613 Update rubygem-foreman_remote_execution to 10.0.5
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-10.0.4.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-10.0.5.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Not yet reviewed, RPM

#9611 Update rubygem-foreman_templates to 9.3.3
  packages/plugins/rubygem-foreman_templates/foreman_templates-9.3.0.gem
  packages/plugins/rubygem-foreman_templates/foreman_templates-9.3.3.gem
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
Labels: Not yet reviewed, RPM, Stable branch

#9615 Update rubygem-foreman_rh_cloud to 8.0.48
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-8.0.47.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-8.0.48.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Not yet reviewed, RPM

#9616 Update rubygem-smart_proxy_container_gateway to 1.0.8
  packages/plugins/rubygem-smart_proxy_container_gateway/rubygem-smart_proxy_container_gateway.spec
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-1.0.7.gem
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-1.0.8.gem
Labels: RPM

#9590 Update rubygem-foreman_salt to 15.2.0
  packages/plugins/rubygem-foreman_salt/foreman_salt-15.1.0.gem
  packages/plugins/rubygem-foreman_salt/foreman_salt-15.2.1.gem
  packages/plugins/rubygem-foreman_salt/rubygem-foreman_salt.spec
Labels: RPM

#9614 Update rex to 10.0.5
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-10.0.4.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-10.0.5.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM

#9630 Update rubygem-foreman_ansible to 12.0.6
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-12.0.5.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-12.0.6.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: RPM

#9632 Updated ruby-foreman-ansible to 12.0.6
  plugins/ruby-foreman-ansible/debian/changelog
  plugins/ruby-foreman-ansible/debian/gem.list
  plugins/ruby-foreman-ansible/foreman_ansible.rb
Labels: DEB, Stable branch

#9633 Update rubygem-foreman_ansible to 12.0.6
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-12.0.5.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-12.0.6.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: Stable branch

#9634 Precompile foreman_azure_rm assets
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
Labels: RPM

#9635 Update katello to 4.8.4
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.8.3.gem
  packages/katello/rubygem-katello/katello-4.8.4.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM

#9617 Include nodejs packages from Foreman in list of updateable packages
  list_updatable_packages
  parse-package-lock
Labels: Not yet reviewed, RPM

#9649 Install npm2rpm globally before bump_rpm
  .github/workflows/bump_packages.yml
Labels: Not yet reviewed

#9290 Manage Copr projects
  package_manifest.yaml
Labels: RPM

#9679 Use NodeJS 14 for update packages workflow
  .github/workflows/bump_packages.yml
Labels: Not yet reviewed

#9685 Update ruby-foreman-maintain to 1.3.4
  dependencies/bullseye/foreman_maintain/changelog
  dependencies/focal/foreman_maintain/changelog
Labels: Stable branch

#9686 Update ruby-foreman-maintain to 1.3.4
  dependencies/bullseye/foreman_maintain/changelog
  dependencies/focal/foreman_maintain/changelog
Labels: Stable branch

#9684 Update rubygem-foreman_maintain to 1.3.4
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.3.3.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.3.4.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: RPM, Stable branch

#9683 Update rubygem-foreman_maintain to 1.3.4
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.3.3.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.3.4.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: RPM, Stable branch

#9692 Update rubygem-foreman_maintain to 1.3.5
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.3.4.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.3.5.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Not yet reviewed

#9693 Update rubygem-foreman_maintain to 1.3.5
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.3.4.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.3.5.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Not yet reviewed

#9694 Update ruby-foreman-maintain to 1.3.5
  dependencies/bullseye/foreman_maintain/changelog
  dependencies/focal/foreman_maintain/changelog
Labels: Not yet reviewed

#9698 Release 3.6.2
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
Labels: Not yet reviewed

#9699 Release 3.6.2
  packages/foreman/foreman-installer/foreman-installer-3.6.1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.6.2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.6.1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.6.2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.6.1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.6.2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.6.1.tar.bz2
  packages/foreman/foreman/foreman-3.6.2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Not yet reviewed

#9702 Release ansible-collection-theforeman-foreman 3.13.0
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: Not yet reviewed

#9576 Add foreman_snapshot_management plugin to deb packaging
  plugins/ruby-foreman-snapshot-management/debian/changelog
  plugins/ruby-foreman-snapshot-management/debian/compat
  plugins/ruby-foreman-snapshot-management/debian/control
  plugins/ruby-foreman-snapshot-management/debian/copyright
  plugins/ruby-foreman-snapshot-management/debian/gem.list
  plugins/ruby-foreman-snapshot-management/debian/install
  plugins/ruby-foreman-snapshot-management/debian/postinst
  plugins/ruby-foreman-snapshot-management/debian/rules
  plugins/ruby-foreman-snapshot-management/debian/source/format
  plugins/ruby-foreman-snapshot-management/foreman_snapshot_management.rb
Labels: DEB

#9741 Update rubygem-foreman-tasks to 8.2.0
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-8.1.2.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-8.2.0.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: RPM

#9744 Update foreman-bootdisk to 21.1.0
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-21.0.4.gem
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-21.1.0.gem
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
Labels: RPM

#9745 Update rubygem-foreman_remote_execution to 10.0.7
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-10.0.5.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-10.0.7.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM

#9743 Add Candlepin Copr repository
  package_manifest.yaml
Labels: Not yet reviewed, RPM

#9709 Bump katello related packages to their 4.10 versions
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Needs re-review, RPM

#9747 Update rubygem-foreman_remote_execution to 11.0.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-10.0.6.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-11.0.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM

#9707 Update rubygem-dynflow to 1.8.0
  packages/foreman/rubygem-dynflow/dynflow-1.7.0.gem
  packages/foreman/rubygem-dynflow/dynflow-1.8.0.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: Not yet reviewed

#9742 Add repoclosure definitions for stagingyum repositories
  package_manifest.yaml
  repoclosure/yum.conf
Labels: Not yet reviewed, RPM

#9751 Fix determining latest version in bump_rpm.sh & fix some shellcheck
  bump_rpm.sh
Labels: RPM

#9752 Update rubygem-kafo to 7.1.0
  packages/foreman/rubygem-kafo/kafo-7.0.0.gem
  packages/foreman/rubygem-kafo/kafo-7.1.0.gem
  packages/foreman/rubygem-kafo/rubygem-kafo.spec
Labels: RPM
