Repository theforeman/foreman-packaging, pull requests merged in 2023-04, with the labels that each got.

#9122 Use Python 3.11 for Ansible in EL8.8
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
Labels: Not yet reviewed, RPM

#9263 Use Python 3.11 for Ansible in EL8.8
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
Labels: Not yet reviewed, RPM, Stable branch

#9264 Use Python 3.11 for Ansible in EL8.8
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
Labels: Not yet reviewed, RPM, Stable branch

#9206 Remove unmaintained m2 plugins
  comps/comps-foreman-plugins-el8.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_m2/foreman_m2-0.0.4.gem
  packages/plugins/rubygem-foreman_m2/rubygem-foreman_m2.spec
  packages/plugins/rubygem-smart_proxy_m2/rubygem-smart_proxy_m2.spec
  packages/plugins/rubygem-smart_proxy_m2/smart_proxy_m2-0.0.1.gem
Labels: RPM

#9235 Fixes #36223 - Make foreman_bootdisk depend on grub2-efi-x64
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
Labels: RPM

#9277 Update katello to 4.8.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.8.0.rc1.gem
  packages/katello/rubygem-katello/katello-4.8.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM

#9275 Update rubygem-prometheus-client to 4.1.0
  packages/foreman/rubygem-prometheus-client/prometheus-client-1.0.0.gem
  packages/foreman/rubygem-prometheus-client/prometheus-client-4.1.0.gem
  packages/foreman/rubygem-prometheus-client/rubygem-prometheus-client.spec
Labels: RPM

#9278 Release ansible-collection-theforeman-foreman 3.10.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.10.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-3.9.0.tar.gz
Labels: RPM

#9291 Update katello to 4.8.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.8.0.gem
  packages/katello/rubygem-katello/katello-4.8.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM, Stable branch

#9300 Update foreman-release to 3.5.3
  packages/foreman/foreman-installer/foreman-installer-3.5.2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.5.3.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.5.2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.5.3.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.5.2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.5.3.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.5.2.tar.bz2
  packages/foreman/foreman/foreman-3.5.3.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: RPM

#9304 Fix tracer dnf plugin location
  packages/client/katello-host-tools/katello-host-tools.spec
Labels: RPM

#9302 exclude overcommit and renovate configs
  gem2rpm/default.spec.erb
Labels: RPM

#9306 Update rubygem-foreman_maintain to 1.3.1
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.3.0.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.3.1.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Not yet reviewed, RPM
