Repository theforeman/foreman-packaging, pull requests merged in 2023-05, with the labels that each got.

#9322 Refs #36345 - Drop Puppet 6 support and de-SCL installer
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: RPM

#9325 Bump nodejs-react-bootstrap to 0.33.1
  packages/foreman/nodejs-react-bootstrap/babel-runtime-6.26.0.tgz
  packages/foreman/nodejs-react-bootstrap/classnames-2.2.6.tgz
  packages/foreman/nodejs-react-bootstrap/classnames-2.3.2.tgz
  packages/foreman/nodejs-react-bootstrap/core-js-2.6.12.tgz
  packages/foreman/nodejs-react-bootstrap/core-js-2.6.9.tgz
  packages/foreman/nodejs-react-bootstrap/csstype-3.1.2.tgz
  packages/foreman/nodejs-react-bootstrap/keycode-2.2.0.tgz
  packages/foreman/nodejs-react-bootstrap/keycode-2.2.1.tgz
  packages/foreman/nodejs-react-bootstrap/nodejs-react-bootstrap-0.32.1-registry.npmjs.org.tgz
  packages/foreman/nodejs-react-bootstrap/nodejs-react-bootstrap-0.33.1-registry.npmjs.org.tgz
  packages/foreman/nodejs-react-bootstrap/nodejs-react-bootstrap.spec
  packages/foreman/nodejs-react-bootstrap/prop-types-15.7.2.tgz
  packages/foreman/nodejs-react-bootstrap/prop-types-15.7.5.tgz
  packages/foreman/nodejs-react-bootstrap/prop-types-15.8.1.tgz
  packages/foreman/nodejs-react-bootstrap/prop-types-extra-1.1.0.tgz
  packages/foreman/nodejs-react-bootstrap/prop-types-extra-1.1.1.tgz
  packages/foreman/nodejs-react-bootstrap/react-18.2.5.tgz
  packages/foreman/nodejs-react-bootstrap/react-bootstrap-0.32.1.tgz
  packages/foreman/nodejs-react-bootstrap/react-bootstrap-0.33.1.tgz
  packages/foreman/nodejs-react-bootstrap/react-is-16.10.2.tgz
  packages/foreman/nodejs-react-bootstrap/react-is-16.13.1.tgz
  packages/foreman/nodejs-react-bootstrap/react-overlays-0.8.3.tgz
  packages/foreman/nodejs-react-bootstrap/react-overlays-0.9.3.tgz
  packages/foreman/nodejs-react-bootstrap/regenerator-runtime-0.11.1.tgz
  packages/foreman/nodejs-react-bootstrap/regenerator-runtime-0.13.11.tgz
  packages/foreman/nodejs-react-bootstrap/regenerator-runtime-0.13.3.tgz
  packages/foreman/nodejs-react-bootstrap/runtime-7.21.5.tgz
  packages/foreman/nodejs-react-bootstrap/runtime-7.6.2.tgz
  packages/foreman/nodejs-react-bootstrap/runtime-corejs2-7.21.5.tgz
  packages/foreman/nodejs-react-bootstrap/scheduler-0.16.3.tgz
  packages/foreman/nodejs-react-bootstrap/uncontrollable-4.1.0.tgz
  packages/foreman/nodejs-react-bootstrap/uncontrollable-7.2.1.tgz
  packages/foreman/nodejs-react-bootstrap/warning-4.0.3.tgz
Labels: Not yet reviewed

#9339 Update rubygem-kafo to 7.0.0
  packages/foreman/rubygem-kafo/kafo-6.5.0.gem
  packages/foreman/rubygem-kafo/kafo-7.0.0.gem
  packages/foreman/rubygem-kafo/rubygem-kafo.spec
Labels: Not yet reviewed

#9352 Update rubygem-foreman_ansible to 11.2.1
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-11.2.0.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-11.2.1.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: RPM

#9367 Update katello-selinux to 5.0.1
  packages/katello/katello-selinux/5.0.0
  packages/katello/katello-selinux/5.0.1
  packages/katello/katello-selinux/katello-selinux.spec
Labels: Not yet reviewed, RPM

#9374 only match `requires_foreman`, not `requires_foreman_plugin`
  add_gem_package.sh
  bump_rpm.sh
Labels: RPM

#9371 Update rubygem-foreman_scc_manager to 2.2.3
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-2.2.0.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-2.2.3.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: RPM

#9376 Update rubygem-foreman_puppet to 5.1.2 rpm develop
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-5.1.1.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-5.1.2.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: RPM

#9375 Update rubygem-foreman_scc_manager to 2.2.3
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-2.2.0.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-2.2.3.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: RPM

#9347 Sunsetting foreman_column_view because functionality being integrated in Foreman itself
  comps/comps-foreman-plugins-el8.xml
  package_manifest.yaml
  packages/foreman/foreman-obsolete-packages/foreman-obsolete-packages.spec
  packages/plugins/rubygem-foreman_column_view/foreman_column_view-0.4.0.gem
  packages/plugins/rubygem-foreman_column_view/rubygem-foreman_column_view.spec
Labels: RPM

#9423 Correct allowed kafo versions
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-installer/control
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-installer/control
Labels: DEB

#9426 Reflect Foreman 3.7 branched
  mock/el8.cfg
  package_manifest.yaml
  packages/foreman/foreman-release/foreman.gpg
  repoclosure/yum.conf
Labels: Not yet reviewed

#9424 Bump to 3.8-develop
  package_manifest.yaml
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Not yet reviewed

#9433 Release 3.7.0-rc2
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
Labels: Not yet reviewed

#9434 Release 3.7.0-rc2
  packages/foreman/foreman-installer/foreman-installer-3.7.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.7.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.7.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.7.0-rc2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Not yet reviewed

#9431 Update rubygem-foreman_templates to 9.4.0
  packages/plugins/rubygem-foreman_templates/foreman_templates-9.3.0.gem
  packages/plugins/rubygem-foreman_templates/foreman_templates-9.4.0.gem
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
Labels: RPM

#9444 Update katello to 4.9.0-rc1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.9.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM

#9436 Update rubygem-foreman_virt_who_configure to 0.5.14
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.13.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.14.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: RPM

#9448 Update rubygem-hammer_cli_katello to 1.9.0
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.9.0.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: RPM, Stable branch
