Repository theforeman/foreman-packaging, pull requests merged in 2024-03, with the labels that each got.

#10513 Use Python 3 for package.json filtering
  debian/bullseye/foreman/changelog
  debian/bullseye/foreman/control
  debian/bullseye/foreman/rules
  debian/focal/foreman/changelog
  debian/focal/foreman/control
  debian/focal/foreman/rules
Labels: DEB

#10515 Update rubygem-fast_gettext to 2.3.0
  packages/foreman/rubygem-fast_gettext/fast_gettext-1.8.0.gem
  packages/foreman/rubygem-fast_gettext/fast_gettext-2.3.0.gem
  packages/foreman/rubygem-fast_gettext/rubygem-fast_gettext.spec
Labels: RPM

#10521 Update foreman requirements after gettext bump
  packages/foreman/foreman/foreman.spec
Labels: Not yet reviewed, RPM

#10520 Regenerate hammer discovery based on latest RPM template
  packages/plugins/rubygem-hammer_cli_foreman_discovery/rubygem-hammer_cli_foreman_discovery.spec
Labels: RPM

#10523 Update rubygem-fog-vsphere to 3.6.4
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.6.3.gem
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.6.4.gem
  packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec
Labels: RPM

#10525 Update smart_proxy_dynflow to 0.9.2
  plugins/smart_proxy_dynflow/changelog
  plugins/smart_proxy_dynflow/dynflow.rb
Labels: DEB

#10531 Release 3.10.0-rc2
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
Labels: DEB, Stable branch

#10530 Release 3.10.0-rc2
  packages/foreman/foreman-installer/foreman-installer-3.10.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.10.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.10.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.10.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.10.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.10.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.10.0-rc1.tar.bz2
  packages/foreman/foreman/foreman-3.10.0-rc2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: RPM, Stable branch

#10534 Bump rubygem-smart_proxy_discovery to 1.0.5-10
  packages/plugins/rubygem-smart_proxy_discovery/rubygem-smart_proxy_discovery.spec
Labels: RPM

#10537 Release 4.12.0-rc3
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.12.0.rc1.gem
  packages/katello/rubygem-katello/katello-4.12.0.rc3.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM, Stable branch

#10549 Regenerate spec file for foreman_kubevirt
  packages/plugins/rubygem-foreman_kubevirt/rubygem-foreman_kubevirt.spec
Labels: RPM

#10526 Update smart_proxy_remote_execution_ssh to 0.10.4
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: DEB

#10529 Update ruby-dynflow to 1.8.3
  dependencies/bullseye/dynflow/changelog
  dependencies/focal/dynflow/changelog
  dependencies/jammy/dynflow/changelog
Labels: DEB

#10467 Update EL8 to PostgreSQL 13
  modulemd/modulemd-foreman-el8.yaml
  package_manifest.yaml
Labels: RPM

#10552 Update rubygem-smart_proxy_remote_execution_ssh to 0.10.4
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.10.3.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.10.4.gem
Labels: RPM, Stable branch

#10551 Update rubygem-smart_proxy_remote_execution_ssh to 0.10.4
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.10.3.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.10.4.gem
Labels: RPM, Stable branch

#10554 Update rubygem-foreman_remote_execution to 13.0.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-12.0.5.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-13.0.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Not yet reviewed, RPM

#10555 Update ruby-foreman-remote-execution to 13.0.0
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB

#10556 Fixes #37246 - Add back ipmitool dependency
  packages/foreman/rubygem-rubyipmi/rubygem-rubyipmi.spec
Labels: RPM

#10566 Update rubygem-smart_proxy_dynflow to 0.9.2
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.9.1.gem
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.9.2.gem
Labels: Not yet reviewed, RPM, Stable branch

#10567 Update rubygem-smart_proxy_dynflow to 0.9.2
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.9.1.gem
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.9.2.gem
Labels: Not yet reviewed, RPM, Stable branch

#10557 Fixes #37246 - Add back ipmitool dependency
  packages/foreman/rubygem-rubyipmi/rubygem-rubyipmi.spec
Labels: Not yet reviewed, RPM, Stable branch

#10559 Fixes #37246 - Add back ipmitool dependency
  packages/foreman/rubygem-rubyipmi/rubygem-rubyipmi.spec
Labels: Not yet reviewed, RPM, Stable branch

#10535 Update rubygem-hammer_cli_foreman_leapp to 0.1.2
  packages/plugins/rubygem-hammer_cli_foreman_leapp/hammer_cli_foreman_leapp-0.1.1.gem
  packages/plugins/rubygem-hammer_cli_foreman_leapp/hammer_cli_foreman_leapp-0.1.2.gem
  packages/plugins/rubygem-hammer_cli_foreman_leapp/rubygem-hammer_cli_foreman_leapp.spec
Labels: RPM

#10574 Regenerate spec file for hammer_cli_foreman_puppet
  packages/plugins/rubygem-hammer_cli_foreman_puppet/rubygem-hammer_cli_foreman_puppet.spec
Labels: RPM

#10595 add journald-native to bookworm
  dependencies/bookworm/journald-native/changelog
  dependencies/bookworm/journald-native/compat
  dependencies/bookworm/journald-native/control
  dependencies/bookworm/journald-native/copyright
  dependencies/bookworm/journald-native/ruby-journald-native.docs
  dependencies/bookworm/journald-native/rules
  dependencies/bookworm/journald-native/source/format
  dependencies/bookworm/journald-native/watch
Labels: Not yet reviewed, DEB

#10593 add hammer webhooks to bookworm
  dependencies/bookworm/hammer_cli_foreman_webhooks/changelog
  dependencies/bookworm/hammer_cli_foreman_webhooks/compat
  dependencies/bookworm/hammer_cli_foreman_webhooks/control
  dependencies/bookworm/hammer_cli_foreman_webhooks/copyright
  dependencies/bookworm/hammer_cli_foreman_webhooks/ruby-hammer-cli-foreman-webhooks.docs
  dependencies/bookworm/hammer_cli_foreman_webhooks/rules
  dependencies/bookworm/hammer_cli_foreman_webhooks/source/format
  dependencies/bookworm/hammer_cli_foreman_webhooks/watch
Labels: Not yet reviewed, DEB

#10594 add journald-logger to bookworm
  dependencies/bookworm/journald-logger/changelog
  dependencies/bookworm/journald-logger/compat
  dependencies/bookworm/journald-logger/control
  dependencies/bookworm/journald-logger/copyright
  dependencies/bookworm/journald-logger/ruby-journald-logger.docs
  dependencies/bookworm/journald-logger/ruby-tests.rake
  dependencies/bookworm/journald-logger/rules
  dependencies/bookworm/journald-logger/source/format
  dependencies/bookworm/journald-logger/watch
Labels: Not yet reviewed, DEB

#10596 add logging-journald to bookworm
  dependencies/bookworm/logging-journald/changelog
  dependencies/bookworm/logging-journald/compat
  dependencies/bookworm/logging-journald/control
  dependencies/bookworm/logging-journald/copyright
  dependencies/bookworm/logging-journald/ruby-logging-journald.docs
  dependencies/bookworm/logging-journald/ruby-logging-journald.examples
  dependencies/bookworm/logging-journald/ruby-tests.rake
  dependencies/bookworm/logging-journald/rules
  dependencies/bookworm/logging-journald/source/format
  dependencies/bookworm/logging-journald/watch
Labels: Not yet reviewed, DEB

#10597 add installer for bookworm
  debian/bookworm/foreman-installer/build_vars.sh
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-installer/compat
  debian/bookworm/foreman-installer/control
  debian/bookworm/foreman-installer/copyright
  debian/bookworm/foreman-installer/postinst
  debian/bookworm/foreman-installer/rules
  debian/bookworm/foreman-installer/source/format
Labels: Not yet reviewed, DEB

#10598 add foreman-proxy to bookworm
  debian/bookworm/foreman-proxy/build_vars.sh
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-proxy/compat
  debian/bookworm/foreman-proxy/control
  debian/bookworm/foreman-proxy/copyright
  debian/bookworm/foreman-proxy/dirs
  debian/bookworm/foreman-proxy/docs
  debian/bookworm/foreman-proxy/foreman-proxy-journald.install
  debian/bookworm/foreman-proxy/foreman-proxy.install
  debian/bookworm/foreman-proxy/foreman-proxy.preinst
  debian/bookworm/foreman-proxy/foreman-proxy.tmpfile
  debian/bookworm/foreman-proxy/links
  debian/bookworm/foreman-proxy/logrotate
  debian/bookworm/foreman-proxy/patches/series
  debian/bookworm/foreman-proxy/patches/settings_yml_defaults.patch
  debian/bookworm/foreman-proxy/postinst
  debian/bookworm/foreman-proxy/preinst
  debian/bookworm/foreman-proxy/prerm
  debian/bookworm/foreman-proxy/rules
  debian/bookworm/foreman-proxy/source/format
Labels: Not yet reviewed, DEB

#10599 add foreman-release for bookworm
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman-release/compat
  debian/bookworm/foreman-release/control
  debian/bookworm/foreman-release/copyright
  debian/bookworm/foreman-release/foreman-release.install
  debian/bookworm/foreman-release/foreman.list
  debian/bookworm/foreman-release/rules
  debian/bookworm/foreman-release/theforeman-archive-keyring.asc
Labels: Not yet reviewed, DEB

#10578 hammer_cli_foreman_google - add locale dir
  packages/plugins/rubygem-hammer_cli_foreman_google/hammer_cli_foreman_google-1.0.1.gem
  packages/plugins/rubygem-hammer_cli_foreman_google/hammer_cli_foreman_google-1.1.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_google/rubygem-hammer_cli_foreman_google.spec
Labels: RPM

#10607 Update rubygem-foreman-tasks to 9.0.4
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-9.0.1.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-9.0.4.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: RPM, Stable branch

#10612 Release Katello 4.12.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.12.0.gem
  packages/katello/rubygem-katello/katello-4.12.0.rc3.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM, Stable branch

#10610 Update rubygem-foreman-tasks to 9.1.1
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-9.1.0.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-9.1.1.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: RPM

#10609 Update ruby-foreman-tasks to 9.1.1
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB

#10608 Update ruby-foreman-tasks to 9.0.4
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB, Stable branch

#10563 Update smart_proxy_remote_execution_ssh to 0.10.4
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: Not yet reviewed, DEB, Stable branch

#10613 update hammer-cli-google for bookworm
  dependencies/bookworm/hammer_cli_foreman_google/changelog
Labels: Not yet reviewed, DEB

#10614 Only require shim-ia32 bootloader on RHEL 8 or less
  packages/foreman/foreman-bootloaders-redhat/foreman-bootloaders-redhat.spec
Labels: RPM

#10620 Bump rubygem-hammer_cli_foreman_kubevirt to 0.2.0-1
  packages/plugins/rubygem-hammer_cli_foreman_kubevirt/hammer_cli_foreman_kubevirt-0.1.5.gem
  packages/plugins/rubygem-hammer_cli_foreman_kubevirt/hammer_cli_foreman_kubevirt-0.2.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_kubevirt/rubygem-hammer_cli_foreman_kubevirt.spec
Labels: RPM

#10619 Bump rubygem-hammer_cli_foreman_azure_rm to 0.3.1-1
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/hammer_cli_foreman_azure_rm-0.3.0.gem
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/hammer_cli_foreman_azure_rm-0.3.1.gem
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/rubygem-hammer_cli_foreman_azure_rm.spec
Labels: RPM

#10617 Update rubygem-foreman-tasks to 9.1.1
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-9.1.0.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-9.1.1.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: RPM, Stable branch

#10618 Update ruby-foreman-tasks to 9.1.1
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB, Stable branch

#10621 Only require shim-ia32 bootloader on RHEL 8 or less
  packages/foreman/foreman-bootloaders-redhat/foreman-bootloaders-redhat.spec
Labels: Not yet reviewed, RPM, Stable branch

#10626 Update rubygem-apipie-dsl to 2.6.2
  packages/foreman/rubygem-apipie-dsl/apipie-dsl-2.6.1.gem
  packages/foreman/rubygem-apipie-dsl/apipie-dsl-2.6.2.gem
  packages/foreman/rubygem-apipie-dsl/rubygem-apipie-dsl.spec
Labels: RPM, Stable branch

#10622 Release 3.10.0
  packages/foreman/foreman-installer/foreman-installer-3.10.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.10.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.10.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.10.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.10.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.10.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.10.0-rc2.tar.bz2
  packages/foreman/foreman/foreman-3.10.0.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: RPM, Stable branch

#10623 Release 3.10.0
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
Labels: DEB, Stable branch

#10650 Rebuild Snapshot Management for Webpack 5
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Not yet reviewed, RPM

#10651 Rebuild Snapshot Management for Webpack 5
  packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
Labels: Not yet reviewed, RPM, Stable branch

#10657 Update rubygem-smart_proxy_dhcp_infoblox to 0.0.18
  packages/plugins/rubygem-smart_proxy_dhcp_infoblox/rubygem-smart_proxy_dhcp_infoblox.spec
  packages/plugins/rubygem-smart_proxy_dhcp_infoblox/smart_proxy_dhcp_infoblox-0.0.17.gem
  packages/plugins/rubygem-smart_proxy_dhcp_infoblox/smart_proxy_dhcp_infoblox-0.0.18.gem
Labels: RPM, Stable branch

#10656 Update rubygem-smart_proxy_dhcp_infoblox to 0.0.18
  packages/plugins/rubygem-smart_proxy_dhcp_infoblox/rubygem-smart_proxy_dhcp_infoblox.spec
  packages/plugins/rubygem-smart_proxy_dhcp_infoblox/smart_proxy_dhcp_infoblox-0.0.17.gem
  packages/plugins/rubygem-smart_proxy_dhcp_infoblox/smart_proxy_dhcp_infoblox-0.0.18.gem
Labels: Not yet reviewed, RPM, Stable branch

#10654 Update ruby-smart-proxy-dhcp-infoblox to 0.0.18
  plugins/smart_proxy_dhcp_infoblox/changelog
  plugins/smart_proxy_dhcp_infoblox/dhcp_infoblox.rb
Labels: Not yet reviewed, DEB, Stable branch

#10653 Update ruby-smart-proxy-dhcp-infoblox to 0.0.18
  plugins/smart_proxy_dhcp_infoblox/changelog
  plugins/smart_proxy_dhcp_infoblox/dhcp_infoblox.rb
Labels: Not yet reviewed, DEB, Stable branch
