Repository theforeman/foreman-packaging, pull requests merged in 2024-11, with the labels that each got.

#11428 update salt repo url to packages.broadcom.com
  repoclosure/yum.conf
Labels: Not yet reviewed, RPM

#11429 update salt repo url to packages.broadcom.com
  repoclosure/yum.conf
Labels: Not yet reviewed, RPM, Stable branch

#11430 update salt repo url to packages.broadcom.com
  repoclosure/yum.conf
Labels: Not yet reviewed, RPM, Stable branch

#11418 Update katello-pull-transport-migrate to 1.0.3
  packages/client/katello-pull-transport-migrate/katello-pull-transport-migrate-1.0.2.tar.gz
  packages/client/katello-pull-transport-migrate/katello-pull-transport-migrate-1.0.3.tar.gz
  packages/client/katello-pull-transport-migrate/katello-pull-transport-migrate.spec
Labels: RPM

#11426 Release mosquitto 2.0.19
  packages/plugins/mosquitto/mosquitto-2.0.17.tar.gz
  packages/plugins/mosquitto/mosquitto-2.0.19.tar.gz
  packages/plugins/mosquitto/mosquitto.spec
Labels: RPM, Stable branch

#11427 Release mosquitto 2.0.19
  packages/plugins/mosquitto/mosquitto-2.0.17.tar.gz
  packages/plugins/mosquitto/mosquitto-2.0.19.tar.gz
  packages/plugins/mosquitto/mosquitto.spec
Labels: RPM, Stable branch

#11435 Update rubygem-pulp_container_client to 2.22.0
  packages/katello/rubygem-pulp_container_client/pulp_container_client-2.21.1.gem
  packages/katello/rubygem-pulp_container_client/pulp_container_client-2.22.0.gem
  packages/katello/rubygem-pulp_container_client/rubygem-pulp_container_client.spec
Labels: RPM

#11438 Update rubygem-hammer_cli_foreman_azure_rm to 0.3.2
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/hammer_cli_foreman_azure_rm-0.3.1.gem
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/hammer_cli_foreman_azure_rm-0.3.2.gem
  packages/plugins/rubygem-hammer_cli_foreman_azure_rm/rubygem-hammer_cli_foreman_azure_rm.spec
Labels: RPM

#11434 Update ruby-smart-proxy-remote-execution-ssh to 0.11.4
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: DEB, Stable branch

#11433 Update rubygem-smart_proxy_remote_execution_ssh to 0.11.4
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.11.3.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.11.4.gem
Labels: RPM, Stable branch

#11436 Bump katello pulp container bindings to 2.22
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM

#11440 Update rubygem-foreman_virt_who_configure to 0.5.25
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.24.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.25.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: RPM

#11444 Add more code owners for rpm packages
  CODEOWNERS
Labels: RPM

#11447 Update ruby-foreman-remote-execution to 14.1.0
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB

#11446 Update rubygem-foreman_remote_execution to 14.1.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-14.0.2.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-14.1.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM

#11448 Bump version to 3.14-develop
  package_manifest.yaml
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: RPM

#11449 Bump changelog to 3.14.0
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: DEB

#11451 Update debian keyring for 3.13
  debian/bookworm/foreman-release/theforeman-archive-keyring.asc
  debian/bullseye/foreman-release/theforeman-archive-keyring.asc
  debian/jammy/foreman-release/theforeman-archive-keyring.asc
Labels: DEB, Stable branch

#11452 Update rubygem-foreman_fog_proxmox to 0.17.1
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.17.0.gem
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.17.1.gem
  packages/plugins/rubygem-foreman_fog_proxmox/rubygem-foreman_fog_proxmox.spec
Labels: RPM

#11450 Foreman 3.13 build updates
  mock/el8.cfg
  mock/el9.cfg
  package_manifest.yaml
  packages/foreman/foreman-release/foreman.gpg
  repoclosure/yum.conf
Labels: RPM, Stable branch

#11457 Release 3.13.0-rc1
  packages/foreman/foreman-installer/foreman-installer-3.13.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.13.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.13.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.13.0-rc1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: RPM, Stable branch

#11458 Release 3.13.0-rc1
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: DEB, Stable branch

#11453 Update rubygem-foreman_fog_proxmox to 0.17.1
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.17.0.gem
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.17.1.gem
  packages/plugins/rubygem-foreman_fog_proxmox/rubygem-foreman_fog_proxmox.spec
Labels: RPM, Stable branch

#11455 Update rubygem-foreman_fog_proxmox to 0.16.3
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.16.2.gem
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.16.3.gem
  packages/plugins/rubygem-foreman_fog_proxmox/rubygem-foreman_fog_proxmox.spec
Labels: RPM, Stable branch

#11454 Update ruby-foreman-fog-proxmox to 0.17.1
  plugins/ruby-foreman-fog-proxmox/debian/changelog
  plugins/ruby-foreman-fog-proxmox/debian/gem.list
  plugins/ruby-foreman-fog-proxmox/foreman_fog_proxmox.rb
Labels: DEB

#11456 Update ruby-foreman-fog-proxmox to 0.16.3
  plugins/ruby-foreman-fog-proxmox/debian/changelog
  plugins/ruby-foreman-fog-proxmox/debian/gem.list
  plugins/ruby-foreman-fog-proxmox/foreman_fog_proxmox.rb
Labels: DEB, Stable branch

#11462 Use Pulpcore 3.63 for Katello 4.15
  packages/katello/katello-repos/katello-repos.spec
Labels: RPM, Stable branch

#11461 Bump Katello + h-c-k for 4.16 branching
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM

#11469 Don't fail when shim-ia32 is missing when generating bootloaders
  packages/foreman/foreman-bootloaders-redhat/foreman-bootloaders-redhat.spec
  packages/foreman/foreman-bootloaders-redhat/foreman-generate-bootloaders
Labels: RPM

#11471 Release 4.14.1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.14.0.gem
  packages/katello/rubygem-katello/katello-4.14.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM, Stable branch

#11477 Update rubygem-foreman_remote_execution to 14.1.1
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-14.1.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-14.1.1.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM

#11478 Drop keycloak-httpd-client-install package
  package_manifest.yaml
  packages/foreman/keycloak-httpd-client-install/keycloak-httpd-client-install-1.2.2.tar.gz
  packages/foreman/keycloak-httpd-client-install/keycloak-httpd-client-install.spec
Labels: RPM

#11488 Release 4.15.0-rc1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.15.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM, Stable branch

#11490 Update rubygem-angular-rails-templates to 1.2.2
  packages/plugins/rubygem-angular-rails-templates/angular-rails-templates-1.1.0.gem
  packages/plugins/rubygem-angular-rails-templates/angular-rails-templates-1.2.2.gem
  packages/plugins/rubygem-angular-rails-templates/enable-fips.patch
  packages/plugins/rubygem-angular-rails-templates/rubygem-angular-rails-templates.spec
Labels: RPM

#11495 Release 3.13.0-rc2
  packages/foreman/foreman-installer/foreman-installer-3.13.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.13.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.13.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.13.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.13.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.13.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.13.0-rc1.tar.bz2
  packages/foreman/foreman/foreman-3.13.0-rc2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: RPM, Stable branch

#11496 Release 4.15.0-rc2
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.15.0.rc1.gem
  packages/katello/rubygem-katello/katello-4.15.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM, Stable branch

#11497 Release ansible-collection-theforeman-foreman 5.0.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-4.2.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-5.0.0.tar.gz
Labels: Not yet reviewed, RPM

#11498 Release ansible-collection-theforeman-foreman 5.0.0
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: Not yet reviewed, DEB

#11501 Release ansible-collection-redhat-satellite 5.0.0
  packages/satellite/ansible-collection-redhat-satellite/ansible-collection-redhat-satellite.spec
  packages/satellite/ansible-collection-redhat-satellite/redhat-satellite-4.2.0.tar.gz
  packages/satellite/ansible-collection-redhat-satellite/redhat-satellite-5.0.0.tar.gz
Labels: Not yet reviewed, RPM

#11500 Release 3.12.1
  packages/foreman/foreman-installer/foreman-installer-3.12.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.12.1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.12.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.12.1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.12.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.12.1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.12.0.tar.bz2
  packages/foreman/foreman/foreman-3.12.1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: RPM, Stable branch

#11516 Update rubygem-foreman_rh_cloud to 11.0.3
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-11.0.2.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-11.0.3.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: RPM

#11515 Drop puppet-strings dependency
  dependencies/bullseye/puppet-strings/changelog
  dependencies/bullseye/puppet-strings/compat
  dependencies/bullseye/puppet-strings/control
  dependencies/bullseye/puppet-strings/copyright
  dependencies/bullseye/puppet-strings/ruby-puppet-strings.docs
  dependencies/bullseye/puppet-strings/rules
  dependencies/bullseye/puppet-strings/source/format
Labels: DEB

#11517 foreman: Update GEM and NPM dependencies
  packages/foreman/foreman/foreman.spec
Labels: RPM

#11520 Release 3.11.5
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: DEB, Stable branch

#11521 Release 3.11.5
  packages/foreman/foreman-installer/foreman-installer-3.11.4.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.11.5.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.11.4.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.11.5.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.11.4.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.11.5.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.11.4.tar.bz2
  packages/foreman/foreman/foreman-3.11.5.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: RPM, Stable branch

#11530 Update rubygem-foreman_resource_quota to 0.3.1
  packages/plugins/rubygem-foreman_resource_quota/foreman_resource_quota-0.2.2.gem
  packages/plugins/rubygem-foreman_resource_quota/foreman_resource_quota-0.3.1.gem
  packages/plugins/rubygem-foreman_resource_quota/rubygem-foreman_resource_quota.spec
Labels: RPM
