Repository theforeman/foreman-packaging, pull requests merged in 2024-12, with the labels that each got.

#11317 Add foreman_ygg_migration package
  comps/comps-foreman-client-el8.xml
  comps/comps-foreman-client-el9.xml
  package_manifest.yaml
  packages/client/foreman_ygg_migration/foreman_ygg_migration.spec
Labels: RPM

#11296 Update foreman_ygg_worker to 0.3.0
  packages/client/foreman_ygg_worker/foreman_ygg_worker-0.2.2.tar.gz
  packages/client/foreman_ygg_worker/foreman_ygg_worker-0.3.0.tar.gz
  packages/client/foreman_ygg_worker/foreman_ygg_worker.spec
Labels: RPM

#11531 Release Katello 4.15.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.15.0.gem
  packages/katello/rubygem-katello/katello-4.15.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM, Stable branch

#11533 Release 3.13.0
  packages/foreman/foreman-installer/foreman-installer-3.13.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.13.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.13.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.13.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.13.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.13.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.13.0-rc2.tar.bz2
  packages/foreman/foreman/foreman-3.13.0.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Not yet reviewed, RPM, Stable branch

#11534 Release 3.13.0
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: Not yet reviewed, DEB, Stable branch

#11551 Update rubygem-fog-kubevirt to 1.4.0
  packages/plugins/rubygem-fog-kubevirt/fog-kubevirt-1.3.7.gem
  packages/plugins/rubygem-fog-kubevirt/fog-kubevirt-1.4.0.gem
  packages/plugins/rubygem-fog-kubevirt/rubygem-fog-kubevirt.spec
Labels: RPM

#11552 Release 4.14.2
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.14.1.gem
  packages/katello/rubygem-katello/katello-4.14.2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM, Stable branch

#11553 Release smart_proxy_container_gateway-3.1.1
  packages/plugins/rubygem-smart_proxy_container_gateway/rubygem-smart_proxy_container_gateway.spec
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-3.1.0.gem
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-3.1.1.gem
Labels: RPM

#11556 Release ansible-collection-theforeman-foreman 5.1.0
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: DEB

#11555 Release ansible-collection-theforeman-foreman 5.1.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-5.0.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-5.1.0.tar.gz
Labels: RPM

#11557 Release ansible-collection-redhat-satellite 5.1.0
  packages/satellite/ansible-collection-redhat-satellite/ansible-collection-redhat-satellite.spec
  packages/satellite/ansible-collection-redhat-satellite/redhat-satellite-5.0.0.tar.gz
  packages/satellite/ansible-collection-redhat-satellite/redhat-satellite-5.1.0.tar.gz
Labels: RPM

#11558 Update rubygem-foreman_kubevirt to 0.3.0
  packages/plugins/rubygem-foreman_kubevirt/foreman_kubevirt-0.2.0.gem
  packages/plugins/rubygem-foreman_kubevirt/foreman_kubevirt-0.3.0.gem
  packages/plugins/rubygem-foreman_kubevirt/rubygem-foreman_kubevirt.spec
Labels: RPM

#11561 Drop python3-psutil on foreman-client-el9
  comps/comps-foreman-client-el9.xml
Labels: RPM

#11554 Release smart_proxy_container_gateway-3.1.1
  packages/plugins/rubygem-smart_proxy_container_gateway/rubygem-smart_proxy_container_gateway.spec
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-3.1.0.gem
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-3.1.1.gem
Labels: RPM, Stable branch

#11566 Update rubygem-foreman_puppet to 8.1.0
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-8.0.0.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-8.1.0.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: Not yet reviewed, RPM

#11443 Rails 7.0.8.6
  packages/foreman/rubygem-actioncable/actioncable-6.1.7.10.gem
  packages/foreman/rubygem-actioncable/actioncable-7.0.8.6.gem
  packages/foreman/rubygem-actioncable/rubygem-actioncable.spec
  packages/foreman/rubygem-actionmailbox/actionmailbox-6.1.7.10.gem
  packages/foreman/rubygem-actionmailbox/actionmailbox-7.0.8.6.gem
  packages/foreman/rubygem-actionmailbox/rubygem-actionmailbox.spec
  packages/foreman/rubygem-actionmailer/actionmailer-6.1.7.10.gem
  packages/foreman/rubygem-actionmailer/actionmailer-7.0.8.6.gem
  packages/foreman/rubygem-actionmailer/rubygem-actionmailer.spec
  packages/foreman/rubygem-actionpack/actionpack-6.1.7.10.gem
  packages/foreman/rubygem-actionpack/actionpack-7.0.8.6.gem
  packages/foreman/rubygem-actionpack/rubygem-actionpack.spec
  packages/foreman/rubygem-actiontext/actiontext-6.1.7.10.gem
  packages/foreman/rubygem-actiontext/actiontext-7.0.8.6.gem
  packages/foreman/rubygem-actiontext/rubygem-actiontext.spec
  packages/foreman/rubygem-actionview/actionview-6.1.7.10.gem
  packages/foreman/rubygem-actionview/actionview-7.0.8.6.gem
  packages/foreman/rubygem-actionview/rubygem-actionview.spec
  packages/foreman/rubygem-activejob/activejob-6.1.7.10.gem
  packages/foreman/rubygem-activejob/activejob-7.0.8.6.gem
  packages/foreman/rubygem-activejob/rubygem-activejob.spec
  packages/foreman/rubygem-activemodel/activemodel-6.1.7.10.gem
  packages/foreman/rubygem-activemodel/activemodel-7.0.8.6.gem
  packages/foreman/rubygem-activemodel/rubygem-activemodel.spec
  packages/foreman/rubygem-activerecord/activerecord-6.1.7.10.gem
  packages/foreman/rubygem-activerecord/activerecord-7.0.8.6.gem
  packages/foreman/rubygem-activerecord/rubygem-activerecord.spec
  packages/foreman/rubygem-activestorage/activestorage-6.1.7.10.gem
  packages/foreman/rubygem-activestorage/activestorage-7.0.8.6.gem
  packages/foreman/rubygem-activestorage/rubygem-activestorage.spec
  packages/foreman/rubygem-activesupport/activesupport-6.1.7.10.gem
  packages/foreman/rubygem-activesupport/activesupport-7.0.8.6.gem
  packages/foreman/rubygem-activesupport/rubygem-activesupport.spec
  packages/foreman/rubygem-rails/rails-6.1.7.10.gem
  packages/foreman/rubygem-rails/rails-7.0.8.6.gem
  packages/foreman/rubygem-rails/rubygem-rails.spec
  packages/foreman/rubygem-railties/railties-6.1.7.10.gem
  packages/foreman/rubygem-railties/railties-7.0.8.6.gem
  packages/foreman/rubygem-railties/rubygem-railties.spec
Labels: Not yet reviewed, RPM

#11567 Update Foreman Rails dependency
  packages/foreman/foreman/foreman.spec
Labels: RPM

#11532 Foreman Client el10 build support
  comps/comps-foreman-client-el10.xml
  package_manifest.yaml
  repoclosure/yum.conf
Labels: RPM

#11588 don't publish katello-pull-transport-migrate until ygg_worker is built
  comps/comps-foreman-client-el10.xml
Labels: RPM

#11598 correctly regenerate Puppet certs when changing hostname
  packages/katello/katello/hostname-change.rb
  packages/katello/katello/katello.spec
Labels: RPM

#11601 Update ruby-foreman-remote-execution to 14.1.4
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB

#11603 Update smart_proxy_remote_execution_ssh to 0.11.5
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: DEB
