Repository theforeman/foreman-packaging, pull requests merged in 2024-09, with the labels that each got.

#11196 Correctly use Pulpcore 3.49 repos
  packages/katello/katello-repos/katello-repos.spec
Labels: RPM, Stable branch

#11197 Use Puppet 8 for repoclosure
  mock/el7.cfg
  mock/el8.cfg
  package_manifest.yaml
  repoclosure/yum.conf
Labels: RPM

#11206 Release 3.11.2
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: DEB, Stable branch

#11205 Release 3.11.2
  packages/foreman/foreman-installer/foreman-installer-3.11.1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.11.2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.11.1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.11.2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.11.1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.11.2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.11.1.tar.bz2
  packages/foreman/foreman/foreman-3.11.2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: RPM, Stable branch

#11207 Release 3.10.1
  packages/foreman/foreman-installer/foreman-installer-3.10.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.10.1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.10.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.10.1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.10.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.10.1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.10.0.tar.bz2
  packages/foreman/foreman/foreman-3.10.1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: RPM, Stable branch

#11209 Rebuild expire_hosts, monitoring, puppet, salt against 3.10
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
  packages/plugins/rubygem-foreman_salt/rubygem-foreman_salt.spec
Labels: Not yet reviewed, RPM, Stable branch

#11210 Rebuild expire_hosts, monitoring, puppet, salt against 3.11
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
  packages/plugins/rubygem-foreman_salt/rubygem-foreman_salt.spec
Labels: Not yet reviewed, RPM, Stable branch

#11211 Rebuild expire_hosts, monitoring, puppet, salt against 3.12
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
  packages/plugins/rubygem-foreman_salt/rubygem-foreman_salt.spec
Labels: Not yet reviewed, RPM, Stable branch

#11212 Rebuild expire_hosts, monitoring, puppet, salt against nightly
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
  packages/plugins/rubygem-foreman_salt/rubygem-foreman_salt.spec
Labels: Not yet reviewed, RPM

#11214 Release 3.12.0-rc2
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: Not yet reviewed, DEB, Stable branch

#11220 Update rubygem-foreman_rh_cloud to 10.0.2
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-10.0.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-10.0.2.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: RPM

#11147 Update rubygem-hammer_cli_foreman_scc_manager to 0.3.0 rpm develop
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/hammer_cli_foreman_scc_manager-0.1.0.gem
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/hammer_cli_foreman_scc_manager-0.3.0.gem
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/rubygem-hammer_cli_foreman_scc_manager.spec
Labels: RPM

#11217 Fix build on amazonlinux
  packages/client/katello-host-tools/katello-host-tools.spec
Labels: RPM

#11216 Update ansible-runner to 2.3.6
  packages/plugins/ansible-runner/ansible-runner-2.2.1.tar.gz
  packages/plugins/ansible-runner/ansible-runner-2.3.6.tar.gz
  packages/plugins/ansible-runner/ansible-runner.spec
Labels: RPM

#11246 Update foreman-remote-execution to 13.2.5
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-13.2.4.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-13.2.5.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: Not yet reviewed, RPM, Stable branch

#11245 Release 4.14.0-rc3
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.14.0.rc2.gem
  packages/katello/rubygem-katello/katello-4.14.0.rc3.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM, Stable branch

#11222 Add fapolicyd restart to ensure rules get loaded
  packages/foreman/foreman-fapolicyd/foreman-fapolicyd.spec
Labels: RPM

#11256 Add fapolicyd restart to ensure rules get loaded
  packages/foreman/foreman-fapolicyd/foreman-fapolicyd.spec
Labels: Stable branch

#11262 Update rubygem-hammer_cli_foreman_scc_manager to 0.3.0 Foreman 3.12
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/hammer_cli_foreman_scc_manager-0.1.0.gem
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/hammer_cli_foreman_scc_manager-0.3.0.gem
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/rubygem-hammer_cli_foreman_scc_manager.spec
Labels: RPM, Stable branch

#11263 Update rubygem-hammer_cli_foreman_scc_manager to 0.3.0 Foreman 3.11
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/hammer_cli_foreman_scc_manager-0.1.0.gem
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/hammer_cli_foreman_scc_manager-0.3.0.gem
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/rubygem-hammer_cli_foreman_scc_manager.spec
Labels: RPM, Stable branch

#11267 Update ruby-foreman-maintain to 1.7.4
  dependencies/bookworm/foreman_maintain/changelog
  dependencies/bullseye/foreman_maintain/changelog
  dependencies/focal/foreman_maintain/changelog
  dependencies/jammy/foreman_maintain/changelog
Labels: Not yet reviewed, DEB, Stable branch

#11266 Update rubygem-foreman_maintain to 1.7.4
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.7.3.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.7.4.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Not yet reviewed, RPM, Stable branch

#11261 add rex-cockpit for debian
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/control
  plugins/ruby-foreman-remote-execution/debian/ruby-foreman-remote-execution-cockpit.dirs
  plugins/ruby-foreman-remote-execution/debian/ruby-foreman-remote-execution-cockpit.install
  plugins/ruby-foreman-remote-execution/debian/rules
Labels: DEB

#11269 Update rubygem-hammer_cli_katello to 1.14.3
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.14.2.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.14.3.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Not yet reviewed, RPM, Stable branch

#11270 Release 3.12.0
  packages/foreman/foreman-installer/foreman-installer-3.12.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.12.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.12.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.12.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.12.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.12.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.12.0-rc2.tar.bz2
  packages/foreman/foreman/foreman-3.12.0.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Not yet reviewed, RPM, Stable branch

#11273 Release 4.14.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.14.0.gem
  packages/katello/rubygem-katello/katello-4.14.0.rc3.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM, Stable branch

#11272 Update rubygem-hammer_cli_foreman_rh_cloud to 1.0.3
  packages/katello/rubygem-hammer_cli_foreman_rh_cloud/hammer_cli_foreman_rh_cloud-1.0.2.gem
  packages/katello/rubygem-hammer_cli_foreman_rh_cloud/hammer_cli_foreman_rh_cloud-1.0.3.gem
  packages/katello/rubygem-hammer_cli_foreman_rh_cloud/rubygem-hammer_cli_foreman_rh_cloud.spec
Labels: RPM

#11280 Update rubygem-foreman_rh_cloud to 11.0.0
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-10.0.2.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-11.0.0.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: RPM

#11278 Update rubygem-hammer_cli_foreman_virt_who_configure to 0.1.1
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/hammer_cli_foreman_virt_who_configure-0.1.0.gem
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/hammer_cli_foreman_virt_who_configure-0.1.1.gem
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/rubygem-hammer_cli_foreman_virt_who_configure.spec
Labels: Not yet reviewed, RPM

#11279 Update rubygem-foreman_azure_rm to 3.0.1
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-3.0.0.gem
  packages/plugins/rubygem-foreman_azure_rm/foreman_azure_rm-3.0.1.gem
  packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
Labels: Not yet reviewed, RPM

#11282 [cherrypick] Update rubygem-hammer_cli_foreman_rh_cloud to 1.0.3
  packages/katello/rubygem-hammer_cli_foreman_rh_cloud/hammer_cli_foreman_rh_cloud-1.0.2.gem
  packages/katello/rubygem-hammer_cli_foreman_rh_cloud/hammer_cli_foreman_rh_cloud-1.0.3.gem
  packages/katello/rubygem-hammer_cli_foreman_rh_cloud/rubygem-hammer_cli_foreman_rh_cloud.spec
Labels: Not yet reviewed, RPM, Stable branch

#11283 [cherrypick] Update rubygem-hammer_cli_foreman_virt_who_configure to 0.1.1
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/hammer_cli_foreman_virt_who_configure-0.1.0.gem
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/hammer_cli_foreman_virt_who_configure-0.1.1.gem
  packages/katello/rubygem-hammer_cli_foreman_virt_who_configure/rubygem-hammer_cli_foreman_virt_who_configure.spec
Labels: Not yet reviewed, RPM, Stable branch

#11281 Update rubygem-foreman_rh_cloud to 10.0.2
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-10.0.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-10.0.2.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: RPM, Stable branch

#11268 Update rubygem-newt to 1.0.1
  packages/plugins/rubygem-newt/newt-0.9.7.gem
  packages/plugins/rubygem-newt/newt-1.0.1.gem
  packages/plugins/rubygem-newt/rubygem-newt.spec
Labels: RPM

#11120 Use legacy-peer-deps in npm2rpm
  add_npm_package.sh
Labels: RPM

#11289 Update ruby-smart-proxy-remote-execution-ssh to 0.11.3
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: DEB, Stable branch

#11288 Update rubygem-smart_proxy_remote_execution_ssh to 0.11.3
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.11.2.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.11.3.gem
Labels: RPM, Stable branch

#11290 Update rubygem-foreman_theme_satellite to 13.3.1
  packages/satellite/rubygem-foreman_theme_satellite/foreman_theme_satellite-13.3.0.gem
  packages/satellite/rubygem-foreman_theme_satellite/foreman_theme_satellite-13.3.1.gem
  packages/satellite/rubygem-foreman_theme_satellite/rubygem-foreman_theme_satellite.spec
Labels: Not yet reviewed, RPM, Stable branch

#11221 Fix fdi-service dependencies and build RPMs
  packages/plugins/foreman-discovery-image-service/foreman-discovery-image-service.spec
Labels: RPM

#11297 add el9 config for mock
  mock/el9.cfg
Labels: RPM

#11298 Update rubygem-foreman_acd to 0.10.0
  packages/plugins/rubygem-foreman_acd/foreman_acd-0.10.0.gem
  packages/plugins/rubygem-foreman_acd/foreman_acd-0.9.7.gem
  packages/plugins/rubygem-foreman_acd/rubygem-foreman_acd.spec
Labels: RPM

#11299 Update rubygem-foreman_acd to 0.10.0
  packages/plugins/rubygem-foreman_acd/foreman_acd-0.10.0.gem
  packages/plugins/rubygem-foreman_acd/foreman_acd-0.9.7.gem
  packages/plugins/rubygem-foreman_acd/rubygem-foreman_acd.spec
Labels: RPM, Stable branch

#11300 Update rubygem-foreman_acd to 0.10.0
  packages/plugins/rubygem-foreman_acd/foreman_acd-0.10.0.gem
  packages/plugins/rubygem-foreman_acd/foreman_acd-0.9.7.gem
  packages/plugins/rubygem-foreman_acd/rubygem-foreman_acd.spec
Labels: RPM, Stable branch

#11303 Update ruby-foreman-maintain to 1.7.5
  dependencies/bookworm/foreman_maintain/changelog
  dependencies/bullseye/foreman_maintain/changelog
  dependencies/focal/foreman_maintain/changelog
  dependencies/jammy/foreman_maintain/changelog
Labels: Not yet reviewed, DEB, Stable branch

#11304 Update rubygem-foreman_maintain to 1.7.5
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.7.4.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.7.5.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Not yet reviewed, RPM, Stable branch
