Repository theforeman/foreman-packaging, pull requests merged in 2024-08, with the labels that each got.

#11076 Update rubygem-foreman_ansible to 14.2.0
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-14.1.1.gem
  packages/plugins/rubygem-foreman_ansible/foreman_ansible-14.2.0.gem
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
Labels: RPM

#11078 Update rubygem-foreman_remote_execution to 13.2.4
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-13.2.3.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-13.2.4.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM

#11081 Update ruby-foreman-puppet to 6.4.0
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: DEB, Stable branch

#11080 Update rubygem-foreman_puppet to 6.4.0
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-6.2.0.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-6.4.0.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: RPM, Stable branch

#11082 Update rubygem-foreman_scc_manager to 3.1.0
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-3.0.0.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-3.1.0.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Not yet reviewed, RPM

#9962 Fix foreman_ygg_worker build on CentOS 9-stream
  packages/client/foreman_ygg_worker/foreman_ygg_worker.spec
Labels: RPM

#11071 Update rubygem-foreman_openscap to 9.0.4
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-9.0.3.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-9.0.4.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: RPM

#11098 Fixes #37687 - Obsolete rubygem-anemone
  packages/foreman/foreman-obsolete-packages/foreman-obsolete-packages.spec
Labels: RPM

#11102 Bump smart_proxy_container_gateway to 3.1.0
  packages/plugins/rubygem-smart_proxy_container_gateway/rubygem-smart_proxy_container_gateway.spec
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-3.0.0.gem
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-3.1.0.gem
Labels: RPM

#11110 Use epel-7-x86_64 copr target for client repos
  package_manifest.yaml
  repoclosure/yum.conf
Labels: RPM

#11100 Update rubygem-foreman_rh_cloud to 10.0.1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-10.0.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-9.0.56.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: RPM, Stable branch

#11099 Cherrypick RH_Cloud 10.0.1 into Foreman 3.11
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-10.0.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-9.0.56.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: RPM, Stable branch

#11113 Use rhel-7 buildroot for EL7 client again
  package_manifest.yaml
Labels: RPM

#11114 use correct archives url for EPEL
  package_manifest.yaml
  repoclosure/yum.conf
Labels: RPM

#11093 Update ruby-foreman-puppet to 7.0.0
  plugins/ruby-foreman-puppet/debian/changelog
  plugins/ruby-foreman-puppet/debian/gem.list
  plugins/ruby-foreman-puppet/foreman_puppet.rb
Labels: DEB, Stable branch

#11115 [TEMP] disable opensuse building of client
  package_manifest.yaml
Labels: Not yet reviewed, RPM

#11092 Update rubygem-foreman_puppet to 7.0.0 Foreman 3.11
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-6.3.0.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-7.0.0.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: RPM, Stable branch

#11118 Fix yggdrasil spec for suse
  packages/client/yggdrasil/yggdrasil.spec
Labels: RPM

#11122 Update rubygem-smart_proxy_dynflow to 0.9.3
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.9.2.gem
  packages/plugins/rubygem-smart_proxy_dynflow/smart_proxy_dynflow-0.9.3.gem
Labels: RPM

#11125 Use EPEL 7 from the archives
  package_manifest.yaml
  repoclosure/yum.conf
Labels: Not yet reviewed, RPM, Stable branch

#11126 Use EPEL 7 from the archives
  package_manifest.yaml
  repoclosure/yum.conf
Labels: RPM, Stable branch

#11083 Update rubygem-foreman_scc_manager to 3.1.0 Foreman 3.10
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-3.0.0.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-3.1.0.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: RPM, Stable branch

#11091 Update rubygem-foreman_scc_manager to 3.1.0 in Foreman 3.11
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-3.0.0.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-3.1.0.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: RPM, Stable branch

#11129 Update rubygem-foreman_fog_proxmox to 0.16.1-1
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.15.1.gem
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.16.1.gem
  packages/plugins/rubygem-foreman_fog_proxmox/rubygem-foreman_fog_proxmox.spec
Labels: RPM, Stable branch

#11145 Update keyring for 3.12
  debian/bookworm/foreman-release/theforeman-archive-keyring.asc
  debian/bullseye/foreman-release/theforeman-archive-keyring.asc
  debian/focal/foreman-release/theforeman-archive-keyring.asc
  debian/jammy/foreman-release/theforeman-archive-keyring.asc
Labels: Not yet reviewed, DEB, Stable branch

#11143 Update rubygem-foreman_virt_who_configure to 0.5.23
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.22.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.23.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: RPM

#11144 3.12 build system updates
  mock/el8.cfg
  package_manifest.yaml
  packages/foreman/foreman-release/foreman.gpg
  repoclosure/yum.conf
Labels: RPM, Stable branch

#11154 Release 3.12.0-rc1
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: Not yet reviewed, DEB, Stable branch

#11153 Release 3.12.0-rc1
  packages/foreman/foreman-installer/foreman-installer-3.12.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.12.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.12.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.12.0-rc1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Not yet reviewed, RPM, Stable branch

#11159 Update rubygem-foreman_maintain to 1.7.1
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.7.0.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.7.1.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Not yet reviewed, RPM, Stable branch

#11160 Fix client 3.12 staging repoclosure
  repoclosure/yum.conf
Labels: Not yet reviewed, RPM, Stable branch

#11161 Release 4.14.0-rc1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.14.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM, Stable branch

#11163 Release hammer_cli_katello 1.14.2
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.14.0.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.14.2.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Not yet reviewed, RPM, Stable branch

#11164 Add rubygem-base64 package
  comps/comps-foreman-plugins-el9.xml
  package_manifest.yaml
  packages/plugins/rubygem-base64/base64-0.2.0.gem
  packages/plugins/rubygem-base64/rubygem-base64.spec
Labels: RPM

#11141 hammer-cli-katello: use main instead of master
  package_manifest.yaml
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: Not yet reviewed, RPM

#11142 Bump Katello related packages to their 4.15 versions
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM

#11188 Update rubygem-foreman_maintain to 1.7.3
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.7.2.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.7.3.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Not yet reviewed, RPM, Stable branch

#11189 Update ruby-foreman-maintain to 1.7.3
  dependencies/bookworm/foreman_maintain/changelog
  dependencies/bullseye/foreman_maintain/changelog
  dependencies/focal/foreman_maintain/changelog
  dependencies/jammy/foreman_maintain/changelog
Labels: Not yet reviewed, DEB, Stable branch

#11192 Release ansible-collection-theforeman-foreman 4.2.0
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: Not yet reviewed, DEB

#11193 Release ansible-collection-theforeman-foreman 4.2.0
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: Not yet reviewed, DEB, Stable branch

#11191 Release ansible-collection-theforeman-foreman 4.2.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-4.1.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-4.2.0.tar.gz
Labels: Not yet reviewed, RPM
