Repository theforeman/foreman-packaging, pull requests merged in 2024-06, with the labels that each got.

#10882 document debian archival
  README.md
Labels: DEB

#10883 Switch EL8 repoclosure to AlmaLinux
  repoclosure/yum.conf
Labels: RPM

#10886 restore module_hotfixes for el8-appstream
  repoclosure/yum.conf
Labels: RPM

#10885 Switch EL8 repoclosure to AlmaLinux
  repoclosure/yum.conf
Labels: RPM, Stable branch

#10884 Switch EL8 repoclosure to AlmaLinux
  repoclosure/yum.conf
Labels: RPM, Stable branch

#10887 Switch EL8 repoclosure to AlmaLinux
  repoclosure/yum.conf
Labels: Not yet reviewed, RPM, Stable branch

#10866 Update rubygem-foreman_expire_host to 8.2.0
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-8.1.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-8.2.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: RPM

#10891 Update rubygem-foreman_expire_host to 8.2.0
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-8.1.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-8.2.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Not yet reviewed, RPM, Stable branch

#10892 Update rubygem-foreman_expire_host to 8.2.0
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-8.1.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-8.2.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Not yet reviewed, RPM, Stable branch

#10893 Update rubygem-foreman_expire_host to 8.2.0
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-8.1.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-8.2.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: Not yet reviewed, RPM, Stable branch

#10868 Update smart_proxy_monitoring to 0.3.0
  packages/plugins/rubygem-smart_proxy_monitoring/rubygem-smart_proxy_monitoring.spec
  packages/plugins/rubygem-smart_proxy_monitoring/smart_proxy_monitoring-0.2.0.gem
  packages/plugins/rubygem-smart_proxy_monitoring/smart_proxy_monitoring-0.3.0.gem
Labels: RPM

#10879 Update rubygem-foreman_monitoring to 3.2.0
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-3.1.0.gem
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-3.2.0.gem
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
Labels: Not yet reviewed, RPM, Stable branch

#10877 Update rubygem-foreman_monitoring to 3.2.0
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-3.1.0.gem
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-3.2.0.gem
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
Labels: Not yet reviewed, RPM, Stable branch

#10876 Update rubygem-foreman_monitoring to 3.2.0
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-3.1.0.gem
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-3.2.0.gem
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
Labels: Not yet reviewed, RPM, Stable branch

#10895 Update smart_proxy_monitoring to 0.3.0
  packages/plugins/rubygem-smart_proxy_monitoring/rubygem-smart_proxy_monitoring.spec
  packages/plugins/rubygem-smart_proxy_monitoring/smart_proxy_monitoring-0.2.0.gem
  packages/plugins/rubygem-smart_proxy_monitoring/smart_proxy_monitoring-0.3.0.gem
Labels: Not yet reviewed, RPM, Stable branch

#10894 Update smart_proxy_monitoring to 0.3.0
  packages/plugins/rubygem-smart_proxy_monitoring/rubygem-smart_proxy_monitoring.spec
  packages/plugins/rubygem-smart_proxy_monitoring/smart_proxy_monitoring-0.2.0.gem
  packages/plugins/rubygem-smart_proxy_monitoring/smart_proxy_monitoring-0.3.0.gem
Labels: RPM, Stable branch

#10897 Release 3.11.0-rc2
  packages/foreman/foreman-installer/foreman-installer-3.11.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.11.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.11.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.11.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.11.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.11.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.11.0-rc1.tar.bz2
  packages/foreman/foreman/foreman-3.11.0-rc2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Not yet reviewed, RPM, Stable branch

#10899 pin FFI to a version compatible with Ruby 2.7
  debian/bullseye/foreman/changelog
  debian/bullseye/foreman/rules
  debian/focal/foreman/changelog
  debian/focal/foreman/rules
Labels: Not yet reviewed, DEB

#10395 Drop noarch and set debug_package to nil rubygem-sassc
  packages/foreman/rubygem-sassc/rubygem-sassc.spec
Labels: RPM

#10919 Update rubygem-dynflow to 1.9.0
  packages/foreman/rubygem-dynflow/dynflow-1.8.4.gem
  packages/foreman/rubygem-dynflow/dynflow-1.9.0.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: RPM

#10920 Update dynflow to 1.9.0
  dependencies/bookworm/dynflow/changelog
  dependencies/bullseye/dynflow/changelog
  dependencies/focal/dynflow/changelog
  dependencies/jammy/dynflow/changelog
Labels: DEB

#10923 fm311
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.6.8.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.6.9.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Not yet reviewed, RPM, Stable branch

#10881 Deduplicate the repoclosure_lookaside_repos values
  package_manifest.yaml
Labels: RPM

#10925 Update ruby-foreman-tasks to 9.2.0
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: Not yet reviewed, DEB

#10930 Update ansiblerole-foreman_scap_client to 0.3.0
  packages/plugins/ansiblerole-foreman_scap_client/ansiblerole-foreman_scap_client.spec
  packages/plugins/ansiblerole-foreman_scap_client/foreman_scap_client-0.2.0.tar.gz
  packages/plugins/ansiblerole-foreman_scap_client/foreman_scap_client-0.3.0.tar.gz
Labels: RPM

#10926 Release 4.12.1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.12.0.gem
  packages/katello/rubygem-katello/katello-4.12.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM, Stable branch

#10931 scap client: support building on suse
  packages/client/rubygem-foreman_scap_client/rubygem-foreman_scap_client.spec
Labels: RPM

#10858 Update rubygem-foreman_scap_client to 0.6.0
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.5.3.gem
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.6.0.gem
  packages/client/rubygem-foreman_scap_client/rubygem-foreman_scap_client.spec
Labels: RPM

#10934 Add recommends on rubygem-irb for rubygem-railties
  packages/foreman/rubygem-railties/rubygem-railties.spec
Labels: RPM, Stable branch

#10935 Update rubygem-smart_proxy_remote_execution_ssh to 0.10.6
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.10.5.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.10.6.gem
Labels: RPM

#10936 Update smart_proxy_remote_execution_ssh to 0.10.6
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: DEB

#10938 Update rubygem-foreman_openscap to 9.0.1
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-9.0.0.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-9.0.1.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: RPM

#10939 Update rubygem-foreman_remote_execution to 13.2.1
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-13.2.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-13.2.1.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM

#10940 Update ruby-foreman-remote-execution to 13.2.1
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB

#10941 Update smart_proxy_remote_execution_ssh to 0.10.6
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: DEB, Stable branch

#10942 Update smart_proxy_remote_execution_ssh to 0.10.6
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: DEB, Stable branch

#10943 Update rubygem-smart_proxy_remote_execution_ssh to 0.10.6
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.10.5.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.10.6.gem
Labels: RPM, Stable branch

#10944 Update rubygem-smart_proxy_remote_execution_ssh to 0.10.6
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.10.5.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.10.6.gem
Labels: RPM, Stable branch

#10765 Bump to katello-host-tools 4.4.0
  packages/client/katello-host-tools/katello-host-tools-4.2.3.tar.gz
  packages/client/katello-host-tools/katello-host-tools-4.4.0.tar.gz
  packages/client/katello-host-tools/katello-host-tools.spec
Labels: RPM

#10679 Add rubygem-foreman_cve_scanner package
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-el9.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_cve_scanner/foreman_cve_scanner-0.0.1.gem
  packages/plugins/rubygem-foreman_cve_scanner/rubygem-foreman_cve_scanner.spec
Labels: RPM

#10957 Release 3.11.0
  packages/foreman/foreman-installer/foreman-installer-3.11.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.11.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.11.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.11.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.11.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.11.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.11.0-rc2.tar.bz2
  packages/foreman/foreman/foreman-3.11.0.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Not yet reviewed, RPM, Stable branch

#10956 Release 3.11.0
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: Not yet reviewed, DEB, Stable branch

#10955 Update rubygem-foreman_rh_cloud to 10.0.1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-10.0.1.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-9.0.56.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: Not yet reviewed, RPM

#10961 Release 4.13.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.13.0.gem
  packages/katello/rubygem-katello/katello-4.13.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM, Stable branch
