Repository theforeman/foreman-packaging, pull requests merged in 2024-05, with the labels that each got.

#10748 Use Candlepin 4.4
  packages/katello/katello-repos/katello-repos.spec
Labels: RPM

#10759 Rebuild plugins to enable webpack asset compression
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
  packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
  packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
  packages/plugins/rubygem-foreman_google/rubygem-foreman_google.spec
  packages/plugins/rubygem-foreman_hdm/rubygem-foreman_hdm.spec
  packages/plugins/rubygem-foreman_leapp/rubygem-foreman_leapp.spec
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
  packages/plugins/rubygem-foreman_statistics/rubygem-foreman_statistics.spec
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
  packages/plugins/rubygem-foreman_webhooks/rubygem-foreman_webhooks.spec
  packages/satellite/rubygem-foreman_theme_satellite/rubygem-foreman_theme_satellite.spec
Labels: Not yet reviewed, RPM

#10760 Add libyaml-dev to Build-Depends for psych
  debian/bookworm/foreman/changelog
  debian/bookworm/foreman/control
Labels: DEB

#10764 Bump pulp-container in rubygem-katello to 2.20
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM

#10763 Fixes #37419 - Patch puma to fix chunked upload bug
  packages/foreman/rubygem-puma/fix-request-chunking.patch
  packages/foreman/rubygem-puma/rubygem-puma.spec
Labels: RPM

#10766 Update rubygem-deface to 1.9.0
  packages/plugins/rubygem-deface/deface-1.5.3.gem
  packages/plugins/rubygem-deface/deface-1.9.0.gem
  packages/plugins/rubygem-deface/rubygem-deface.spec
Labels: RPM, Stable branch

#10761 Add rubygem-foreman_resource_quota package
  comps/comps-foreman-plugins-el8.xml
  comps/comps-foreman-plugins-el9.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_resource_quota/foreman_resource_quota-0.2.2.gem
  packages/plugins/rubygem-foreman_resource_quota/rubygem-foreman_resource_quota.spec
Labels: RPM

#10767 Bump hammer-cli-katello to 1.13
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: RPM

#10784 Update rubygem-foreman_openscap to 8.0.1
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-8.0.0.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-8.0.1.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: RPM

#10783 Release rubygem-foreman_scap_client 0.5.3
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.5.2.gem
  packages/client/rubygem-foreman_scap_client/foreman_scap_client-0.5.3.gem
  packages/client/rubygem-foreman_scap_client/rubygem-foreman_scap_client.spec
Labels: RPM

#10780 Update rubygem-smart_proxy_shellhooks to 0.9.3
  packages/plugins/rubygem-smart_proxy_shellhooks/rubygem-smart_proxy_shellhooks.spec
  packages/plugins/rubygem-smart_proxy_shellhooks/smart_proxy_shellhooks-0.9.2.gem
  packages/plugins/rubygem-smart_proxy_shellhooks/smart_proxy_shellhooks-0.9.3.gem
Labels: RPM

#10781 Update ruby-smart_proxy_shellhooks to 0.9.3
  plugins/smart_proxy_shellhooks/changelog
Labels: DEB

#10778 Update foreman_git_templates to 2.0.0
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.6.gem
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-2.0.0.gem
  packages/plugins/rubygem-foreman_git_templates/rubygem-foreman_git_templates.spec
Labels: RPM

#10777 Update rubygem-foreman_dlm to 3.0.0
  packages/plugins/rubygem-foreman_dlm/foreman_dlm-2.0.0.gem
  packages/plugins/rubygem-foreman_dlm/foreman_dlm-3.0.0.gem
  packages/plugins/rubygem-foreman_dlm/rubygem-foreman_dlm.spec
Labels: RPM

#10775 Update foreman_rescue to 4.0.0
  packages/plugins/rubygem-foreman_rescue/foreman_rescue-3.0.0.gem
  packages/plugins/rubygem-foreman_rescue/foreman_rescue-4.0.0.gem
  packages/plugins/rubygem-foreman_rescue/rubygem-foreman_rescue.spec
Labels: RPM

#10776 Update rubygem-foreman_wreckingball to 5.0.0
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-4.0.0.gem
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-5.0.0.gem
  packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
Labels: RPM

#10782 Update rubygem-smart_proxy_openscap to 0.10.0
  packages/plugins/rubygem-smart_proxy_openscap/rubygem-smart_proxy_openscap.spec
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.10.0.gem
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.9.2.gem
Labels: RPM

#10785 Update rubygem-foreman_remote_execution to 13.1.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-13.0.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-13.1.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM

#10786 Update ruby-foreman-remote-execution to 13.1.0
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB

#10797 Update rubygem-dynflow to 1.8.4
  packages/foreman/rubygem-dynflow/dynflow-1.8.3.gem
  packages/foreman/rubygem-dynflow/dynflow-1.8.4.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: RPM

#10798 Update ruby-dynflow to 1.8.4
  dependencies/bookworm/dynflow/changelog
  dependencies/bullseye/dynflow/changelog
  dependencies/focal/dynflow/changelog
  dependencies/jammy/dynflow/changelog
Labels: DEB

#10796 Update rubygem-foreman_wreckingball to 5.0.0
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-4.0.0.gem
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-5.0.0.gem
  packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
Labels: Not yet reviewed, RPM, Stable branch

#10795 Update rubygem-foreman_wreckingball to 5.0.0
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-4.0.0.gem
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-5.0.0.gem
  packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
Labels: Not yet reviewed, RPM, Stable branch

#10794 Update foreman_git_templates to 2.0.0
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.6.gem
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-2.0.0.gem
  packages/plugins/rubygem-foreman_git_templates/rubygem-foreman_git_templates.spec
Labels: Not yet reviewed, RPM, Stable branch

#10793 Update rubygem-foreman_vault to 2.0.0
  packages/plugins/rubygem-foreman_vault/foreman_vault-1.2.0.gem
  packages/plugins/rubygem-foreman_vault/foreman_vault-2.0.0.gem
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
Labels: Not yet reviewed, RPM, Stable branch

#10792 Update foreman_rescue to 4.0.0
  packages/plugins/rubygem-foreman_rescue/foreman_rescue-3.0.0.gem
  packages/plugins/rubygem-foreman_rescue/foreman_rescue-4.0.0.gem
  packages/plugins/rubygem-foreman_rescue/rubygem-foreman_rescue.spec
Labels: Not yet reviewed, RPM, Stable branch

#10791 Update rubygem-foreman_dlm to 3.0.0
  packages/plugins/rubygem-foreman_dlm/foreman_dlm-2.0.0.gem
  packages/plugins/rubygem-foreman_dlm/foreman_dlm-3.0.0.gem
  packages/plugins/rubygem-foreman_dlm/rubygem-foreman_dlm.spec
Labels: Not yet reviewed, RPM, Stable branch

#10789 Update rubygem-foreman_vault to 2.0.0
  packages/plugins/rubygem-foreman_vault/foreman_vault-1.2.0.gem
  packages/plugins/rubygem-foreman_vault/foreman_vault-2.0.0.gem
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
Labels: Not yet reviewed, RPM, Stable branch

#10787 Update rubygem-foreman_dlm to 3.0.0
  packages/plugins/rubygem-foreman_dlm/foreman_dlm-2.0.0.gem
  packages/plugins/rubygem-foreman_dlm/foreman_dlm-3.0.0.gem
  packages/plugins/rubygem-foreman_dlm/rubygem-foreman_dlm.spec
Labels: Not yet reviewed, RPM, Stable branch

#10790 Update foreman_git_templates to 2.0.0
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-1.0.6.gem
  packages/plugins/rubygem-foreman_git_templates/foreman_git_templates-2.0.0.gem
  packages/plugins/rubygem-foreman_git_templates/rubygem-foreman_git_templates.spec
Labels: Not yet reviewed, RPM, Stable branch

#10803 Add libyaml-dev to Depends for psych
  debian/bookworm/foreman/changelog
  debian/bookworm/foreman/control
Labels: DEB

#10731 un-SCL-ify hammer-cli-katello
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: RPM

#10805 Update foreman_rescue to 4.0.1
  packages/plugins/rubygem-foreman_rescue/foreman_rescue-4.0.0.gem
  packages/plugins/rubygem-foreman_rescue/foreman_rescue-4.0.1.gem
  packages/plugins/rubygem-foreman_rescue/rubygem-foreman_rescue.spec
Labels: RPM

#10806 Update foreman_rescue to 4.0.1
  packages/plugins/rubygem-foreman_rescue/foreman_rescue-4.0.0.gem
  packages/plugins/rubygem-foreman_rescue/foreman_rescue-4.0.1.gem
  packages/plugins/rubygem-foreman_rescue/rubygem-foreman_rescue.spec
Labels: RPM, Stable branch

#10807 Update foreman_rescue to 4.0.1
  packages/plugins/rubygem-foreman_rescue/foreman_rescue-4.0.0.gem
  packages/plugins/rubygem-foreman_rescue/foreman_rescue-4.0.1.gem
  packages/plugins/rubygem-foreman_rescue/rubygem-foreman_rescue.spec
Labels: RPM, Stable branch

#10810 Update rubygem-foreman_rh_cloud to 9.0.56
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-9.0.55.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-9.0.56.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: RPM, Stable branch

#10804 add opensuse-leap-15.5-x86_64 build target
  comps/comps-foreman-client-sles155.xml
  package_manifest.yaml
Labels: RPM

#10812 merge back plugins-copr-with-el9 into plugins-copr
  package_manifest.yaml
Labels: RPM

#10813 repoclosure for Leap 15.5
  package_manifest.yaml
  repoclosure/yum.conf
Labels: RPM

#10816 Foreman 3.11 branching build updates
  mock/el8.cfg
  package_manifest.yaml
  packages/foreman/foreman-release/foreman.gpg
  repoclosure/yum.conf
Labels: RPM, Stable branch

#10817 Foreman 3.11 branching updates
  debian/bookworm/foreman-release/theforeman-archive-keyring.asc
  debian/bullseye/foreman-release/theforeman-archive-keyring.asc
  debian/focal/foreman-release/theforeman-archive-keyring.asc
  debian/jammy/foreman-release/theforeman-archive-keyring.asc
Labels: DEB, Stable branch

#10815 Bump version to 3.12-develop
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: DEB

#10814 Bump version to 3.12-develop
  package_manifest.yaml
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: RPM

#10823 Release 3.11.0-rc1
  packages/foreman/foreman-installer/foreman-installer-3.11.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.11.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.11.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.11.0-rc1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: RPM, Stable branch

#10818 Update rubygem-foreman_virt_who_configure to 0.5.22
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.21.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.22.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: RPM

#10824 Release 3.11.0-rc1
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: DEB, Stable branch

#10821 Update rubygem-foreman_openscap to 8.0.2
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-8.0.1.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-8.0.2.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: RPM

#10825 Update rubygem-foreman_remote_execution to 13.1.1
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-13.1.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-13.1.1.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM

#10826 Update ruby-foreman-remote-execution to 13.1.1
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB

#10839 Release hammer_cli 3.11.0
  dependencies/bookworm/hammer_cli/changelog
  dependencies/bullseye/hammer_cli/changelog
  dependencies/focal/hammer_cli/changelog
  dependencies/jammy/hammer_cli/changelog
Labels: Not yet reviewed, DEB

#10820 Release hammer_cli[_foreman] 3.11.0
  dependencies/bookworm/hammer_cli_foreman/changelog
  dependencies/bookworm/hammer_cli_foreman/control
  dependencies/bullseye/hammer_cli_foreman/changelog
  dependencies/bullseye/hammer_cli_foreman/control
  dependencies/focal/hammer_cli_foreman/changelog
  dependencies/focal/hammer_cli_foreman/control
  dependencies/jammy/hammer_cli_foreman/changelog
  dependencies/jammy/hammer_cli_foreman/control
Labels: Not yet reviewed, DEB

#10840 Release hammer_cli 3.11.0
  dependencies/bookworm/hammer_cli/changelog
  dependencies/bullseye/hammer_cli/changelog
  dependencies/focal/hammer_cli/changelog
  dependencies/jammy/hammer_cli/changelog
Labels: Not yet reviewed, DEB, Stable branch

#10841 Release hammer_cli_foreman 3.11.0
  dependencies/bookworm/hammer_cli_foreman/changelog
  dependencies/bookworm/hammer_cli_foreman/control
  dependencies/bullseye/hammer_cli_foreman/changelog
  dependencies/bullseye/hammer_cli_foreman/control
  dependencies/focal/hammer_cli_foreman/changelog
  dependencies/focal/hammer_cli_foreman/control
  dependencies/jammy/hammer_cli_foreman/changelog
  dependencies/jammy/hammer_cli_foreman/control
Labels: Not yet reviewed, DEB, Stable branch

#10822 Bump hammer-cli-katello to 1.14
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: RPM

#10846 Update ruby-foreman-monitoring to 3.1.0
  plugins/ruby-foreman-monitoring/debian/changelog
  plugins/ruby-foreman-monitoring/debian/gem.list
  plugins/ruby-foreman-monitoring/foreman_monitoring.rb
Labels: Not yet reviewed, DEB, Stable branch

#10849 Update rubygem-foreman_monitoring to 3.1.0
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-3.0.0.gem
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-3.1.0.gem
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
Labels: Not yet reviewed, RPM, Stable branch

#10851 Update rubygem-foreman_monitoring to 3.1.0
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-3.0.0.gem
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-3.1.0.gem
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
Labels: Not yet reviewed, RPM, Stable branch

#10850 Update rubygem-foreman_monitoring to 3.1.0
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-3.0.0.gem
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-3.1.0.gem
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
Labels: Not yet reviewed, RPM, Stable branch

#10847 Update ruby-foreman-monitoring to 3.1.0
  plugins/ruby-foreman-monitoring/debian/changelog
  plugins/ruby-foreman-monitoring/debian/gem.list
  plugins/ruby-foreman-monitoring/foreman_monitoring.rb
Labels: Not yet reviewed, DEB, Stable branch

#10848 Update ruby-foreman-monitoring to 3.1.0
  plugins/ruby-foreman-monitoring/debian/changelog
  plugins/ruby-foreman-monitoring/debian/gem.list
  plugins/ruby-foreman-monitoring/foreman_monitoring.rb
Labels: Not yet reviewed, DEB, Stable branch

#10852 Bump Katello devel version to 4.14
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM

#10861 Release 4.13.0-rc1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.13.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM, Stable branch

#10860 Update smart_proxy_remote_execution_ssh to 0.10.5
  plugins/smart_proxy_remote_execution_ssh/changelog
  plugins/smart_proxy_remote_execution_ssh/remote_execution_ssh.rb
Labels: DEB

#10859 Update rubygem-smart_proxy_remote_execution_ssh to 0.10.5
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/rubygem-smart_proxy_remote_execution_ssh.spec
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.10.4.gem
  packages/plugins/rubygem-smart_proxy_remote_execution_ssh/smart_proxy_remote_execution_ssh-0.10.5.gem
Labels: RPM

#10857 Update ruby-foreman-remote-execution to 13.2.0
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB

#10856 Update rubygem-foreman_remote_execution to 13.2.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-13.1.1.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-13.2.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM

#10855 Update rubygem-smart_proxy_openscap to 0.11.0
  packages/plugins/rubygem-smart_proxy_openscap/rubygem-smart_proxy_openscap.spec
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.10.0.gem
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.11.0.gem
Labels: RPM

#10854 Update rubygem-foreman_openscap to 9.0.0
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-8.0.2.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-9.0.0.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: RPM

#10853 Update rubygem-foreman_openscap to 8.0.2
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-8.0.1.gem
  packages/plugins/rubygem-foreman_openscap/foreman_openscap-8.0.2.gem
  packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
Labels: RPM, Stable branch

#10869 Add a puppet_version to the package manifest
  package_manifest.yaml
Labels: RPM
