Repository theforeman/foreman-packaging, pull requests merged in 2024-02, with the labels that each got.

#10355 Use the copr_project_user to calculate the Copr repo root
  package_manifest.yaml
Labels: RPM

#10389 Use --legacy-peer-deps in bundled NPM packages
  packages/foreman/nodejs-babel-core/nodejs-babel-core.spec
  packages/foreman/nodejs-babel-loader/nodejs-babel-loader.spec
  packages/foreman/nodejs-babel-plugin-transform-class-properties/nodejs-babel-plugin-transform-class-properties.spec
  packages/foreman/nodejs-babel-preset-env/nodejs-babel-preset-env.spec
  packages/foreman/nodejs-babel-preset-react/nodejs-babel-preset-react.spec
  packages/foreman/nodejs-buffer/nodejs-buffer.spec
  packages/foreman/nodejs-css-loader/nodejs-css-loader.spec
  packages/foreman/nodejs-react-bootstrap/nodejs-react-bootstrap.spec
  packages/foreman/nodejs-react-intl/nodejs-react-intl.spec
  packages/foreman/nodejs-sass-loader/nodejs-sass-loader.spec
  packages/foreman/nodejs-sass/nodejs-sass.spec
  packages/foreman/nodejs-style-loader/nodejs-style-loader.spec
  packages/foreman/nodejs-theforeman-builder/nodejs-theforeman-builder.spec
  packages/foreman/nodejs-use-deep-compare-effect/nodejs-use-deep-compare-effect.spec
  packages/foreman/nodejs-webpack-cli/nodejs-webpack-cli.spec
  packages/foreman/nodejs-webpack/nodejs-webpack.spec
Labels: RPM

#10392 build nodejs packages using node 18 on el9
  package_manifest.yaml
Labels: RPM

#10165 Drop koji
  README.md
  add_gem_package.sh
  add_npm_package.sh
  add_pypi_package.sh
  comps/tag-latest-builds
  koji/copy-os.sh
  koji/copy-tags-commands.sh
  list_koji_tags
  package_manifest.yaml
Labels: RPM

#10394 Cleanup foreman copr definitions now that all foreman is built on el9
  package_manifest.yaml
Labels: RPM

#10403 Update rubygem-deface to 1.9.0
  packages/plugins/rubygem-deface/deface-1.5.3.gem
  packages/plugins/rubygem-deface/deface-1.9.0.gem
  packages/plugins/rubygem-deface/rubygem-deface.spec
Labels: RPM

#10404 move all cockpit related files to cockpit subpackage
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM

#10405 Drop downshift dependency from Katello
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM

#10406 Remove nodejs-downshift
  comps/comps-katello-el8.xml
  comps/comps-katello-el9.xml
  package_manifest.yaml
  packages/katello/nodejs-downshift/compute-scroll-into-view-1.0.14.tgz
  packages/katello/nodejs-downshift/downshift-5.4.7.tgz
  packages/katello/nodejs-downshift/js-tokens-4.0.0.tgz
  packages/katello/nodejs-downshift/loose-envify-1.4.0.tgz
  packages/katello/nodejs-downshift/nodejs-downshift-5.4.7-registry.npmjs.org.tgz
  packages/katello/nodejs-downshift/nodejs-downshift.spec
  packages/katello/nodejs-downshift/object-assign-4.1.1.tgz
  packages/katello/nodejs-downshift/prop-types-15.7.2.tgz
  packages/katello/nodejs-downshift/react-is-16.13.1.tgz
  packages/katello/nodejs-downshift/regenerator-runtime-0.13.7.tgz
  packages/katello/nodejs-downshift/runtime-7.10.5.tgz
Labels: RPM

#10407 Katello el9 nodejs
  package_manifest.yaml
Labels: RPM

#10409 split katello hammer packages and build on el9
  package_manifest.yaml
Labels: RPM

#10411 anemone: Require webrick on Ruby 3.0+
  packages/katello/rubygem-anemone/rubygem-anemone.spec
Labels: RPM

#10413 add foreman-devel:el9 module
  modulemd/modulemd-foreman-el9.yaml
Labels: RPM

#10412 bring back katello and katello-selinux packages
  comps/comps-katello-el9.xml
Labels: RPM

#10415 Rebuild Theme Satellite for Webpack 5
  packages/satellite/rubygem-foreman_theme_satellite/rubygem-foreman_theme_satellite.spec
Labels: Not yet reviewed, RPM

#10416 ignore rdoc 6.6 from ruby 3.3 module
  repoclosure/yum.conf
Labels: RPM

#10417 ignore rdoc 6.6 from ruby 3.3 module
  repoclosure/yum.conf
Labels: Not yet reviewed, RPM, Stable branch

#10418 ignore rdoc 6.6 from ruby 3.3 module
  repoclosure/yum.conf
Labels: Not yet reviewed, RPM, Stable branch

#10424 Update rubygem-foreman_kernel_care to 2.0.0
  packages/katello/rubygem-foreman_kernel_care/foreman_kernel_care-1.2.1.gem
  packages/katello/rubygem-foreman_kernel_care/foreman_kernel_care-2.0.0.gem
  packages/katello/rubygem-foreman_kernel_care/rubygem-foreman_kernel_care.spec
Labels: Not yet reviewed, RPM, Stable branch

#10427 Update ruby-foreman-tasks to 9.1.0
  plugins/ruby-foreman-tasks/debian/changelog
  plugins/ruby-foreman-tasks/debian/gem.list
  plugins/ruby-foreman-tasks/foreman-tasks.rb
Labels: DEB

#10425 Update rubygem-foreman_kernel_care to 2.0.0
  packages/katello/rubygem-foreman_kernel_care/foreman_kernel_care-1.2.1.gem
  packages/katello/rubygem-foreman_kernel_care/foreman_kernel_care-2.0.0.gem
  packages/katello/rubygem-foreman_kernel_care/rubygem-foreman_kernel_care.spec
Labels: Not yet reviewed, RPM, Stable branch

#10426 Update rubygem-foreman-tasks to 9.1.0
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-9.0.2.gem
  packages/plugins/rubygem-foreman-tasks/foreman-tasks-9.1.0.gem
  packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
Labels: RPM

#10442 Update rubygem-hammer_cli_katello to 1.11.2
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.11.1.gem
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.11.2.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: RPM, Stable branch

#10447 Regenerate smart_proxy_dynflow specfile to drop scl references
  packages/plugins/rubygem-smart_proxy_dynflow/rubygem-smart_proxy_dynflow.spec
Labels: RPM

#10450 Update rubygem-kafo to 7.4.0
  packages/foreman/rubygem-kafo/kafo-7.3.0.gem
  packages/foreman/rubygem-kafo/kafo-7.4.0.gem
  packages/foreman/rubygem-kafo/rubygem-kafo.spec
Labels: RPM

#10448 Exit early if a conflicting version bump is detected
  bump_rpm.sh
Labels: RPM

#10451 Bump version to 3.11-develop
  package_manifest.yaml
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Not yet reviewed, RPM

#10453 Foreman 3.10 branching build updates
  mock/el8.cfg
  package_manifest.yaml
  packages/foreman/foreman-release/foreman.gpg
  repoclosure/yum.conf
Labels: RPM, Stable branch

#10454 Foreman 3.10 branching updates - DEB edition
  debian/bullseye/foreman-release/theforeman-archive-keyring.asc
  debian/focal/foreman-release/theforeman-archive-keyring.asc
Labels: DEB, Stable branch

#10458 Release 3.10.0-rc1
  packages/foreman/foreman-installer/foreman-installer-3.10.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.10.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.10.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.10.0-rc1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Not yet reviewed, RPM, Stable branch

#10459 Release 3.10.0-rc1
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
Labels: Not yet reviewed, DEB, Stable branch

#10455 Release hammer-cli[-foreman] 3.10.0
  packages/foreman/rubygem-hammer_cli/hammer_cli-3.10.0.gem
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/hammer_cli_foreman-3.10.0.gem
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: Not yet reviewed, RPM, Stable branch

#10456 Updated hammer_cli[_foreman] to 3.10.0
  dependencies/bullseye/hammer_cli/changelog
  dependencies/bullseye/hammer_cli_foreman/changelog
  dependencies/bullseye/hammer_cli_foreman/control
  dependencies/focal/hammer_cli/changelog
  dependencies/focal/hammer_cli_foreman/changelog
  dependencies/focal/hammer_cli_foreman/control
Labels: DEB

#10463 Updated hammer_cli[_foreman] to 3.10.0
  dependencies/bullseye/hammer_cli/changelog
  dependencies/bullseye/hammer_cli_foreman/changelog
  dependencies/bullseye/hammer_cli_foreman/control
  dependencies/focal/hammer_cli/changelog
  dependencies/focal/hammer_cli_foreman/changelog
  dependencies/focal/hammer_cli_foreman/control
Labels: DEB, Stable branch

#10465 Rebuild foreman_puppet 6.2.0 for Webpack 5
  plugins/ruby-foreman-puppet/debian/changelog
Labels: Not yet reviewed, DEB

#10466 Rebuild foreman_puppet 6.2.0 for Webpack 5
  plugins/ruby-foreman-puppet/debian/changelog
Labels: Not yet reviewed, DEB, Stable branch

#10473 rebuild amazing print without zstd
  dependencies/jammy/amazing_print/changelog
Labels: Not yet reviewed, DEB

#10472 Release 4.12.0-rc1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.12.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM, Stable branch

#10464 Bump Katello to 4.13.0 and related packages to newest versions
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM

#10469 Update rubygem-foreman_virt_who_configure to 0.5.21
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.20.gem
  packages/katello/rubygem-foreman_virt_who_configure/foreman_virt_who_configure-0.5.21.gem
  packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
Labels: RPM

#10275 build amazing_print for bookworm
  dependencies/bookworm/amazing_print/changelog
  dependencies/bookworm/amazing_print/compat
  dependencies/bookworm/amazing_print/control
  dependencies/bookworm/amazing_print/copyright
  dependencies/bookworm/amazing_print/ruby-amazing-print.docs
  dependencies/bookworm/amazing_print/ruby-tests.rake
  dependencies/bookworm/amazing_print/rules
  dependencies/bookworm/amazing_print/source/format
Labels: Not yet reviewed, DEB

#10496 build apipie-* for jammy
  dependencies/jammy/apipie-bindings/changelog
  dependencies/jammy/apipie-bindings/compat
  dependencies/jammy/apipie-bindings/control
  dependencies/jammy/apipie-bindings/copyright
  dependencies/jammy/apipie-bindings/ruby-apipie-bindings.docs
  dependencies/jammy/apipie-bindings/rules
  dependencies/jammy/apipie-bindings/source/format
  dependencies/jammy/apipie-bindings/watch
  dependencies/jammy/apipie-params/changelog
  dependencies/jammy/apipie-params/compat
  dependencies/jammy/apipie-params/control
  dependencies/jammy/apipie-params/copyright
  dependencies/jammy/apipie-params/rules
  dependencies/jammy/apipie-params/source/format
Labels: Not yet reviewed, DEB

#10502 journald-native for jammy
  dependencies/jammy/journald-native/changelog
  dependencies/jammy/journald-native/compat
  dependencies/jammy/journald-native/control
  dependencies/jammy/journald-native/copyright
  dependencies/jammy/journald-native/ruby-journald-native.docs
  dependencies/jammy/journald-native/rules
  dependencies/jammy/journald-native/source/format
  dependencies/jammy/journald-native/watch
Labels: Not yet reviewed, DEB

#10503 journald-logger for jammy
  dependencies/jammy/journald-logger/changelog
  dependencies/jammy/journald-logger/compat
  dependencies/jammy/journald-logger/control
  dependencies/jammy/journald-logger/copyright
  dependencies/jammy/journald-logger/ruby-journald-logger.docs
  dependencies/jammy/journald-logger/ruby-tests.rake
  dependencies/jammy/journald-logger/rules
  dependencies/jammy/journald-logger/source/format
  dependencies/jammy/journald-logger/watch
Labels: Not yet reviewed, DEB

#10501 logging-journald, logging-native, journald-logger for jammy
  dependencies/jammy/logging-journald/changelog
  dependencies/jammy/logging-journald/compat
  dependencies/jammy/logging-journald/control
  dependencies/jammy/logging-journald/copyright
  dependencies/jammy/logging-journald/ruby-logging-journald.docs
  dependencies/jammy/logging-journald/ruby-logging-journald.examples
  dependencies/jammy/logging-journald/ruby-tests.rake
  dependencies/jammy/logging-journald/rules
  dependencies/jammy/logging-journald/source/format
  dependencies/jammy/logging-journald/watch
Labels: Not yet reviewed, DEB

#10510 foreman-proxy for jammy
  debian/jammy/foreman-proxy/build_vars.sh
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-proxy/compat
  debian/jammy/foreman-proxy/control
  debian/jammy/foreman-proxy/copyright
  debian/jammy/foreman-proxy/dirs
  debian/jammy/foreman-proxy/docs
  debian/jammy/foreman-proxy/foreman-proxy-journald.install
  debian/jammy/foreman-proxy/foreman-proxy.install
  debian/jammy/foreman-proxy/foreman-proxy.preinst
  debian/jammy/foreman-proxy/foreman-proxy.tmpfile
  debian/jammy/foreman-proxy/links
  debian/jammy/foreman-proxy/logrotate
  debian/jammy/foreman-proxy/patches/series
  debian/jammy/foreman-proxy/patches/settings_yml_defaults.patch
  debian/jammy/foreman-proxy/postinst
  debian/jammy/foreman-proxy/preinst
  debian/jammy/foreman-proxy/prerm
  debian/jammy/foreman-proxy/rules
  debian/jammy/foreman-proxy/source/format
Labels: Not yet reviewed, DEB

#10511 add foreman-release for jammy
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman-release/compat
  debian/jammy/foreman-release/control
  debian/jammy/foreman-release/copyright
  debian/jammy/foreman-release/foreman-release.install
  debian/jammy/foreman-release/foreman.list
  debian/jammy/foreman-release/rules
  debian/jammy/foreman-release/theforeman-archive-keyring.asc
Labels: Not yet reviewed, DEB
