Repository theforeman/foreman-packaging, pull requests merged in 2024-10, with the labels that each got.

#11314 Update rubygem-foreman_scc_manager to 3.1.1
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-3.1.0.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-3.1.1.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Not yet reviewed, RPM, Stable branch

#11313 Update rubygem-foreman_scc_manager to 3.1.1
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-3.1.0.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-3.1.1.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: Not yet reviewed, RPM, Stable branch

#11327 Update rubygem-foreman_fog_proxmox to 0.16.2 Foreman 3.12
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.16.1.gem
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.16.2.gem
  packages/plugins/rubygem-foreman_fog_proxmox/rubygem-foreman_fog_proxmox.spec
Labels: RPM, Stable branch

#11326 Update rubygem-foreman_fog_proxmox to 0.16.2 Foreman 3.11
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.16.1.gem
  packages/plugins/rubygem-foreman_fog_proxmox/foreman_fog_proxmox-0.16.2.gem
  packages/plugins/rubygem-foreman_fog_proxmox/rubygem-foreman_fog_proxmox.spec
Labels: RPM, Stable branch

#11328 Update ruby-foreman-fog-proxmox to 0.16.2 Foreman 3.11
  plugins/ruby-foreman-fog-proxmox/debian/changelog
  plugins/ruby-foreman-fog-proxmox/debian/gem.list
  plugins/ruby-foreman-fog-proxmox/foreman_fog_proxmox.rb
Labels: Not yet reviewed, DEB, Stable branch

#11329 Update ruby-foreman-fog-proxmox to 0.16.2 Foreman 3.12
  plugins/ruby-foreman-fog-proxmox/debian/changelog
  plugins/ruby-foreman-fog-proxmox/debian/gem.list
  plugins/ruby-foreman-fog-proxmox/foreman_fog_proxmox.rb
Labels: Not yet reviewed, DEB, Stable branch

#11334 only chmod things we created
  .github/workflows/bump_packages.yml
Labels: Not yet reviewed

#11336 smart_proxy_pulp: Regenerate spec based on latest template to drop SCL remains
  packages/plugins/rubygem-smart_proxy_pulp/rubygem-smart_proxy_pulp.spec
Labels: RPM

#11232 Narrow yggdrasil version requirements
  packages/client/foreman_ygg_worker/foreman_ygg_worker.spec
Labels: Waiting on contributor, RPM

#11198 add satellite collections to packaging
  package_manifest.yaml
  packages/satellite/ansible-collection-redhat-satellite/ansible-collection-redhat-satellite.spec
  packages/satellite/ansible-collection-redhat-satellite/redhat-satellite-4.2.0.tar.gz
  packages/satellite/ansible-collection-redhat-satellite_operations/ansible-collection-redhat-satellite_operations.spec
  packages/satellite/ansible-collection-redhat-satellite_operations/redhat-satellite_operations-3.0.0.tar.gz
Labels: RPM

#11344 Release mosquitto 2.0.19
  packages/plugins/mosquitto/mosquitto-2.0.17.tar.gz
  packages/plugins/mosquitto/mosquitto-2.0.19.tar.gz
  packages/plugins/mosquitto/mosquitto.spec
Labels: RPM

#11341 add codeowners
  CODEOWNERS
Labels: Not yet reviewed

#11340 add codeowners
  CODEOWNERS
Labels: Not yet reviewed, RPM

#11342 add codeowners
  CODEOWNERS
Labels: Not yet reviewed, DEB

#11345 Exclude pkgconf definition from yggdrasil
  packages/client/yggdrasil/yggdrasil.spec
Labels: RPM

#11361 Release rubygem-foreman_maintain 1.7.6
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.7.5.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.7.6.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Not yet reviewed, RPM, Stable branch

#11362 ruby-foreman-maintain 1.7.6-1
  dependencies/bookworm/foreman_maintain/changelog
  dependencies/bullseye/foreman_maintain/changelog
  dependencies/focal/foreman_maintain/changelog
  dependencies/jammy/foreman_maintain/changelog
Labels: Not yet reviewed, DEB, Stable branch

#11371 Drop katello-candlepin comps file
  comps/comps-katello-candlepin-el8.xml
Labels: RPM

#11375 Update rubygem-kafo to 7.6.0
  packages/foreman/rubygem-kafo/kafo-7.5.1.gem
  packages/foreman/rubygem-kafo/kafo-7.6.0.gem
  packages/foreman/rubygem-kafo/rubygem-kafo.spec
Labels: Not yet reviewed, RPM

#11382 Release 3.11.4
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/focal/foreman-installer/changelog
  debian/focal/foreman-proxy/changelog
  debian/focal/foreman-release/changelog
  debian/focal/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: DEB, Stable branch

#11381 Release 3.11.4
  packages/foreman/foreman-installer/foreman-installer-3.11.2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.11.4.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.11.2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.11.4.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.11.2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.11.4.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.11.2.tar.bz2
  packages/foreman/foreman/foreman-3.11.4.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: RPM, Stable branch

#11378 Conflict satellite-maintain < 0.0.3
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: RPM

#11332 Drop EL8 bits from Nightly
  comps/comps-foreman-el8.xml
  comps/comps-foreman-plugins-el8.xml
  comps/comps-katello-el8.xml
  modulemd/modulemd-foreman-el8.yaml
  modulemd/modulemd-katello-el8.yaml
  package_manifest.yaml
  remove_from_comps
  repoclosure/yum.conf
Labels: RPM

#11376 installer: Require kafo >= 7.6
  packages/foreman/foreman-installer/foreman-installer.spec
Labels: RPM

#11377 installer: Require kafo >= 7.6
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-installer/control
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-installer/control
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-installer/control
Labels: DEB

#11415 Bump rubygem-katello pulp bindings to 3.63
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM
