Repository theforeman/foreman-packaging, pull requests merged in 2025-08, with the labels that each got.

#12339 [rpm] optionally update only specific packages
  list_updatable_packages
Labels: RPM

#12353 Update fog-proxmox to 0.15.2 dependency for foreman_fog_proxmox
  plugins/ruby-foreman-fog-proxmox/debian/changelog
  plugins/ruby-foreman-fog-proxmox/debian/gem.list
Labels: DEB

#12354 Add rubygem-foreman_ovirt package (RPM)
  comps/comps-foreman-plugins-el9.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_ovirt/foreman_ovirt-2.0.0.gem
  packages/plugins/rubygem-foreman_ovirt/rubygem-foreman_ovirt.spec
Labels: RPM

#12357 Fix broken "gem unpack" calls in add_gem_package.sh
  add_gem_package.sh
Labels: RPM

#12362 Update rubygem-foreman_scc_manager to 5.0.1
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-5.0.0.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-5.0.1.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: RPM, Stable branch

#12364 RPM: Bump version to 3.17-develop
  package_manifest.yaml
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: RPM

#12365 DEB: Bump changelog to 3.17.0 to match VERSION
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: DEB

#12371 Release 4.18.0.rc1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.18.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM, Stable branch

#12373 Update Katello-repos with Candlepin 4.6
  packages/katello/katello-repos/candlepin.gpg
  packages/katello/katello-repos/katello-repos.spec
Labels: RPM

#12384 Exclude uuid bin to avoid upgrade issues with the binary from other p…
  packages/foreman/nodejs-uuid/nodejs-uuid.spec
Labels: RPM

#12396 Add oVirt as owner of the oVirt packages (RPM)
  CODEOWNERS
Labels: RPM

#12395 Add oVirt as owner of the oVirt packages (DEB)
  CODEOWNERS
Labels: DEB

#12401 Update rubygem-foreman_rh_cloud to 12.2.4
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-12.2.3.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-12.2.4.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: RPM

#12402 RPM: Release 3.16.0-rc2
  packages/foreman/foreman-installer/foreman-installer-3.16.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.16.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.16.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.16.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.16.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.16.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.16.0-rc1.tar.bz2
  packages/foreman/foreman/foreman-3.16.0-rc2.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: RPM, Stable branch

#12403 DEB: Release 3.16.0-rc2
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: DEB, Stable branch

#12416 Update rubygem-foreman_scc_manager to 5.0.3
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-5.0.1.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-5.0.3.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: RPM, Stable branch

#12413 Update rubygem-foreman_scc_manager to 5.0.3
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-5.0.1.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-5.0.3.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: RPM, Stable branch

#12415 Update rubygem-hammer_cli_foreman_scc_manager to 0.4.0
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/hammer_cli_foreman_scc_manager-0.3.0.gem
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/hammer_cli_foreman_scc_manager-0.4.0.gem
  packages/katello/rubygem-hammer_cli_foreman_scc_manager/rubygem-hammer_cli_foreman_scc_manager.spec
Labels: RPM, Stable branch

#12417 Update rubygem-foreman_remote_execution to 16.2.0
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-16.1.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-16.2.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM
