Repository theforeman/foreman-packaging, pull requests merged in 2025-04, with the labels that each got.

#11901 Cover h-f-templates in codeowners
  CODEOWNERS
Labels: RPM

#11903 Update rubygem-angular-rails-templates to 1.3.1
  packages/plugins/rubygem-angular-rails-templates/angular-rails-templates-1.2.2.gem
  packages/plugins/rubygem-angular-rails-templates/angular-rails-templates-1.3.1.gem
  packages/plugins/rubygem-angular-rails-templates/rubygem-angular-rails-templates.spec
Labels: RPM, Stable branch

#11906 Update rubygem-hammer_cli_foreman_rh_cloud to 1.0.4
  packages/katello/rubygem-hammer_cli_foreman_rh_cloud/hammer_cli_foreman_rh_cloud-1.0.3.gem
  packages/katello/rubygem-hammer_cli_foreman_rh_cloud/hammer_cli_foreman_rh_cloud-1.0.4.gem
  packages/katello/rubygem-hammer_cli_foreman_rh_cloud/rubygem-hammer_cli_foreman_rh_cloud.spec
Labels: RPM

#11909 Update rubygem-foreman_puppet to 8.1.1
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-8.1.0.gem
  packages/plugins/rubygem-foreman_puppet/foreman_puppet-8.1.1.gem
  packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
Labels: RPM, Stable branch

#11910 Update ruby-hammer-cli-foreman to 3.14.1
  dependencies/bookworm/hammer_cli_foreman/changelog
  dependencies/jammy/hammer_cli_foreman/changelog
Labels: DEB, Stable branch

#11922 Release rubygem-smart_proxy_container_gateway-3.3.0
  packages/plugins/rubygem-smart_proxy_container_gateway/rubygem-smart_proxy_container_gateway.spec
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-3.2.0.gem
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-3.3.0.gem
Labels: RPM

#11929 Add dependency on base64 gem for foreman-proxy
  packages/foreman/foreman-proxy/foreman-proxy.spec
Labels: RPM

#11941 Fix codeowners
  CODEOWNERS
Labels: DEB

#11942 Update rubygem-smart_proxy_openscap to 0.12.1
  packages/plugins/rubygem-smart_proxy_openscap/rubygem-smart_proxy_openscap.spec
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.12.0.gem
  packages/plugins/rubygem-smart_proxy_openscap/smart_proxy_openscap-0.12.1.gem
Labels: RPM

#11953 jammy, bookworm: set ruby-webrick dependency to >= 1.7.0
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-proxy/control
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-proxy/control
Labels: DEB

#11944 Bump Katello Pulp bindings requirements to 3.73
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM

#11962 Drop obsolete from rubygem-pulp_container_client
  packages/katello/rubygem-pulp_container_client/rubygem-pulp_container_client.spec
Labels: RPM

#11966 [deb] Release 3.13.1
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/bullseye/foreman-installer/changelog
  debian/bullseye/foreman-proxy/changelog
  debian/bullseye/foreman-release/changelog
  debian/bullseye/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: DEB, Stable branch

#11971 foreman: Update GEM dependencies
  packages/foreman/foreman/foreman.spec
Labels: RPM

#11955 jammy, bookworm: set ruby-webrick dependency to >= 1.7.0
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-proxy/control
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-proxy/control
Labels: DEB, Stable branch

#11976 Add obsoletes to python-daemon for smooth upgrade
  packages/plugins/python-daemon/python-daemon.spec
Labels: RPM

#11977 Update foreman_ygg_worker to 0.3.1
  packages/client/foreman_ygg_worker/foreman_ygg_worker-0.3.0.tar.gz
  packages/client/foreman_ygg_worker/foreman_ygg_worker-0.3.1.tar.gz
  packages/client/foreman_ygg_worker/foreman_ygg_worker.spec
Labels: RPM
