Repository theforeman/foreman-packaging, pull requests merged in 2025-06, with the labels that each got.

#12027 package oauth
  dependencies/bookworm/oauth/changelog
  dependencies/bookworm/oauth/control
  dependencies/bookworm/oauth/copyright
  dependencies/bookworm/oauth/ruby-oauth.docs
  dependencies/bookworm/oauth/rules
  dependencies/bookworm/oauth/source/format
  dependencies/bookworm/oauth/watch
  dependencies/jammy/oauth/changelog
  dependencies/jammy/oauth/control
  dependencies/jammy/oauth/copyright
  dependencies/jammy/oauth/ruby-oauth.docs
  dependencies/jammy/oauth/rules
  dependencies/jammy/oauth/source/format
  dependencies/jammy/oauth/watch
Labels: DEB

#12098 Update rubygem-foreman_rh_cloud to 12.1.1
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-12.1.0.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-12.1.1.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: RPM

#12114 Release 3.15.0
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: Not yet reviewed, DEB, Stable branch

#12113 Release 3.15.0
  packages/foreman/foreman-installer/foreman-installer-3.15.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.15.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.15.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.15.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.15.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.15.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.15.0-rc1.tar.bz2
  packages/foreman/foreman/foreman-3.15.0.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: Not yet reviewed, RPM, Stable branch

#12117 Release ansible-collection-theforeman-foreman 5.4.0
  packages/plugins/ansible-collection-theforeman-foreman/ansible-collection-theforeman-foreman.spec
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-5.3.0.tar.gz
  packages/plugins/ansible-collection-theforeman-foreman/theforeman-foreman-5.4.0.tar.gz
Labels: RPM

#12118 Release ansible-collection-redhat-satellite 5.4.0
  packages/satellite/ansible-collection-redhat-satellite/ansible-collection-redhat-satellite.spec
  packages/satellite/ansible-collection-redhat-satellite/redhat-satellite-5.3.0.tar.gz
  packages/satellite/ansible-collection-redhat-satellite/redhat-satellite-5.4.0.tar.gz
Labels: RPM

#12119 Release 4.17.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.17.0.gem
  packages/katello/rubygem-katello/katello-4.17.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM, Stable branch

#12123 foreman: update NPM dependencies
  packages/foreman/foreman/foreman.spec
Labels: Not yet reviewed, RPM

#12097 Remove oVirt [deb]
  debian/bookworm/foreman/changelog
  debian/bookworm/foreman/control
  debian/bookworm/foreman/foreman-ovirt.install
  debian/jammy/foreman/changelog
  debian/jammy/foreman/control
  debian/jammy/foreman/foreman-ovirt.install
Labels: DEB

#12129 hammer_cli_foreman: Update based on latest template
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: RPM

#12132 Update rubygem-foreman_expire_hosts to 9.0.0
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-8.2.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-9.0.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: RPM, Stable branch

#12138 Update rubygem-foreman_expire_hosts to 9.0.1
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-9.0.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-9.0.1.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: RPM

#12140 Update rubygem-foreman_expire_hosts to 9.0.1
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-9.0.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-9.0.1.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: RPM, Stable branch

#12139 Update rubygem-foreman_expire_hosts to 9.0.1
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-9.0.0.gem
  packages/plugins/rubygem-foreman_expire_hosts/foreman_expire_hosts-9.0.1.gem
  packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
Labels: RPM, Stable branch

#12166 Update ansiblerole-foreman_scap_client to 0.4.0
  packages/plugins/ansiblerole-foreman_scap_client/ansiblerole-foreman_scap_client.spec
  packages/plugins/ansiblerole-foreman_scap_client/foreman_scap_client-0.3.1.tar.gz
  packages/plugins/ansiblerole-foreman_scap_client/foreman_scap_client-0.4.0.tar.gz
Labels: RPM
