Repository theforeman/foreman-packaging, pull requests merged in 2025-05, with the labels that each got.

#11983 Update rubygem-foreman_rh_cloud to 12.1.0
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-12.0.0.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-12.1.0.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: RPM

#11985 Update rubygem-fog-vsphere to 3.7.1
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.7.0.gem
  packages/foreman/rubygem-fog-vsphere/fog-vsphere-3.7.1.gem
  packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec
Labels: RPM

#11992 Release 4.16.1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.16.0.gem
  packages/katello/rubygem-katello/katello-4.16.1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM, Stable branch

#12006 Update katello-host-tools to 4.5.0
  packages/client/katello-host-tools/katello-host-tools-4.4.0.tar.gz
  packages/client/katello-host-tools/katello-host-tools-4.5.0.tar.gz
  packages/client/katello-host-tools/katello-host-tools.spec
Labels: RPM

#12008 Add rubygem-llhttp package
  comps/comps-foreman-plugins-el9.xml
  package_manifest.yaml
  packages/plugins/rubygem-llhttp/llhttp-0.6.1.gem
  packages/plugins/rubygem-llhttp/rubygem-llhttp.spec
Labels: RPM

#12009 Bump rubygem-http to 5.2.0-1
  packages/plugins/rubygem-http/http-3.3.0.gem
  packages/plugins/rubygem-http/http-5.2.0.gem
  packages/plugins/rubygem-http/rubygem-http.spec
Labels: RPM

#11148 Update rubygem-foreman_supervisory_authority to 0.2.0
  packages/plugins/rubygem-elastic-apm/elastic-apm-2.9.1.gem
  packages/plugins/rubygem-elastic-apm/elastic-apm-4.7.3.gem
  packages/plugins/rubygem-elastic-apm/rubygem-elastic-apm.spec
  packages/plugins/rubygem-foreman_supervisory_authority/foreman_supervisory_authority-0.0.2.gem
  packages/plugins/rubygem-foreman_supervisory_authority/foreman_supervisory_authority-0.2.0.gem
  packages/plugins/rubygem-foreman_supervisory_authority/rubygem-foreman_supervisory_authority.spec
Labels: RPM

#12019 Update rubygem-kubeclient to 4.12.0
  packages/plugins/rubygem-kubeclient/kubeclient-4.10.1.gem
  packages/plugins/rubygem-kubeclient/kubeclient-4.12.0.gem
  packages/plugins/rubygem-kubeclient/rubygem-kubeclient.spec
Labels: RPM

#12020 Update ruby-apipie-bindings to 0.7.1
  dependencies/bookworm/apipie-bindings/changelog
  dependencies/jammy/apipie-bindings/changelog
Labels: DEB

#12022 allow @theforeman/cli to manage apipie packages
  CODEOWNERS
Labels: RPM

#12021 allow @theforeman/cli to manage apipie packages
  CODEOWNERS
Labels: DEB

#9517 Add ruby-foreman-hdm v1.1.0 & smart_proxy_hdm v1.0.0
  plugins/ruby-foreman-hdm/debian/changelog
  plugins/ruby-foreman-hdm/debian/control
  plugins/ruby-foreman-hdm/debian/copyright
  plugins/ruby-foreman-hdm/debian/gem.list
  plugins/ruby-foreman-hdm/debian/install
  plugins/ruby-foreman-hdm/debian/rules
  plugins/ruby-foreman-hdm/debian/source/format
  plugins/ruby-foreman-hdm/debian/watch
  plugins/ruby-foreman-hdm/foreman_hdm.rb
  plugins/smart_proxy_hdm/changelog
  plugins/smart_proxy_hdm/control
  plugins/smart_proxy_hdm/copyright
  plugins/smart_proxy_hdm/install
  plugins/smart_proxy_hdm/rules
  plugins/smart_proxy_hdm/source/format
Labels: DEB

#12043 Update rubygem-foreman_rescue to 5.0.0
  packages/plugins/rubygem-foreman_rescue/foreman_rescue-4.0.1.gem
  packages/plugins/rubygem-foreman_rescue/foreman_rescue-5.0.0.gem
  packages/plugins/rubygem-foreman_rescue/rubygem-foreman_rescue.spec
Labels: RPM, Stable branch

#12050 Update rubygem-foreman_dlm to 4.0.0
  packages/plugins/rubygem-foreman_dlm/foreman_dlm-3.0.0.gem
  packages/plugins/rubygem-foreman_dlm/foreman_dlm-4.0.0.gem
  packages/plugins/rubygem-foreman_dlm/rubygem-foreman_dlm.spec
Labels: RPM, Stable branch

#12049 Update rubygem-foreman_vault to 3.0.0
  packages/plugins/rubygem-foreman_vault/foreman_vault-2.0.0.gem
  packages/plugins/rubygem-foreman_vault/foreman_vault-3.0.0.gem
  packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
Labels: RPM, Stable branch

#12048 Update rubygem-foreman_wreckingball to 6.0.0
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-5.0.0.gem
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-6.0.0.gem
  packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
Labels: RPM, Stable branch

#12047 Update rubygem-foreman_rescue to 5.0.0
  packages/plugins/rubygem-foreman_rescue/foreman_rescue-4.0.1.gem
  packages/plugins/rubygem-foreman_rescue/foreman_rescue-5.0.0.gem
  packages/plugins/rubygem-foreman_rescue/rubygem-foreman_rescue.spec
Labels: RPM, Stable branch

#12046 Update rubygem-foreman_dlm to 4.0.0
  packages/plugins/rubygem-foreman_dlm/foreman_dlm-3.0.0.gem
  packages/plugins/rubygem-foreman_dlm/foreman_dlm-4.0.0.gem
  packages/plugins/rubygem-foreman_dlm/rubygem-foreman_dlm.spec
Labels: RPM, Stable branch

#12044 Update rubygem-foreman_wreckingball to 6.0.0
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-5.0.0.gem
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-6.0.0.gem
  packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
Labels: RPM, Stable branch

#12056 allow DM team to merge their plugins
  CODEOWNERS
Labels: RPM

#12055 allow DM team to manage foreman rescue debs
  CODEOWNERS
Labels: DEB

#12057 Update rubygem-foreman_monitoring to 3.3.0
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-3.2.0.gem
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-3.3.0.gem
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
Labels: RPM, Stable branch

#12058 Update rubygem-foreman_monitoring to 3.3.0
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-3.2.0.gem
  packages/plugins/rubygem-foreman_monitoring/foreman_monitoring-3.3.0.gem
  packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
Labels: RPM, Stable branch

#12059 RPM: Bump version to 3.16-develop
  package_manifest.yaml
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman.spec
  packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
  packages/foreman/rubygem-hammer_cli_foreman/rubygem-hammer_cli_foreman.spec
Labels: RPM

#12060 DEB: Bump changelog to 3.16.0 to match VERSION
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: DEB

#12063 Foreman 3.15 debian keyring updates
  debian/bookworm/foreman-release/theforeman-archive-keyring.asc
  debian/jammy/foreman-release/theforeman-archive-keyring.asc
Labels: DEB, Stable branch

#12068 Add ruby-foreman-hdm v1.1.0 & smart_proxy_hdm v1.0.0
  plugins/ruby-foreman-hdm/debian/changelog
  plugins/ruby-foreman-hdm/debian/control
  plugins/ruby-foreman-hdm/debian/copyright
  plugins/ruby-foreman-hdm/debian/gem.list
  plugins/ruby-foreman-hdm/debian/install
  plugins/ruby-foreman-hdm/debian/rules
  plugins/ruby-foreman-hdm/debian/source/format
  plugins/ruby-foreman-hdm/debian/watch
  plugins/ruby-foreman-hdm/foreman_hdm.rb
  plugins/smart_proxy_hdm/changelog
  plugins/smart_proxy_hdm/control
  plugins/smart_proxy_hdm/copyright
  plugins/smart_proxy_hdm/install
  plugins/smart_proxy_hdm/rules
  plugins/smart_proxy_hdm/source/format
Labels: DEB, Stable branch

#12069 Add ruby-foreman-hdm v1.1.0 & smart_proxy_hdm v1.0.0
  plugins/ruby-foreman-hdm/debian/changelog
  plugins/ruby-foreman-hdm/debian/control
  plugins/ruby-foreman-hdm/debian/copyright
  plugins/ruby-foreman-hdm/debian/gem.list
  plugins/ruby-foreman-hdm/debian/install
  plugins/ruby-foreman-hdm/debian/rules
  plugins/ruby-foreman-hdm/debian/source/format
  plugins/ruby-foreman-hdm/debian/watch
  plugins/ruby-foreman-hdm/foreman_hdm.rb
  plugins/smart_proxy_hdm/changelog
  plugins/smart_proxy_hdm/control
  plugins/smart_proxy_hdm/copyright
  plugins/smart_proxy_hdm/install
  plugins/smart_proxy_hdm/rules
  plugins/smart_proxy_hdm/source/format
Labels: DEB, Stable branch

#12025 Bump katello related packages to their 4.18 versions
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM

#12061 Drop unversioned obsoletes from foreman_rh_cloud
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: RPM

#12071 Release 3.15.0-rc1
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: DEB, Stable branch

#12070 Release 3.15.0-rc1
  packages/foreman/foreman-installer/foreman-installer-3.15.0-rc1.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.15.0-rc1.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.15.0-rc1.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.15.0-rc1.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: RPM, Stable branch

#12054 Update rubygem-foreman_dlm to 4.0.0
  packages/plugins/rubygem-foreman_dlm/foreman_dlm-3.0.0.gem
  packages/plugins/rubygem-foreman_dlm/foreman_dlm-4.0.0.gem
  packages/plugins/rubygem-foreman_dlm/rubygem-foreman_dlm.spec
Labels: Not yet reviewed, RPM, Stable branch

#12052 Update rubygem-foreman_wreckingball to 6.0.0
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-5.0.0.gem
  packages/plugins/rubygem-foreman_wreckingball/foreman_wreckingball-6.0.0.gem
  packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
Labels: Not yet reviewed, RPM, Stable branch

#12051 Update rubygem-foreman_rescue to 5.0.0
  packages/plugins/rubygem-foreman_rescue/foreman_rescue-4.0.1.gem
  packages/plugins/rubygem-foreman_rescue/foreman_rescue-5.0.0.gem
  packages/plugins/rubygem-foreman_rescue/rubygem-foreman_rescue.spec
Labels: Not yet reviewed, RPM, Stable branch

#12067 Add ruby-foreman-hdm v1.1.0 & smart_proxy_hdm v1.0.0
  plugins/ruby-foreman-hdm/debian/changelog
  plugins/ruby-foreman-hdm/debian/control
  plugins/ruby-foreman-hdm/debian/copyright
  plugins/ruby-foreman-hdm/debian/gem.list
  plugins/ruby-foreman-hdm/debian/install
  plugins/ruby-foreman-hdm/debian/rules
  plugins/ruby-foreman-hdm/debian/source/format
  plugins/ruby-foreman-hdm/debian/watch
  plugins/ruby-foreman-hdm/foreman_hdm.rb
  plugins/smart_proxy_hdm/changelog
  plugins/smart_proxy_hdm/control
  plugins/smart_proxy_hdm/copyright
  plugins/smart_proxy_hdm/install
  plugins/smart_proxy_hdm/rules
  plugins/smart_proxy_hdm/source/format
Labels: DEB, Stable branch

#12073 Release 4.17.0.rc1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.17.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM, Stable branch

#12087 Update cjson to 1.7.18
  packages/plugins/cjson/cjson-1.7.17.tar.gz
  packages/plugins/cjson/cjson-1.7.18.tar.gz
  packages/plugins/cjson/cjson.spec
Labels: RPM

#12091 Update rubygem-foreman_netbox to 2.0.0
  packages/plugins/rubygem-foreman_netbox/foreman_netbox-1.2.0.gem
  packages/plugins/rubygem-foreman_netbox/foreman_netbox-2.0.0.gem
  packages/plugins/rubygem-foreman_netbox/rubygem-foreman_netbox.spec
Labels: RPM, Stable branch

#12090 Update rubygem-foreman_netbox to 2.0.0
  packages/plugins/rubygem-foreman_netbox/foreman_netbox-1.2.0.gem
  packages/plugins/rubygem-foreman_netbox/foreman_netbox-2.0.0.gem
  packages/plugins/rubygem-foreman_netbox/rubygem-foreman_netbox.spec
Labels: RPM, Stable branch

#12089 Update rubygem-foreman_netbox to 2.0.0
  packages/plugins/rubygem-foreman_netbox/foreman_netbox-1.2.0.gem
  packages/plugins/rubygem-foreman_netbox/foreman_netbox-2.0.0.gem
  packages/plugins/rubygem-foreman_netbox/rubygem-foreman_netbox.spec
Labels: RPM, Stable branch
