Repository theforeman/foreman-packaging, pull requests merged in 2025-09, with the labels that each got.

#12419 Revert "Update nodejs-symbol-observable to 4.0.0"
  packages/foreman/nodejs-symbol-observable/nodejs-symbol-observable.spec
  packages/foreman/nodejs-symbol-observable/symbol-observable-1.2.0.tgz
  packages/foreman/nodejs-symbol-observable/symbol-observable-4.0.0.tgz
Labels: Not yet reviewed, RPM

#12440 Update rubygem-foreman_remote_execution to 16.2.0 (#12417)
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-16.1.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-16.2.0.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM, Stable branch

#12441 Drop probing plugins
  comps/comps-foreman-plugins-el9.xml
  package_manifest.yaml
  packages/plugins/rubygem-foreman_probing/foreman_probing-0.0.4.gem
  packages/plugins/rubygem-foreman_probing/rubygem-foreman_probing.spec
  packages/plugins/rubygem-smart-proxy-probing/rubygem-smart-proxy-probing.spec
  packages/plugins/rubygem-smart-proxy-probing/smart-proxy-probing-0.0.4.gem
Labels: RPM

#12424 Update rubygem-foreman_maintain to 1.13.2
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.12.4.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.13.2.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: RPM, Stable branch

#12434 Update rubygem-foreman_theme_satellite to 15.3.1
  packages/satellite/rubygem-foreman_theme_satellite/foreman_theme_satellite-15.3.0.gem
  packages/satellite/rubygem-foreman_theme_satellite/foreman_theme_satellite-15.3.1.gem
  packages/satellite/rubygem-foreman_theme_satellite/rubygem-foreman_theme_satellite.spec
Labels: RPM, Stable branch

#12450 Update rubygem-foreman_rh_cloud to 12.2.6
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-12.2.5.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-12.2.6.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: RPM, Stable branch

#12449 Update rubygem-hammer_cli_foreman_rh_cloud to 1.0.5
  packages/katello/rubygem-hammer_cli_foreman_rh_cloud/hammer_cli_foreman_rh_cloud-1.0.4.gem
  packages/katello/rubygem-hammer_cli_foreman_rh_cloud/hammer_cli_foreman_rh_cloud-1.0.5.gem
  packages/katello/rubygem-hammer_cli_foreman_rh_cloud/rubygem-hammer_cli_foreman_rh_cloud.spec
Labels: RPM, Stable branch

#12452 Update cJson to fix CVE-2025-57052
  packages/plugins/cjson/0001-fix_the_incorrect_check_in_decode_array_index_from_pointer.patch
  packages/plugins/cjson/cjson.spec
Labels: RPM

#12453 Update cJson to fix CVE-2025-57052
  packages/plugins/cjson/0001-fix_the_incorrect_check_in_decode_array_index_from_pointer.patch
  packages/plugins/cjson/cjson.spec
Labels: RPM, Stable branch

#12456 DEB: Release Foreman 3.16.0
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: DEB, Stable branch

#12455 RPM: Release Foreman 3.16.0
  packages/foreman/foreman-installer/foreman-installer-3.16.0-rc2.tar.bz2
  packages/foreman/foreman-installer/foreman-installer-3.16.0.tar.bz2
  packages/foreman/foreman-installer/foreman-installer.spec
  packages/foreman/foreman-proxy/foreman-proxy-3.16.0-rc2.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy-3.16.0.tar.bz2
  packages/foreman/foreman-proxy/foreman-proxy.spec
  packages/foreman/foreman-release/foreman-release.spec
  packages/foreman/foreman-selinux/foreman-selinux-3.16.0-rc2.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux-3.16.0.tar.bz2
  packages/foreman/foreman-selinux/foreman-selinux.spec
  packages/foreman/foreman/foreman-3.16.0-rc2.tar.bz2
  packages/foreman/foreman/foreman-3.16.0.tar.bz2
  packages/foreman/foreman/foreman.spec
Labels: RPM, Stable branch

#12461 Update rubygem-dynflow to 1.9.3
  packages/foreman/rubygem-dynflow/dynflow-1.9.2.gem
  packages/foreman/rubygem-dynflow/dynflow-1.9.3.gem
  packages/foreman/rubygem-dynflow/rubygem-dynflow.spec
Labels: RPM, Stable branch

#12472 Update rubygem-smart_proxy_container_gateway to 3.4.1
  packages/plugins/rubygem-smart_proxy_container_gateway/rubygem-smart_proxy_container_gateway.spec
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-3.4.0.gem
  packages/plugins/rubygem-smart_proxy_container_gateway/smart_proxy_container_gateway-3.4.1.gem
Labels: RPM

#12477 Update ruby-foreman-remote-execution to 16.2.1
  plugins/ruby-foreman-remote-execution/debian/changelog
  plugins/ruby-foreman-remote-execution/debian/gem.list
  plugins/ruby-foreman-remote-execution/foreman_remote_execution.rb
Labels: DEB, Stable branch

#12476 Update rubygem-foreman_remote_execution to 16.2.1
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-16.2.0.gem
  packages/plugins/rubygem-foreman_remote_execution/foreman_remote_execution-16.2.1.gem
  packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
Labels: RPM, Stable branch

#12484 Update rubygem-foreman_scc_manager to 5.0.4
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-5.0.3.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-5.0.4.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: RPM, Stable branch

#12483 Update rubygem-foreman_scc_manager to 5.0.4
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-5.0.3.gem
  packages/katello/rubygem-foreman_scc_manager/foreman_scc_manager-5.0.4.gem
  packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
Labels: RPM, Stable branch

#12486 Release ansible-collection-theforeman-foreman 5.6.0
  plugins/ansible-collection-theforeman-foreman/debian/changelog
Labels: Not yet reviewed, DEB, Stable branch

#12490 Update rubygem-foreman_bootdisk to 23.1.2 (cherrypick rpm 3.16)
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-23.1.1.gem
  packages/plugins/rubygem-foreman_bootdisk/foreman_bootdisk-23.1.2.gem
  packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
Labels: RPM, Stable branch

#12496 Release 4.18.0
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.18.0.gem
  packages/katello/rubygem-katello/katello-4.18.0.rc2.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: Not yet reviewed, RPM, Stable branch

#12498 Update rubygem-hammer_cli_katello to 1.18.0
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.18.0.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: RPM, Stable branch

#12500 Correct dependency on prime for Ruby >= 3.1
  packages/foreman/rubygem-fast_gettext/rubygem-fast_gettext.spec
Labels: RPM

#11124 Add foreman_opennebula plugin
  plugins/ruby-foreman-opennebula/debian/changelog
  plugins/ruby-foreman-opennebula/debian/compat
  plugins/ruby-foreman-opennebula/debian/control
  plugins/ruby-foreman-opennebula/debian/copyright
  plugins/ruby-foreman-opennebula/debian/gem.list
  plugins/ruby-foreman-opennebula/debian/install
  plugins/ruby-foreman-opennebula/debian/postinst
  plugins/ruby-foreman-opennebula/debian/rules
  plugins/ruby-foreman-opennebula/debian/source/format
  plugins/ruby-foreman-opennebula/foreman_opennebula.rb
Labels: DEB

#12519 Update rubygem-foreman_maintain to 1.13.3
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.13.2.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.13.3.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Not yet reviewed, RPM, Stable branch

#12523 Add rubygem-treetop package
  comps/comps-foreman-plugins-el9.xml
  package_manifest.yaml
  packages/plugins/rubygem-treetop/rubygem-treetop.spec
  packages/plugins/rubygem-treetop/treetop-1.6.14.gem
Labels: RPM

#12520 Add rubygem-opennebula package
  comps/comps-foreman-plugins-el9.xml
  package_manifest.yaml
  packages/plugins/rubygem-opennebula/opennebula-6.8.2.gem
  packages/plugins/rubygem-opennebula/rubygem-opennebula.spec
Labels: RPM

#12531 Update rubygem-foreman_rh_cloud to 12.2.9
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-12.2.8.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-12.2.9.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: RPM, Stable branch

#12536 Update rubygem-foreman_maintain to 1.13.4
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.13.3.gem
  packages/foreman/rubygem-foreman_maintain/foreman_maintain-1.13.4.gem
  packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
Labels: Not yet reviewed, RPM, Stable branch

#12516 Update foreman-fapolicyd to 1.1.0
  packages/foreman/foreman-fapolicyd/foreman-fapolicyd-1.0.1.tar.gz
  packages/foreman/foreman-fapolicyd/foreman-fapolicyd-1.1.0.tar.gz
  packages/foreman/foreman-fapolicyd/foreman-fapolicyd.spec
Labels: RPM
