Repository theforeman/foreman-packaging, pull requests merged in 2025-02, with the labels that each got.

#11703 Add python-setuptools-rust
  comps/comps-foreman-plugins-el9.xml
  package_manifest.yaml
  packages/plugins/python-setuptools-rust/python-setuptools-rust.spec
  packages/plugins/python-setuptools-rust/setuptools-rust-1.9.0.tar.gz
Labels: Not yet reviewed, RPM

#11705 Add python-markupsafe
  comps/comps-foreman-plugins-el9.xml
  package_manifest.yaml
  packages/plugins/python-markupsafe/python-markupsafe.spec
Labels: RPM

#11706 Add python-maturin
  comps/comps-foreman-plugins-el9.xml
  package_manifest.yaml
  packages/plugins/python-maturin/maturin-1.7.1-vendor.tar.xz
  packages/plugins/python-maturin/maturin-1.7.1.tar.gz
  packages/plugins/python-maturin/python-maturin.spec
Labels: Not yet reviewed, RPM

#11711 Add ansible-core
  package_manifest.yaml
  packages/plugins/ansible-core/ansible-core-2.16.14.tar.gz
  packages/plugins/ansible-core/ansible-core.spec
  packages/plugins/ansible-core/ansible-documentation-2.16.14.tar.gz
Labels: RPM

#11713 Provides python3.12-resolvelib
  packages/plugins/python-resolvelib/python-resolvelib.spec
Labels: Not yet reviewed, RPM

#11710 Update rubygem-foreman_rh_cloud to 11.1.0
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-11.0.3.gem
  packages/katello/rubygem-foreman_rh_cloud/foreman_rh_cloud-11.1.0.gem
  packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
Labels: RPM

#11714 Add ansible-test to plugins comps
  comps/comps-foreman-plugins-el9.xml
Labels: Not yet reviewed, RPM

#11718 Release katello-selinux 5.2.0
  packages/katello/katello-selinux/5.1.0
  packages/katello/katello-selinux/5.2.0
  packages/katello/katello-selinux/katello-selinux.spec
Labels: RPM

#11730 Fix rubygem-font-awesome-sass
  packages/foreman/rubygem-font-awesome-sass/rubygem-font-awesome-sass.spec
Labels: RPM

#11735 Update rubygem-foreman_templates to 10.0.5
  packages/plugins/rubygem-foreman_templates/foreman_templates-10.0.4.gem
  packages/plugins/rubygem-foreman_templates/foreman_templates-10.0.5.gem
  packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
Labels: RPM

#11736 Foreman 3.14 branching build updates
  mock/el8.cfg
  mock/el9.cfg
  package_manifest.yaml
  packages/foreman/foreman-release/foreman.gpg
  repoclosure/yum.conf
Labels: RPM, Stable branch

#11737 Foreman 3.14 keyring updates
  debian/bookworm/foreman-release/theforeman-archive-keyring.asc
  debian/jammy/foreman-release/theforeman-archive-keyring.asc
Labels: DEB, Stable branch

#11748 Release 3.14.0-rc1
  debian/bookworm/foreman-installer/changelog
  debian/bookworm/foreman-proxy/changelog
  debian/bookworm/foreman-release/changelog
  debian/bookworm/foreman/changelog
  debian/jammy/foreman-installer/changelog
  debian/jammy/foreman-proxy/changelog
  debian/jammy/foreman-release/changelog
  debian/jammy/foreman/changelog
Labels: DEB, Stable branch

#11768 Release 4.16.0-rc1
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/katello-4.16.0.rc1.gem
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM, Stable branch

#11738 Bump Katello and Katello packages to 4.17 versions
  packages/katello/katello-repos/katello-repos.spec
  packages/katello/katello/katello.spec
  packages/katello/rubygem-katello/rubygem-katello.spec
Labels: RPM

#11782 Rewrite spec files with %scl_package
  bump_rpm.sh
Labels: RPM

#11634 Add support for devcontainers
  .devcontainer/devcontainer.json
  Containerfile
Labels: RPM

#11166 Bump rubygem-http-form_data to 2.3.0-1
  packages/plugins/rubygem-http-form_data/http-form_data-2.1.1.gem
  packages/plugins/rubygem-http-form_data/http-form_data-2.3.0.gem
  packages/plugins/rubygem-http-form_data/rubygem-http-form_data.spec
Labels: RPM

#11794 Update rubygem-fog-proxmox to 0.15.1
  packages/plugins/rubygem-fog-proxmox/fog-proxmox-0.15.0.gem
  packages/plugins/rubygem-fog-proxmox/fog-proxmox-0.15.1.gem
  packages/plugins/rubygem-fog-proxmox/rubygem-fog-proxmox.spec
Labels: RPM

#11798 Update rubygem-angular-rails-templates to 1.3.1
  packages/plugins/rubygem-angular-rails-templates/angular-rails-templates-1.2.2.gem
  packages/plugins/rubygem-angular-rails-templates/angular-rails-templates-1.3.1.gem
  packages/plugins/rubygem-angular-rails-templates/rubygem-angular-rails-templates.spec
Labels: RPM

#11799 Release rubygem-hammer_cli_katello 1.16.0
  packages/katello/rubygem-hammer_cli_katello/hammer_cli_katello-1.16.0.gem
  packages/katello/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec
Labels: RPM, Stable branch
